### ISSUE TITLE
Failing Tests # 4 and #11 on Technical Documentation Page Project

### ISSUE THREAD

**Issue by Supertechie2010** [freeCodeCamp/testable-projects-fcc#100]
#### Issue Description

When I run the test on my page it claims I am failing 2 tests, #4 and #11. my code appears to meet these requirements but I cannot manage to get it to pass these tests.  

#### Browser Information

* Chrome, Version 58.0.3029.110 (64-bit) 
* Windows 7
* Desktop

#### Your Code / Link to Your Pen

```
 https://codepen.io/Supertechie2010/pen/JNqKeg?editors=1100

**Comment by paweltar** [comment]
I've had similiar issue yesterday (or even the same issue), the problem is that if you put your header text inside some additional markup inside your header elements like for example `<header>
        <h2>What You Should Already Know</h2>
      </header>` test expects `id` with extra underscores at the beginning or at the end like `What_You_Should_Already_Know__`. But if you remove any additional elements like `h2` tag and put text directly inside `header` in one line without any spaces, then tests are passed like you can see in this fork [https://codepen.io/paweltar/full/jwqNbE/](https://codepen.io/paweltar/full/jwqNbE/) . 
So it seems that your version with `h2` tags is ok and there is some problem with tests. Probably before title string is converted to its underscored version, the whitespaces an the beggining and at the end should be trimmed first.

**Comment by Supertechie2010** [comment]
So basically my code is fine and it is the test that is not functioning properly as my code is valid HTML5.

**Comment by paweltar** [comment]
Yes, in my opinion test should pass with your original code, however at the moment it doesn't, so probably you'll have to adjust your solution by removing `h2` tags and any spaces inside `header` or wait until test is fixed.

**Comment by no-stack-dub-sack** [comment]
@paweltar @Supertechie2010 thanks for reporting these issues, we're working to fix all of these before the beta curriculum goes live!

**Comment by tbushman** [comment]
OK @Supertechie2010, once updated, the test might still fail because the text, "If...Else_Statement", when replacing spaces with underscores, won't fully match id="If_Else_Statement".  You can use "..." in your id attribute.
