### ISSUE TITLE
Survey Form Test 1 "I can see a title with id="title" in H1 sized text." expects ID to be in ALL CAPS

### ISSUE THREAD

**Issue by jpvajda** [freeCodeCamp/testable-projects-fcc#1000]
#### Issue Description

Survey Form Test 1 "I can see a title with id="title" in H1 sized text." expects ID to be in ALL CAPS. This took me a while to figure out as I assumed all `id` values should be lower case. Perhaps the test can be consist with the instructions which say:

User Story 1: I can see a title with id="title" in H1 sized text.

Failed Test Results 

```
1. I can see a title with id="title" in H1 sized text.

#title should be in H1 sized text : expected 'TITLE' to equal 'H1'
a@https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:106:475
FCC_Global</e.exports/o.prototype.assert@https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:534:1366
c@https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:549:1881
l@https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:431:130
FCC_Global</e.exports/n.strictEqual@https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:574:655
test/</</<@https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:657:136512
c@https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:35224
FCC_Global</</<[33]</</p.prototype.run@https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:35154
FCC_Global</</<[34]</</T.prototype.runTest@https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:41723
i/<@https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:42605
o@https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:41019
o/<@https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:41089
o@https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:40141
FCC_Global</</<[34]</</T.prototype.hook/<@https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:40906
f@https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:593:1377


```

#### Browser Information

Firefox 70.0 (64-bit)
Mac OS: Mojave 10.14.6 (18G103)
Desktop view

#### Your Code / Link to Your Pen
https://codepen.io/jpvajda/pen/BaaxybB

#### Screenshots
![Screen Shot 2019-11-06 at 12 26 19 PM](https://user-images.githubusercontent.com/1395158/68330565-b62e4e00-0090-11ea-8984-3552d39be094.png)

![Screen Shot 2019-11-06 at 12 26 34 PM](https://user-images.githubusercontent.com/1395158/68330566-b62e4e00-0090-11ea-8595-ac4bb29d073e.png)

**Comment by petercr** [comment]
I just tried running these tests on CodePen with:
- FireFox v.70.1
- FireFox v.71.0
On Windows 10 and it ran all the tests without a problem. 
So _maybe_ it's a Mac specific bug 🤔

**Comment by jpvajda** [comment]
@petercr  I reran the test on my FCC project and it seems to pass ok now, maybe the test got fixed?  I think this can be closed.

``` var e=document.getElementById("title");o.assert.isNotNull(e,'There should be an element with id="title" '),o.assert.strictEqual(e.tagName,"H1","#title should be in H1 sized text "),o.assert.isAbove(e.innerText.length,0,"#title should contain some text ") ```
