### ISSUE TITLE
Unable to use Test Suite

### ISSUE THREAD

**Issue by codebyal** [freeCodeCamp/testable-projects-fcc#1001]
#### Issue Description

I am unable to test my tribute page, when I attempt to 'Run Tests' or 'Load Tests' I am not served any results, I will instead see a line '#mocha div missing, add it to your document' - however this does not seem to correspond to any of the user-stories listed for the task. 

#### Browser Information

- Browser Name, Version: Chrome 78.0.3904.87
- Operating System: Windows 7
- Mobile, Desktop, or Tablet: Mobile & Desktop

#### Your Code / Link to Your Pen

https://codepen.io/Codebyal/pen/JjjBLJx

#### Screenshot

![image](https://user-images.githubusercontent.com/30072397/68598521-e7df5480-0496-11ea-9771-df970a0a859e.png)

**Comment by RandellDawson** [comment]
@codebyal When you have problems with your project code, please use [our forum](https://www.freecodecamp.org/forum) to ask for help first.  GitHub issues are only for reporting true bugs.  You need to remove the `<script src="https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js"></script>` from the HTML module.  It is already included in the external scripts/pens section of the JS module.

![image](https://user-images.githubusercontent.com/5313213/68599185-015fac80-0455-11ea-990e-40471982432d.png)
