### ISSUE TITLE
When I click a .nav-link button in the nav element, I am taken to the corresponding section of the landing page.'

### ISSUE THREAD

**Issue by guptaji048** [freeCodeCamp/testable-projects-fcc#1002]
Hey, im working on product landing page but the cdn test issues an error of 
**Each .nav-link element should have an href attribute : expected false to equal true**
but you can see clearly in attached image that i have included "href". please help

![image](https://user-images.githubusercontent.com/56163936/68658554-abc1f780-055b-11ea-88a5-0c6e4c57b775.png)

#### Browser Information

- Browser Name, Version:
- Operating System:
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen

```
https://codepen.io/guptaji048/pen/WNNgNaE


```

**Comment by petercr** [comment]
Hello @guptaji048 👋  so only 1 of your links in `.nav-link` has a button. The rest are just links, and the tests specifically call for `<button>`s 
Also put your `<a>` tag **inside** your `<button>`
That's the way you're supposed to do it for accessibility reasons

**Comment by guptaji048** [comment]
> Hello @guptaji048  so only 1 of your links in `.nav-link` has a button. The rest are just links, and the tests specifically call for `<button>`s
> Also put your `<a>` tag **inside** your `<button>`
> That's the way you're supposed to do it for accessibility reasons
![image](https://user-images.githubusercontent.com/56163936/68763610-df298280-063e-11ea-8711-460b87fc7672.png)
i tried but its still showing same error...

**Comment by petercr** [comment]
Just remove the `<ul>`s and `<li>`s out of the `nav` and it will pass all of the tests. 
![passes all tests](https://user-images.githubusercontent.com/26460352/68787877-53006680-0610-11ea-9ffb-3ab0528354ba.png)

**Comment by RandellDawson** [comment]
@guptaji048 GitHub issues are meant for reporting bugs with the challenges.  Please use [our forum](https;//www.freecodecamp.org/forum) for help with the challenges/certification projects code.

Thank you.
