### ISSUE TITLE
The test to check the action on form is failing

### ISSUE THREAD

**Issue by rajendrach** [freeCodeCamp/testable-projects-fcc#1003]
Product Landing pafe

#### Issue Description
The test to test the action element for form with form id="action" is failing even after me having the action attribute with right URL 
 

#### Browser Information
Chrome

- Browser Name, Version:
- Operating System:
- Mobile, Desktop, or Tablet:Desktop

#### Your Code / Link to Your Pen

```

<form id="form" action="https://www.freecodecamp.com/email-submit">

https://codepen.io/rajendrach/pen/wvvYbqE

```

#### Screenshot
![Screen Shot 2019-11-14 at 4 26 05 PM](https://user-images.githubusercontent.com/12751421/68901474-9c79b000-06fb-11ea-9187-7a30bb2fef22.png)

**Comment by RandellDawson** [comment]
@rajendrach GitHub issues are only meant to be used for reporting bugs.  For help with your project code, please use [our forum](https;//www.freecodecamp.org/forum).

Thank you.

**Comment by rajendrach** [comment]
Sorry, I was trying to report the bug in the testing script it is not able to validate, Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by RandellDawson** [comment]
There is no bug.  Your code is not correct.

**Comment by rajendrach** [comment]
Okay thanks will look into it

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
