### ISSUE TITLE
Faulty tests in Pomodoro Clock Project

### ISSUE THREAD

**Issue by johngicharu** [freeCodeCamp/testable-projects-fcc#1005]
#### Issue Description

Multiple tests are failing despite the application working as expected and the variables, classes and id's displaying as required. 

#### Browser Information

- Browser Name: Firefox, Version: 70.0.1
- Operating System: Ubuntu, 19.04
- Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen
https://codepen.io/johngicharu/pen/WNNLvya

**Comment by RandellDawson** [comment]
Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects.  If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.  GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.

Thank you for understanding.
