### ISSUE TITLE
freeCodeCamp codepen.io test says #mocha div missing and not giving back any tests or errors

### ISSUE THREAD

**Issue by tanasievlad246** [freeCodeCamp/testable-projects-fcc#1007]
https://codepen.io/tanasievlad246/pen/YzKmoKV

On the pen above, i just get the button that was supposed to tell what tests i passed to be gray and say load tests.

**Comment by kroham2019** [comment]
Same thing is happening to me, along with a banner that says
A referer from CodePen is required to render this page view, and your browser is not sending one (more details).

**Comment by gaopidev** [comment]
Same for me

**Comment by Annie4Star** [comment]
January 26, 2020.  I am similarly running into this issue.  I'm trying to do the survey form.  None of the tests are loading.

![image](https://user-images.githubusercontent.com/20718565/73148403-31007700-408a-11ea-81d7-bebe1cf8adb9.png)

**Comment by RandellDawson** [comment]
Make sure to put the test script link right before the closing body tag (`</body>`).

**Comment by Annie4Star** [comment]
I got mine to work.  @tanasievlad246 Have you tried checking your cookie settings?  A pivotal cookie was being blocked in my Chrome browser and it worked.

**Comment by tanmay2810** [comment]
#mocha div missing, add it to your document
![error](https://user-images.githubusercontent.com/64138141/79988950-e5b10580-84cc-11ea-85a6-94900e3cc151.PNG)

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
