### ISSUE TITLE
On the Drum Machine test, I scored 8/8, but when I run the log, it shows some 'wrong' things, like it needs to play the sound - which my app actually does.  I assume this is known and that's why it scores me 8/8

### ISSUE THREAD

**Issue by pauloconnell** [freeCodeCamp/testable-projects-fcc#1008]
#### Browser Information

- Browser Name, Version:
- Operating System:
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen

```



```

**Comment by RandellDawson** [comment]
@pauloconnell Can you please ask this question on [the forum](https://www.freecodecamp.org/forum).  If the consensus is that there is a bug, then feel free to request this issue to be reopened.  Please try to always use the forum first.

Thank you.
