### ISSUE TITLE
Not able to use test Suit

### ISSUE THREAD

**Issue by Nims5** [freeCodeCamp/testable-projects-fcc#1009]
#### Browser Information

Hi.. I am not able to run test suit.
- Browser Name, Version: Google Chrome
- Operating System: Windows 7
- Mobile, Desktop, or Tablet: Laptop

#### Your Code / Link to Your Pen
https://codepen.io/nims5/full/ExxzWxj

https://codepen.io/nims5/full/ExxzWxj
```



```

**Comment by tbushman** [comment]
It seems to be working fine. There are three errors in your code. The first line of each expanded error message has some clues. Thank you.
