### ISSUE TITLE
Issue with Technical Documentation Page

### ISSUE THREAD

**Issue by NormanEWright** [freeCodeCamp/testable-projects-fcc#101]
#### Issue Description

When I run the tests for Technical Documentation Page project I get an error for Layout Test 1:

1.  On regular sized devices (laptops, desktops), the element with id="navbar" should be shown on the left side of the screen and should always be visible to the user. 

The element with id="navbar" is shown on the left side of the screen for regular sized devices.

#### Browser Information

* Using the latest version of Chrome
* Mac OS Sierra version 10.12.5

#### Your Code / Link to Your Pen

[View the Technical Documentation Page](https://normanewright.github.io/technical-documentation-page/)
 
 
 
```

#### Screenshot
<!-- Add a screenshot of your issue -->
![Screenshot](http://normanewright.com/wp-content/uploads/2017/06/technical-doc-page-screenshot.png)

**Comment by tbushman** [comment]
@NormanEWright I reproduced the error only with a window resized to < 850px wide. The error message contains the additional info: 'Please run this test in a larger window (before any media queries) '. I think that should close this issue.

**Comment by tbushman** [comment]
Reopening because it looks like the screenshot referenced by @NormanEWright is erroring on a wider screen. I was not able to reproduce the error in Chrome / OS Sierra.

**Comment by NormanEWright** [comment]
I just checked the test results on the updated page, all tests are passing now. Thanks.

[View the Technical Documentation Page](https://normanewright.github.io/technical-documentation-page/)

**Comment by tbushman** [comment]
OK. Thank you.
