### ISSUE TITLE
My markdown previewer works fine but can't pass two of the requirements 

### ISSUE THREAD

**Issue by Summerflowerling** [freeCodeCamp/testable-projects-fcc#1011]
#### Issue Description

Hi~ I am trying to build the markdown previewer. It seems working fine but when running the test, I can’t pass these:

User Story #3:**  When I enter text into the  `#editor`  element, the  `#preview`  element is updated as I type to display the content of the textarea.
User Story #4:**  When I enter GitHub flavored markdown into the  `#editor`  element, the text is rendered as HTML in the  `#preview`  element as I type (HINT: You don't need to parse Markdown yourself - you can import the Marked library for this: https://cdnjs.com/libraries/marked).

#### Browser Information

- Browser Name, Version: chrome
- Operating System: MacOs
- Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```

My codepen page: [links](https://codepen.io/Summerflower/pen/QWWRqdy)


```

**Comment by RandellDawson** [comment]
Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects.  If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.  GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.

Thank you for understanding.

**Comment by Summerflowerling** [comment]
I see, sorry about it.
However, there was one time when I tried to run it with the tester it said "There is something wrong, please write an email to us." It only showed one time and after that the tester seems still working, so I ignored the message. Now my page works fine but still can't pass it; so was wondering if the error message would be the case?
(So far no one said anything about my post.)
