### ISSUE TITLE
I am facing this bug for the testable projects fcc

### ISSUE THREAD

**Issue by meeramenon07** [freeCodeCamp/testable-projects-fcc#1012]
#### Issue Description

After I write my code in the forked pen, when I click on Run Test, the response is 'Referred from Pen Fork Me! FCC: Test Suite Template
What happened?

A link in this Pen has a missing `href` value, or this Pen is trying to change the document.location more details

'

#### Browser Information

- Browser Name, Version:
- Operating System:
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen

`https://codepen.io/meeramenon07/pen/VwYZMBQ`

```



```

#### Screenshot

![Screenshot (15)](https://user-images.githubusercontent.com/46912602/69899796-69474a00-13a6-11ea-9897-c5eff60f59c6.png)

**Comment by tbushman** [comment]
I was unable to reproduce the issue. Please try adding your code again.

**Comment by cpof-tea** [comment]
Try to disable all browser extensions, and then enable them one by one to find out which one proceed this error

**Comment by Shrumpf** [comment]
You should disable the "hide referrer" option in uMatrix to solve this issue. @meeramenon07

**Comment by tbushman** [comment]
#618

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
