### ISSUE TITLE
It's impossible to create a media query in this challenge

### ISSUE THREAD

**Issue by Chika-Okafor** [freeCodeCamp/testable-projects-fcc#1013]
#### Browser Information

- Browser Name, Version:
- Operating System:
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen

```



```

**Comment by RandellDawson** [comment]
Since you have not provided any further information, we are closing this issue.  If you are having troubles working on the projects, please visit [our forum](https://www.freecodecamp.org) for help.

Thank you.
