### ISSUE TITLE
No error in project code - test returns error

### ISSUE THREAD

**Issue by tbd007** [freeCodeCamp/testable-projects-fcc#1015]
#### Issue Description

Copy pasted the exact same code now from sample project that passes all tests but still receiving same error.  My code is correct, every main-section has a header and it's always the first child element, had it all double checked but still can't pass test. Can you pls check what the issue is.

#### Browser Information

- Browser Name, Version:
- Operating System:
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen
https://codepen.io/TBD007/pen/abzvvpv

```



```

**Comment by RandellDawson** [comment]
@tbd007 As I stated in the other issue you created, what response did you get back from the forum?  If none, please check there first and if members determine there is a problem with the tests, then reply back to this issue and request it to be reopened.  Please do not create a third issue for this.

Thank you.
