### ISSUE TITLE
Is the testing system working, cant seem to find bug causing issue

### ISSUE THREAD

**Issue by noelw19** [freeCodeCamp/testable-projects-fcc#1016]
#### Issue Description

Completing my final project on responsive web design and ive made working nav bar elements but according to tester, i have not completed this but they work? just wondering if it is that or just me 

#### Browser Information

 just wondering if my code is correct have been checking for errors for awhile now 

- Browser Name, Version: firefox
- Operating System: windows
- Mobile, Desktop, or Tablet: laptop

#### Your Code / Link to Your Pen - https://codepen.io/noelw19/pen/YzzmMbV

```
<nav id="navbar" class="nav">
    <ul class="nav-list">
      <li><a href="#welcome-section" id="nav-link">About</a></li>
      <li><a href="#projects" id="nav-link">Work</a></li>
      <li><a href="#footer" id="nav-link">Contact</a></li>
    </ul>
  </nav>


```

**Comment by RandellDawson** [comment]
Hi @noelw19 Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects.  If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.  GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.

Thank you for understanding.
