### ISSUE TITLE
Code pen isn't loading any of my code, what should i do? Auto-Updating Preview is enabled by default.

### ISSUE THREAD

**Issue by vukojevicc** [freeCodeCamp/testable-projects-fcc#1019]
#### Browser Information

- Browser Name, Version:
- Operating System:
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen

```



```

**Comment by tbushman** [comment]
Hello @vukojevicc , please provide some more information about the error you are experiencing. Indicate which test is failing and provide a screenshot, a code sample, or a link to your project.
