### ISSUE TITLE
Images tag

### ISSUE THREAD

**Issue by ipkipkorir** [freeCodeCamp/testable-projects-fcc#1021]
#### Issue Description

There is not test for actual existence of an image in the project. 
That is; the project passes all tests even when the image source is blank (src="")
#### Browser Information

- Browser Name, Version:
- Operating System:
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen

```



```

**Comment by tbushman** [comment]
Hello @ipkipkorir , please provide some more information about the error you are experiencing. Indicate which project and provide a code sample, or a link to your project.
