### ISSUE TITLE
#mocha error

### ISSUE THREAD

**Issue by ppagarawal** [freeCodeCamp/testable-projects-fcc#1022]
#### Issue Description
I am getting the below error when I click on Run test
#mocha div missing, add it to your document
 

I get this everytime for all the projects when I try to run the test suite

#### Browser Information
Google Chrome

- Browser Name, Version: Google Chrome Version 79.0.3945.79 (Official Build) (64-bit)
- Operating System: Windows 10 
- Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen
https://codepen.io/freeCodeCamp/pen/MJjpwO

```



```

#### Screenshot
![image](https://user-images.githubusercontent.com/6276256/71261153-aa59cb00-2362-11ea-9d0f-4e98e814b82e.png)

**Comment by RandellDawson** [comment]
Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects.  If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.  GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.

Thank you for understanding.
