### ISSUE TITLE
Finished my html and the editor section crashed

### ISSUE THREAD

**Issue by odinsrevenge** [freeCodeCamp/testable-projects-fcc#1024]
#### Issue Description

I wrote all of the html I was going to use for the Survey Form section. When I started to check back to make sure all of the tags I used were in the right spots <-div->,<-/div-> the html editing tab locked up. The result tab was working properly and hit wait a couple times in hopes of not having to redo all of that code again.
#### Browser Information

- Browser Name, Version: Google Chrome, Version 78.0.3904.108 (Official Build) (64-bit)
- Operating System: Windows 10 home
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen

https://codepen.io/freeCodeCamp/pen/MJjpwO
```



```

**Comment by RandellDawson** [comment]
Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects.  If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.  GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.

Thank you for understanding.
