### ISSUE TITLE
Form in Product Landing Page

### ISSUE THREAD

**Issue by yahyaqr** [freeCodeCamp/testable-projects-fcc#1025]
#### Browser Information

- Browser Name, Version:
- Operating System:
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen

```
link: https://codepen.io/yahyaqr/pen/MWYoEMZ

        <form id="form" action="https://www.freecodecamp.com/email-submit">
            <input id="email" type="email" class="form" placeholder="Enter your email adress"> <br>
            <input id="submit" class="form" type="submit" value="Submit">
        </form>
```

#### Screenshot

![image](https://user-images.githubusercontent.com/41809239/71484549-881eec00-283f-11ea-82ce-f928892a905a.png)

**Comment by RandellDawson** [comment]
Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects.  If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.  GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.

Thank you for understanding.
