### ISSUE TITLE
FCC #3 Front End Certification Test #7 issue

### ISSUE THREAD

**Issue by gpavanb-osi** [freeCodeCamp/testable-projects-fcc#1028]
#### Issue Description

Test #7 is not passing even though the code is correctly functioning.

#### Browser Information

- Browser Name, Version: Chrome Version 79.0
- Operating System: Windows
- Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

https://codepen.io/gpavanb-osi/pen/VwYGJWa

**Comment by jasonrsadler** [comment]
+1
http://jasonrsadler-drum-machine.glitch.me/
Same test #7

**Comment by jasonrsadler** [comment]
Ah! Found the problem:
`__triggerClickEventCaller(pad);` It looks like it might be expected that `drumPads` id is assigned to the buttons but I had it assigned to the divs. Moving the `id=drumPads` to the buttons allowed all tests to pass.

https://github.com/freeCodeCamp/testable-projects-fcc/blob/master/src/project-tests/drum-machine-tests.js#L187
`__triggerClieckEventCaller` ends up testing mouse and click events

I think it might be enough to just change the instructions to use buttons that are assigned the id `drumPads` although I would've thought those events could have hooked into `div`s as well?

cc @tbushman, @gpavanb-osi

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
