### ISSUE TITLE
Testing hangs, never completes...inordinately long?

### ISSUE THREAD

**Issue by PirateMike66** [freeCodeCamp/testable-projects-fcc#1029]
#### Browser Information

- Browser Name, Version: Chrome stable version 79.0.3945.130 (Official Build) (64-bit)
- Operating System: Lixux Mint (Trica) LTS
- Mobile, Desktop, or Tablet: Hybrid laptop/cloud

#### Your Code / Link to Your Pen
https://codepen.io/meddelaney/full/oNgQzLY

```
no error pops up, test just never completes. Button says testing doesn't change color, or give any other indication of progress. 


```

**Comment by tbushman** [comment]
@PirateMike66 Seems resolved. Tested in Chrome. Take care.
