### ISSUE TITLE
Issue with test validation section 12 - Technical Documentation Page

### ISSUE THREAD

**Issue by 5t4r8ucK** [freeCodeCamp/testable-projects-fcc#1030]
#### Issue Description
**The test fails to validate section 12 (Content):** 
_12. Each element with the class of "nav-link" should contain text that corresponds to the &lt;header&gt; text within each &lt;section&gt; (e.g. if you have a "Hello world" section/header, your navbar should have an element which contains the text "Hello world")._

**While the test does validate section 4 (Content):**
_Each &lt;section&gt; element with the class of "main-section" should also have an id comprised of the &lt;header&gt; innerText contained within it, with underscores in place of spaces. The id may include special characters if there are special characters in the respective &lt;header&gt; innerText. (e.g. The &lt;section&gt; that contains the header, "JavaScript & Java", should have a corresponding id="JavaScript_&_Java")._

The text for both sections is identical but both the header and the link use a &lt;span&gt; element within the text so I wonder if there is something not accounted for there.

#### Browser Information
Firefox 72.0.1 (64-bit)
Windows 10 Enterprise
Desktop

#### Your Code / Link to Your Pen
https://codepen.io/St4r8ucK/pen/rNaWegy
Example code for section 12 validation:
```
<a class="nav-link" href="#2.1.1_Define_the_word_space_to_suit_the_size_and_natural_letterfit_of_the_font">
                    <span>2.1.1</span>Define the word space to suit the size and natural letterfit of the font
</a>
```
Example code for section 4 validation
```
<section id="2.1.1_Define_the_word_space_to_suit_the_size_and_natural_letterfit_of_the_font" 
             class="main-section">
      <header class="section-header">
        <h2>
          <span>2.1.1</span>Define the word space to suit the size and natural letterfit of the font
        </h2>
      </header>
</secton>
```
#### Screenshot
![Capture2](https://user-images.githubusercontent.com/39564849/72976185-611df080-3dd2-11ea-9197-bbd10494f531.PNG)

**Comment by 5t4r8ucK** [comment]
Sorry had the wrong codepen linked. Now the error is reproducible. I have also noticed that if I set the css of the span element (#table-of-contents span) to display:block then the error disappears. Not sure why that should be.

**Comment by tbushman** [comment]
@5t4r8ucK Did you try omitting the `<span>` tags that surround your section numbers? In the error stack it looks like the titles are interpreted to each have a newline instead of a single space between them and their associated section numbering. Same with the `<section>` `id`s

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
