### ISSUE TITLE
im having problem with the seventh rule of building a tribute page

### ISSUE THREAD

**Issue by mcakiqi** [freeCodeCamp/testable-projects-fcc#1033]
Down is my code tell me if ive done any mistakes or its just a bug in the web.

thanks!!!1

<a
        id="tribute-link"
        href="https://globalrust.org/page/dr-norman-borlaug"
        target="_blank"
        >Click here for more</a
      >.

**Comment by RandellDawson** [comment]
Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects.  If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.  GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.

Thank you for understanding.
