### ISSUE TITLE
Responsive Web Design Projects - Build a Technical Documentation Page

### ISSUE THREAD

**Issue by ACS99** [freeCodeCamp/testable-projects-fcc#1035]
#### Issue Description

The example project doesn't accomplish one of the sixteen items
https://codepen.io/freeCodeCamp/full/NdrKKL
#### Browser Information

- Browser Name, Version:
- Operating System:
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen

```



```

#### Screenshot

![Screenshot_20200128-115132](https://user-images.githubusercontent.com/45497660/73274619-9b1d3700-41c4-11ea-9d3d-aad65d3fb3b6.png)

**Comment by RandellDawson** [comment]
@tbushman If this is true, then there now is a breaking change for previous projects submitted.  It is my understanding that add or changed tests should still be backwards compatible and not break any previously submitted projects which are part of a claimed certification.

**Comment by ACS99** [comment]
> @tbushman If this is true, then there now is a breaking change for previous projects submitted. It is my understanding that add or changed tests should still be backwards compatible and not break any previously submitted projects which are part of a claimed certification.

Ok, my bad, had the wrong zooming on the page, thanks
