### ISSUE TITLE
what is this "mocha div" missing?

### ISSUE THREAD

**Issue by GePajarinen** [freeCodeCamp/testable-projects-fcc#1037]
#### Issue Description

It comes to me this "#mocha div missing, add it to your document". I was looking for others who had the same problem. I am doing as they advice, but it doesn't change. 
Is that a real problem?

#### Browser Information

- Browser Name, Version: Google Chrome Version 79.0.3945.130 (Official Build) (64-bit)
- Operating System: MacOSHight Sierra 10.13.6
- Mobile, Desktop, or Tablet: Laptop

#### Your Code / Link to Your Pen

https://codepen.io/Gesiane/pen/povYbYw
```



```

**Comment by tbushman** [comment]
This error seems resolved for your project, but it comes up at times... #1043 #1048 #1061  
Please open a new issue if you encounter it again.
