### ISSUE TITLE
its not reading the id="name" in the input feild

### ISSUE THREAD

**Issue by Tmhawary** [freeCodeCamp/testable-projects-fcc#1039]
#### Browser Information

- Browser Name, Version: firefox
- Operating System:Mac
- Mobile, Desktop, or Tablet: laptop

#### Your Code / Link to Your Pen

https://codepen.io/Tmhawary/pen/PoqYjrQ
```



```

#### Screenshot

![image](https://user-images.githubusercontent.com/24938190/73767693-71de4700-4780-11ea-9df0-c28289d2e93e.png)

**Comment by RandellDawson** [comment]
Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects.  If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.  GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.

Thank you for understanding.

**Comment by Tmhawary** [comment]
The problem is definitely NOT in the code! that is what i am saying

**Comment by RandellDawson** [comment]
It is in your code.
