### ISSUE TITLE
Spanish accents language issue

### ISSUE THREAD

**Issue by Osc100** [freeCodeCamp/testable-projects-fcc#1042]
Technical Documentation Page

#### Issue Description
I did everything well, but the system don't recognizes it because in my lenguage we use accents " ´ " " ó " and, i don't want to change it because there'll be spelling mistakes.  idk if this bug is caused for the accents or i did something wrong.

Having accents "´" in the headings sorry, english isn't my native language.
#### Browser Information
Chrome Versión 79.0.3945.130 (Build oficial) (64 bits)

- Browser Name, Version: Chrome, Versión 79.0.3945.130 (Build oficial) (64 bits)
- Operating System: Windows 10
- Mobile, Desktop, or Tablet: Laptop 

#### Your Code / Link to Your Pen
https://codepen.io/Osc100/pen/MWwWbej

#### Screenshot
![image](https://user-images.githubusercontent.com/60488755/73910215-4e94c400-4874-11ea-9e05-5dcf1472bc98.png)

**Comment by tbushman** [comment]
Hello @Osc100 , sorry for the delay. The issue isn't with the accents. Accents work fine. The problem was with this section:  
Please change  
```  
<section class="main-section" >
      <header id="¿Qué_es_un_trastorno_de_ansiedad?"> <h2>¿Qué es un trastorno de ansiedad?</h2></header> 
      <h3>Es básicamente lo explicado anteriormente, una persona con un trastorno de ansiedad puede tener miedo irracional sin razón aparente, un ataque de pánico, fobia social, depende del tipo de trastornos pero básicamente todos se basan en lo mismo: ansiedad.</h3>
    </section>   
```  
to  
```  
<section class="main-section" id="¿Qué_es_un_trastorno_de_ansiedad?" >
      <header> <h2>¿Qué es un trastorno de ansiedad?</h2></header> 
      <h3>Es básicamente lo explicado anteriormente, una persona con un trastorno de ansiedad puede tener miedo irracional sin razón aparente, un ataque de pánico, fobia social, depende del tipo de trastornos pero básicamente todos se basan en lo mismo: ansiedad.</h3>
    </section>   
```  
...i.e. put the `id="¿Qué_es_un_trastorno_de_ansiedad?"` in the `<section>` element and not in the `<header` element.
