### ISSUE TITLE
#mocha div missing, add it to your document

### ISSUE THREAD

**Issue by baberbam** [freeCodeCamp/testable-projects-fcc#1043]
#### Issue Description
Error: #mocha div missing, add it to your document

When testing

#### Browser Information

- Browser Name, Version: Edge
- Operating System: Win 10
- Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
https://codepen.io/baberbam/pen/ZEGEPJo


```

**Comment by RandellDawson** [comment]
Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects.  If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.  GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.

Thank you for understanding.
