### ISSUE TITLE
Perosnal Portfolio Test Suite BUG

### ISSUE THREAD

**Issue by Wayupblessed** [freeCodeCamp/testable-projects-fcc#1044]
#### Issue Description

When click test the page open multiple tabs with 502 error (bad gateway) host error.

#### Browser Information

- Browser Name, Version: Google Chrome Version 79.0.3945.130 (Official Build) (64-bit)
- Operating System: Win 10
- Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

https://codepen.io/KennyGodfried/pen/QWweqjK?editors=1100

```



```

**Comment by petercr** [comment]
All you have to do is remove the `<html>` tags from the project and it passes all tests. 
Next time please try the Free Code Camp Forum first, thank you 👍
