### ISSUE TITLE
Not successful even when all requirements passed

### ISSUE THREAD

**Issue by devanshjshah** [freeCodeCamp/testable-projects-fcc#1046]
#### Issue Description
The test suite for the markdown previewer did not finish all the tests even when I had done everything. I have double-checked all the user stories and and have not missed out on anything. 

Running the test suite on code pen will reproduce the issue. 
#### Browser Information

- Browser Name, Version: Chrome
- Operating System: Windows
- Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

https://codepen.io/dev6799/pen/bGdeaRG
```



```

#### Screenshot

![image](https://user-images.githubusercontent.com/60310113/74962968-ed095380-5436-11ea-891c-38d7adf5231e.png)

**Comment by tbushman** [comment]
Please use hashes (atx-style) for your `<h{n}>` header elements:  
```  
const ini = `
# H1 Tag
## H2 Tag  
...  
```
