### ISSUE TITLE
I followed the link for the project and got to a completed project-all tests passed. Is this intended?

### ISSUE THREAD

**Issue by CodeByLine** [freeCodeCamp/testable-projects-fcc#1047]
#### Browser Information

- Browser Name, Version:
- Operating System:
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen

```



```

**Comment by RandellDawson** [comment]
Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects.  If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.  GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.

Thank you for understanding.

**Comment by CodeByLine** [comment]
Discovered it was my mistake. Thanks!
