### ISSUE TITLE
Viewport sizing for welcome-section

### ISSUE THREAD

**Issue by elchicofrommo** [freeCodeCamp/testable-projects-fcc#1049]
#### Issue Description
The test Layout #2 is asking the viewport be the full screen which also includes the fixed positioned header. This, however, puts the scrollable area behind a fixed nav section (see your scroll bars  https://codepen.io/freeCodeCamp/full/zNBOYG). 

I, however, have made the scrollable section below the fixed nav which puts the scrolling section below the fixed position nav (thus ignoring the fixed header as part of the scrollable section). As a result my welcome-section is height 100% - fixed nav height. It is fully within viewable section of the page. How can we fix the test to accomidate. this or even require engineers to not include any fixed position navigation into the scrollable area? 

You can see my example here: https://codepen.io/mariano-hernandez/pen/BaNpBzX

**Comment by RandellDawson** [comment]
Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects.  If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.  GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.

Thank you for understanding.

**Comment by elchicofrommo** [comment]
I know what the problem is and how to pass the test. I'm saying the test is set to force bad UX design. So how does this process work in terms of getting the test updated? I make a post on the forum and ask for support for my change. What is the metric for making a decision to adjust the test?

**Comment by RandellDawson** [comment]
> I know what the problem is and how to pass the test. I'm saying the test is set to force bad UX design. So how does this process work in terms of getting the test updated? I make a post on the forum and ask for support for my change. What is the metric for making a decision to adjust the test?

@elchicofrommo I have reopened the PR to have other mods review.  Can you please explain in detail how you think the challenge description/instructions and/or tests should be changed?

**Comment by elchicofrommo** [comment]
I don't know anymore. I just checked out apple and logitec and they both have a scrollable area that extends into the fixed menu at the top. Maybe it's just a personal preference for me. It seems to me that the scrollable area for a website shouldn't include a fixed nav at the top. so basically the scroll bar wouldn't overlay/underlay a fixed nav section, but scroll within the movable window (below the nav section). You accomplish this by setting the height of nav section to some fixed value then adjusting the height of the window (below the nav) by that fixed amount. CSS would look like :
`
body,
html {

  margin: 0px;
  height: 100%;
overflow: hidden;
}

nav {
	position: fixed;
	top: 0;
	left: 0;
	width: 100%;
	z-index: 10;
        height: 50px;
}


main {
	height: calc(100% - 50px);
	margin-top: 50px;
	overflow-x: auto;
	scroll-behavior: smooth;
}
`

and HTML looks like: 
`
<body>
 <nav> some content </nav>
<main> some more contet taking up a height larger than the viewport </main>
`

**Comment by elchicofrommo** [comment]
sorry guys, I didn't know how to use the code section markdown.

**Comment by tbushman** [comment]
@elchicofrommo Please try giving your `<main>` element `position: absolute; overflow-y: hidden;`, then putting a scrolling element inside the `<main>` element.   

```  
body,
html {

  margin: 0px;
  height: 100%;
overflow: hidden;
}

nav {
	position: fixed;
	top: 0;
	left: 0;
	width: 100%;
	z-index: 10;
        height: 50px;
}


main {
        position: absolute;
	height: 100vh;
	margin-top: 50px;
	overflow-x: auto;
        overflow-y: hidden;
}  

.scrolling {
        position: relative;
        height: 100%;
        overflow-y: scroll;
	scroll-behavior: smooth;
}
```  

```  
<body>
<nav> some content </nav>
<main><div class="scrolling">some more content taking up a height larger than the viewport </div></main></body>  
```

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
