### ISSUE TITLE
When I am clicking the 'Run Tests' button it is showing the 'Testing' button is enabled but the testing is not completing/executing. Even the samle codepen projects also are not completing test cases. Kindly suggest!

### ISSUE THREAD

**Issue by soham-mitra** [freeCodeCamp/testable-projects-fcc#1051]
#### Browser Information

- Browser Name, Version:
- Operating System:
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen

```



```

**Comment by RandellDawson** [comment]
Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects.  If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.  GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.

Thank you for understanding.

**Comment by soham-mitra** [comment]
> Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects. If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened. GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.
> 
> Thank you for understanding.

Hi, I understood that fact, but my query was that, even for the sample projects available, in that case also it is happening. So wanted to understand if there is an issue with browser or do I need to do anything. Will check in forum surely. Thanks!
