### ISSUE TITLE
id="name" doesn 't work in the second proyect of Responsive Web Design

### ISSUE THREAD

**Issue by PabloPaps21** [freeCodeCamp/testable-projects-fcc#1052]
#### Browser Information

- Browser Name, Version:
- Operating System:
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen

```



```

**Comment by RandellDawson** [comment]
Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects.  If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.  GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.

Thank you for understanding.
