### ISSUE TITLE
When I click Run Tests, it is only running 3 tests and not all tests although I have done all the parts. Please help with the bug issue.

### ISSUE THREAD

**Issue by meeramenon07** [freeCodeCamp/testable-projects-fcc#1053]
#### Browser Information

- Browser Name, Version:
- Operating System:
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen

```



```

**Comment by ojeytonwilliams** [comment]
Hi! If you have not already done so, please ask for help on the [forum](https://www.freecodecamp.org/forum/).  The users there can often help and, if not, make sure this is a bug.  In that case please link to the discussion and reopen this issue.
