### ISSUE TITLE
Technical Documentation Page

### ISSUE THREAD

**Issue by mekdimt** [freeCodeCamp/testable-projects-fcc#1059]
I have done "Technical Documentation Page exam several times and I can't seem to pass 12/16 every time I do it. What am I doing wrong. Please help
Below you will find the 4 question I can't seem to pass

#### Issue Description
10. Additionally, the navbar should contain link (<a>) elements with the class of "nav-link". There should be one for every element with the class "main-section".

12. Each element with the class of "nav-link" should contain text that corresponds to the <header> text within each <section> (e.g. if you have a "Hello world" section/header, your navbar should have an element which contains the text "Hello world").

13. When I click on a navbar element, the page should navigate to the corresponding section of the "main-doc" element (e.g. If I click on a "nav-link" element that contains the text "Hello world", the page navigates to a <section> element that has that id and contains the corresponding <header>.

#Layout
1. On regular sized devices (laptops, desktops), the element with id="navbar" should be shown on the left half of the screen. It should always be visible to the user and should remain stationary. You may need to enlarge the viewport or zoom out to ensure the navbar doesn't scroll with the page content.

#### Browser Information
Google Chrome
 Codepen

- Browser Name, Version:Google Chrome
- Operating System: win10
- Mobile, Desktop, or Tablet: Laptop

#### Your Code / Link to Your Pen
https://codepen.io/mekdim/pen/bGdLJbj

```

**Comment by RandellDawson** [comment]
@mekdimt Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects.  If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.  GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.

Thank you for understanding.
