### ISSUE TITLE
Mocha issue- wrong message given. test not running

### ISSUE THREAD

**Issue by Siegfried13** [freeCodeCamp/testable-projects-fcc#1063]
#### Issue Description

on Select Test Suite i choose tribure page and then i press run tests. the only reponse i get is 
#mocha div missing, add it to your document

#### Browser Information

- Browser Name, Version: Google Chrome 2020
- Operating System: Windows 10
- Mobile, Desktop, or Tablet: Laptop

#### Your Code / Link to Your Pen

https://codepen.io/freeCodeCamp/pen/MJjpwO?editors=1010

```



```

#### Screenshot

![image](https://user-images.githubusercontent.com/31182989/77181824-8c704380-6ad4-11ea-90fa-d59d4a4b2188.png)

**Comment by RandellDawson** [comment]
Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects.  If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.  GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.

Thank you for understanding.
