### ISSUE TITLE
Pomodoro Clock Failing all timer related Tests

### ISSUE THREAD

**Issue by saro928** [freeCodeCamp/testable-projects-fcc#1066]
#### Pomodoro Clock Failing all timer related Tests

Hi all, thank you for taking the time to read and hopefully help me with this!

My Pomodoro Clock is failing all tests related to the timer, but my timer works fine, it does the required tasks, don't know if this happens beacuse I made it using setInterval(), I hope someone can help me with this.

#### Browser Information

- Browser Name Google Chrome, Version 80:
- Windows 10:
- Desktop.

#### Your Code / Link to Your Pen

Codepen: https://codepen.io/saro928/pen/NWqvKME?editors=0010

#### Screenshot

![timer_fails](https://user-images.githubusercontent.com/46197259/77236986-c81d1300-6b91-11ea-89db-b0ed3e11da30.png)

**Comment by RandellDawson** [comment]
Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects.  If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.  GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.

Thank you for understanding.
