### ISSUE TITLE
Test Suite not running

### ISSUE THREAD

**Issue by basedantoni** [freeCodeCamp/testable-projects-fcc#1067]
#### Issue Description

When pressing the run tests button and then pressing the load tests button a pop up modal shows this message: "Run Test Suite to See Unit Tests!"

#### Browser Information

- Browser Name, Version: Brave 1.5.113
- Operating System: Windows 10
- Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

https://codepen.io/basedantoni/pen/vYOzewp

```



```

**Comment by RandellDawson** [comment]
Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects.  If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.  GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.

Thank you for understanding.
