### ISSUE TITLE
Test Failing: Pomodoro  Clock

### ISSUE THREAD

**Issue by ZaynMalloc** [freeCodeCamp/testable-projects-fcc#107]
I doubled checked my work, but I cannot seems to get tests 11, 18, and 19 to pass despite the fact that my promodoro clock already achieves the functionality of these tests. I am using google chrome Version 59.0.3071.86 64 bit in Windows 10. 

https://codepen.io/zachgacer/pen/zzZMpr?editors=1010

**Comment by tchaffee** [comment]
@ZaynMalloc Thanks for reporting this. I just ran the tests on your CodePen and was able to repeat the problems. For whoever takes this issue, note that test 11 is failing due to a timeout, and the others say "TypeError: Cannot read property '1' of null".

**Comment by tbushman** [comment]
Tested https://codepen.io/zachgacer/pen/zzZMpr?editors=1010 and found that the start_stop button only functions to start the timer, so when clicked more than once, the first setInterval keeps running. @ZaynMalloc Try checking this.state.status in startTimer() and add a conditional to either start or pause the timer based on that status.  
 
@tchaffee Also found that test 18 in pomodoro-clock-test.js (line 257) doesn't have a message associated with the assert function, so it's just returning a TypeError.

**Comment by ZaynMalloc** [comment]
I added the conditional as you recommended. The tests are still failing.
https://codepen.io/zachgacer/pen/zzZMpr

**Comment by tbushman** [comment]
Thanks. A few more tests pass after removing the duplicate id="time-left" from the parent div: 
`<div id="time-left"> 
          <span id="time-left">
            {this.convertSecondsToFormat(this.state.minutes)}
          </span>
  </div>` 
because the test looks for `document.getElementById("time-left").innerHTML` (mm:ss format) and gets the span element here. Still working on isolating other problems. Thanks for your patience.

**Comment by ZaynMalloc** [comment]
Thanks, I just removed the duplicate id="time-left". Test 11 is still failing even though the reset button resets the session length to 25 , the break length to 5, and the time-left to 25:00.

**Comment by tbushman** [comment]
OK. A few changes and you should be able to pass: 
- a typo ('sesssion'): 
```
    this.state = {
      sessionMinutes: 1500,
      breakMinutes: 300,
      minutes: 1500,
      interval: "",
      mode: "sesssion",
      status: true
    };
```
- When reset, update this.state.status and this.state.mode: 
```
    resetTimer() {
        clearInterval(this.state.interval);
        this.setState({
          minutes: 1500,
          sessionMinutes: 1500,
          breakMinutes: 300,
	  status: true,
	  mode: "session"
       });
    }
``` 
- On start_stop click, only setInterval if the directive is "start", otherwise clear: 
```
    setTimer() {
        this.setState(prevState => ({
          status: !prevState.status
        }));
	if (this.state.status) {
		this.state.interval = setInterval(this.tickDown, 1000);
	} else {
	    clearInterval(this.state.interval);		
	}
    }
``` 
With these changes, all tests but the last one (audio) pass.

**Comment by tbushman** [comment]
Also this (re: this.state.mode): 
```
    <div id="timer-label">
	{this.state.mode}
    </div> 
```

**Comment by ZaynMalloc** [comment]
Thank you for the help! It is working now.

**Comment by tbushman** [comment]
Awesome. :D

**Comment by tchaffee** [comment]
@tbushman Thanks for resolving this. @QuincyLarson going forward, I have a question about the best place to help campers debug their code once it looks like these tests are correct but the camper's code has a problem. Does it make sense to ask the camper to move the discussion to gitter and to get help from other campers there? Or should we continue to help campers debug their code here on github until we are out of beta?
