### ISSUE TITLE
Test unpassed Survey Form (too much nesting elements?)

### ISSUE THREAD

**Issue by wikode** [freeCodeCamp/testable-projects-fcc#1072]
#### Issue Description

Hi, I just made the survey form challenge and a lots of test didn't pass, despite I made everything. I'm pretty sure this is because I have too much nesting. But this is for design purpose.
Is it possible to pass the challenge without removing my code ?
Thanks, have a nice day ! (sorry for my bad english)

#### Your Code / Link to Your Pen

https://codepen.io/freeCodeCamp/pen/MJjpwO

```

**Comment by AshNaz87** [comment]
Hi @wikode 

The link takes you to a CodePen project with the test suite and nothing else
