### ISSUE TITLE
Product Landing Project issue

### ISSUE THREAD

**Issue by lthao9** [freeCodeCamp/testable-projects-fcc#1079]
I have completed all the stories for the Product Landing project and passed but when I got back to the Learn page the radio button on the project is not marked. I have tried submitting it several times on different days and it still shows the same error.

This is my work enviornment.
- Browser Name, Version: Chrome
- Operating System: Windows 10
- Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen
file:///C:/Users/linda/Desktop/computer%20stuff/ProductLanding.html

Here I have 16 out of 16 for passing all the stories.
![image](https://user-images.githubusercontent.com/63131232/78600858-98644100-7808-11ea-9ee0-edd58c4fc2b5.png)

Here it shows I've completed the project.
![image](https://user-images.githubusercontent.com/63131232/78600899-a7e38a00-7808-11ea-8cb0-8b32598f3e94.png)

And back on the Learn page it's not marked as complete.
![image](https://user-images.githubusercontent.com/63131232/78600951-c21d6800-7808-11ea-8127-0feff7d10fff.png)

**Comment by RandellDawson** [comment]
@lthao9 The page must be live.  You must submit a url (not a file).  Most users use Codepen or something like it, though are you free to host the page on your own domain if you chose.
