### ISSUE TITLE
FCC: Build Product Landing Page Failed Test.

### ISSUE THREAD

**Issue by jemmamariex3** [freeCodeCamp/testable-projects-fcc#1081]
Hello,
My test says that my nav bar is not at the very top of my view port. I only have 15 px margin.. but it is saying 400+px? 

Can you please investigate.
Thank you!

![image](https://user-images.githubusercontent.com/18317799/78717937-383bd080-78d6-11ea-8842-d6ba253519c7.png)

![image](https://user-images.githubusercontent.com/18317799/78717897-29edb480-78d6-11ea-993f-a0c2b6007dda.png)

Code Pen: https://codepen.io/jemmamariex3/pen/poJMMqa

**Comment by tbushman** [comment]
@jemmamariex3 The test checks whether the `<nav>` element stays at the top in the viewport even while the rest of the page scrolls. Most students are using CSS `position: fixed;` to achieve this.

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
