### ISSUE TITLE
Pomodoro clock test

### ISSUE THREAD

**Issue by WonjoonYang** [freeCodeCamp/testable-projects-fcc#1083]
#### Browser Information

- Browser Name, Version: Chrome, Version 80.0.3987.132 (Official Build) (64-bit)
- Operating System: Mac OS
- Mobile, Desktop, or Tablet: Macbook Air 13" late 2013

#### Your Code / Link to Your Pen

```

https://codepen.io/WonjoonYang/pen/eYNwXKE?editors=0011

```

#### Screenshot
My Pomodoro clock cannot pass some tests, while it's working functionally fine, and it does what the user story required. I've uploaded the question on the forum, and fellow camper also found it weird as there's no big issue with my code. Thank you!

**Comment by davi-ao** [comment]
I'm facing the same issue. [My pen](https://codepen.io/davi-ao/pen/MNbKWO).

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
