### ISSUE TITLE
id selector in anchor tag using the id selector of a section is correct for navigating to a section of the webpage but it is not accepting it 

### ISSUE THREAD

**Issue by naman99sha** [freeCodeCamp/testable-projects-fcc#1085]
#### Browser Information

- Browser Name, Version:
- Operating System:
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen

```



```

**Comment by tbushman** [comment]
Hello, please provide some more information about the error you are experiencing. Indicate which test is failing and provide a screenshot, a code sample, or a link to your project.
