### ISSUE TITLE
Tweet quote react component not tagged as valid child in test

### ISSUE THREAD

**Issue by zenlex** [freeCodeCamp/testable-projects-fcc#1086]
#### Issue Description

Test ran a fail on the clickable <a> element with id "tweet-quote" inside of #quote-box. I assume this happened because I built the tweet quote button as a separate stateless functional component in the react file and nested that react element inside #quote-box. So there is a clickable <a> element inside #quote-box element with id=#tweet-quote but there's a layer of react abstraction in between. 

#### Your Code / Link to Your Pen

https://zenlex.github.io/randquote/

 render() {
        return(
                <div id='quote-box'>
                    <CSSTransitionGroup
                    transitionName="fadeboth"
                    transitionEnterTimeout={1000}
                    transitionLeaveTimeout={0}
                    transitionLeave={false}
                    >
                    <div  id='text' key={this.state.quoteindex} className='fontDefs'>"{this.state.quote}"</div>
                    <div  id='author' key={this.state.quoteindex + 1} className='fontDefs'>-{this.state.author}</div> 
                    </CSSTransitionGroup>
                    <input id='new-quote' className='fontDefs' type="submit" value="Get New Quote" onClick={this.clickHandle} />
                    <TweetIt quote={encodeURIComponent(this.state.quote)} author={this.state.author}/>  
                </div>
            )

    }    
}
    
    export default QuoteGen;

function TweetIt(props){
    return(
        <div className='icoButton'>
            <a id='tweet-quote' href = 
            {`https://twitter.com/intent/tweet?text="${String(props.quote)}"%0a-${props.author}`} target="_blank" rel="noopener noreferrer">
                <img id="twitter-logo" src="./assets/twitter_bird.png" alt="Twitter Logo"></img>
                <span className='fontDefs' id='tweet-quote'>Tweet It!</span>
            </a>
        </div> 
    )
}
```



```

**Comment by lasjorg** [comment]
@zenlex You have the `tweet-quote` id twice on two different elements, ids must be unique. Remove the `tweet-quote` id from the span element, keep it on the link.

Remove id from this span:

`<span class="fontDefs" id="tweet-quote">Tweet It!</span>`

**Comment by zenlex** [comment]
Thanks so much, I don’t know how I missed that. 

 

Much appreciated!
