### ISSUE TITLE
what is the mistake

### ISSUE THREAD

**Issue by mehta29** [freeCodeCamp/testable-projects-fcc#1088]
#### Browser Information

- Browser Name, Version:
- Operating System:
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen

```


<div class="form-group">
  <p>Any suggestion or comment</p>
  <textarea id="comments" class="form-control" name="comments" placeholder="Enter your comments here"></textarea></div>
<div class="form-group">
  <button type="submit" id="submit" class="submit-button">Submit</button></div></form></div><br>
```

**Comment by tbushman** [comment]
Hello, please provide some more information about the error you are experiencing. Indicate which test is failing and provide a screenshot, a code sample, or a link to your project.
