### ISSUE TITLE
test script Calculator

### ISSUE THREAD

**Issue by stvo1980** [freeCodeCamp/testable-projects-fcc#1090]
#### Issue Description
Project Calculator. test was passed successfully but bug stills there regarding consecutive operators.

In my project I fixed the issue with test case 5*-+5 than should be equal to 10 and got 16/16. But I did not fix other operators like * and / at that time. For sure I fixed that in my project, but  it makes sense to check if 5*-/5 provides the correct result in your script.
#### Browser Information

- Browser Name, Version:
Chrome Version 80.0.3987.163 (Official Build) (64-bit)
- Operating System: windows 10  1809 (OS Build 17763.1098)
- Mobile, Desktop, or Tablet: desktop

#### Your Code / Link to Your Pen
https://codepen.io/vecherstvo/pen/oNjgeLp?editors=1010

```



```

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
