### ISSUE TITLE
unable to run test. https://codepen.io/ldbsda85/full/abvvRwE

### ISSUE THREAD

**Issue by ldbsda85** [freeCodeCamp/testable-projects-fcc#1093]
#### Browser Information

- Browser Name, Version:
- Operating System:
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen

```



```

**Comment by ldbsda85** [comment]
I choose the tribute test to run. Nothing happens

**Comment by tbushman** [comment]
Hello @ldbsda85 , please provide some more information about the error you are experiencing. Indicate which test is failing and provide a screenshot, a code sample, or a link to your project.

**Comment by ldbsda85** [comment]
Thanks for your reply.  But since this virus thing, I've had to put it down
for a bit. Kinda hot a mess here. Ugh.
Thanks,  Lisa

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
