### ISSUE TITLE
D3: Scatterplot Graph: "y-values don't line up with y-locations" when Date object is not in isoFormat

### ISSUE THREAD

**Issue by qwen-3108** [freeCodeCamp/testable-projects-fcc#1094]
### Issue Description

The project's User Story #6 only requires that the `data-yvalue` attribute of a data point be set to a `Date` object. It does not explicitly state that the object has to be in ISO format. Hence, 

**Expected behavior**

> Test #8: The data-yvalue and its corresponding dot should align with the corresponding point/value on the y-axis

The above test should return true regardless whether a student set the `data-yvalue` attribute to take `Date` objects in ISO format or the JavaScript default format.

**Actual behavior**

Test *only* pass when `Date` object in `data-yvalue` attribute is explicitly formatted to ISO Dates. See screenshots.

**How to Reproduce**
Toggle line 66 and 67 of Javascript in the following pen
```
.attr('data-yvalue', d=>d3.isoFormat(d3.timeParse("%M:%S")(d.Time)))
//  .attr('data-yvalue', d=>d3.timeParse("%M:%S")(d.Time))

```

### Link to Pen
https://codepen.io/qwenloh/pen/dyYGzjW

### Browser Information
- Browser Name, Version: Google Chrome, 80.0.3987.163 (Official Build)(64-bit)
- Operating System: Windows 10
- Mobile, Desktop, or Tablet: Desktop

### Screenshot

Test pass when `Date` object in the `data-yvalue` attribute is in ISO format
![pass](https://user-images.githubusercontent.com/14256866/79372681-9298f900-7f88-11ea-9590-8c2f436789b1.png)

Test fail when the exact same code is tested, but without explicitly formatting the `Date` object
![fail](https://user-images.githubusercontent.com/14256866/79373023-c542f180-7f88-11ea-852f-4d610852ef41.png)

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
