### ISSUE TITLE
Survey form challenge

### ISSUE THREAD

**Issue by venkateshrnaik** [freeCodeCamp/testable-projects-fcc#1095]
#### Issue Description

This is the survey form challenge. I am getting 12/17 passes whereas all criteria have been met. Can you please help?

#### Browser Information

- Browser Name, Version: Google Chrome Version 81.0.4044.113 (Official Build) (32-bit)
- Operating System: Windows
- Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
https://codepen.io/venkateshrnaik/pen/PoPqOVQ


```

#### Screenshot

![Capture](https://user-images.githubusercontent.com/63755803/79395565-c2b3ae00-7f2e-11ea-8c93-39de004cdfeb.PNG)

**Comment by tbushman** [comment]
@venkateshrnaik You have a stray `</div>` closing tag after `input#number`  
```  
  <input id="number" name="age" type ="number" placeholder = "  Enter your Age in years" min="18" max="100" required>
  <!-- </div> --> // here
```  
Please remove stray closing tag and re-run the test. Thank you.

**Comment by venkateshrnaik** [comment]
> @venkateshrnaik You have a stray `</div>` closing tag after `input#number`

> @tbushman - Thanks for your help. I looked at my code again and do not think it is a stray closing tag. It belongs to this part of the code =>  <div id = "form-style"> ......... </div>. There are a total of 5 pairs of <div> </div> tag in this piece of code.
Is it an issue if I have multiple <div> tags? However, I did comment that </div> and ran the script and got all 17/17, but it did mess up the formatting. Thanks - Venkatesh


> 
>   <input id="number" name="age" type ="number" placeholder = "  Enter your Age in years" min="18" max="100" required>
>    // here
> ```
> 
> Please remove stray closing tag and re-run the test. Thank you.

**Comment by venkateshrnaik** [comment]
> > @venkateshrnaik You have a stray `</div>` closing tag after `input#number`
> 
> > @tbushman - Thanks for your help. I looked at my code again and do not think it is a stray closing tag. It belongs to this part of the code =>   ......... . There are a total of 5 pairs of   tag in this piece of code.
> > Is it an issue if I have multiple  tags? However, I did comment that  and ran the script and got all 17/17, but it did mess up the formatting. Thanks - Venkatesh

So I put everything in one <div>...</div> container and it passed. Can you please help me to understand why is that? Thanks a lot! :)
> 
> > // here
> > ```
> > Please remove stray closing tag and re-run the test. Thank you.

**Comment by tbushman** [comment]
@venkateshrnaik the opening / closing tags were mixed up. Glad you got it working.
