### ISSUE TITLE
My portfolio should have a link with an id of "profile-link", which opens my GitHub or FCC profile in a new tab.

### ISSUE THREAD

**Issue by nishthasharma09** [freeCodeCamp/testable-projects-fcc#1096]
#### Browser Information

- Browser Name, Version:
- Operating System:
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen

```



```

**Comment by tbushman** [comment]
Hello, please provide some more information about the error you are experiencing. Indicate which test is failing and provide a screenshot, a code sample, or a link to your project.
