### ISSUE TITLE
Reporting Bug - Personal Portfolio 

### ISSUE THREAD

**Issue by S36F4UL7** [freeCodeCamp/testable-projects-fcc#1099]
When i run tests provided by freeCodeCamp script, i have 11/12 success. On that one failure it says that i do not have link with id "profile-link" (#content 8.). I have anchor tag with id = "profile-link" that goes to FCC github page when clicked, so i don't understand what i'm doing wrong.
![Screenshot from 2020-04-19 14-23-18](https://user-images.githubusercontent.com/44125315/79687780-f140ca00-8249-11ea-88e7-ab923837af71.png)
![Screenshot from 2020-04-19 14-27-12](https://user-images.githubusercontent.com/44125315/79687782-f43bba80-8249-11ea-97e2-d7aff4bbf6c3.png)

#### Issue Description

It happens when i run tests for personal portfolio page.

#### Browser Information

- Browser Name, Version: Opera 67.0.3575.137
- Operating System: Linux Ubuntu 18.04.4 LTS
- Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

https://codepen.io/Dzon_/pen/rNOLqbL
```



```

**Comment by jeremyfiel** [comment]
Your misspelling of "taget" in your profile-link is causing the error.

**Comment by S36F4UL7** [comment]
I wouldn't notice that misspelling in 100 years i think. Thank you.
