### ISSUE TITLE
an error in test case

### ISSUE THREAD

**Issue by tanmay2810** [freeCodeCamp/testable-projects-fcc#1105]
sir i had created a tribute page as  you had mentioned.
![error](https://user-images.githubusercontent.com/64138141/79974290-ae375e80-84b6-11ea-8310-86d2a0f000a1.PNG)

**Comment by tbushman** [comment]
Hello, please provide some more information about the error you are experiencing. Indicate which test is failing and provide a screenshot, a code sample, or a link to your project.

**Comment by tanmay2810** [comment]
#mocha div missing add it to your document. It has been solve thank you @tbushman for asking I just reinstalled chrome and it worked
