### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mywebpixie** [freeCodeCamp/testable-projects-fcc#1107]
#### Issue Description
says input needs id="name" , but there is an id "name".

#### Browser Information

- Browser Name, Version: Chrome latest
- Operating System: Windows 10
- Mobile, Desktop, or Tablet: Asus Laptop

#### Your Code / Link to Your Pen
   <label for="name" id="name-label">Your Name</label>
<input type="text" id="name" placeholder="name please">

**Comment by tbushman** [comment]
Hello, please provide some more information about the error you are experiencing. Indicate which test is failing and provide a screenshot, a code sample, or a link to your project.

**Comment by mywebpixie** [comment]
Thanks for responding, I found the error.Regards, Lydie El 29 abr. 2020 0:26, Tracey Bushman <notifications@github.com> escribió:
Hello, please provide some more information about the error you are experiencing. Indicate which test is failing and provide a screenshot, a code sample, or a link to your project.
