### ISSUE TITLE
No media query ued

### ISSUE THREAD

**Issue by temitolawilliams** [freeCodeCamp/testable-projects-fcc#1109]
Technical documentation code issue

#### Issue Description
my code keeps saying at least one media query should used when infact i used more than 1 media query

#### Browser Information
i preview my work with google chrome

- Browser Name, Version:Google Chrome, Version 80.0.3987.163 (Official Build) (64-bit)

- Operating System: windows 7
- Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

@media screen and (max-width: 700px) {
  .sidebar {
    width: 100%;
    height: 200px;
    position: top;
  }
    .sidebar-item{
        float: none;
    }  
  main{
      position: absolute;
      top: 200px;
      margin-top: 300px;
  }
}

```

#### Screenshot

<!-- Add a screenshot of your issue -->
![image](https://user-images.githubusercontent.com/54205070/80315527-05f40380-87f0-11ea-89c0-8d0634f96a61.png)
![image](https://user-images.githubusercontent.com/54205070/80315536-1310f280-87f0-11ea-91e9-f3862e82c7ad.png)

**Comment by tbushman** [comment]
Hello @temitolawilliams This is possibly due to running code without a server. Please see the end of the discussion on the PR, #1092

**Comment by temitolawilliams** [comment]
Thanks tracey,
It worked perfectly well.
i guess that it should be added in the info for every project, informing
who ever would be coding from their local host that some test wont pass
till server is installed. VS studio code was pretty easy to fix. just
google it and install.

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
