### ISSUE TITLE
product landing page

### ISSUE THREAD

**Issue by KAnthony29** [freeCodeCamp/testable-projects-fcc#1115]
#### Browser Information

- Browser Name, Version:
- Operating System:
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen

```the page is not loading completely; i cannot fork the the site.
when i click to it it opens to a blankpage


```

**Comment by Sky020** [comment]
Hello there. Could you be more specific as to what you are clicking on, and what you are trying to do?

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
