### ISSUE TITLE
[Responsive web design projects] Product landing page

### ISSUE THREAD

**Issue by frank-tran** [freeCodeCamp/testable-projects-fcc#1119]
#### Issue Description

The codepen url seems to be not working properly. It is basicially empty without the screen to code and test.

#### Browser Information

- Browser Name, Version: Chrome Version 81.0.4044.129 (Official Build) (64-bit)
- Operating System: Windows 10
- Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen
https://codepen.io/freeCodeCamp/full/MJjpwO

```
![image](https://user-images.githubusercontent.com/53467943/81161670-1eb1a580-8fb6-11ea-84d7-065a781857bd.png)



```

**Comment by Sky020** [comment]
Hello there.

In general, for issues like this, I recommend opening a topic on the [forum](https://www.freecodecamp.org/forum). Reason being, this is not an issue with the source code.

The link is directing you to the _full_ view of the Pen. You should be able to select _Change View_, then _Editor View_, and this will take you to where you can edit the code:
![image](https://user-images.githubusercontent.com/51722130/81176769-890a1c00-8f9d-11ea-8090-44665f9e3db9.png)

Remember to _FORK_ the project, and work on your own copy.

Hope this helps. I am closing this issue.
