### ISSUE TITLE
dada

### ISSUE THREAD

**Issue by lzhang2020** [freeCodeCamp/testable-projects-fcc#1121]
#### Browser Information

- Browser Name, Version:
- Operating System:
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen

```



```

**Comment by lzhang2020** [comment]
okso https:///

**Comment by Sky020** [comment]
As this issue does not contain any information, I am closing it. If you have a question, I recommend opening a topic of the [forum](https://www.freecodecamp.org/forum).
