### ISSUE TITLE
Problem with Tribute page test

### ISSUE THREAD

**Issue by Bryndu** [freeCodeCamp/testable-projects-fcc#1124]
![Screenshot (9)](https://user-images.githubusercontent.com/65012187/81386807-89292980-910d-11ea-9f05-2dcdda933775.png)

#### Issue Description: I have run a test on the tibute page codepen but failed on the 2nd user storey "element with id "title".
However this has been added in my code - see screen shot. I can't seem to find where the code error is.

#### Browser Information: I am using Firefox - all other 'user storey' tests pass.

- Browser Name, Version: Firefox v. 76.0
- Operating System: Windows 10
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen: 

```



```

**Comment by Sky020** [comment]
Hello there,

In general, I recommend you open issues like this on the [forum](https://www.freecodecamp.org/forum), as this does not have anything to do with the _Test Suite_ or the source code, but your code. Be sure to include a link to your project.

In your case, you are asked to give an element an `id` equal to `test`. You have given one an `id` of `Test`.

I am closing this issue.
