### ISSUE TITLE
Build a Product Landing Page

### ISSUE THREAD

**Issue by tejaswichak** [freeCodeCamp/testable-projects-fcc#1125]
Hi 
I can’t pass the Product Landing Page, I don’t understand where I’m wrong about nav-link button, this is the code,

User Story #5: When I click a .nav-link button in the nav element, I am taken to the corresponding section of the landing page.

#### Browser Information

- Browser Name, Version:
- Operating System:
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen

```
<body>
  <header id="header">
    <nav id="nav-bar">
   <img id="header-img" 
        src="/media/examples/grapefruit-slice-332-332.jpg" alt="Grapefruit slice atop a pile of other slices"> 
     <a class="nav-link" href="#infoLinks">Episodes</a>
               <a class="nav-link" href="#how-it-works">Works</a>
               <a class="nav-link" href="#moreInfo">Role</a>
           </nav>
    
  </header>
  
     <main id="main">
    
    
      <div id="coffee">
      <br>
        <br>
          <br>
      </div>   
  <section id="how-it-works">
    <iframe id="video" width="420"                height="315"                src="https://www.youtube.com/embed/tgbNymZ7v    qY" type="video">
    </iframe>
   </section>
  
  <section>
    <form id="form"     action="https://www.freecodecamp.com/email- submit">
      <label for="email">Email:</label>
      <input type="email" id="email" name="email" placeholder="Enter your email" required>
      <input name="submit" id="submit" type="submit" value="Subscribe"/>
      </form>
  </section>
  
</body>

<script src="https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js"></script>


```

**Comment by Sky020** [comment]
Hello there,

I recommend you open this as a topic on the [forum](https://www.freecodecamp.org/forum). Please remember to include a link to your CodePen. You have 3 `.nav-links` and only 1 corresponding `section`.

As this is not an issue with the Test Suite, or the code base, I am closing this issue. Thank you.

**Comment by tejaswichak** [comment]
hi i am new can tell me how i can ask for help

**Comment by Sky020** [comment]
If you head over to the [freeCodeCamp forum](https://www.freecodecamp.org/forum), you will be able to create an account (you can use the one you made on the curriculum platform (where you found the project)). and open a post, where you can  ask for help in the _Certification Help_ sub-forum.

Hope this helps
