### ISSUE TITLE
survey-form

### ISSUE THREAD

**Issue by jack12345-dot** [freeCodeCamp/testable-projects-fcc#1126]
#### Browser Information

- Browser Name, Version:
- Operating System:
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen

```



```

**Comment by Sky020** [comment]
Hello there,

Seeing as this appears to have been accidentally created, and does not have any content, I am closing this issue.

If you are looking for assistance with your freeCodeCamp projects, head over to the [forum](https://www.freecodecamp.org/forum).
