### ISSUE TITLE
Inovando

### ISSUE THREAD

**Issue by labs2018** [freeCodeCamp/testable-projects-fcc#1127]
#### Browser Information

- Browser Name, Version:
- Operating System:
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen

```



```

**Comment by Sky020** [comment]
Hello there.

I am going to assume this was accidentally created. So, I am closing this issue.

If you are looking for help, head over to the [forum](https://www.freecodecamp.org/forum).
