### ISSUE TITLE
.play() Promise causes .pause() to throw an Error

### ISSUE THREAD

**Issue by JoshuaHall** [freeCodeCamp/testable-projects-fcc#1128]
#### Issue Description

The issue happens when testing the Pomodoro Clock project. My implementation passes all tests, but after passing them I get an error in my console:

`Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22`

This is because [`HTMLMediaElement.play()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/play) is asynchronous, so `.pause()` should really be called in a `.then()` attached to the `.play()` promise.

However, following the [guidelines recommended by Google linked in the error](https://goo.gl/LdLk22) causes the tests to fail, I assume because it immediately checks if the audio was paused, not asynchronously checks.

This ideally should be fixed to encourage correct and modern coding practices.

#### Browser Information

- Browser Name, Version: Google Chrome, Version 81.0.4044.138 (Official Build) (64-bit)
- Operating System: Windows 10 Version 10.0.18363 Build 18363
- Mobile, Desktop, or Tablet: Desktop

#### Screenshot

![Image of the tests passing with the error in the console](https://i.imgur.com/wItaPSU.png)

**Comment by JoshuaHall** [comment]
[https://github.com/JoshuaHall/pomodoro-clock](https://github.com/JoshuaHall/pomodoro-clock)

Link to my implementation.

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
