### ISSUE TITLE
Video not detected by running Product Landing Page tests

### ISSUE THREAD

**Issue by JethroSmylee** [freeCodeCamp/testable-projects-fcc#1129]
#### Issue Description

Running test number 6 on the Landing Page Project doesn't detect the embedded video in my Pen

#### Browser Information

- Browser Name, Version: Mozilla Firefox 76.0.1 (64bits)
- Operating System: Windows 10
- Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

https://codepen.io/JethroSmylee/pen/vYNaZPg
```<!-- VIDEO SECTION -->
<div id="video" class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">Video</h1>
  <iframe id="video" width="560" height="315" src="https://www.youtube.com/embed/1TJ08caetkw" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  <p class="lead">Quickly build an effective video section for your potential customers with this Bootstrap example. It’s built with default Bootstrap components and utilities with little customization.</p>
</div>
```

#### Screenshot

![Screenshot_Landing_Page_Test_Issue](https://user-images.githubusercontent.com/28784861/81927825-97cb8100-95e4-11ea-82dd-803d8553bb21.png)

**Comment by Sky020** [comment]
Hello there,

In general, I recommend you open up an issue like this in the [forum](https://www.freecodecamp.org/forum) as this is not an issue with the source code, or the test suite, but your code.

In the above example, you have a `div` with an `id="video"` as well as the `iframe` with the same `id`. In HTML the `id` attribute must be unique. This is confusing the tests, as they are noticing the first element with an `id="video"`, which is not an `iframe`.

I am closing this issue. Thank you.
