### ISSUE TITLE
On test 'product landing page' shows me a lot of things like i didn't do even if i done it

### ISSUE THREAD

**Issue by Milan432** [freeCodeCamp/testable-projects-fcc#1139]
#### Browser Information

- Browser Name, Version:
- Operating System:
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen

```



```

**Comment by Sky020** [comment]
Hello there,

As this issue contains no information, I will assume you accidentally opened it. If you have any queries, I recommend you use the [forum](https://www.freecodecamp.org/forum).

As such, I am closing this issue. Thank you.
