### ISSUE TITLE
D3 Scatter Plot

### ISSUE THREAD

**Issue by sa-mm** [freeCodeCamp/testable-projects-fcc#114]
(fixed typo)
#### Issue Description

Hello!

I have a concern regarding the tests for the D3 Scatter Plot. They seem to be assuming that we use `d3.scaleLinear()`while plotting the data points, as opposed to something like `d3.scaleTime()`. This seems odd to me given that we’re plotting minutes and years.

Specifically, test 5 says,

> Each dot should have the properties "data-xvalue" and "data-yvalue" containing their corresponding x and y values.

This is easy enough to fulfill if you’ve used `d3.scaleTime()`. When setting each of these properties just pass the same datum to the same scale/function as you did with the corresponding `cx` or `cy` attribute.

However, the next test will fail, then.

Test 6:

> The data-xvalue and data-yvalue of each dot should be within the range of the actual data.

If I’m understanding things correctly, then passing `1995` to the `yScale` I've set up returns `119`, which is outside whatever constants have been set as the minimum (1990?) and maximum years.

As it stands, I don’t see how I can pass all of the tests while using `scaleTime()`, which could be a recurring issue for people since they'll gravitate towards `d3.scaleTime()` when dealing with time.

Am I understanding this correctly?

#### Your Code / Link to Your Pen

[Github](https://github.com/sa-mm/scatterplot)
[Demo](http://fcc-scatterplot.surge.sh)

**Comment by tbushman** [comment]
@tchaffee I tested both scaleLinear() and scaleTime() in @sa-mm 's code and get a truncated year (i.e. 119 instead of 1990) for xScale(dates[0]). No idea yet why...

**Comment by tbushman** [comment]
Ok, I misunderstood what xScale was returning, but it is within your range (in pixels, not years as I misunderstood). Both scaleLinear() and scaleTime() should return 119, an expected pixel value.

**Comment by sa-mm** [comment]
Thanks for looking into this.

**Comment by tbushman** [comment]
NP. :)
