### ISSUE TITLE
2 Audio tests fail, but appear to be functioning

### ISSUE THREAD

**Issue by zenlex** [freeCodeCamp/testable-projects-fcc#1140]
#### Issue Description

All tests pass, timer visibly reads 00:00 and sound function call is the first thing to happen when that test is true. Sound also demonstratably pauses and rewinds to (0) when the reset or start/stop buttons are pressed but those 2 tests are failing. 

#### Browser Information

- Browser Name, Version: Chrome v 83.0.4103.61
- Operating System: Windows 10
- Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen
https://github.com/zenlex/pomodoro
```



```

**Comment by tbushman** [comment]
@zenlex The audio tests are limited to `<audio>` html elements. Instead of `this.beep = new Audio(..)`, please try `const beep = document.getElementById('beep')`, then `beep.play()`, etc.

**Comment by zenlex** [comment]
thanks tbushman - that fixed it.
