### ISSUE TITLE
product-landing-page

### ISSUE THREAD

**Issue by adrienneeaston** [freeCodeCamp/testable-projects-fcc#1141]
#### Issue Description

Test #12 shows as "passing" but I haven't doe anything to connect the email to any mock page.

#### Browser Information

- Browser Name, Version: Chrome
- Operating System: windows
- Mobile, Desktop, or Tablet: dektop

#### Your Code / Link to Your Pen

This is all I have for the form element. I don't think #12 should be passing yet:

      <form id="form" action="">
        <input type="email" name="email" id="email" placeholder="email address">
        <input id="submit" type="submit">
      </form>

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
