### ISSUE TITLE
Usability: Confusing test runner labels lead to "false negative" tests

### ISSUE THREAD

**Issue by jevakallio** [freeCodeCamp/testable-projects-fcc#1142]
I was helping a frustrated learner who couldn't figure out why the tests keep failing even when they're doing the wrong thing. Turns out this is a minor usability issue.

#### Issue Description

The label for test summary button is "Tests 9/10", and the legend next to the button indicates that the color of the button describes whether the tests are passed or failed. 

So, when **any** tests are failing, the button is red, so the learner read it as "9/10 failed".

#### Screenshot

<img width="320" alt="Screenshot 2020-05-25 at 15 21 58" src="https://user-images.githubusercontent.com/1203949/82821205-92e7b680-9e9b-11ea-96b3-9fa200636391.png">

#### Suggested fix

Easy fix would be to change the button label to explicitly say "9/10 tests passed"

<img width="321" alt="Screenshot 2020-05-25 at 15 25 05" src="https://user-images.githubusercontent.com/1203949/82821439-0a1d4a80-9e9c-11ea-90b7-4371e9a03d84.png">

**Comment by jevakallio** [comment]
Submitted a single line UI text fix at https://github.com/freeCodeCamp/testable-projects-fcc/pull/1143

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
