### ISSUE TITLE
The FCC test suite is flagging two errors on the FCC pomodoro clock

### ISSUE THREAD

**Issue by sriramvsharma** [freeCodeCamp/testable-projects-fcc#1145]
#### Issue Description

Hit "Run Tests" on the FCC App: 
https://codepen.io/freeCodeCamp/pen/XpKrrW?editors=0010

Only 27/29 tests pass. 

#### Browser Information

- Browser Name, Version: Chrome
- Operating System: MacOS Mojave
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen

```
https://codepen.io/freeCodeCamp/pen/XpKrrW


```

#### Screenshot

![image](https://user-images.githubusercontent.com/6435829/83442552-333e5d80-a3fd-11ea-9551-84cb25d24882.png)

![image](https://user-images.githubusercontent.com/6435829/83442575-3b969880-a3fd-11ea-8f28-6d25649a50a5.png)

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
