### ISSUE TITLE
Update audio file link for Pomodoro Clock example project

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/testable-projects-fcc#1146]
@scissorsneedfoodtoo @tbushman

The current link used for the [Pomodoro Clock example project](https://codepen.io/freeCodeCamp/pen/XpKrrW) on Codepen does not work.

```
GET https://www.peter-weinberg.com/files/1014/8073/6015/BeepSound.wav net::ERR_CERT_COMMON_NAME_INVALID

pen.js:166 Uncaught (in promise) DOMException: The element has no supported sources.
```

I made a PR on the CDN repo, after it has been approved we can update the link on Codpen.
https://github.com/freeCodeCamp/cdn/pull/50

**Comment by lasjorg** [comment]
@scissorsneedfoodtoo When you have time, can you update the Codepen?

Here is the new file and where it need to be changed, link to the project is in the first post.

New audio file
https://raw.githubusercontent.com/freeCodeCamp/cdn/master/build/testable-projects-fcc/audio/BeepSound.wav

Line: 212

From:

```
<audio
  id="beep"
  preload="auto"
  src="https://goo.gl/65cBl1"
  ref={(audio) => {
    this.audioBeep = audio;
  }}
/>
```

To:

```
<audio
  id="beep"
  preload="auto"
  src="https://raw.githubusercontent.com/freeCodeCamp/cdn/master/build/testable-projects-fcc/audio/BeepSound.wav"
  ref={(audio) => {
    this.audioBeep = audio;
  }}
/>
```

**Comment by scissorsneedfoodtoo** [comment]
@lasjorg, thank you for this fix! Sorry for the delay.

Just updated the project on [CodePen](https://codepen.io/freeCodeCamp/pen/XpKrrW?editors=1010).
