### ISSUE TITLE
Glitch/Twitch API Down

### ISSUE THREAD

**Issue by MikeIke24** [freeCodeCamp/testable-projects-fcc#115]
#### Issue Description

The API that FCC recommends to use for the Twitch Streaming app seems to be down. It's not just an issue with my project because I can't access the website's API at all. I was just wondering if this was a known issue, but also it might cause a lot of people's project to stop working.

#### Browser Information

* Browser Name, Version: Chrome, latest version.
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
 https://codepen.io/MikeIke/full/bREEyX
 
 
```

#### Screenshot

![image](https://user-images.githubusercontent.com/19289881/27519995-c2dd1d30-59c5-11e7-8f30-2ff50c7ba166.png)

**Comment by tchaffee** [comment]
@MikeIke24 Thanks for reporting this. I just looked at your project and it seems to be working now? 

Even the best APIs do *occasionally* go down however if it happens a lot we would need to take this into consideration. If your project is working now, I think we can close this issue and then keep a close eye on whether it was a one time thing or if Twitch is having regular problems with API availability. @tbushman what do you think?

**Comment by MikeIke24** [comment]
Yeah it seems to work now, thank you though, I'll close this.
