### ISSUE TITLE
#Layout/1 test for Product Landing Page failing despite implementation meeting user story

### ISSUE THREAD

**Issue by dvbsknd** [freeCodeCamp/testable-projects-fcc#1152]
#### Issue Description

My implementation meets the business requirement, however due to the way the test has been implemented it fails. I'm not quite able to understand what the test is trying to assert in order to pass, so not sure how to change my implementation to pass it, but I have met the literal requirement which is:

> The navbar should always be at the top of the viewport.

#### Browser Information

- Browser Name, Version: Chrome 83.0.4103.61
- Operating System: MacOS 10.15.4

#### Your Code / Link to Your Pen

https://codepen.io/dvbsknd/full/eYpqZoe

#### Screenshot

As you can see, the nav bar is sticky but the test doesn't agree.

![image](https://user-images.githubusercontent.com/1005395/83691840-3a9c7b80-a636-11ea-85af-cd6b8edf2aa6.png)

![image](https://user-images.githubusercontent.com/1005395/83691888-4e47e200-a636-11ea-9d33-69b547d4c631.png)

![image](https://user-images.githubusercontent.com/1005395/83691920-5738b380-a636-11ea-9602-e81588359533.png)

![image](https://user-images.githubusercontent.com/1005395/83691980-78999f80-a636-11ea-8d45-8c9595471c7c.png)

![image](https://user-images.githubusercontent.com/1005395/83692014-8818e880-a636-11ea-9cb9-08826cd2662a.png)

**Comment by Sky020** [comment]
Hello there,

You have definitely met the requirement. However, the tests are not robust enough to account for the use of JavaScript to set the `position: fixed;`.

Easiest fix is for you to use plain CSS for the `#header` element.

I will leave this issue up for discussion, but, seeing as this is a project from the HTML & CSS portion of the curriculum, you can understand why the tests were never written to account for this sort of implementation.

**Comment by dvbsknd** [comment]
Thanks @Sky020, that's a very fair assessment. I've actually already completed the subsequent JS module, which most people probably would do after this one, so you're right that a JS solution is unexpected here. I'll attempt a CSS-only solution and leave you to decide whether to close the issue or not.

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
