### ISSUE TITLE
freecodecamp "survey form" challenge.

### ISSUE THREAD

**Issue by yonahaile** [freeCodeCamp/testable-projects-fcc#1153]
I just got stuck on the first test for the "survey form" challenge. The question is
   1. Can I see a title with id="title" in H1 sized text." 
may answer is :

<div id="main">
  <div id="title">
  <h1>title</h1>
  </div>
</div>

Can anyone help me point out where I made the error? Thanks!
OS-Windows 10
Browser-Chrome
Laptop

**Comment by Sky020** [comment]
Hello there,

In general, I recommend you open an issue like this on the [forum](https://www.freecodecamp.org/forum). Be sure to include a link to your project.

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
