### ISSUE TITLE
My tester is not testing.

### ISSUE THREAD

**Issue by Chris-webuser** [freeCodeCamp/testable-projects-fcc#1156]

**Comment by tbushman** [comment]
Hello, please provide some more information about the error you are experiencing. Indicate which test is failing and provide a screenshot, a code sample, or a link to your project.

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
