### ISSUE TITLE
Test Item #13 Product Landing Page Assignment

### ISSUE THREAD

**Issue by jsprague23** [freeCodeCamp/testable-projects-fcc#1157]
#### Issue Description

When attempting to complete test item #13, it asks to include an action attribute in the form element. Doing so doesn't pass the test. The test is only passed if it has this, as well as giving the email the name attribute. The item#13 has embedded in the 2nd line that it is expecting a name element for email, but that isn't really relevant for this item and it is confusing for the user. Perhaps if a name is required for the email putting the requirement more expressly, as well as in the item relating to the email element and not the submit element?
#### Browser Information

- Browser Name, Version: Chrome
- Operating System: Windows 10
- Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

https://codepen.io/jsprague23/pen/LYpaBYZ

```
  <form action="https://www.freecodecamp.com/email-submit" id="form">
    <input id="email" type="email" name="email" placeholder="Email Address">
    <input id="submit" type="submit">
      
  </form>

/**If you use the above form, it passes, if you use the form below it doesnt**/

<form action="https://www.freecodecamp.com/email-submit" id="form">
    <input id="email" type="email" placeholder="Email Address">
    <input id="submit" type="submit">
      
  </form>


```

**Comment by nhcarrigan** [comment]
![image](https://user-images.githubusercontent.com/63889819/83961644-fda8d280-a849-11ea-9ae4-706a1f4b8e71.png)

The test script does properly display this error to inform the user of why the test is passing.
However, a quick look through the HTML curriculum leads me to a couple of instances where the user is taught to set the name attribute, but it doesn't seem to fully explain the purpose. Might be worth re-evaluating to add that information to the curriculum? Anyone have thoughts on this?

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
