### ISSUE TITLE
[BUG] - Running Test Suite twice without page fresh throws an error.

### ISSUE THREAD

**Issue by nhcarrigan** [freeCodeCamp/testable-projects-fcc#1158]
#### Issue Description

Running the tests more than once without refreshing the page throws an error that prevents the tests from running.

To reproduce:
1. Open the FCC test pen below.
2. Select any test suite.
3. Click the "Run Tests" button.
4. Choose another test suite (optional, but issue still persists if you do.)
5. Click the "Run Tests" button a second time.

#### Browser Information

- Browser Name, Version: Chrome Version 83.0.4103.97 (Official Build) (64-bit)
- Operating System: Windows 10 Home Version 1909.
- Mobile, Desktop, or Tablet: Desktop.

#### Your Code / Link to Your Pen

[FCC Test Suite Pen](https://codepen.io/freeCodeCamp/pen/MJjpwO)
[Completed FCC Portfolio Page](https://codepen.io/freeCodeCamp/full/zNBOYG) - to show it is an issue that persists even with completed page.
#### Screenshot
Error Message:
![image](https://user-images.githubusercontent.com/63889819/83961617-adca0b80-a849-11ea-881f-cc304ccedad7.png)

**Comment by lasjorg** [comment]
I'm guessing the update to Mocha in https://github.com/freeCodeCamp/testable-projects-fcc/pull/1149 broke something.

This change in [Mocha release v7.2.0](https://github.com/mochajs/mocha/releases/tag/v7.2.0)

> #4234: Add ability to run tests in a mocha instance multiple times (@nicojs)

Sounds related.

@tbushman Should we just rollback to "mocha": "^7.1.0" or do we try to figure out what is happening? I haven't really look at it yet and I'm not familiar with the Mocha part of the test suite.

I can try to look into it but for now, it might be better to just roll back to 7.1.0. I haven't yet confirmed this is the issue though but I'm guessing it is.

**Comment by nicojs** [comment]
Hi there 👋

Sorry to have (possible) broken your test suite. Running one mocha instance multiple times worked before, but only sometimes and it was more of an undocumented feature. 

You should be able to reuse a mocha instance in mocha@7.2 with the following piece of code:

```js
const mocha = new Mocha(opts);
mocha.cleanReferencesAfterRun(false);
mocha.run(() => {
   // I want to reuse the mocha instance!
  mocha.reset();
  mocha.run(secondResult => {
    // Hooray!
  })
});
```

**Comment by lasjorg** [comment]
Hello @nicojs

I'm so sorry, I didn't mean to @ you when I posted the changelog, my bad. But thank you for posting a possible solution though, very kind of you.


And just to confirm, rolling back to 7.1.2 does seem to fix our issue.

**Comment by lasjorg** [comment]
Adding `mocha.cleanReferencesAfterRun(false);` before `mocha.run()` inside the `FCCInitTestRunner` function also fixes the issue.

I'm just not just when or where (or if) we are supposed to manually dispose of the mocha instance?

https://mochajs.org/api/mocha#cleanReferencesAfterRun
https://mochajs.org/api/mocha#dispose

**Comment by nicojs** [comment]
Great to hear it works!

The manual disposing is only needed when you want to close mocha and keep your application/process running. It's a common courtesy to let devs dispose stuff if they want. It is not needed when you are killing the process yourself (nodejs) or close your application by navigating away for example.
