### ISSUE TITLE
Test failing but everything working fine in project

### ISSUE THREAD

**Issue by ridvanaltun** [freeCodeCamp/testable-projects-fcc#1162]
#### Issue Description

Everything working fine in project but the test fails.

#### Browser Information

- Browser Name, Version: Google Chrome 83.0.4103.97 (Official Build) (64-bit)
- Operating System: Windows 10 Pro 19.09
- Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

https://codepen.io/ridvanaltun/pen/VweedGL

#### Screenshot

![1](https://user-images.githubusercontent.com/10441216/84299271-1d493f00-ab59-11ea-9f5f-21a446706eab.png)

**Comment by tbushman** [comment]
@ridvanaltun on line 244, `timer.clear();` is called while the initial `timer` state is `null`. Please add a check, i.e.:  
```
if (timer) {
   timer.clear()
}
```
