### ISSUE TITLE
My Tribute Page - User Story no 8 - Test is incorrect

### ISSUE THREAD

**Issue by Peterhf3142** [freeCodeCamp/testable-projects-fcc#1164]
## Issue Description##
1022 User case 8 fails to pass the auto tests. 

According to freebootcamp article https://www.freecodecamp.org/news/how-to-center-things-with-style-in-css-dc87b7542689 this test should be satisfied by the following css:

#img-caption{
  text-align:center;
   }
#image{
max-width: 100%;
display: block;
}
however the automatic test is only passed if the left and right margins are set as follows
#image{
  max-width: 100%;
margin-left: auto;
margin-right: auto;
display: block;
}
As these are default margins, the test should NOT require them in order to pass

#### Browser Information

- Edge: version 83.0.478.45 (Official build) (64-bit)
- Operating System: Windows 10
- Mobile, Desktop, or Tablet: surface pro 4

#### Your Code / Link to Your Pen

https://codepen.io/Peterhf/pen/pogyOJX

```



```

**Comment by Sky020** [comment]
Hello there,

In general, I recommend you open an issue like this on the [forum](https://www.freecodecamp.org/forum), as this is not an issue with the test suite, but your code.

Specifically:
1) You have some syntax errors in your HTML:
 - use `img` tag, not `image` tag, and `img` tag is self-closing.
 - Missing `>` in one of your `a` tags.
2) Once you give your `img` tag a source, you will see that the image is **not** centred, without the margin.

Also, I do not think you can apply the _news_ post directly, seeing as it does not deal with images, but _text elements_.

I am closing this issue. Thank you.
