### ISSUE TITLE
Problem in testing on 'Technical Documentation' Project

### ISSUE THREAD

**Issue by Bisrat-Aregawi** [freeCodeCamp/testable-projects-fcc#1165]
#### Issue Description
1. testing takes forever when document is changed either using media query or just retesting without changing the document.
1. checklists are fully correct on one media query and on on another.

#### Browser Information

- Browser Name, Version: 
    - Firefox ( Developer Edition version 78.0b6 ( 64-bit ) ), 
    - Chrome ( 83.0.4103.97 ( Official Build ) ( 64-bit ) )
    - Edge ( 83.0.478.45 ( Official build ) ( 64-bit ) )
    - Firefox ( 77.0.1 ( 64-bit ) )
- Operating System:
    - Windows 10 Pro 19041.264
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen
[Technical Doc (replica)] (https://codepen.io/Bisrat-Aregawi/full/RwrWgBJ)

#### Screenshot

This is when changing the size for the-
media query to kick in and also when retesting without changing any thing.
![image](https://user-images.githubusercontent.com/61229555/84540517-33443480-acfe-11ea-9144-a0c8c0f9da3b.png)

This is before media query
![image](https://user-images.githubusercontent.com/61229555/84540801-ce3d0e80-acfe-11ea-9955-7185caf3946c.png)

This is after media query
![image](https://user-images.githubusercontent.com/61229555/84540949-1a884e80-acff-11ea-9e4a-395796792a63.png)

< I found this on the technical page project but have not tested if it still behaves the same on other projects>

**Comment by Sky020** [comment]
Hello there,

Thank you, for taking the time to report this.

This is most likely connected to this issue: https://github.com/freeCodeCamp/testable-projects-fcc/issues/1158

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
