### ISSUE TITLE
The 'Test Suite' is stuck on 'Testing' and isn't completing. I don't want to refresh in case I lose progress and when I duplicate the tab, the new codePen is blank.

### ISSUE THREAD

**Issue by Tomathy7** [freeCodeCamp/testable-projects-fcc#1167]
#### Browser Information

- Browser Name, Version:
- Operating System:
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen

```



```

**Comment by Sky020** [comment]
Hello there,

Seeing as the body of this issue contains no information, it is _invalid_. Therefore, I am closing this issue.

If you would like this to be re-opened, I suggest you  edit the issue to include relevant information. Thank you.
