### ISSUE TITLE
Tree Map test 11 should see svg <title>

### ISSUE THREAD

**Issue by mrkjesus2** [freeCodeCamp/testable-projects-fcc#1169]
Using d3.append('title'') on 'mouseover' event handler with an id of 'tooltip', the test fails to see
the tooltip though it is clearly working as you can see it on the screen.  Please note that test 12 is passing so it is clearly finding the tooltip as some point.

The issue happens every time I run the test on my code

#### Browser Information

- Browser Name, Version: Chrome - version 83.0.4103.61
- Operating System: Windows 10
- Mobile, Desktop, or Tablet: Only tried on desktop

#### Your Code / Link to Your Pen
[https://codepen.io/markweig/pen/pogEGqN](url)

```
    function handleMouseOver(d) {
        d3.select(this)
            .append('title')
            .attr('id', 'tooltip')
            .attr('data-value', d => d.data.value)
            .text(d => d.data.name + '\n' + d.data.value)
    }
```

**Comment by tbushman** [comment]
See #979 for discussion. Feel free to open a pull-request with a test for `<title>` svg elements.

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
