### ISSUE TITLE
15 / 16 Tests Passed in Technical Documentation Page (HTML)

### ISSUE THREAD

**Issue by Depesh-Agarwal** [freeCodeCamp/testable-projects-fcc#1170]
#### Issue Description

In Responsive Web Designs (in HTML) is a project (4th) ' Build a Technical Documentation Page', which 15 user stories to be fulfilled. When visited the website to be used for referral and creating a similar one, it shows that 16  user stories (tests) need to pass. Also 16th test passes on the website, but when clicked on the name to see the coding behind it and then run test it shows '15 / 16 Tests Passed'
#### Browser Information

- Browser Name, Version: Microsoft Edge
- Operating System:-
- Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```

https://codepen.io/freeCodeCamp/pen/NdrKKL

```

#### Screenshot

This Screenshot is when all tests passed
![All Tests Passed](https://user-images.githubusercontent.com/67053753/84898493-f9d84400-b0c4-11ea-9801-923532e73c27.png)
But when clicked on coding part, then 1 failed
![1 Test Failed](https://user-images.githubusercontent.com/67053753/84898533-0fe60480-b0c5-11ea-9f9b-8521c138dcee.png)

**Comment by Sky020** [comment]
Hello there,

If you click on the _"Tests"_ button to view the test output, you will see this message which clearly explains the reason for the failed test:
>Please run this test in a larger window (before any media queries) : expected 801 to be above 850

I am closing this issue. Thank you.

**Not related**: Just to let you know, the latest stable release of Chrome is the recommended browser for the freeCodeCamp curriculum.
