### ISSUE TITLE
Pomodoro Clock testable project on Codepen

### ISSUE THREAD

**Issue by aubreytaylor89** [freeCodeCamp/testable-projects-fcc#1171]
#### Issue Description

My Pomodoro Clock project on Codepen is failing four tests: #Timer test 10, 12, 14, and #Audio test 1. Timer test 10 says, "Pomodoro has started but time displayed is not changing: expected '00' to not equal '00'."  The other three all say the same thing: "Timer has not reached 00:00."  My timer does reach 00:00, it does pause when start_stop is clicked, the string does display the change between Session and Break, and and audio does sound when it reaches 00:00.  Somehow the tests aren't passing.

#### Browser Information

- Browser Name, Version: Google Chrome
- Operating System: Mac OS
- Mobile, Desktop, or Tablet: Macbook Pro

#### Your Code / Link to Your Pen

https://codepen.io/aubreytaylor89/pen/NWxxbvg

#### Screenshot

<img width="1428" alt="Screen Shot 2020-06-17 at 2 38 31 PM" src="https://user-images.githubusercontent.com/28690407/84947945-51b48200-b0a8-11ea-8aef-4c2114df1233.png">

**Comment by nhcarrigan** [comment]
Taking a look at your pen, I believe the issues are caused by the 1 second delay when the timer first starts, and the 1 second delay when it starts the break segment. 

I do not believe this is a bug with the test script, but I could be wrong. 🙂

**Comment by aubreytaylor89** [comment]
Oh my goodness, I think I see what you are saying.  I will look into this further.  Thank you so much for your time and input!
