### ISSUE TITLE
Problem with a project. 

### ISSUE THREAD

**Issue by Kaczusia-14** [freeCodeCamp/testable-projects-fcc#1172]
#### Issue Description

Hi, I am trying to submit my project. 
User Story #14: My product landing page should have at least one media query.

User Story #15: My product landing page should utilize CSS flexbox at least once.

The problem is- I have written a code that contains both flexbox and media query. 

And both of those codes work- the website has been altered by them-n they do their job. 

However- the test says I don't have a flexbox or media query in my code. 

#### Browser Information

- Browser Name, Version:
- Operating System:
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen

```.forma{
	display: flex;
  	flex-direction: column;
  	align-items: center;
  	justify-content: center;
  	text-align: center;
is that not flexbox? 


@media only screen and (max-width: 600px) {
    .main-nav {
        font-size: 0.5em;
        padding: 0;

is that not a media query?? 


```

**Comment by Sky020** [comment]
Hello there,

Some things to note:
1) If you are developing locally, the tests will struggle to pick up the media queries. So, host your project somewhere, as you will have to do this to submit the project, anyway.
2) If you are running the tests whilst the media query is active, the tests will not pick it up. In your case, if you are running the tests when the screen width is less than 600px.
3) Without seeing the rest of your code, We cannot help any more.
4) This is likely not an issue with the test suite, but your code (this happens to campers often). Opening a topic on the forum, with a link to your CodePen (or similar) is your best bet of getting quick, detailed help.

I will leave this issue open for now, but do suggest you open a topic on the forum, and close this.

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
