### ISSUE TITLE
Front End Project #3, Test Item #6 Is Not Registering Correctly

### ISSUE THREAD

**Issue by patrickmiskel** [freeCodeCamp/testable-projects-fcc#1174]
### Issue Description

Front End Project #3, test item #6 is not registering correctly. It states "No audio plays when the Q key is pressed", but it seems to be working fine for me.

#### Browser Information

- Browser Name, Version: Chrome Version 83.0.4103.116
- Operating System: Microsoft Windows 7 Professional x64
- Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```

https://codepen.io/patrickmiskel/full/RwrVMGy

```

**Comment by Sky020** [comment]
Hello there,

Could you confirm if this is still an issue for you? The link you provided does not produce a pen. So, I went to your profile, and found this one that passes all of the tests:
![image](https://user-images.githubusercontent.com/51722130/85803054-40214900-b73e-11ea-9696-0292cae8222e.png)

**Comment by patrickmiskel** [comment]
Hi sorry about that, right after I sent the email I got it to work but
didn't know how to follow up. Thank you for the help.

Patrick
