### ISSUE TITLE
the section has been set to a viewport height and the navbar is at the top always ,but the run tests still does not consider it ..on my personal portfolio project

### ISSUE THREAD

**Issue by ncube-eng** [freeCodeCamp/testable-projects-fcc#1175]
#### Browser Information

- Browser Name, Version:
- Operating System:
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen

```



```

**Comment by Sky020** [comment]
Hello there,

Please provide more details, for us to debug the issue. A link to your project would be helpful.

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
