### ISSUE TITLE
My portfolio website

### ISSUE THREAD

**Issue by FirdavsiA** [freeCodeCamp/testable-projects-fcc#1177]
#### Issue Description
My portfolio website test is failing
11 correct or passing only 1 out of 12 is failing. Any idea what the 1 issue is?

#### Browser Information
Mozilla Firefox

Codepen.io 
Here is a link 
- Browser Name, Version:
- Operating System:
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen
https://codepen.io/Firdavsi_Q/pen/wvMrapo?editors=1100

```



```

**Comment by Sky020** [comment]
Hello there,

There are two things you need to change, to pass the tests. They are, however, very easy to debug. So, here is the error message from the test:
>Navbar's parent should be body and it should be at the top of the viewport : expected 50 to be close to 0 +/- 15

Now, I suggest you use the devTools to view your structure, as well as find what is causing your `#navbar` to be `50px` below the top of the viewport.

Hope this helps. Please remember to close this issue, once you correct the error.

**Comment by FirdavsiA** [comment]
Thanks.
