### ISSUE TITLE
survey form test not working

### ISSUE THREAD

**Issue by royston45** [freeCodeCamp/testable-projects-fcc#1182]
survey form test not working

The survey form test on freecodecamp is still asking for dropdown , checkbok, submit btn ,<textarea> but it is there amoung the codes

https://codepen.io/royston45/pen/yLegmpE

----------------------------------------------------------------------------------------------------------------------------------------------
here are my codes

<script src="https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js"></script>

<div class="container">
  <header id="header">
    <h1 id="title" class="text-center">Sports Survey Form</h1>
    <p id="description" class="description text-center">Thank you for taking the time to help us.</p>
  </header>
  <form id="survey-form">
    <div class="form-group">
      <label id="name-label" for="name">Name</label>
      <input
             type="text"
             name="name"
             id="name"
             class="form-control"
             placeholder="Enter your name"
             required
             />
    </div>
    
    <div class="form-group">
      <label id="email-label" for="email">Email</label>
      <input
             type="email"
             name="email"
             id="email"
             class="form-group"
             placeholder="Enter your email"
             required
             />
    </div>
    
    <div class="form-group">
      <label id="number-label" for="age">Age<span class="clue">(Optional)</span></label>
      <input
             type="number"
             name="age"
             id="number"
             min="1"
             max="100"
             class="form-control"
             placeholder="Age"       
             />
    </div>
    <div="form-group">
      <p>Do you like Sports</p>
      <label>
        <input
               name="preference"
               value="yes"
               type="radio"
               class="input-radio"
               checked
               />Yes</label>
      <label>
        <input
               name="preference"
               value="no"
               type="radio"
               class="input"
               />No</label>
    </div>
       <div="form-group">
         <p>Which of this sports do you like ?</p>
         <select id="dropdown" name="like" class="form-control" required>
           <option disabled selected value>Select favorite sports</option>
           <option value="cricket">Cricket</option>
           <option value="football">Football</option>
           <option value="basketball">Basketball</option>
           <option value="baseball">Baseball</option>
           <option value="tennis">Tennis</option>
           <option value="other">Other</option>
         </select>
    </div>
    <div class="form-group">
      <p>Would you recommend this survey to a friend?</p>
      <label>
        <input
               name="user-recommend"
               value="definitely"
               type="radio"
               class="input-radio"
               checked
               />Definitely</label>
      <label>
        <input
               name="user-recommend"
               value="maybe"
               type="radio"
               class="input-radio"               
               />Maybe</label>
      <label>
        <input
               name="user-recommend"
               value="not-sure"
               type="radio"
               class="input-radio"
               />Not sure</label>
    </div>
    <div class="form-group">
      <p>What type of tournament do like to see?</p>
      <select id="most-like" name="mostlike" class="form-control" required>
        <option disabled selected value>Tournament</option>
        <option value="internation">International tournament</option>
        <option value="Domestic">Domestic tournament</option>
        <option value="neither">Neither one</option>    
      </select>
    </div>
    
    <div class="form-group">
      <p>What is your primary interest in participating in sports activities?<span class="clue">(check all that apply)</span></p>
      <label>
        <input
               name="prefer"
               value="health-and-fitness"
               type="checkbox"
               class="input-checkbox"
               />Health and Fitness</label>
      <label>
        <input
               name="prefer"
               value="personal-interist"
               type="checkbox"
               class="input-checkbox"
               />Personal Interist</label>
      <label>
        <input
               name="prefer"
               value="entertainment-and-recreation"
               type="checkbox"
               class="input-checkbox"
               />Entertainment and Recreation</label>
      <label>
        <input
               name="prefer"
               value="sport-skills-enhancement"
               type="checkbox"
               class="input-checkbox"
               />Sport Skills Enhancement</label>
    </div>
    <div class="form-group">
      <p>Which environment do you prefer for sports activities?</p>
      <label>
        <input
               name="ask"
               value="indoor"
               type="radio"
               class="input-radio"
               checked
               />Indoor</label>
      <label>
        <input
               name="ask"
               value="outdoor"
               type="radio"
               class="input-radio"
               />Outdoor</label>
      <label>
        <input
               name="ask"
               value="no-special-preference"
               type="radio"
               class="input-radio"
               />No Special Preference</label>                                        
    </div>
    
     <div class="form-group">
      <p>comment who is your favorite player? and why?</p>
      <textarea
        id="comments"
        class="input-textarea"
        name="comment"
        placeholder="Enter your comment here..."
      ></textarea>
    </div>

    <div class="form-group">
      <button type="submit" id="submit" class="submit-button">
        Submit
      </button>
    </div>
  </form>
</div>

**Comment by Sky020** [comment]
Hello there,

In general, I recommend you open a topic on the [forum](https://forum.freecodecamp.org/), as this is not an issue with the test suite but your code.

In your case, you code contains multiple syntax errors. I suggest you use the built-in code analyser in CodePen to find some of them.

I am closing this issue. Thank you.

**Comment by royston45** [comment]
Thank you
