### ISSUE TITLE
Profile ERROr

### ISSUE THREAD

**Issue by Dayakar66** [freeCodeCamp/testable-projects-fcc#1183]
#### Browser Information

- Browser Name, Version:
- Operating System:
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen

```



```

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
