### ISSUE TITLE
My Survery Form has been deleted and replaced in a Tribute form. i finished the survery form in the morning..

### ISSUE THREAD

**Issue by MrMoshkovitz** [freeCodeCamp/testable-projects-fcc#1184]
#### Browser Information

- Browser Name, Version:
- Operating System:
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen

```



```

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
