### ISSUE TITLE
"Front End Libraries Projects - Build a Pomodoro Clock" Test Error

### ISSUE THREAD

**Issue by patrickmiskel** [freeCodeCamp/testable-projects-fcc#1185]
The code I wrote for the "Front End Libraries Projects - Build a Pomodoro Clock" project (https://codepen.io/patrickmiskel/pen/jOWaBeO?editors=0110) follows all the test requirements and functions identically to the example code (https://codepen.io/freeCodeCamp/pen/XpKrrW), but when I run the test, 13 of the 29 items in the "#Timer" and "#Audio" sections incorrectly fail. I'm not sure what the issue could be at this point other than something test system related. Thank you for the help!

#### Browser Information

- Browser Name, Version: Google Chrome Version 83.0.4103.116 (Official Build) (64-bit)
- Operating System: Microsoft Windows 7 Professional x64
- Mobile, Desktop, or Tablet: Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```

Pen: https://codepen.io/patrickmiskel/pen/jOWaBeO?editors=0110

```

#### Screenshot

![image](https://user-images.githubusercontent.com/51799016/87067524-08e47a80-c1c9-11ea-86f9-1042c4497d6c.png)

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
