### ISSUE TITLE
"D3: Bar Chart" test errors

### ISSUE THREAD

**Issue by tsunghao-huang** [freeCodeCamp/testable-projects-fcc#1186]
#### Issue Description

I believe my code should pass all the tests (14) but failed the following 2 user stories regarding TooltipTests.

User Story 12: I can mouse over an area and see a tooltip with a corresponding id="tooltip" which displays more information about the area.

User Story 13: My tooltip should have a data-date property that corresponds to the data-date of the active area.

For the tooltip, I follow the lesson from 
https://www.freecodecamp.org/learn/data-visualization/data-visualization-with-d3/add-a-tooltip-to-a-d3-element
and use the `title` element with the following code

```javascript
  svg.selectAll('rect')
     .append('title')
     .text((d) => `Date: ${d[0]} \n \$${d[1]} Billion`)
     .attr('id', 'tooltip')
     .attr('data-date', (d) => `${d[0]}`)
     .attr('data-gdp', (d) => `${d[1]}`)
```

and the tooltips (with required property data-date and id='tooltip') are shown correctly when I hovered.

#### Browser Information

- Browser Name, Version: Firefox Developer Edition, Version 79.0b6 (64-bit)
- Operating System: macOS
- Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

Link to the pen: https://codepen.io/tsunghao-huang/pen/MWKGJOJ

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
