### ISSUE TITLE
Portfolio Project - User Story 7

### ISSUE THREAD

**Issue by Tomathy7** [freeCodeCamp/testable-projects-fcc#1188]
Hi FCC!

I'm a newbie so there's maybe a simple error preventing this. I am completing the Personal Portfolio Project and cannot seem to make the navigation bar work. 

I've tried using a few different techniques, learned from earlier projects/tasks as well as a few Google suggestions but can't get anywhere. I was also getting a 'boomboom/v2 Bad Path' error code when trying to link up the 'Welcome-section' tag, that I've since removed. Here is the limited code I've added so far.
```
<script src="https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js"></script>

<header>
<nav id="navbar">
  <ul>
      <li><a href="#projects">Projects</a></li>
      <li><a href="#experience"> Experience</a></li>
      <li><a href="#social">Social</a></li>
  </nav>
</header>

<main>
<section id="welcome-section">
  <h1> Welcome </h1>
</section>

<section id="projects"> 
  <h2 class="project-tile"> Project tile to go here </h2>
  <a id="project-link1" href="https://codepen.io/Tomathy7/full/VwepEeK"> Link to project bwoia </a> 
</section>

<section id="experience">
  <h2 class="experience"> Experience Title <h2>
</section>

<section id="social"> 
  <p> See my <a id="profile-link" href="https://www.freecodecamp.org/tomathy7"> FreeCodeCamp Profile Here </a> to see what I'm working on.
</section>
    
</main>
```
As I've mentioned, I've tried various ways of making this pass, putting the nav-bar within a <section>, within <div> tags, within <header> tags and including/exluding <header> tags placing them inside and outside.

Would really appreciate this looking at or a little advice on the error of my ways!

Thank you :)

Tom.

- Browser Name, Version: Google Chrome
- Operating System: Unsure (Windows?)
- Mobile, Desktop, or Tablet: Laptop 

Your Code / Link to Your Pen - https://codepen.io/Tomathy7/pen/NWxBwxE?editors=1100

**Comment by Sky020** [comment]
Hello there,

In general, I recommend you open a topic like this on the [forum](https://forum.freecodecamp.org). Reason being, this is not an issue with the source code/test-suite, but the user code.

Specifically, your page has a total `height` less than that of the window, which means the window cannot scroll. To elaborate, try adding this code, and you should get an idea of the problem:
```
#experience {
  height: 100vh;
}
```

I am closing this issue. Thank you.

**Comment by Tomathy7** [comment]
I see that this issue is closed, I just wanted to say thank you Shaun! I’d
have been pulling my hair out today not being able to figure it out, and
believe me, I cannot rock a bald head!

Thanks again and have an awesome day!
