### ISSUE TITLE
Confused about product landing page project

### ISSUE THREAD

**Issue by streetlightkids** [freeCodeCamp/testable-projects-fcc#1194]
test number 11 of the product landing page project says to include an input within a form that has an id of submit... I believe that I meet the requirement. If not, then I'm confused. I'm using chrome.

https://codepen.io/streetlightkids/pen/WNrPYxx

```

 <form
            class="form-group"
            action="https://www.freecodecamp.com/email-submit"
            id="form"
          >
            <label for="email">
              <h3 id="email-label">
                Sign up for sick updates and offers here!🤙🏾
              </h3>
            </label>
            <br />
            <input
              name="email"
              type="email"
              id="email"
              placeholder="  Enter yer email"
              required
            />
            <input class="btn" name="button" type="submit" id="submit" value="Yewwwww" />
          </form>

```

**Comment by nhcarrigan** [comment]
Hey there~!

The issue I see is you have multiple `button` elements all with `id="submit"`. `id` attributes should be unique - you should not have multiple elements with the same `id`. 

In general, it is best to share your code/questions on our [forum](https://forum.freecodecamp.org) before opening an issue. If the community decides that there is indeed a bug in the tests, and not an error in the code, *then* an issue should be opened. 

I am going to close this issue. Feel free to reopen it with additional information if it is determined there is a bug. 🙂
