### ISSUE TITLE
Portfolio Page - Cannot pass Test, even though it works as expected

### ISSUE THREAD

**Issue by HotRodHarrison** [freeCodeCamp/testable-projects-fcc#1195]
#### Issue Description
Test 8 fails: My portfolio should have a link with an id of "profile-link", which opens my GitHub or FCC profile in a new tab. 

Which it does have an id profile-link and a target which opens a new page, see below.

<a id="profile-link" href="https://github.com/freecodecamp" target="_blank" class="btn contact-details"><i class="fab fa-github"></i> GitHub</a>

I have inspected others Portfolio Pages, and they look the same and pass. What am I missing?

#### Your Code / Link to Your Pen
https://codepen.io/hotrodharrison/pen/MWKLrZM

**Comment by nhcarrigan** [comment]
Hello~!

Looking at the test error, it appears you have a `section` element with the id `profile-link`, while the test expected an `a` element with that id.
![image](https://user-images.githubusercontent.com/63889819/88409675-23eae900-cd8a-11ea-9dad-440b3e71da62.png)

**Comment by HotRodHarrison** [comment]
Thanks @nhcarrigan, you saved me. Looking at this problems for awhile and didn't see my mistake. Thanks much.
