### ISSUE TITLE
Media query not detected

### ISSUE THREAD

**Issue by Sedki-Sghairi** [freeCodeCamp/testable-projects-fcc#1200]
https://sedki-sghairi.github.io/Javascript-documentation/
I used Media query in the project 

above, it works just fine but the test can't detect it.
(browser: google Chrome and i tried it on firefox as well,, OS: windows 10)
here is a screen shot:
<img width="283" alt="cccode" src="https://user-images.githubusercontent.com/67509559/89119223-8b591500-d4bd-11ea-8b11-ade85a956e11.png">

thank you.

**Comment by Sky020** [comment]
Hello there,

I cannot see the test suite on your live page. So, I assume you ran the tests on your local dev environment. In which case, this is known behaviour of the tests, whereby some of them will fail, if there is no server hosting the page.

Could you confirm this by including the test suite in your gh-pages project?

**Comment by Sedki-Sghairi** [comment]
Sure will do it now

Le dim. 2 août 2020 à 3:09 PM, Shaun Hamilton <notifications@github.com> a
écrit :

**Comment by Sedki-Sghairi** [comment]
Now it shows that it passes the test. Thank you

Le dim. 2 août 2020 à 6:39 PM, Sedki sghairi <boredsedki@gmail.com> a
écrit :
