### ISSUE TITLE
Bug in Create Product Landing Page tests

### ISSUE THREAD

**Issue by Missypointyshoes** [freeCodeCamp/testable-projects-fcc#1202]
Hi, 

I am finding that there is a bug in the codepen.io test for user story #12. I have added action="https://www.freecodecamp.com/email-submit" to my <form> element, yet the test is not passing for this part of the assignment. 

Link to the codepen concerned: https://codepen.io/missypointyshoes/pen/WNwNBdw (project is not finished yet, still working on two other user stories + the looks ;-) )

KR, 

Wonderbird Pointyshoes

**Comment by Sky020** [comment]
Hello there,

In general, I recommend opening a topic on the [forum](https://forum.freecodecamp.org/) for an issue like this, as it does not have to do with the test-suite, but your code.

Specifically, the error message says:
> The #email input should have a name attribute : expected false to equal true

If you fulfil this requirement, you can move on. If you get stuck, I suggest you use the forum.

I am closing this. Thank you.
