### ISSUE TITLE
The test button isn't working properly.

### ISSUE THREAD

**Issue by AlexBitesTheDust** [freeCodeCamp/testable-projects-fcc#1203]
#### Issue Description
As I run test it locally goes to 0/0 which makes me confused on how I can progress through the step without knowing what is right in my script. 

#### Screenshot
![image](https://user-images.githubusercontent.com/69322858/89574898-1dc52580-d7ea-11ea-83b4-8a063cfd1f43.png)

**Comment by nhcarrigan** [comment]
Hello~!

It looks like you have not selected a specific test suite in the dropdown menu above. You will need to select the appropriate test suite for the project you are working on before the script will run any tests. 🙂

**Comment by nhcarrigan** [comment]
Heya~!

I have not heard a response from you, so I am going to go ahead and close this issue as resolved. If you still feel there is a bug, feel free to reopen this issue with more information. :)
