### ISSUE TITLE
I can't pass the test

### ISSUE THREAD

**Issue by kby906** [freeCodeCamp/testable-projects-fcc#1205]
#### Issue Description
 I can't pass the test even though on the error message there's no problem.

Hi! I'm doing my project to pass final  section of front-end libraries certification.
Since I clicked test button and couldn't pass 3 tests which are number 22, 24, 25.
However when I checked the error message, it says 
```
Timer has reached zero but didn't switch back to Session time.: expected '<h3>SESSION</h3><h4 id="time-left">01:00</h4>' to not equal '<h3>SESSION</h3><h4 id="time-left">01:00</h4>'
AssertionError: Timer has reached zero but didn't switch back to Session time.: expected '<h3>SESSION</h3><h4 id="time-left">01:00</h4>' to not equal '<h3>SESSION</h3><h4 id="time-left">01:00</h4>'
```
It seems they are the same message and my clock works fine. I posted on the forum but still nobody answered me.
My code probably has some issue but I can also assume there's no error when it comes to error message.

#### Browser Information

- Browser Name, Version: Chrome 84.0.4147.89
- Operating System: MacOS Catalina 10.15.6
- Mobile, Desktop, or Tablet: Macbook Air 2019 

#### Your Code / Link to Your Pen
https://codepen.io/atiktook/pen/vYGYwrw?editors=0110

```
 changeTime = () =>{
 const _timeleft = this.state.timeleft
 if(_timeleft > 0) {
   this.setState({timeleft: _timeleft-1})
 } else if (_timeleft === 0 && this.state.type === 'session'){
   this.buzzer()
   this.setState({timeleft: this.state.breaklength*60, type: 'break'})
 } else if (_timeleft === 0 && this.state.type === 'break') {
   this.buzzer()
   this.setState({timeleft: this.state.sessionlength*60, type: 'session'})
 }
   
 }





```

#### Screenshot

![screenshot](https://user-images.githubusercontent.com/61088223/89731056-14082000-da7f-11ea-98a2-809b32dbac0f.png)

**Comment by Sky020** [comment]
Hello there,

I have replied to your forum post, and, as such, am closing this issue.
