### ISSUE TITLE
Bug about not correct tests

### ISSUE THREAD

**Issue by TalooBob** [freeCodeCamp/testable-projects-fcc#1206]
#### Issue Description
Test number 4 has an issue. On the test that comes with this cdn link {https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js} number 4 is wrong and it won't let me complete all the tests. When I run tests, this is what it gives me: 
"4. Inside the form element, I am required to enter my name in a field with id="name". If I do not enter a name I will see an HTML5 validation error.",
Whereas, on the user story page it says this for user story 4: 
"User Story #4: Inside the form element, I am required to enter my name in a field with id="name"".

#### Your Code / Link to Your Pen

Link: [https://codepen.io/taloobob/pen/yLONMvr](https://codepen.io/taloobob/pen/yLONMvr)

#### Screenshot

![This is the error i got](https://user-images.githubusercontent.com/67945050/89738337-9be62e00-da6f-11ea-88c7-85428dca006a.JPG)
![And this is the user story.](https://user-images.githubusercontent.com/67945050/89738352-b4564880-da6f-11ea-9978-3977e02a79c3.JPG)

**Comment by nhcarrigan** [comment]
Hello~!

The test description is a little more specific, but they both ultimately ask for the same thing: I should be *required* to enter my name. As this is not an issue with the test suite directly, I'm going to go ahead and close this issue. I recommend checking out our [forums](https://forum.freecodecamp.org) for assistance with your code. 🙂

**Comment by TalooBob** [comment]
Thanks! I really appreciate it. I understand now. Thanks again!
________________________________
