### ISSUE TITLE
 the template for tribute page from freecodecamp.org

### ISSUE THREAD

**Issue by MisterPietrzak** [freeCodeCamp/testable-projects-fcc#1207]
tribute page

5. Within the "img-div" element, I should see either a <figcaption> or <div> element with a corresponding id="img-caption" that contains textual content describing the image shown in "img-div".
expected null to not equal null
AssertionError: expected null to not equal null
    at Proxy.c (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:549:1889)
    at Proxy.l (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:431:130)
    at Function.n.isNotNull (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:574:1549)
    at a.<anonymous> (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:657:119559)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:38668
    at i.g.run (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:38963)
    at N.runTest (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:45686)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:46651
    at o (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:45075)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:598:45145

#### Issue Description

I have fulfilled the requirement for this line of code and I verified this with an experience coder and it is not accepting the code solution on line 5

#### Browser Information

google chrome

- Browser Name, Version:
- Operating System: windows 10
- Mobile, Desktop, or Tablet: laptop

#### Your Code / Link to Your Pen
https://codepen.io/freeCodeCamp/pen/MJjpwO?editors=1100

<div>
    <figure id="img-div">
      <img src="https://upload.wikimedia.org/wikipedia/en/thumb/3/3b/SpongeBob_SquarePants_character.svg/1200px-SpongeBob_SquarePants_character.svg.png" alt="Spongebob" id="image" />
      <figcaption>SpongeBob pointing</figcaption>
      </div>
```



```

#### Screenshot
![day6](https://user-images.githubusercontent.com/69498329/89860628-25295d80-db61-11ea-965b-abaf828ad8c0.png)

**Comment by nhcarrigan** [comment]
Hello~!

The link you have provided is for the freeCodeCamp test suite pen. In order to debug your code, we would need a link to *your* pen. Prior to opening an issue here, however, I recommend posting the error you are encountering on our [forum](https://forum.freecodecamp.org) - if the community determines that the error is indeed with the test suite and not the code you have written, then consider opening an issue here. 

For now, I am going to go ahead and close this issue. 🙂

**Comment by MisterPietrzak** [comment]
well then I have no idea how to do that I copied the link in the address bar while I am in the pen that is the other thing there is no save function on the pens when you are doing a codecamp test it's very weird and forced me to have to redo this twice already. I know when I make a pen without doing the tests there is no issue using the url or saving and reaccessing the pen. 
     On Monday, August 10, 2020, 11:30:45 p.m. MDT, Nicholas Carrigan <notifications@github.com> wrote:  
 
 


Hello~!

The link you have provided is for the freeCodeCamp test suite pen. In order to debug your code, we would need a link to your pen. Prior to opening an issue here, however, I recommend posting the error you are encountering on our forum - if the community determines that the error is indeed with the test suite and not the code you have written, then consider opening an issue here.

For now, I am going to go ahead and close this issue. 🙂

**Comment by nhcarrigan** [comment]
Make sure that you click the "Fork" option in the bottom right corner of the test suite pen - this will create a copy of the pen (with the test suite!) under your account so you can save your changes. Also ensure that you are logged in to the CodePen website.

**Comment by MisterPietrzak** [comment]
https://codepen.io/MisterPietrzak/pen/gOraxxm     On Tuesday, August 11, 2020, 09:05:28 a.m. MDT, Nicholas Carrigan <notifications@github.com> wrote:  
 
 


Make sure that you click the "Fork" option in the bottom right corner of the test suite pen - this will create a copy of the pen (with the test suite!) under your account so you can save your changes. Also ensure that you are logged in to the CodePen website.

**Comment by nhcarrigan** [comment]
![image](https://user-images.githubusercontent.com/63889819/89914821-6e51cf80-dbaa-11ea-92a7-2c4a9ef963cd.png)

Your `figcaption` element does not have the `id` attribute that the test is asking for. 🙂

**Comment by MisterPietrzak** [comment]
What the actual hell I swear I was not trying to waste your time and that it did have id="img-caption" in the element yesterday I must have re edited out me and a few people went over it and tried the element in a number of combinations and it wasn't working for literally hours last night. I am very sorry anyhow as now it's somehow working out.... blah lol I hope you have a good day and thanks for being polite and helpful!
 Jason     On Tuesday, August 11, 2020, 09:13:21 a.m. MDT, Nicholas Carrigan <notifications@github.com> wrote:  
 
 




Your figcaption element does not have the id attribute that the test is asking for. 🙂
