### ISSUE TITLE
Build a tribute page _ Layout test #2 failure

### ISSUE THREAD

**Issue by iKwesi** [freeCodeCamp/testable-projects-fcc#121]
#### Issue Description

This is the only test failing although i have centered the image in it's parent div.

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: macOs 10.11.6
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
 https://codepen.io/iKwesi/pen/LLjejW?editors=1100
 
 
```

#### Screenshot

![image](https://user-images.githubusercontent.com/24443531/27722158-ae31f010-5d33-11e7-93ca-8c6970f84889.png)

**Comment by tchaffee** [comment]
@iKwesi Nice styling on your page! And thank you for reporting this. There is a bug in our tests in that we are not taking the border width into consideration. As a work around you can change the border-width of your container from 15px to 14px and the test should pass.

@tbushman Do you want to take this since you are already working on issue #111?

**Comment by tbushman** [comment]
@tchaffee OK.

**Comment by iKwesi** [comment]
after changing the border-width to 14px the test still fails.
![image](https://user-images.githubusercontent.com/24443531/27756569-b6071f5c-5dc6-11e7-9761-9dff99f50635.png)

**Comment by tchaffee** [comment]
@iKwesi Sorry about that. It looks like I was using a newer but yet unreleased version of the tests that are a little more forgiving allowing 30px (total) of wiggle room concerning centering. The current tests only allow 10px (total), so if you change the border to 5px (border is on 2 sides) the tests should pass. Here is a [fork of your pen](https://codepen.io/tchaffee/pen/NgYbgM?editors=1100) that passes the tests.

Thanks for your patience and for reporting this problem to us so we can improve the tests.

**Comment by tbushman** [comment]
@iKwesi @tchaffee, The PR, once merged, will fix this. Thanks for your patience.

**Comment by iKwesi** [comment]
@tchaffee @tbushman thanks guys. I am very grateful. Kindly lemme know when the new test becomes available but I am working on the survey form.
Happy coding

**Comment by tbushman** [comment]
Reopening because we're waiting to get this merged. Thanks @iKwesi .

**Comment by tbushman** [comment]
@iKwesi OK. Your pen should pass now.

**Comment by iKwesi** [comment]
Thanks guys.
