### ISSUE TITLE
Technical Documentation Page - Test 11 not working properly

### ISSUE THREAD

**Issue by shin1code** [freeCodeCamp/testable-projects-fcc#1214]
#### Issue Description

Hi freeCodeCamp Team.
I'm new to the site and I'm trying to go over all the challenges. I'm currently working on the Technical Documentation Page challenge and as soon as I run the test checker I get 2/16. I know the first one is always marked as completed because of the link to the tester's script. However, I get test 11 marked as passing even if I have written no code. 

Even if I try to fail the test on purpose, it's still marked as passing (as seen in the last screenshot).
#### Browser Information

- Browser Name, Version: Mozilla Firefox, 79.0 (64-bit)
- Operating System: Windows 10
- Mobile, Desktop, or Tablet:
 Tested on Chrome and it didn't work either.
#### Your Code / Link to Your Pen

```

https://codepen.io/shin1code/pen/vYGgJqV

```

#### Screenshots

![screentshot1](https://user-images.githubusercontent.com/69829464/90989988-4d528c80-e563-11ea-8f71-b461fb32ebfc.png)

![screenshot2](https://user-images.githubusercontent.com/69829464/90990017-88ed5680-e563-11ea-94f6-04b31e6b2dba.png)

![screenshot4](https://user-images.githubusercontent.com/69829464/90990282-d5399600-e565-11ea-87a2-b48ecb927284.png)

**Comment by Sky020** [comment]
Hello there,

Thank you, for pointing this out. However, if you continue with the user stories, it is not possible to pass `11` and `10`, because the test for this is:
```
const navLinks = document.querySelectorAll('#navbar a.nav-link');
const header = document.querySelectorAll('#navbar header').item(0);
let allAbove = true;

navLinks.forEach((navLink) => {
    /* eslint no-bitwise: ["error", { "allow": ["&"] }] */
      if (
         !(
           header.compareDocumentPosition(navLink) &
           Node.DOCUMENT_POSITION_FOLLOWING
          )
        ) {
          allAbove = false;
        }
      });

assert.strictEqual(
  allAbove,
  true,
  'The <header> element contained by the navbar must be come before ' +
    'any link (<a>) elements contained by the navbar'
);
```
So, the default is `allAbove = true;`, and, if this element is not found `'#navbar a.nav-link'`. then the check for whether the `header` is above or not does not run.

I will leave this issue open. However, I do not think there is any need to change the tests for this, because `11` cannot be passed incorrectly, after entering the rest of the user story requirements.

@lasjorg Again, do you think this is something that should be changed?

**Comment by shin1code** [comment]
I understand. Thanks!
Should I then close this issue?

**Comment by lasjorg** [comment]
@Sky020 Not sure there is any need for a change here. But I also am not sure if/why this test needs to pass by default.

I haven't tested this or thought much about it, but I would think we should be able to reverse the logic so it starts out failing and only passes when the if condition is met.

**Comment by Sky020** [comment]
> ...but I would think we should be able to reverse the logic so it starts out failing and only passes when the if condition is met.

I thought about this too. So, if another contributor agrees, then we could open this up for that change.
