### ISSUE TITLE
Possible bug in tester for JS Calculator test

### ISSUE THREAD

**Issue by noelbray** [freeCodeCamp/testable-projects-fcc#1215]
#### Issue Description

Concerning the JS Calculator: 

When I run the test, it says that I didn't pass the 13th test which is to use the last sign as sign for the arithmetic operation.
When inputting arithmetic operators ( +, -, *, x, /) my code instantaneously replaces the current operator with the new operator of the operator button that was pressed.  I think this may be a bug because my program is calculating well (as far as I know). Is this a bug or does the program not account for the type of code I wrote?

#### Your Code / Link to Your Pen

https://codepen.io/nwbnwb/full/rNeypVE

**Comment by nhcarrigan** [comment]
Hello~!

Generally it is best to ask these questions on the [forum](https://forum.freecodecamp.org) prior to opening an issue. If the community determines that there is indeed a bug with the test, and not the code you have written, then an issue should be opened. 🙂 

In this case, looking at your code and the test requirements, your code does not allow me to use negative numbers. The test calls for `5 * - 5` to be entered in the calculator, and expects a return value of `-25`. In other words, the calculator should read this as "five times negative five". On your calculator, the `-` overrides the `*`, and I get `5-5` which returns `0`. 

Hopefully this points you in the right direction. I am going to go ahead and close this issue - if you have further questions about your project, feel free to ask us on the forum! If you feel this is indeed a bug in the test suite, you are welcome to re-open this issue and provide more information. 🙂
