### ISSUE TITLE
Test failing but test requirement has been met

### ISSUE THREAD

**Issue by mikofresh01** [freeCodeCamp/testable-projects-fcc#1217]
#### Issue Description

Freecodecamp Product Landing Page user story #5 requires navbar elements to contain a href attribute that points to a specific point on the page. I met the requirement but the test is still failing.
#### Browser Information

- Browser Name, Version: Google chrome Version 84.0.4147.135 
- Operating System: windows 10
- Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen
https://codepen.io/michaeladejoh02/pen/LYNyzdd?editors=1100

```



```

#### Screenshot

![Screenshot (2)](https://user-images.githubusercontent.com/34838966/91466391-f4e2fe00-e886-11ea-8a80-b983c23afa31.png)

**Comment by Sky020** [comment]
Hello there,

In general, I recommend you open an issue like this on the [forum](https://forum.freecodecamp.org), as this is not an issue with the source code/test-suite.

In this case, you have almost got the answer:
> Each .nav-link element should have an href attribute : expected false to equal true

What you have:
```
<li class="nav-link"><a href="#products">Products</a></li>
```
Have a think about whether the above **.nav-link** element has an **href** attribute...

I will leave it up to you to close this, if you no longer see it as an issue. Thank you
