### ISSUE TITLE
Test scripts are not correct

### ISSUE THREAD

**Issue by paiikachuu** [freeCodeCamp/testable-projects-fcc#1225]
I am building a project for Landing Page but the test scripts are still in Tribute Page.

**Comment by Sky020** [comment]
Hello there,

In general, I recommend you open a topic on the [forum](https://forum.freecodecamp.org), for matters like this.

You should be able to change which tests are being run, by clicking on the dropdown, and selecting another:
![image](https://user-images.githubusercontent.com/51722130/92458043-da7d1e80-f1bc-11ea-995d-4aefc15e3c1f.png)
