### ISSUE TITLE
Markdown Preview tests not compatible with Vue

### ISSUE THREAD

**Issue by TheJaredWilcurt** [freeCodeCamp/testable-projects-fcc#1234]
#### Issue Description

All 8 tests should pass, however 3 of them are failing. I believe this may be due to how Vue optimizes when it updates the DOM.

* https://codepen.io/TheJaredWilcurt/pen/QWNVVVQ

Though even if you modify the code to force Vue to update the DOM after every keyup event, it still doesn't work:

* https://jsfiddle.net/Lv612a9n

Even if it did work, the original code is much cleaner and matches with the "vue way" of coding, so you shouldn't have to write your Vue code differently just to satisfy the automated tests.

**Comment by RandellDawson** [comment]
@TheJaredWilcurt Vue is not guaranteed to work with our tests.  We state this in each project description.  See below for this statement.

> You can use any mix of HTML, JavaScript, CSS, Bootstrap, SASS, React, Redux, and jQuery to complete this project. You should use a frontend framework (like React for example) because this section is about learning frontend frameworks. Additional technologies not listed above are not recommended and using them is at your own risk. **We are looking at supporting other frontend frameworks like Angular and Vue, but they are not currently supported.** We will accept and try to fix all issue reports that use the suggested technology stack for this project. Happy coding!
