### ISSUE TITLE
D3 Scatter Plot Tests

### ISSUE THREAD

**Issue by sa-mm** [freeCodeCamp/testable-projects-fcc#124]
#### Issue Description

Test 6 expects that you've assigned something like a date string to the data-yvalue: `var yDate = new Date(dot.getAttribute("data-yvalue"));`

Given that it expects a plain old year (e.g., '1994') for the data-xvalue, should something like that be possible for data-yvalue (e.g., '38:45')?

**Comment by tbushman** [comment]
Yes. You've used d3.timeParse(), and it looks like it assigns January 1, 1900 to each mm:ss and returns a Date object. The domain for your years is also set by Date objects. xScale() and yScale() should be pixels. @tchaffee I think test 6 passes for the FCC sample because the range is 1000 pixels and therefore the xScale() returns what looks like a year, but the expected value is pixels. Either we need to require a 1000 pixel range or reconfigure this test. Thanks @sa-mm .

**Comment by tbushman** [comment]
@sa-mm the data-xvalue and data-yvalue both expect Date objects, so you can timeParse d.Time and d.Year in a separate step or before assigning the data-xvalue and data-yvalue attributes.

**Comment by sa-mm** [comment]
@tbushman Thank you for continuing to look at this. I think I'm not understanding things correctly. You say, 

> the data-xvalue and data-yvalue both expect Date objects,

From my understanding, the tests expect the data-xvalue to be of the form "1994," but when you write that they expect "Date objects" I think of the string representation of something like `new Date(1994, 0, 1)` which is "Sat Jan 01 1994 00:00:00 GMT-0600 (CST)" (or close to that depending on where you live?).

If I set the data-xvalue to "Sat Jan 01 1994 00:00:00 GMT-0600 (CST)", then the tests fail.

So, for instance, this element will pass the test:

```html
<circle class="dot doping" r="6" cx="90" cy="308.8888888888889" data-xvalue="1994" data-yvalue="Mon Jan 01 1900 00:39:30 GMT-0600 (CST)"></circle>
```

And this will fail:

```html
<circle class="dot doping" r="6" cx="90" cy="308.8888888888889" data-xvalue="Sat Jan 01 1994 00:00:00 GMT-0600 (CST)" data-yvalue="Mon Jan 01 1900 00:39:30 GMT-0600 (CST)"></circle>
```

My thought was that it would be better to either (1) expect the data-x/y values to be of a similar form (e.g., 1994 & 39:30) or (2) to allow for a variety of options for either value. Option 1 makes sense if you think that what's in the data-xvalue should correspond to the tooltip you see when hovering over the element. Option 2 makes more sense if you're trying to write tests that allow for a greater number of approaches to pass those tests.

I've got all of the tests passing on my end, but (from what I can tell) they require me to create circles where the attributes look like this:

- data-xvalue="1994" 
- data-yvalue="Mon Jan 01 1900 00:39:30 GMT-0600 (CST)"

That strikes me as odd.

**Comment by tbushman** [comment]
OK. I was wrong about data-xvalue, sorry! You're right that it expects just a full year. So, in your code it would be `.attr('data-xvalue', (d, i) => new Date(dates[i]).getFullYear())` And you want to pass a Date object to your data-yvalue attribute like `.attr('data-yvalue', (d, i) => new Date(minutes[i]))`.

**Comment by tchaffee** [comment]
@sa-mm In order to make the tests maintainable, we actually want to make them as descriptive and *as restrictive* as possible. We aren't trying to build the tests to pass all possible solutions, but instead the test narrative should guide campers to one correct solution, and the solutions campers come up with should be fairly similar, as well as being similar to the sample app.

With that said, is there a more "correct" way of coding this that you have in mind? Are you just looking for consistency between the way the data-xvalue and data-yvalue is treated? As you said here:

> Given that it expects a plain old year (e.g., '1994') for the data-xvalue, should something like that be possible for data-yvalue (e.g., '38:45')?

Or do you have a preference for option 1 or option 2 as you described them?

**Comment by sa-mm** [comment]
@tbushman @tchaffee apologies for my absence over the holidays here in the U.S.

My initial preference would be to opt for a variety of options, but your concern regarding maintainability is important. I guess the flip side of that is that when these tests go live, you might have a lot of people asking questions about why the tests are failing if they're projects are, on the face of it, satisfying the user stories. Someone will have quite a bit of work dealing with them.

I'd say that if you go with more restrictive tests, then it might help to have some sort of discussion about what the x/y value actually is when those words are used in the test descriptions.

a) Is it the thing you appear to be plotting? (e.g., something in the form MM:SS and 1996)
b) Is it whatever you're passing in to a scale? (Mon Jan 01 1900 00:39:30 GMT-0600 (CST))

It seems like the current tests are choosing (a) for the x-value and (b) for the y-values.

Summary:

In the end, I think I would go for greater variety, which is maybe where things are headed with @tbushman's latest [PR]( https://github.com/freeCodeCamp/testable-projects-fcc/pull/127). But, if that makes maintainability too much of an issue, then I would go with (a).

**Comment by sa-mm** [comment]
Got it!

I just want to summarize my point (and this is just because communication over the internet is hard):

I think it’s odd to have tests that require `data-yvalue=“some date string which happens to have the correct minutes and seconds”`, and that it makes sense for the tests to at least permit `data-yvalue=“38:45”`.

However, I have definitely belabored the point!

Thanks again for the work on the tests. They are very helpful!

**Comment by tbushman** [comment]
@sa-mm  we've been talking about how to re-word a few things, and this will be part of that process. Thanks for calling this out, and sorry I caused confusion here.
