### ISSUE TITLE
Issue with image running Tribute Page tests

### ISSUE THREAD

**Issue by PatrickW96** [freeCodeCamp/testable-projects-fcc#1240]
#### Issue Description
I have completed a tribute page for the responsive first web design project and the test will not let me pass. The test is reading that I need to make my image responsive but the problem is my image is responsive. I have looked at project multiple various screen sizes and the image is responsive. SOS. 

#### Your Code / Link to Your Pen

```
.container {
    display: grid;
    padding-right: 15px;
    padding-left: 15px;
    margin: 5px auto;
    width: 65%;
    text-align: center;
}

footer {
    padding-right: 15px;
    padding-left: 15px;
    margin: 5px auto;
    text-align: center; 
}

aside {
    display: grid;
    justify-content: center;
    margin: auto;
}

li {
    text-align: left;
}

h3 {
    margin-bottom: 20px;
}

p {
    line-height: 2rem;
}

#image {
    display:grid;
    max-width: 100%;
    height: auto;
    width: 100%;
}

@media screen and (max-width: 768px) {
    .container {
        width: 95%;
        margin: auto;
    }
}

```

#### Screenshot

![Screen Shot 2020-09-22 at 6 00 40 AM](https://user-images.githubusercontent.com/67624311/93868816-01495380-fc99-11ea-9820-f154816cd491.png)
![Screen Shot 2020-09-22 at 6 00 35 AM](https://user-images.githubusercontent.com/67624311/93868846-0c03e880-fc99-11ea-9af4-317abd37b1d2.png)
![Screen Shot 2020-09-22 at 6 00 31 AM](https://user-images.githubusercontent.com/67624311/93868865-11613300-fc99-11ea-941a-b9cf6f634dbb.png)
![Screen Shot 2020-09-22 at 6 00 24 AM](https://user-images.githubusercontent.com/67624311/93868882-14f4ba00-fc99-11ea-9b57-1e0eaf35f3bd.png)

**Comment by PatrickW96** [comment]
![Screen Shot 2020-09-22 at 6 16 21 AM](https://user-images.githubusercontent.com/67624311/93870406-2dfe6a80-fc9b-11ea-9926-4d054d9779fa.png)

You can also find the full code for this where my repos are stored. It is titled: "Mac Miller Tribute Page."

**Comment by nhcarrigan** [comment]
As the error message states, the tests are specifically looking for the `max-width` property to be applied to your image. 🙂 

Please use our [forum](https://forum.freecodecamp.org) for debugging the code of challenges/your projects. If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened. GitHub issues are meant for reporting bugs and not troubleshooting the code.

Thank you for understanding.
