### ISSUE TITLE
Automate the testing of this project

### ISSUE THREAD

**Issue by tchaffee** [freeCodeCamp/testable-projects-fcc#126]
In order to speed up the development process and to make sure we don't break anything, I would like to automate the testing which is currently performed manually. There is not much to do in terms of writing the tests. It's basically just picking the correct test, clicking the 'Run Tests' button and making sure they all pass within a reasonable amount of time. The automated tests would need a list of all the sample projects to make sure each sample project is visited when testing.

What I don't know, and what I need help with, is if there are any currently automated tests in any fcc project so that I can do this the same way. @QuincyLarson is this something totally new I can develop on my own or are there other projects to look at that have already automated testing? Do we use a CI server like Travis or Jenkins? Any info is appreciated.

**Comment by tchaffee** [comment]
FYI, I think this is the first best step before we start trying to "break the project tests", and before we start making the camper tests more descriptive / restrictive / reliable by adding more requirements (i.e. in the form of Mocha scenarios).

**Comment by QuincyLarson** [comment]
@tchaffee yes - we can definitely get a CI server going. I can add Travis CI, but I think you need to decide what tests you want to run. I've written a bit about this here: https://medium.freecodecamp.com/how-to-stop-errors-before-they-ever-hit-your-codebase-with-travis-ci-and-eslint-7a5a6b1fcd4a

**Comment by tchaffee** [comment]
@QuincyLarson Thanks for the article. It helpful and I've used CI before so I don't foresee any problems getting this set up. As a first step I can add the ESLint tests, but the important goal for me is to fire up a headless browser for each CodePen, click the "Run Tests" button, and make sure all the tests pass. I wrote a CasperJS script to do this, but it only works some of the time (https://github.com/casperjs/casperjs/issues/1847) so I may have to try to use PhantomJS directly or even Selenium, which is unfortunate because both are lower level than CasperJS and take more work to automate. If you have other ideas or you already made a choice about this for other projects, I'll be happy to keep it consistent.

**Comment by tchaffee** [comment]
@QuincyLarson @no-stack-dub-sack @tbushman Just giving a quick progress update here. **tl;dr:** Unless there is some objection I would like to go ahead with Selenium for automatically checking each CodePen and that the tests pass.

I tried PhantomJS and it also has documented problems with iframes. With CasperJS and PhantomJS out of the picture it's down to Selenium, which is fortunately working great. Just a couple dozen lines of code to automatically test any CodePen.

Travis CI supports Selenium, via Sauce Labs which supports 170 different device/OS/browser combinations. Sauce Labs is free for open source projects. The tests will also run locally using node and npm, so contributors will be able to make sure they haven't broken anything before submitting a PR. **This will greatly speed up development since we will no longer have to manually configure the `local_test` directory and manually run the tests.** I should be able to submit a preliminary PR in the next day or two at which point anyone can try it out locally and give a thumbs up or down before me getting started into the other work that would follow: 1) Set up Travis CI and Sauce Labs to run the tests 2) Update our documentation and get rid of the `local_tests` dir.

**Comment by no-stack-dub-sack** [comment]
@tchaffee this sounds awesome to me! about to check out the PR
