### ISSUE TITLE
Quote Machine - Test 10 fails if use a button instead of anchor link with href to tweet quote

### ISSUE THREAD

**Issue by marigerr** [freeCodeCamp/testable-projects-fcc#128]
#### Issue Description

 [Quote Machine tests](https://github.com/freeCodeCamp/testable-projects-fcc/blob/master/src/project-tests/quote-machine-tests.js) 
Test 10 is failing for me because it requires an  <a> link to be used with an href. 
```
assert.isOk(document.getElementById("tweet-quote").hasAttribute('href')
#tweet-quote element must have an href attribute
```

In my pen, I instead use a button with a click handler in my script file to let the user Tweet a Quote.  
```
$("#tweet-quote").on("click", tweetQuote);
var tweetQuote = function(){
  var quote = $('#text').html();
  var author = $('#author').html();
  window.open('https://twitter.com/intent/tweet' + '?text=' + quote + ' - ' + author, '_blank');
};
```

Wondering if possible to change Test 10 to allow for buttons with click handlers to be used as alternative.   Possibly have a fallback test, if href isn't present to check in script for the click handler?

#### Browser Information

* Browser Name, Version:  Chrome/59.0.3071.115
* Operating System: Windows NT 10.0; Win64; x64
* Mobile, Desktop, or Tablet:  Desktop

#### Your Code / Link to Your Pen

 https://codepen.io/marigerr/pen/KNQexq

#### Screenshot

![test10fail](https://user-images.githubusercontent.com/15229372/27925104-d2c98ff0-6283-11e7-978e-86f45a83376b.PNG)

**Comment by marigerr** [comment]
I actually was looking more into using a button in this situation on https://css-tricks.com/use-button-element/

Thinking now maybe a somewhat not best practice and not worth changing the test for, so closing my issue.

**Comment by tbushman** [comment]
@marigerr Thank you for sharing that informative article.

**Comment by tchaffee** [comment]
Reopening this because we should make the the test text clearer to specify that the tweet element should be an anchor (`<a href=.../>`) element.

**Comment by marigerr** [comment]
Okdokee.
I can possibly submit a PR for this.   Could possibly change Test 5 instead to check at that point that the tweet-quote element is an anchor tag.   Then Test 10 could stay the same to just check the href path.

Currently Test 5 just checks the element id and that its a child of quote-box element. (below)   
Can add anchor tag requirement and additional test there.

```
it('5. Within #quote-box, I can see a clickable "tweet" element with 
corresponding id="tweet-quote".', function() {
  | FCC_Global.assert.isNotNull(document.getElementById("tweet-quote"));
  | FCC_Global.assert.strictEqual(document.querySelectorAll('#quote-box #tweet-quote').length,
 1, '#tweet-quote button is not a child of #quote-box ');
  | });
```

**Comment by tchaffee** [comment]
@marigerr That sounds good to me.

**Comment by marigerr** [comment]
I have a PR ready, but I believe that the build needs to be run for the last commit/merge - [fix all indentations and quotes](https://github.com/freeCodeCamp/testable-projects-fcc/commit/9490a0b5deee0c2a93864eea540887e9a8aec3d6)? I don't see that bundle.js was updated?

I noticed this when I run build after making updates for this my issue, I'm see diff changes to bundle.js that I believe were for that prior commit.

**Comment by tbushman** [comment]
@marigerr Before submitting a PR, make sure to create a branch on your fork from which to submit. Commit to that, then switch to local master (git branch master) and see if you can rebase latest upstream/master over your local master. Then checkout your fix/* branch... push. I might be missing something, and this is new to me. I have found this useful for reference: https://2buntu.com/articles/1459/keeping-your-forked-repo-synced-with-the-upstream-source/. 
Also see CONTRIBUTING.md for reference. You'll be presented with a checklist at the time of the PR. 
 
Then we will be able to better see what's going on and be better able to make next steps recommendations. 
 
It might cause issues not to run a bundle for @no-stack-dub-sack 's last merge, but we would want to see the diffs to determine. The current PR has a merge conflict, but not based on formatting. Thank you!

**Comment by marigerr** [comment]
@tbushman  
Howdy!  I did my changes on a up-to date branch that was checked out from master after fetching the latest commits.   So it wasn't a problem there.   

I think I would prefer not to include changes from the prior commit with my commit.   I could submit a PR with just the changes to bundle.js that reflect the latest [commit](https://github.com/freeCodeCamp/testable-projects-fcc/commit/9490a0b5deee0c2a93864eea540887e9a8aec3d6).   But probably better if @no-stack-dub-sack submitted it?

**Comment by no-stack-dub-sack** [comment]
@marigerr oddly I'm just getting an email notification about this thread now... but looks like all has been resolved?

**Comment by tbushman** [comment]
@no-stack-dub-sack Yes. @marigerr 's PR is merged, which will help clarify expectations for these tests. Thank you!

**Comment by themagicbean** [comment]
I would support reopening this and reconsidering the tweet test (tests 5 and 10).   It seems like there are at least a few ways to make the Tweet button work (with or without it being an anchor or having initial href text).  I also personally think having the Tweet and More Quotes buttons both be as similar as possible has something to be said for it in terms of design and accessibility.    Example: https://codepen.io/themagicbean/pen/wvKearK
