### ISSUE TITLE
Show the Local Weather example broken

### ISSUE THREAD

**Issue by aw1231** [freeCodeCamp/testable-projects-fcc#133]
#### Issue Description
When you open the codepen the example looks broken.

#### Browser Information
I am running the latest verions of Windows 10 and Chrome

* Browser Name, Version: Chrome 59.0.3071.115 
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen
https://codepen.io/freeCodeCamp/full/bELRjV

#### Screenshot
![2017-07-13](https://user-images.githubusercontent.com/1181968/28181683-81c7836a-67d7-11e7-8b91-932a714cebd5.png)

**Comment by tbushman** [comment]
In its current form, this app requires disabling https. 
The latest versions of Chrome won't let you do that from the browser (https://stackoverflow.com/questions/41498423/how-to-get-latest-chrome-version-55-to-allow-mixed-content). 
There should be another weather api using https that could be used in place of openweathermap (https://forum.freecodecamp.org/t/show-the-local-weather-cant-use-geolocation-api-on-insecure-server-codepen-io/1215/2) 
In the meantime, Firefox will let you disable https to view the working app.

**Comment by marigerr** [comment]
There was a recent commit on the non-beta version of FCC that made changes to the Local Weather App challenge :  [Add glitch API to Front-End weather project](https://github.com/freeCodeCamp/freeCodeCamp/commit/c9d4da3146e64391e72489edc9a0c255d91af969)   
There is a [closed issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/15598#issuecomment-313928572) where @MiloATH stated there was a need to update the codepen with the new glitch API, but it hasn't been done yet. 
It looks like that issue might need to be re-opened.  

This repo _testable-projects-fcc_ doesn't cover the Local Weather App challenge as it's not part of the beta version of FCC.

**Comment by MiloATH** [comment]
I forked and updated the codepen. It can be found [here](https://codepen.io/Miloath/pen/zzJGqP). The  only thing that needs to be updated in the freeCodeCamp pen is the javascript. It would be great if the freeCodeCamp pen could be updated @QuincyLarson. Here is the updated javascript:
```js
var app = angular.module('Weather', []);

app.factory('WeatherApi', function($http) {
  var obj = {};
  
  obj.getLoc = function() {
    return $http.jsonp("https://ipinfo.io/json?callback=JSON_CALLBACK");
  };
  obj.getCurrent = function(loc) {
    var api = "https://fcc-weather-api.glitch.me/api/current?";
    loc = loc.split(",");
    var lat = "lat=" + loc[0];
    var lon = "&lon=" + loc[1];
    var cb = "&callback=JSON_CALLBACK";
    return $http.jsonp(api + lat + lon + cb);
  };
  return obj
});

app.controller('MainCtrl', function($scope, WeatherApi) {
  $scope.Data = {};
  $scope.Data.unit ='C';
  $scope.Data.sysChange = false;
  WeatherApi.getLoc().success(function(data) {
    var city = data.loc + ',' + data.country;
    $scope.Data.city = data.city;
    $scope.Data.country = data.country;
    WeatherApi.getCurrent(data.loc).success(function(data) {
      CurrentWeather(data)
    });
  });

  function CurrentWeather(data) {
    $scope.Data.temp = Math.round(data.main.temp);
    $scope.Data.Cel = Math.round(data.main.temp);
    $scope.Data.des = data.weather[0].main;
    $scope.Data.Fah = Math.round( ($scope.Data.temp * 9)/5 + 32 );
    return IconGen($scope.Data.des);
  }

  function IconGen(city) {
    var city = city.toLowerCase()
    switch (city) {
      case 'drizzle':
        addIcon(city)
        break;
      case 'clouds':
        addIcon(city)
        break;
      case 'rain':
        addIcon(city)
        break;
      case 'snow':
        addIcon(city)
        break;
      case 'clear':
        addIcon(city)
        break;
      case 'thunderstom':
        addIcon(city)
        break;
      default:
    $('div.clouds').removeClass('hide');
    }
  }

  function addIcon(city) {
    $('div.' + city).removeClass('hide');
  }
  
  $scope.Data.sys= function(){
   if($scope.Data.sysChange){
     $scope.Data.unit ='C';
     $scope.Data.temp = $scope.Data.Cel;
     return $scope.Data.sysChange = false;
     }
    $scope.Data.unit ='F';
    $scope.Data.temp = $scope.Data.Fah;
    return $scope.Data.sysChange = true;
  }
  
  
});
```

**Comment by aw1231** [comment]
@marigerr would you like me close this issue and ask that https://github.com/freeCodeCamp/freeCodeCamp/issues/15598 be reopened?

**Comment by marigerr** [comment]
@aw1231   I'm new to contributing, but that seems like a good idea to try to reopen [#15598](https://github.com/freeCodeCamp/freeCodeCamp/issues/15598) and finish resolving there.   
Thanks for the further info @MiloATH !

**Comment by aw1231** [comment]
Will do.
