### ISSUE TITLE
Bar Chart CORS error for shortened json url

### ISSUE THREAD

**Issue by tbushman** [freeCodeCamp/testable-projects-fcc#141]
#### Browser Information

* Browser Name, Version: Chrome
* Operating System: OSX Sierra
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
 
 
 
```

#### Screenshot

The shortened URLs cause tests 7 and 8 to error with the message: `No 'Access-Control-Allow-Origin' header is present on the requested resource.` The error goes away in local testing when the full URL is used in the project_tests/bar-chart-tests.js ajax calls in tests 7 and 8. The error is still present in the Codepen Selenium test with local bundle.js.

**Comment by tchaffee** [comment]
@tbushman good catch. I was wondering why those tests were breaking. I think this needs to be fixed by the CoePen author, and not as a part of this project? @QuincyLarson @no-stack-dub-sack Do you know who can fix this?

Here's a link to the [D3 Bar Chart CodePen](https://codepen.io/freeCodeCamp/pen/GrZVaM) for convenience.

**Comment by tbushman** [comment]
@tchaffee The Codepen is correct. The test module shortens the url. Changing that back to 'https://raw.githubusercontent.com/FreeCodeCamp/ProjectReferenceData/master/GDP-data.json' in  src/project-tests/bar-chart-tests.js line 95 and 121 fixes the error in local dev build. But the access-control-allow-origin error still occurs with the local bundle served through https in your selenium test.

**Comment by tchaffee** [comment]
@tbushman The Selenium test should work if you rebuild the bundle with `npm run build`. If no one knows of any good reason to be using the URL shortener, then let's get this fixed by using the full URL. @no-stack-dub-sack any idea why the shortener is used in the tests?

**Comment by tbushman** [comment]
@tchaffee Ah, yes. That did it. OK. The PR #142 is one commit behind #139 feature/automated-tests-inject. But it might be good to merge #142 first. Whatever you think will work best. Thanks!

**Comment by no-stack-dub-sack** [comment]
@tchaffee yeah, it was purely stylistic. It worked at the time before this automation, and it just made the code a bit cleaner. No problem at all changing it back if it will solve this problem.
