### ISSUE TITLE
Product Landing Page Test #5 fails despite working code

### ISSUE THREAD

**Issue by taariya** [freeCodeCamp/testable-projects-fcc#143]
Product Landing Page (beta) project
http://beta.freecodecamp.com/en/challenges/applied-responsive-web-design-projects/build-a-product-landing-page

The unit test for internal linking using anchor tags does not execute successfully even though my anchor tags are properly set up within the page and confirmed to be working.

* Browser Name, Version: Chrome 59.0.3071.115
* Operating System: Ubuntu 17.04
* Mobile, Desktop, or Tablet: Desktop
 
link to codepen  project:
https://codepen.io/taariya/pen/ybKbMb?editors=1100

**Comment by taariya** [comment]
I have figured out the problem in the test suite that is causing this. Rather than checking for anchor tags with a "name" attribute that matches the "href" attribute of a corresponding anchor tag, the test suite checks for a corresponding id attribute. This conflicts with the instructions given in the [challenge about linking internal sections of a page](http://beta.freecodecamp.com/en/challenges/basic-html-and-html5/link-to-internal-sections-of-a-page-with-anchor-elements).

**Comment by tbushman** [comment]
@taariya Thanks for submitting an issue. Could you please move it to https://github.com/freeCodeCamp/freeCodeCamp and put beta in the issue title? This repo is for the projects (currently the CodePens). Thanks!

**Comment by tchaffee** [comment]
Hi @taariya, thanks for submitting an issue. I see a problem in your code. You have an html element `<main>` which is indeed a valid element type. But the tests require an element with an id attribute of "main". You can keep the `<main>` element, but you need to assign an id to it. Can you let us know if this solves your problem?

**Comment by taariya** [comment]
This did not solve the problem. In fact, the tests run perfectly fine even
without there being any element with an id attribute of "main" as long as
one uses the id attribute for anchor tags rather than the name attribute
which the curriculum instructed us to do. I think this lends weight to my
belief that the testing suite needs to be revised because my code is able
to pass without fulfilling a requirement.

To clarify my position, the problem is not with my code, it's with the
testing suite written for this project and/or the beta lesson on internal
linking. We were instructed in that lesson to use the name attribute for
anchor tags that link to sections of the same page, and several other
sources reiterate this information. However the testing suite doesn't check
for the "name" attribute, it checks by id. This is not invalid by the HTML
specifications, but the aforementioned lesson doesn't provide that
information, so it's then not logical to assume in the testing suite that a
camper would know that.

**Comment by tchaffee** [comment]
@taariya My apologies, I was running the wrong test suite! I will take a closer look at this as soon as I get a chance. Thanks for reporting the issue.

**Comment by marigerr** [comment]
I found on the W3C docs under [obsolete features](https://www.w3.org/TR/html5/obsolete.html#obsolete) that they recommend against using `name ` attribute on anchor tags, but to use `id `instead.

> Authors should not specify the name attribute on a elements. If the attribute is present, its value must not be the empty string and must neither be equal to the value of any of the IDs in the element’s home subtree other than the element’s own id, if any, nor be equal to the value of any of the other name attributes on a elements in the element’s home subtree. If this attribute is present and the element has an id, then the attribute’s value must be equal to the element’s id. In earlier versions of the language, this attribute was intended as a way to specify possible targets for fragment identifiers in URLs. The id attribute should be used instead.

I think instead of changing the test, that an issue should be opened on main repo for the [related challenge](http://beta.freecodecamp.com/en/challenges/basic-html-and-html5/link-to-internal-sections-of-a-page-with-anchor-elements) (and possibly others) to instruct to use `id` instead of `name `for the target anchor.

**Comment by marigerr** [comment]
@tchaffee @tbushman   
I opened an [issue ](https://github.com/freeCodeCamp/freeCodeCamp/issues/15672)for this on the main fcc repo.   Hopefully will get approval to submit a PR to the lesson itself to use `id `instead of `name  `

**Comment by marigerr** [comment]
@tchaffee @tbushman  
The lesson on beta freecodecamp was updated to remove instructions about using `name `attribute with anchor tags and to instead use `id` to create internal links.    
It is not yet reflected on live site,  but the change has been merged.    (Not sure how long it takes for changes to be reflected on live site?)
So I believe this issue can be closed, as the current tests align with using `id `instead of `name`.

**Comment by tbushman** [comment]
@taariya , your pen passes tests if your section elements have id tags corresponding to hrefs in the navbar. Thank you!
