### ISSUE TITLE
URL Shortener cannot be tested 

### ISSUE THREAD

**Issue by Enikol** [freeCodeCamp/testable-projects-fcc#154]
#### Issue Description
Testing app https://narrow-plane.glitch.me/ doesn't test the URL Shortener project correctly. It fails tests 2 and 4 with error message saying only 'error' (I ran these tests sequentially, so that shouldn't be the cause of the problem). I tried to test the example project, https://thread-paper.glitch.me, and the result is the same. In the developer console it prints the following: "XMLHttpRequest cannot load https://curse-arrow.gomix.me/api/timestamp. Redirect from 'https://curse-arrow.gomix.me/api/timestamp' to 'https://curse-arrow.glitch.me/api/timestamp' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access."

#### Browser Information
* Browser Name, Version: Google Chrome
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

I think the problem is caused by the outdated domain name "gomix.me" that is written into the tests. Here's my remix of the testing app, where "gomix.me" is changed into "glitch.me", and it seems to work fine with both the example project and my own. I'd love to create a PR, but I can't find where the source code for the testing file is.

**Comment by marigerr** [comment]
Hi @Enikol !  

Currently this project/repo only tracks issues for the tests run on the front-end projects.   

For the back-end projects from the _Apis and Microservices_ section, there are a few open issues on the main fcc repo that detail some problems.    I believe there is an awareness that unfortunately the testing is not currently working for the back-end Glitch projects. 

https://github.com/freeCodeCamp/freeCodeCamp/issues/13095

**Comment by tchaffee** [comment]
@Enikol Thank you for reporting this problem. I cannot find any automated tests for the URL Shortener project. Can you give me a step-by-step description of how to repeat the problem? How are you running the tests?

**Comment by tchaffee** [comment]
@Enikol Thanks for reporting this. I am closing this issue because as @marigerr said, this git repo is only for the tests for the frontend project. And please do comment on issue freeCodeCamp/freeCodeCamp#13095 so the right people are aware of this problem.
