### ISSUE TITLE
Rename the `src/assets` directory to `src/utils`.

### ISSUE THREAD

**Issue by tchaffee** [freeCodeCamp/testable-projects-fcc#160]
The `assets` name is traditionally (idiomatically) used to store web assets such as images and fonts. In this project it is being used to store javascript modules, which is confusing.  It should be renamed to something like `src/utils`. This requires a lot of grunt work in also fixing the references to this directory in any code that imports javascript modules from that directory.

**Comment by tbushman** [comment]
Thanks @jnmorse !!
