### ISSUE TITLE
Find a better way to inject mocha CSS

### ISSUE THREAD

**Issue by tchaffee** [freeCodeCamp/testable-projects-fcc#195]
The mocha-CSS.js file contains a very long and ugly string with the mocha CSS. Not sure why it is done like this, but assume it needs to be dynamically injected or something like that. We should see if we can find a more maintainable way of doing this. Hopefully via a normal css file with a .css extension?

**Comment by tbushman** [comment]
@tchaffee we can just use the test_suite_skeleton.js style section (existing). In my PR, I'm omitting mocha-CSS.js. If we omit markdown, then a custom mocha reporter shouldn't disrupt the test suite. I'll prepare that.

**Comment by tchaffee** [comment]
I just looked and test_suite_skeleton.js is also one big ugly string of both CSS and HTML :-( I hope there is some way around that. There might not be, but it's worth looking into.
