### ISSUE TITLE
Random Quote Machine example on CodePen sometimes fails the tests

### ISSUE THREAD

**Issue by tchaffee** [freeCodeCamp/testable-projects-fcc#217]
#### Issue Description
Both locally and on Travis CI, the Random Quote Machine Codepen sometimes fails the automated tests.

#### Browser Information
N/A

#### Your Code / Link to Your Pen
Official freeCodeCamp example pen:
https://codepen.io/freeCodeCamp/pen/qRZeGZ

**Comment by tbushman** [comment]
@no-stack-dub-sack @QuincyLarson The Random Quote machine quote api gives the error: 'Too many requests. Please try again.'

**Comment by QuincyLarson** [comment]
@tbushman @tchaffee Instead of using an API, we should just provide a JSON file with some quotes, and they can alternatively hard-code their own quotes. This will be more reliable, and simpler for campers than working with an API endpoint. What do you all think about this approach?

**Comment by tbushman** [comment]
@QuincyLarson That would be fine and fulfill test requirements. The error is infrequent enough that it's not a huge issue, and usually we can re-run Travis and get it to pass when it does error. It's passing right now. Thanks!

**Comment by QuincyLarson** [comment]
@tbushman Awesome! I've created a new issue for that and am closing this issue.
