### ISSUE TITLE
Update Random Quote Machine project to use JSON instead of an API

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/testable-projects-fcc#218]
Instead of using an API, we should just provide a JSON file with some quotes, and they can alternatively hard-code their own quotes. This will be more reliable, and simpler for campers than working with an API endpoint.

See discussion of this fix on https://github.com/freeCodeCamp/testable-projects-fcc/issues/217#issuecomment-328684702

**Comment by tchaffee** [comment]
How can we get the JSON file to the Campers in a way that isn't confusing? Could we use a gist that declares a variable for them and they can just copy paste into their code? Something like this but assigned to a variable name? https://gist.github.com/nasrulhazim/54b659e43b1035215cd0ba1d4577ee80

**Comment by QuincyLarson** [comment]
@tchaffee Great idea. Yes. I've forked this gist to freeCodeCamp. Here's the link: https://gist.github.com/camperbot/5a022b72e96c4c9585c32bf6a75f62d9

Would you be interested in updating the example app? Instead of copy/pasting this, could the example declare a variable using this JSON remotely? That would look a lot cleaner in the code.

**Comment by tchaffee** [comment]
@QuincyLarson I was thinking the Camper could just copy / paste from the gist, but I will see if it's possible to grab the JSON directly from the gist. I think it might be possible using the rawgit CDN. If so, I'll update the example app.

**Comment by tchaffee** [comment]
This is fixed in the official example CodePen to use the newly created gist. I made a backup here in case there are any problems: https://codepen.io/freeCodeCamp/pen/bapjJP

**Comment by QuincyLarson** [comment]
@tchaffee Wow - you work fast! That's great! Thanks for figuring this out and implementing it!
