### ISSUE TITLE
possible import of framework components for testing

### ISSUE THREAD

**Issue by tbushman** [freeCodeCamp/testable-projects-fcc#224]
#### Issue Description

In frameworks, it is sometimes the case that DOM elements from projects, when queried in the tests, return non-updated values due to their rendering lifecycles. The latest suggestions for testing components involve the import and mounting of those components. If a generic way of mounting components isn't available, it might be best to develop tests per framework (vue, react, ...)

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 
 
```

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
