### ISSUE TITLE
Product Landing Page test [#Content 5] issue

### ISSUE THREAD

**Issue by bomholtm** [freeCodeCamp/testable-projects-fcc#227]
#### Issue Description

Without having anything else added to my pen the test suite passes content test 5:
"When I click a .nav-link button in the nav element, I am taken to the corresponding section of the landing page.'"

#### Browser Information

* Browser Name, Version: Google Chrome Version 60.0.3112.113 (Official Build) (64-bit)
* Operating System: macOS Sierra 10.12.6
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

![landing_page_test_issue](https://user-images.githubusercontent.com/14976046/30924521-41716d08-a3af-11e7-8d4b-68cd075ac9cf.png)

**EDIT:** As soon as you insert the `<nav>` element the test is working!

**Comment by tbushman** [comment]
@bomholtm Thanks for reporting this. Have a nice day. :)
