### ISSUE TITLE
Markdown Links Test Pass If No Links 

### ISSUE THREAD

**Issue by jnmorse** [freeCodeCamp/testable-projects-fcc#229]
#### Issue Description

Test 7 passes if your initial markdown contains no links, or if the test suite is unable to grab the preview content.

I feel this can be misleading. Since as someone is developing their project for this, they may think they already have an optional test done, only to find when they add a link to the initial text that it is suddenly failing.

If I remove all the code in the example, test 7 still will pass.

#### Browser Information

* Browser Name, Version: Chrome 61
* Operating System: Ubuntu
* Mobile, Desktop, or Tablet: Desktop

[Example Codepen](https://codepen.io/jnmorse/pen/EwmypB)

#### Screenshot

![optional-test-should-fail](https://user-images.githubusercontent.com/1467889/30945749-f902d1d2-a3cd-11e7-960c-492fc0cc10fc.png)

**Comment by tbushman** [comment]
@jnmorse Were you going to use the bit you had included initially in #225 in a new PR to address this issue? That was good.

**Comment by jnmorse** [comment]
@tbushman yes I was planning on it. I just hadn't had much time and got too busy playing with other code bits I was trying. Was also debating on waiting to see if #225 was accepted or not. Think for now I'll just submit a pull request with the existing code.

Though in regards to that pull request, I noticed while one of the things I was playing with was the new `ReactDOM.createPortal` in React 16, that I may need to try and address some things in that pull request as it seems like it some of the code will prevent tests from actually running if certain conditions aren't met.

So I'm gonna look into revising the code and push an updated pull request at some point in the future. The fix you had for React 15.6 still works in 16 btw.

**Comment by tbushman** [comment]
@jnmorse Thanks for checking. As a rule we're trying to keep PRs addressing single issues, so that might want to be broken into two PRs. Not all reviewers are able to review or merge right now so these will queue up, fyi. Thank you.

**Comment by jnmorse** [comment]
Okay, pull request has been made for this issue.
