### ISSUE TITLE
Fix .babelrc file to use 'env' instead of 'es2015'

### ISSUE THREAD

**Issue by tchaffee** [freeCodeCamp/testable-projects-fcc#231]
In PR #226 we started using babel-preset-env instead of bable-preset-es2015. But we missed the .bablerc file, which needs to be changed too.

@jnmorse Do you have time to submit a PR for this?

**Comment by jnmorse** [comment]
@tchaffee Am I missing something here? There does not appear to be a .babelrc file. Rather than the file, there is this in the webpack configs which I did switch to 'env' under the babel-loader

```javascript
query: {
  presets: ['env']
}
```

running `npm run build` still, builds on my end? I can certainly add a .babelrc file if needed though.

**Comment by tchaffee** [comment]
@jnmorse It's a new file in my branch only! :-) Sorry about that. Closing.
