### ISSUE TITLE
Heat Map Assertions

### ISSUE THREAD

**Issue by jnmorse** [freeCodeCamp/testable-projects-fcc#241]
#### Issue Description

When looking into the issue #234 I was looking at the code and noticed the line in test number 8

```javascript
// NOTE:  This test contains the same exact tests from 6 and 7.
// Is there a way to only run test 8 if test 6 and 7 pass?
// Should we be putting this code in a utility function?
```

The only assertions I think that would be necessary here is the one that checks if cells exist, which ensures that the test will fail if there are no cells, and the loops to check values.

The previous test 7 is already checking if the properties exist, and this test will fail if they do not since the return value for them will be undefined.

Additionally, the cells specific test could be moved to a describe block, and add a beforeEach hook that will test that there are cells before the tests.

```javascript
  describe('# Cells Test', () => {
      beforeEach('There should be cells', () => {
        const cells = document.querySelectorAll('.cell');

        assert.isAbove(
          cells.length,
          0,
          'Could not find any elements with class="cell"'
        );
      });

      let reqNum = 0;

      reqNum++;
      it(`${reqNum}. There should be at least 4 different fill colors used for
        the cells.`,
        function() {
          const cells = document.querySelectorAll('.cell');
          var uniqueColors = [];

          for (var i = 0; i < cells.length; i++) {
            var cellColor = cells[i].style.fill ||
              cells[i].getAttribute('fill');

            // if the current color isn't in the uniqueColors arr, push it
            if (uniqueColors.indexOf(cellColor) === -1) {
              uniqueColors.push(cellColor);
            }
          }

          assert.isAtLeast(
            uniqueColors.length,
            4,
            'There should be more than four fill colors used for the cells '
          );
        });

        reqNum++;
        it(`${reqNum}. Each cell will have the properties "data-month",
        "data-year", "data-temp" containing their corresponding month, year, and
        temperature values.`,
        function() {
          const cells = document.querySelectorAll('.cell');

          for (var i = 0; i < cells.length; i++) {
            var cell = cells[i];
            assert.isNotNull(
              cell.getAttribute('data-month'),
              'Could not find property "data-month" in cell '
            );

            assert.isNotNull(
              cell.getAttribute('data-year'),
              'Could not find property "data-year" in cell '
            );

            assert.isNotNull(
              cell.getAttribute('data-temp'),
              'Could not find property "data-temp" in cell '
            );
          }
        });

      reqNum++;
      it(`${reqNum}. The "data-month", "data-year" of each cell should be
      within the range of the data.`,
      function() {
        cells.forEach((cell) => {
          const dataMonth = cell.getAttribute('data-month');

          assert.isAtLeast(dataMonth, 0, 'data-month should be at least 0');
          assert.isAtMost(dataMonth, 11, 'data-month should be at most 11');
        });

        cells.forEach((cell) => {
          const dataYear = cell.getAttribute('data-year');

          assert.isAtLeast(dataYear, 1753, 'data-year should be at least 1753');
          assert.isAtMost(dataYear, 2015, 'data-year should be at most 2015');
        });
      });
    });
```

The only issue with this approach is only the first test that fails the beforeEach hook is listed. Though the reason is listed as ' "before each" hook: There should be cells for "1. There should be at least 4 different fill colors used for the cells." '

**Comment by tbushman** [comment]
@jnmorse This is a good approach. The assertion error stack detail provides is clear that .cell elements are missing. I think it would be ok to implement this approach with your open PR.

**Comment by tchaffee** [comment]
@jnmore @tbushman I always prefer small focused PRs because if we have to reverse one for some reason and unrelated code is in the same PR then it gets messy. You end up having to reverse the PR but create a new PR to re-implement the part that's not broken.

**Comment by tchaffee** [comment]
@jnmorse PR #240 looks good to me. I'm just having a problem with getting the tests to pass. Seems like CodePen is being fussy lately with timeouts. I will look closer at that when I get a chance.

I like the approach of having a dedicated test rather than using beforeEach. It's better if the camper can see the requirement along with all the other requirements.

**Comment by tchaffee** [comment]
Closing because this is outdated. If you still think this issue is relevant, please feel free to reopen it.
