### ISSUE TITLE
Portfolio Project Example missing images - Suggesting new example

### ISSUE THREAD

**Issue by ddcornwall** [freeCodeCamp/testable-projects-fcc#252]
#### Issue Description

I wanted to point out that the example you use for the personal portfolio project - (https://codepen.io/freeCodeCamp/full/YqLyXB), has ongoing issues with its images. Looking through the forum I see there were a number of forum posts in 2016 reporting this issue and it seemed intermittent. But since it’s still having issues after a year I, I’d like to suggest posting an alternate example.

The example is linked from https://www.freecodecamp.org/challenges/build-a-personal-portfolio-webpage. A possible replacement might be this pen that got good feedback in a project feedback thread - https://codepen.io/ItamarRosenblum/full/eGozMa/. I don’t love the background color but it seems to have the appropriate user stories.

#### Browser Information

* Browser Name, Version: Chrome, Firefox, IE
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Laptop

#### Your Code / Link to Your Pen

```
https://codepen.io/freeCodeCamp/full/YqLyXB - This is the Portfolio Page example pen, not my own. 
 
 
```

**Comment by tbushman** [comment]
That is a really neat site. You can add the automatic test code to your scripts and ensure the tests pass: `https://gitcdn.link/repo/freeCodeCamp/testable-projects-fcc/master/build/bundle.js`.
  
The images in https://codepen.io/ItamarRosenblum/full/eGozMa/ are hosted on postimg.org.   
  
This is the pen for the testable projects Portfolio page: https://codepen.io/freeCodeCamp/pen/zNBOYG. It's images are hosted on github and there seem to be no issues there. We had an image issue with the Product Landing testable pen and @QuincyLarson ended up using s3 to secure the image. It might be best to work with him on the best bet for image hosting. 
  
@QuincyLarson ...

**Comment by QuincyLarson** [comment]
@ddcornwall Yes - as @tbushman mentioned, we are hosting images on GitHub for these new projects. All of the projects on www.freecodecamp.org and their examples will be replaced once we launch beta.freecodecamp.org as the replacement curriculum.
