### ISSUE TITLE
triggers a 404 in codepen after running the portfolio test

### ISSUE THREAD

**Issue by Alexever17** [freeCodeCamp/testable-projects-fcc#261]
#### Issue Description
As soon as i click run test, after adding the id="navbar" it crashes 
exactly on this line, not on id="navba" or something else

and it also opens my github profile page 2 times.

feel free to contact me on github if necessery

#### Browser Information

* Chrome: Version 63.0.3239.84 (Official Build) (64-Bit)
* Operating System:  Windows 10 on a 2017 Surface Pro Tablet if relevant

#### Your Code / Link to Your Pen
Live Bugged version:
https://codepen.io/alexever17/pen/WdQRXQ

#### Screenshot
https://i.imgur.com/qWj6Eam.png

**Comment by tbushman** [comment]
Hello. Codepen is blocking your window.open directives as popups. You might have better results using a Bootstrap modal and iFrame with src=`${database[category]}` or similar ...

**Comment by Alexever17** [comment]
Thank a lot for the answer @tbushman!
