### ISSUE TITLE
Markdown Previewer list item test fails when using a * (asterisk) or + (plus sign) as a list marker

### ISSUE THREAD

**Issue by iabrenne** [freeCodeCamp/testable-projects-fcc#267]
#### Issue Description

When using either asterisk, plus sign or a minus sign to mark a list item, it gets correctly interpreted as \<li>  in the rendered html.

However, tests are failing on asterisk and plus signs. They are passing as expected on a minus.

If you guys confirm this is a bug, I would love to work on a fix. This would be my first contribution to open  source   :smile_cat: 

#### Your Code / Link to Your Pen

I believe the issue with the regexp in  

```
assert.notStrictEqual(
          markdown.search(/(?:-|\d\.)\s[^|\s-*].+/),
          -1,
          'write some markdown representing an <li> item '
        );
```
in markdown-previewer-tests.js 

Here are the pens.
First two below are to the pens that are failing. ( using  * and + as a list item marker ) 
Last one is to the pen that is passing ( using - as an list item marker )

```
https://codepen.io/irinabrennen/pen/PEPZXj/
Markdown - Failed(*)

https://codepen.io/irinabrennen/pen/wpgpNR
Markdown - Failed(+)

https://codepen.io/irinabrennen/pen/rpjpEe
Markdown - Pass(-)
 
 ```

#### Screenshot

Write some markdown representing an \<li> item test is failing with an asterisk:

![image](https://user-images.githubusercontent.com/24214306/34367909-621cae5c-ea75-11e7-9d70-0e548846adf5.png)

**Comment by tbushman** [comment]
@iabrenne Thank you for catching this. The (*) and (-) are indeed missing from the regex in test 5! If you wish you may submit a pull request. Let us know what you decide. Happy holidays.

**Comment by iabrenne** [comment]
@tbushman Yes, I would love to give it a try. Happy Holidays to you too!

**Comment by tchaffee** [comment]
@iabrenne Regex is a pain to verify that you got it just right. This online regex tester might help. https://regex101.com/

**Comment by iabrenne** [comment]
@tchaffee Thank you for the link to the regex tester. It was very helpful. 

I ran against 5 test strings through the tool - regex appears to be working as expected.

![image](https://user-images.githubusercontent.com/24214306/34417169-a5678086-ebbc-11e7-88c9-3c8ae1054404.png)

Link to the tests : https://regex101.com/r/HhjC8A/1/tests

**Comment by tbushman** [comment]
@iabrenne Indeed it does. @tchaffee , did you see a problem with it?
