### ISSUE TITLE
Buttons move with the button css selector 

### ISSUE THREAD

**Issue by slamoureux** [freeCodeCamp/testable-projects-fcc#269]
#### Issue Description

In codepen if you do something like:

button {
margin-left: 100px;
}

it will move the buttons over 100px in the test suite buttons.

#### Browser Information

* Browser Name, Version: Chromium 63
* Operating System: Linux Mint 18.3
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
I adjusted for this by just using an id selector but figured it was worth mentioning. 
 
 
```

#### Screenshot

![test1](https://user-images.githubusercontent.com/16889593/34645840-df49b5b0-f325-11e7-8e40-3bbce3b10ff7.png)

**Comment by tbushman** [comment]
@slamoureux Thank you very much for reporting this. !!

**Comment by tbushman** [comment]
I still want to try loading the Mocha modal along with the rest of the test ui into an iframe. There may be a more straightforward way to avoid style conflicts via CSS naming, but here are things tried so far:  
- Forcing fCC styles to load last via webpack  
    ...
- ShadowDOM  
- iframe  
    ...

Still looking into this...
