### ISSUE TITLE
Landing Page Video Issue

### ISSUE THREAD

**Issue by arhillis** [freeCodeCamp/testable-projects-fcc#271]
#### Issue Description

I am currently working on the landing page for the Responsive Web Design Certificate. Whenever I run the tests, test 12 always fails, mentioning the "scr" attribute. I have a feeling it should be 'src', but I'm not sure.

#### Browser Information

* Browser Name, Version: Mozilla Firefox v. 57.0.4
* Operating System: Windows 10 Creator Update
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
 <video id="video" controls>
     <source src="https://arhillis.github.io/BlueDeveloper/video/ad.mp4">
                        <p>Please update your browser.</p>
  </video>
 
 
```
https://codepen.io/arhillis/pen/KZBpXL
#### Screenshot

![landingpageissueedited](https://user-images.githubusercontent.com/16339566/34942007-a873e082-f9bb-11e7-8e0d-aa290a5ae8e4.png)

**Comment by arhillis** [comment]
Never mind. Fixed the issue.

**Comment by tbushman** [comment]
@arhillis thanks for bringing the typo to our attention, though :)
