### ISSUE TITLE
Use collapsed state by default

### ISSUE THREAD

**Issue by Knochenmark** [freeCodeCamp/testable-projects-fcc#272]
#### Issue Description
It is super annoying that the test suite thing overlaps while you are actually writing code, but not testing anything. Every reload will expand the test suite again when you collapsed it by hand. Therefor i suggest to set the collapsed state to collapsed by default or at least add a checkbox that can be toggled to do so.
Store the state in localStorage for example, thats totally sufficient for a session.

**Comment by tbushman** [comment]
Agreed.

**Comment by Knochenmark** [comment]
@tbushman Thanks, good stuff :+1: Real quality of life change
