### ISSUE TITLE
Barchart testcase 11 should output actual comparison values

### ISSUE THREAD

**Issue by Knochenmark** [freeCodeCamp/testable-projects-fcc#273]
#### Issue Description

The testcase 11 for the bar chart only outputs the following when the test fails:
`AssertionError: y values don't line up with y locations : expected false to be true`

It is not helpful at all that the testcase outputs exspected false to be true, instead the actual y values and y location values should be in the description. The test case is still failing for me and I have no indication on how to fix it.

#### Your Code / Link to Your Pen
This is my current codepen for the challenge https://codepen.io/Knochenmark/pen/ZvMvjo

**Comment by tbushman** [comment]
@knochenmark A pull-request is pending to address this problem. Thank you for your patience.

**Comment by tbushman** [comment]
@Knochenmark Your bar chart has no misaligned elements. Once the new alignment test PR is merged, your chart will pass all tests. In the future, we may have more detailed stacktraces / error reporting, but for now I will let this issue be closed with that merge. Thanks!
