### ISSUE TITLE
Issue with "Use the JavaScript Console" test case.

### ISSUE THREAD

**Issue by AdityaOli** [freeCodeCamp/testable-projects-fcc#275]
#### Issue Description

In the Use the Javascript Console tutorial, the input accepts and string in the test case whereas it should accept only 'Hello world!'.

#### Browser Information

* Browser Name, Version: Google Chrome, 56.0.2924.76 (64-bit)
* Operating System: Windows 7
* Mobile, Desktop, or Tablet: Desktop

#### Explanation

The correct acceptable answer should have been:
```
console.log('Hello world!'); 

```
But:
```
console.log('Something!'); 

```
also shows it as the right answer. It shows show the test case as failed.

**Comment by tbushman** [comment]
@AdityaOli The test asserts whether you have used the console.log() code only.   
```
    assert(code.match(/console\\.log\\(a\\)/g), 'message: Your code should use <code>console.log()</code> to check the value of the variable <code>a</code>.');  
```

**Comment by tbushman** [comment]
Closing because this issue would have to be submitted to the main repo.
