### ISSUE TITLE
Find a replacement for the serve-https npm package.

### ISSUE THREAD

**Issue by tchaffee** [freeCodeCamp/testable-projects-fcc#277]
The [serve-https package](https://www.npmjs.com/package/serve-https) helps us run automated tests in the development environment by serving web pages over https. Usually that requires setting up certificates and a lot of other work, but the package just does everything for us. Unfortunately they do not host the package on github and their git servers keep going down, causing our automated build to fail. We should try to find alternatives to this package. We may even continue to use serve-https if they fix the problems, but having a backup plan is important so we don't slow down development when there are problems with the package.

**Comment by tchaffee** [comment]
@tbushman What do you think about going back to the approach we used in the past? Using the 'live-serve' npm package and creating our own self-signed certs? Here is the commit where I removed all of that.

https://github.com/freeCodeCamp/testable-projects-fcc/commit/89bef7370e69c895c44c1f22644962e9c716228d

**Comment by tbushman** [comment]
@tchaffee That would work for me!
