### ISSUE TITLE
Portfolio Project Test #7

### ISSUE THREAD

**Issue by arhillis** [freeCodeCamp/testable-projects-fcc#278]
#### Issue Description

Whenever I run tests for my porfolio site, test #7 always fails, even though I do have a link to another section of the page. 

#### Browser Information

* Browser Name, Version:  Mozilla Firefox
* Operating System: Windows 10, Creator Edition
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
 <a href="#projects" class="nav-link">Projects</a><!-- LINE 14-->
 
 
```
https://codepen.io/arhillis/pen/ppOzbQ

#### Screenshot

![image](https://user-images.githubusercontent.com/16339566/35313517-64073166-0086-11e8-8368-78bc7366f7dd.png)

**Comment by tbushman** [comment]
Thanks @arhillis . Your pen should pass. One problem is the github link -- the scroll test clicks anchors within the navbar, of which `a#profile-link` is one. But the scroll test should otherwise pass. Looking into this.

**Comment by arhillis** [comment]
Just to let you know that the pen passed in Chrome, but not Firefox.

**Comment by sfiquet** [comment]
I encountered this problem on Chrome when all the content fits in the window (my process is to go through the test suite and make the tests pass, then transform the project into something decent). When you click on the navbar links there is no scrolling, which is normal behaviour, but the test doesn't allow for that. I got around it by resizing the window and adding more content.

**Comment by Tirjasdyn** [comment]
I'm having the same problem in Chrome:

https://codepen.io/Tirjasdyn/pen/LNoGqG

I had to remove javascript from the link that I had on there for scrolling effect.

**Comment by tbushman** [comment]
Confirmed that adding vertical content as explained by @sfiquet to fulfill scroll requirements fixes this issue.

**Comment by SpecialAgentOne** [comment]
I have tried to add more content according to @sfiquet solution, but still have this issue in Chrome:
https://codepen.io/SpecialAgentOne/pen/WaYvrV

**Comment by ValeraS** [comment]
@SpecialAgentOne look carefully at line `4`

**Comment by SpecialAgentOne** [comment]
@ValeraS thanks! Now all is OK!
