### ISSUE TITLE
Portfolio layout test #1

### ISSUE THREAD

**Issue by sfiquet** [freeCodeCamp/testable-projects-fcc#281]
#### Issue Description

I get a security error for layout test 1 when using my own CSS file (see screenshot). 

While I was going through the Content tests in my portfolio project, I added a link to Bootstrap 4, which didn't cause the security error and actually made the test pass because of Bootstrap's media queries. When I added my own stylesheet at a later stage, the security error occurred.

The problem exists when using the CDN link but not when using the CodePen test suite template. I made an simplified pen to see if the issue occurred but it didn't. Then I made my own local web page with the same code (see below) and it was there.

The content of the CSS file doesn't seem to matter. If I remove all the content and the file is empty, the error still occurs.

However if I link to a non-existent CSS file, e.g. style2.css the security error disappears and I get the normal test failure:
```
AssertionError: No media queries detected : expected 0 to be above 0
```

#### Browser Information

* Browser Name, Version: Chrome Canary, Version 66.0.3335.0 (Official Build) canary (64-bit)
* Operating System: OS X
* Mobile, Desktop, or Tablet: desktop

#### Your Code / Link to Your Pen

INDEX.HTML:
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="style.css">
  </head>
  <body>
    <div class="mydiv">Hello World</div>
    
    <script type="text/javascript" src="https://gitcdn.link/repo/freeCodeCamp/testable-projects-fcc/master/build/bundle.js"></script>       
  </body>
</html>
 
```
STYLE.CSS:
```
.mydiv {
  background-color: blue;
  color: white;
  padding: 2em;
  text-align: center;
}
```

#### Screenshot

![screen shot 2018-02-01 at 19 02 33](https://user-images.githubusercontent.com/4646869/35697849-4b26cfd6-0783-11e8-94df-7745737b813c.png)

**Comment by tbushman** [comment]
@sfiquet Are you still receiving this error?

**Comment by sfiquet** [comment]
No, the security error is gone. 

However if I add a media query it's not recognised: Layout test 1 fails - but that's a different issue.
