### ISSUE TITLE
Temporarily use github repo instead of npm for serve-https

### ISSUE THREAD

**Issue by tchaffee** [freeCodeCamp/testable-projects-fcc#282]
#### Issue Description
Per the Daplie team who provides the npm serve-https package, they are having problems with their servers and we should use the github servers instead:  `git+https://github.com/Daplie/serve-https.git`. When they fix the npm package problems we can revert this change.

**Comment by tchaffee** [comment]
@tbushman I tried to do this locally, but all my tests are failing saying `TimeoutError: Waiting for element to be located By(css selector, *[id="fcc_test_message-box-rerun-button"]`. This is kind strange because the serve-https package should have no effect on that. Any ideas on what might be causing that issue? I can't find any recent commits that might cause this. Are the tests passing for you locally?

**Comment by tchaffee** [comment]
@tbushman I finally got it mostly working. There are some new bugs - one in the latest version of the Chrome browser, and another possibly with CodePen or Selenium. AND someone deleted the JavaScript from the official Random Quote Machine pen! :-( When it rains, it pours. Well I've got everything fixed except the Random Quote Machine. I opened an issue for that over on the freeCodeCamp repo. https://github.com/freeCodeCamp/freeCodeCamp/issues/16620

I will create a PR soon.

**Comment by tbushman** [comment]
@tchaffee OK! Thanks for all this. And yes, the old npm serve-https was working locally, just not on Travis.

**Comment by tchaffee** [comment]
@tbushman When was last time all of the tests passed for you locally? That might help us pinpoint when the Random Quote Machine JavaScript got clobbered. I'm probably going to have to re-write that from memory :-(

**Comment by tbushman** [comment]
Hi Todd, sorry I didn't send this sooner. I have the JS.
[index.zip](https://github.com/freeCodeCamp/testable-projects-fcc/files/1689817/index.zip)

**Comment by tchaffee** [comment]
@tbushman Thanks for the ZIP file. That has the older version, where it's getting the quotes from https://andruxnet-random-famous-quotes.p.mashape.com. I recently changed it to get quotes from our own gist. Per issue #218. You don't happen to have that most recent code? Anything after Dec. 20th should work.

**Comment by tbushman** [comment]
@tchaffee Sorry, that's the only one I had.

**Comment by tchaffee** [comment]
This was fixed quite a while ago by @tbushman reverting to the older code where we create our own https server using node. Closing.
