### ISSUE TITLE
Get a hint button not working

### ISSUE THREAD

**Issue by Syknapse** [freeCodeCamp/testable-projects-fcc#284]
#### Issue Description
+ Click on any item from Map menu (tested several randomly)
+ Click on the <kbd>Get a hint</kbd> button
+ Results in a 404 message

#### Browser Information
* Browser Name, Version: Chrome  63.0.3239.132 
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

![image](https://user-images.githubusercontent.com/29199184/35777247-dfe59598-09aa-11e8-853a-1d2e1ab010a2.png)

**Comment by tbushman** [comment]
@Syknapse Hi, if this is still an issue, please submit it to the main repo: https://github.com/freeCodeCamp/freeCodeCamp
