### ISSUE TITLE
Not checking html tags properly in test

### ISSUE THREAD

**Issue by KarthikKadambi** [freeCodeCamp/testable-projects-fcc#285]
#### Issue Description

use the del tag to strikethrough text doesnt actually validate the second test condition. 
I added the code as <h4><del>Google</del>< Alphabet /h4> and it worked.

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: Mac 10.13.3
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```html
 
  <h4><del>Google</del>< Alphabet /h4> 
 
```

#### Screenshot

<img width="1440" alt="screen shot 2018-02-22 at 10 16 50 am" src="https://user-images.githubusercontent.com/1627832/36523430-87123ce8-17c7-11e8-8e51-b15391a164fb.png">

**Comment by tchaffee** [comment]
Hi @KarthikKadambi. Thank you for submitting this bug. Could you please report this at the main freeCodeCamp repo? This is a bug in the challenges and not with the code in this repo. Here is the main repo https://github.com/freeCodeCamp/freeCodeCamp

Thanks!
