### ISSUE TITLE
Markdown previewer test 6

### ISSUE THREAD

**Issue by LizzieM2003** [freeCodeCamp/testable-projects-fcc#288]
#### Issue Description

For the test "When my markdown previewer first loads, the default markdown in the #editor field should be rendered as HTML in the #preview element", if it doesn't find an h1 in the markdown prefixed with a # or a h2 in the markdown prefixed with a ## it throws an error. However in markdown you can specify h1s as:
Heading
======

and h2s as:
Sub-heading
-------

without the # prefixes.  

#### Your Code / Link to Your Pen

Extract of my code is below:
```
 const markdown =  `
Heading
=======

Sub-heading
---------

### Another deeper heading
 
 
```

**Comment by tchaffee** [comment]
@LizzieM2003 Thank you for reporting this. We will look into it as soon as we can.
