### ISSUE TITLE
[Survey Form] Add user story/unit test for submit button

### ISSUE THREAD

**Issue by chznbaum** [freeCodeCamp/testable-projects-fcc#29]
#### Issue Description
The survey form test suite will indicate a project passes all tests even if they do not include a submit button for their survey.

#### Browser Information

* Browser Name, Version: Google Chrome version 55.0.2883.87 (64-bit)
* Operating System: Ubuntu Linux 16.04 LTS
* Mobile, Desktop, or Tablet: Laptop

#### Your Code

```
<body>
  <h1 id="title">Survey Form</h1>
  <p id="description">This is a short description of the survey.</p>
  <form>
    <fieldset>
      <div class="input-group">
        <label for="name" id="name-label">Name:</label>
        <input type="text" id="name" placeholder="John Doe" required>
      </div>
      <div class="input-group">
        <label for="email" id="email-label">Email:</label>
        <input type="email" id="email" placeholder="john@doe.com" required>
      </div>
      <div class="input-group">
        <label for="number" id="number-label">Choose a number:</label>
        <input type="number" id="number" min="1" max="100" placeholder="10">
      </div>
      <div class="input-group">
        <label for="select">Choose from the list:</label>
        <select>
          <option value="option-1">Option 1</option>
          <option value="option-2">Option 2</option>
          <option value="option-3">Option 3</option>
        </select>
      </div>
      <div class="input-group">
        <label>Choose a button:</label>
        <input type="radio" value="left">Left
        <input type="radio" value="right">Right
      </div>
      <div class="input-group">
        <label>Choose some boxes:</label>
        <input type="checkbox" name="one" value="one">One
        <input type="checkbox" name="two" value="two">Two
        <input type="checkbox" name="three" value="three">Three
      </div>
      <div class="input-group">
        <label for="text-area">Write some text:</label>
        <textarea rows="5" wrap="soft"></textarea>
      </div>
    </fieldset>
  </form>
</body> 
```

#### Screenshot

![screenshot from 2017-01-29 16-29-53](https://cloud.githubusercontent.com/assets/20505284/22408066/526a7780-e640-11e6-8cb4-536c0d0a4b9f.png)

![screenshot from 2017-01-29 16-30-21](https://cloud.githubusercontent.com/assets/20505284/22408069/5a5328fc-e640-11e6-987a-ba91aee545c0.png)

**Comment by no-stack-dub-sack** [comment]
@chznbaum nice catch! Open to making a PR to fix your discovery? If not, no worries, figured I'd give you the first right of refusal though. If so, check out the contributing guidelines so you have a good idea of whats going on. Thanks!

**Comment by chznbaum** [comment]
@no-stack-dub-sack Sorry for the delayed response. I'm out of town and have had less time than usual lying around. I'll need to pass for now just for lack of time, but thanks!

**Comment by SehrOne** [comment]
If nobody is already working on it, could I give it a try?

**Comment by no-stack-dub-sack** [comment]
@SehrOne All yours! PM me on gitter if you have any questions when coming up with the new test.
