### ISSUE TITLE
http://c9.io is no more freely accessible

### ISSUE THREAD

**Issue by Jefreesujit** [freeCodeCamp/testable-projects-fcc#290]
Hi,

I just started with the backend development certification, and it requires an account in c9. Since c9 is acquired by AWS now, it requires users to have an aws account (Paid Service). It will be nice if FreeCodeCamp comes up with a better alternative for c9, so that it will be easier for users to get started easily.

**Comment by tchaffee** [comment]
@Jefreesujit Thanks for reporting this. Could you please report it on the main repository at https://github.com/freeCodeCamp/freeCodeCamp? This repository only concerns the testable projects. Thanks!
