### ISSUE TITLE
Technical Documentation- Matching Nav-Link and Header text not passing test 12

### ISSUE THREAD

**Issue by charlottejoy** [freeCodeCamp/testable-projects-fcc#291]
#### Issue Description

Can't get test 12 to pass, but seems it meets the requirements. Maybe I'm missing something.
It passed when I was first working on this, but at some point, it stopped passing. Sorry, I don't know which change did it. 

Things I've tried:
- Forked the test suite again and copied my code. 
- Removed the div surrounding the nav-links
- Removed the H2 surrounding the header text in the sections
- Removed the onclick I've got with the nav-links, the letter cases match. 

#### Browser Information
* Browser Name, Version:  Google Chrome, Version 65.0.3325.146 (Official Build) (64-bit)
* Operating System:  Windows 10 home
* Mobile, Desktop, or Tablet: Laptop

#### Your Code / Link to Your Pen
 https://codepen.io/charlottejoy/pen/GQarMm
```
 ...<a class="nav-link" href="#Intro" onclick= "hideNav()">Intro</a>...  
<section class="main-section" id="Intro">
     <header><h2>Intro</h2></header>...
```

#### Screenshot
![image](https://user-images.githubusercontent.com/17909419/37213516-42123afc-2380-11e8-8a3f-402f339ccb41.png)

**Comment by tbushman** [comment]
@charlottejoy Thanks for reporting this. I have reproduced the error and am looking into it.

**Comment by charlottejoy** [comment]
@tbushman Thank you. Very much appreciated.
