### ISSUE TITLE
Scroll-behavior: smooth causes navbar link test to fail

### ISSUE THREAD

**Issue by charlottejoy** [freeCodeCamp/testable-projects-fcc#295]
#### Issue Description
Test 11 of the portfolio project wasn't passing anymore. 
I realized that it passes if I remove the scroll-behavior: smooth that I had added. 

#### Browser Information
* Browser Name, Version: Google Chrome, Version 65.0.3325.146 (Official Build) (64-bit)
* Operating System: Windows 10 home
* Mobile, Desktop, or Tablet: Laptop

#### Your Code / Link to Your Pen
https://codepen.io/charlottejoy/pen/pLvjGe

```
 html{scroll-behavior: smooth} = failed test

/*html{scroll-behavior: smooth}*/ = passed test
```

#### Screenshot

![image](https://user-images.githubusercontent.com/17909419/37523423-42c1f5dc-28fd-11e8-9ddb-0232b7691754.png)

Thanks for looking into this.

**Comment by tbushman** [comment]
@charlottejoy I'm stumped on this one. I thought it might be a problem with designating scroll-behavior on `<html>`. This error has been reproduced with scroll-behavior: smooth on a wrapping div as well. I've tried adding a setTimeout and using a callback for each anchor click in test 7 to see if maybe the smooth-scroll delays the position reading...

**Comment by tchaffee** [comment]
@charlottejoy This is fixed now. Could you please test it and make sure it works with your CodePen. Thanks!

**Comment by charlottejoy** [comment]
Just tested it on the same setup as above and it works. Yay! Thank you very much people :-)
