### ISSUE TITLE
testable-projects-fcc has been blacklisted

### ISSUE THREAD

**Issue by ArielLeslie** [freeCodeCamp/testable-projects-fcc#297]
#### Issue Description
Users are not able to test their projects in CodePen because importing the external resource fails with a 403.

Just for funsies I tried browsing to https://gitcdn.link/repo/freeCodeCamp/testable-projects-fcc/master/build/bundle.js which gave me the following message:
"Forbidden - This repo/gist is on the blacklist. If you wish to appeal, please open an issue here: https://github.com/schme16/gitcdn.xyz/issues, with why you feel this repo should not be on the blacklist."

#### Browser Information
* Browser Name, Version:  Chrome Version 64.0.3282.186 
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen
This was in response to a forum post. Here is the camper's pen: https://codepen.io/freeCodeCamp/pen/MJjpwO

#### Screenshot
![image](https://user-images.githubusercontent.com/6234475/37791664-6cb04354-2dcf-11e8-93c5-bdb43980cb15.png)

![image](https://user-images.githubusercontent.com/6234475/37791699-82e9a8ea-2dcf-11e8-954a-c0e13f76d74b.png)

**Comment by tchaffee** [comment]
Thank you for reporting this. I opened an issue with them here: https://github.com/schme16/gitcdn.xyz/issues/26

**Comment by tchaffee** [comment]
If you want to temporarily change the JavaScript settings for the CodePen, this link should at least get it working for now. When we get this fixed you will need to change it back or it will cause problems in the future.

https://cdn.rawgit.com/freeCodeCamp/testable-projects-fcc/a8c73bc53149aec717b08b9c14f2273eecd31c39/build/bundle.js

**Comment by tchaffee** [comment]
This is fixed now, per the issue I opened with gitcdn.
