### ISSUE TITLE
when I load the test for my portfolio, it first passes as 7/12, then changes to 12/12 after about 2 seconds

### ISSUE THREAD

**Issue by Oyelowo** [freeCodeCamp/testable-projects-fcc#299]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 
 
```

#### Screenshot

![image](https://user-images.githubusercontent.com/31687368/38486021-7b24ba0a-3be4-11e8-80e8-075edcf1f267.png)

![image](https://user-images.githubusercontent.com/31687368/38486043-89c63c32-3be4-11e8-9230-407557e5bb32.png)

**Comment by tchaffee** [comment]
@Oyelowo Cool background! Thanks for reporting this. Could you give us a link to your CodePen so we can understand if it is a problem or working as designed? Thanks!

**Comment by Oyelowo** [comment]
Thank you, tchaffee! I'm so sorry for the belated response. Just found the notification while searching through my spam folder. Here is the link with the test, hosted on my github: https://oyelowo.github.io/oyelowo_portfolio_tested/html/main.html#section-4

**Comment by tchaffee** [comment]
@Oyelowo That is working as designed. Everything is ok. The tests take some time to run, some tests longer than others. You will see this on other projects too. I'm closing this issue but feel free to reopen it if there are still any doubts.

**Comment by Oyelowo** [comment]
All right. I was just wondering if that was why I could not claim the responsive web design certificate. Thanks a bunch @tchaffee

**Comment by OJKT** [comment]
Okay, so I'm getting the same issue and can not claim the responsive web design certificate. https://codepen.io/ojkt/full/OaOrEe/
here is mine... I have the same loading issue.
maybe the bot that measures the score doesn't wait until final test score comes in?

**Comment by OJKT** [comment]
Never mind, I had to try a couple of times until it went through... still odd, didn't happen with the other projects.
