### ISSUE TITLE
testable-projects-fcc has been blacklisted

### ISSUE THREAD

**Issue by Heleanna** [freeCodeCamp/testable-projects-fcc#306]
It's exactly the same issue as this one from March 3rd: https://github.com/freeCodeCamp/testable-projects-fcc/issues/297

Users are not able to test their projects in CodePen because importing the external resource fails with a 403.

Opening https://gitcdn.link/repo/freeCodeCamp/testable-projects-fcc/master/build/bundle.js gives the following message:
"Forbidden - This repo/gist is on the blacklist. If you wish to appeal, please open an issue here: https://github.com/schme16/gitcdn.xyz/issues, with why you feel this repo should not be on the blacklist."

#### Browser Information

* Browser Name, Version: Opera 52.0.2871.64 / Firefox Quantum 59.0.2 (64-bit) / Google Chrome Version 65.0.3325.181 (Official Build) (64-bit)
* Operating System: Windows 10 64-bit (WoW64)
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

https://codepen.io/freeCodeCamp/pen/MJjpwO

**Comment by tchaffee** [comment]
@Heleanna Thank you for reporting this. We might need to look for another CDN long term. In the meantime I commented on existing issue https://github.com/schme16/gitcdn.xyz/issues/36 which someone else opened a few hours ago.

**Comment by tchaffee** [comment]
@Heleanna This seems to be working now, even though the issue is still open over at gitcdn. Could you test it and let us know if it's working for you?

**Comment by Heleanna** [comment]
Yes, it's working now.

**Comment by tchaffee** [comment]
@Heleanna Thanks so much for letting us know.
