### ISSUE TITLE
[BETA] Build a Drum Machine Tests 5-7 Not Passing (possible React issue)

### ISSUE THREAD

**Issue by vipatron** [freeCodeCamp/testable-projects-fcc#307]
#### Issue Description
The last three tests aren't passing for me (5 - click to play a sound, 6 - press a key to play a sound, 7 - the #display element displays a string name for the sound), even though all three things are happening.

I checked the ["bundle.js"](https://gitcdn.link/cdn/freeCodeCamp/testable-projects-fcc/db389c49dd321d8fc6d34fcad29c28d1d969c6f9/build/bundle.js) file, and the relevant code from the 5th test (click to play) is:
```
reqNum++;
it(reqNum + '. When I click on a .drum-pad element, the audio clip\n      contained in its child <audio> element should be triggered.', function () {
	_chai.assert.isAtLeast(audioElements.length, 9, 'Audio elements do not exist ');
	audioElements.forEach(function (el) {
		document.getElementById(el.parentElement.id).click();
		_chai.assert.isNotOk(document.getElementById(el.id).paused, 'The <audio> element with id="' + el.id + '" does not play when the ' + el.id + ' .drum-pad is clicked ');
	});
});
```
To explain *why I believe* it is failing, a brief explanation of my program logic:

I built my Drum Machine with React, using Stateless Functional Components for everything but the highest-level container. I had to resort to using three global-context arrays, one for the keys in order, and two others in parallel order for the two soundbanks.

5. I handle clicks via "MouseDown" events that allow the button to be re-classed so it lights up, and subsequent "MouseUp" events that reset the Container component's state. The event handlers are defined at the top-level Container component, and passed in as props through this branch of my component tree:
```
<Container />
  <PadBank />
    <Button />
      <div className="button" onMouseDown="..." onMouseUp="...">
```
So, the buttons don't have a click event, so this may be why it's failing. 

6. Also, looking at the next codeblock in "bundle.js", I noticed that the keydown event gets sent to the parent element of the audio clip. However, in the React lessons in the Beta, I noticed that in [the "add Event Listeners" lesson](https://beta.freecodecamp.org/en/challenges/react/add-event-listeners), `keydown` event listeners were added to the document. When I googled around, it seemed that I couldn't add keydown events to specific elements that weren't inputs or textareas (per stackoverflow), despite W3Schools' saying that `<div>`s weren't on the excluded list. So, i just followed the example in the curriculum, and it worked. I don't think this is a problem with my implementation, but of course I could be totally wrong.
```
reqNum++;
it(reqNum + '. When I press the trigger key associated with each\n      .drum-pad, the audio clip contained in its child <audio> element should be\n      triggered (e.g. pressing the Q key should trigger the drum pad which\n      contains the string "Q", pressing the W key should trigger the drum pad\n      which contains the string "W", etc.).', function () {
	this.timeout(900);
	var keyCodes = [81, 87, 69, 65, 83, 68, 90, 88, 67];
	_chai.assert.isAtLeast(audioElements.length, 9, 'Audio elements do not exist ');
	return new Promise(function (resolve) {
		setTimeout(function () {
			audioElements.forEach(function (el, i) {
				__triggerKeyboardEvent(document.getElementById(el.parentElement.id), keyCodes[i]);
				_chai.assert.isNotOk(document.getElementById(el.id).paused, 'No audio plays when the ' + el.id + ' key is pressed ');
			});
			resolve();
		}, 800);
	});
});
```

7. I looked at the code for the display string, but I think the issue is clicking vs mouseDown-ing again. I've reproduced it here:
```
reqNum++;
it(reqNum + '. When a .drum-pad is triggered, a string describing the\n      associated audio clip is displayed as the inner text of the #display\n      element (each string must be unique).', function () {
	this.timeout(900);
	var displayText = [];
	return new Promise(function (resolve, reject) {
		setTimeout(function () {
			drumPads.forEach(function (pad) {
				document.getElementById(pad.id).click();
				displayText.push(document.getElementById('display').innerText);
			});
			displayText = displayText.filter(function (str, i) {
				return displayText[0] === displayText[i];
			});
			if (displayText.length === 1) {
				resolve();
			} else {
				reject(new Error('Each time a drum pad is triggered, a unique string should ' + 'be displayed in the element with the id "display"'));
			}
		}, 800);
	});
});
```

#### Browser Information
* Browser Name, Version: Windows 10, 64-bit
* Operating System: Chrome 65.0.3325.181
* Mobile, Desktop, or Tablet: Desktop 

#### Your Code / Link to Your Pen
https://codepen.io/vipatron/full/wjzYJo/

**Comment by tbushman** [comment]
@vipatron Thanks. You're right, it looks like `HTMLElement.click()` doesn't trigger `mousedown`... https://stackoverflow.com/questions/41137818/why-doesnt-htmlelement-click-fire-mousedown-up   
We might need to add a dispatchEvent() with the workaround used in markdown-previewer.

**Comment by vipatron** [comment]
Thanks, @tbushman. That would probably solve the issues with tests #5 & 7. Regarding the keydown event, is this an issue with my implementation (i.e.: is there a keydown hook on divs to which I can attach an event handler, and I should just refactor my code to use class components rather than functional ones?) or is there something in the testing codebase that could be modified? I wish I were able to be of more help.

**Comment by tbushman** [comment]
@vipatron This PR passes all of your tests, so I do think there was an issue with the configuration of the `<audio>` object for programmatic events on our end. We had a similar issue with a `<textarea>` Object in markdown-previewer tests #223 .
