### ISSUE TITLE
[markdown previewer] tests 3, 4 (and 7?) fail in vue.js implementation

### ISSUE THREAD

**Issue by no-stack-dub-sack** [freeCodeCamp/testable-projects-fcc#31]
When implemented with vue.js, the markdown editor does not pass all tests even though it functions according to specs. 

Thanks @christophherr for reporting this! I've forked your pen to preserve this issue in case you change or delete it. 

### Pen: 
http://codepen.io/no_stack_dub_sack/pen/bgvoMa

**Comment by no-stack-dub-sack** [comment]
Hey @QuincyLarson, @christophherr reported this issue on the forum, and it's an interesting one. I know we discussed when this was being developed, that testing implementations in jQuery, React, and vanilla would cover about 90% of campers - well... here's one of our 10%!

Problem is, i have no idea what's going on under the hood in Vue.js - so I'm at a loss on how to test for what it's doing.  I know we wanted to be as implementation agnostic as possible on these, but I would guess there are also other libraries out there that will break these tests. Any thoughts?

Also - now that beta has launched, I anticipate a higher frequency of campers completing these projects and giving us feedback, which is great, because we def need more before launching this suite into full blown production - some of the projects have not been QA built at all yet (such as choropleth). 

Point being, with the recent addition of the "report bug" link ( #24 ), I'm inclined to close (or at least un-list) the forum QA threads, so that all bugs/issues can be tracked in one place. 

![image](https://cloud.githubusercontent.com/assets/18563015/22535159/29b86084-e8c7-11e6-92f2-e8938c225ae9.png)

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack I agree with your suggestion. I think we should lock these threads and encourage people to click the "report bug". I can make the announcement.

Other than Choropleth, are there any other challenges which no one has attempted a QA build yet? I can tweet links to them and probably get people working on them immediately.

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson Only one person each have done both the [bar chart](https://forum.freecodecamp.com/t/bar-chart-project-with-testable-user-stories-guinea-pigs-needed/71909/4) and the [tree map](https://forum.freecodecamp.com/t/tree-map-d3-project-with-testable-user-stories-guinea-pigs-needed/78623/2) (and both unsuccessfully in terms of passing all tests), and no one has done the other 2 D3 projects, Choropleth and Scatterplot. 

Would def be good to get people working on these.

Also, any thoughts on the first part of this issue?

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack OK - I'm locking these threads now. I think with the volume of people who will be working through these soon, you should get issues for both Choropleth and Scatterplot. I'm going to announce these prominently once we iron out a few more issues, then leave them in beta for a few weeks with people working through them.
