### ISSUE TITLE
Heatmap - test #9 fails on a wrong element

### ISSUE THREAD

**Issue by iabrenne** [freeCodeCamp/testable-projects-fcc#315]
#### Issue Description

Test 9 is failing with "TypeError: Cannot read property 'toLowerCase' of null".

However, it appears that the shape element it's erroring on is actually for first `<rect>` on my legend, rather than the `<rect>` on the actual heatmap.

I realize these tests are difficult to setup perfectly to accommodate various ways campers may set up their projects. I see there were previous improvements made to this specific test  in [D3 Heat Map - Test #9 Edge Case #71](https://github.com/freeCodeCamp/testable-projects-fcc/issues/71). I will keep tinkering with my project until it passes the FCC tests - otherwise I don't feel right claiming this one as completed :-) However, I wanted to bring this one up, as it appears that test is tripping up on the wrong element.

Here is my pen : https://codepen.io/irinabrennen/full/JvzbWB/

Unless I am missing something obvious, everything appears to meet all the user stories. 

#### Screenshot

![image](https://user-images.githubusercontent.com/24214306/40336354-b4b598be-5d2e-11e8-825b-5d79f55eaf51.png)
![image](https://user-images.githubusercontent.com/24214306/40336359-bc6c9f94-5d2e-11e8-9c98-a98d95edfb39.png)
![image](https://user-images.githubusercontent.com/24214306/40336412-0da8db98-5d2f-11e8-99b7-961ecc560227.png)

**Comment by tbushman** [comment]
@iabrenne Thank you for reporting this. A PR is pending to fix it.
