### ISSUE TITLE
Survey form: checkbox test broken on safari

### ISSUE THREAD

**Issue by thomaskuntzz** [freeCodeCamp/testable-projects-fcc#325]
#### Issue Description

The test for the checkboxes in the Survey Form project (User Story 14) fails in safari whereas the code is good and passes the tests on chrome

#### Browser Information

* Browser Name, Version: Safari Version 11.1 (13605.1.33.1.4)
* Operating System: macOS High Sierra 10.13.4
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

https://codepen.io/thomaskuntzz/pen/WyQgzB

**Comment by thomaskuntzz** [comment]
Yeah, right, but I reported this so maybe this bug could be solved and thus the support of safari could be improved 😉

**Comment by tchaffee** [comment]
@thomaskuntzz We don't have an short term plans for supporting Safari so I am closing this. We do want to look at this in the future though and will open issues about that support when we get closer. Thanks for reporting this and happy coding!
