### ISSUE TITLE
Pass in Chrome but Fail in Codepen?

### ISSUE THREAD

**Issue by darrylmorley** [freeCodeCamp/testable-projects-fcc#326]
Tribute Page

#### Issue Description
So, although basic, my code passes the criteria in the Chrome browser using a local file but fails in Codepen.

#### Browser Information
Laptop
Ubuntu 18.04
Atom Text Editor
Chrome Version 67.0.3396.62 (Official Build) (64-bit)

#### Your Code / Link to Your Pen

https://codepen.io/daz1uk/pen/RazBBE

#### Screenshot

![screenshot from 2018-06-03 19-45-33](https://user-images.githubusercontent.com/20406137/40889960-c1ae4768-6766-11e8-80dc-9cc30ddd24b5.png)
![screenshot from 2018-06-03 19-45-52](https://user-images.githubusercontent.com/20406137/40889961-c1c985aa-6766-11e8-8647-0ceecf59e09b.png)

**Comment by tbushman** [comment]
@darrylmorley Thanks for reporting this. I've reproduced this issue as described. Looking into it! Thanks.

**Comment by tbushman** [comment]
The problem is that the workaround for testing whether a property is set to 'auto', namely first setting that element's display property to 'none', doesn't seem to work in Codepen.  

```
        // In order to determine if the height style is "auto", we
        // need to use a little trick. If we use getComputedStyle and the
        // element has an actual size we will get the actual pixels. So we
        // temporarily set the "display" style to "none", which will tell
        // us if the height is "auto".
        img.style.display = 'none';
        heightValue = getPropValue(img, 'height');
        assert.equal(
          heightValue,
          'auto',
          'Use the "height" style property with a value of "auto" for' +
          'responsive images.'
        );
```

`console.log(img.style.display);`
Codepen and Chrome:
>Logs 'none'

`console.log(heightValue);`
Codepen:
>Logs a float in px

Chrome:
>Logs 'none'

**Comment by darrylmorley** [comment]
Thanks @tbushman for looking into this :+1:
