### ISSUE TITLE
Product Landing Page - Check 6 failed for valid syntax

### ISSUE THREAD

**Issue by GeoffMooreMedia** [freeCodeCamp/testable-projects-fcc#327]
Test 6 returns an error for a valid video tag of the form. 
`<video>
    <source src="VidSource" type="video/mp4">
    <source src="AudSource" type="audio/ogg">
</video>  `    

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 
 
```

**Comment by tbushman** [comment]
Thanks @GeoffMooreMedia . The current test is looking for the `src` attribute within the `<video>` element. We should add support for this method, so I'll keep this issue open. Until that's fixed, in order to pass the test, you will need to assign `<video>` the `src` attribute.
