### ISSUE TITLE
Porfolio Page error regarding navbar (error: timeout of 10000ms exceeded)

### ISSUE THREAD

**Issue by nareeratty** [freeCodeCamp/testable-projects-fcc#328]
#### Issue Description

When I clicked on the run test, the error message is displayed inside the  Unit Test #Content No.7

#### Browser Information

Firefox60

* Browser Name, Version: Firefox 60
* Operating System: Window 7
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 https://codepen.io/nareeratty/pen/qKbPax
 
 
```

#### Screenshot

![errorcontentno7](https://user-images.githubusercontent.com/36248686/40900072-07f10336-67f4-11e8-88c1-15ec86f82e6d.jpg)

**Comment by tbushman** [comment]
@nareeratty Thank you for reporting this. We'll look into it.
@tchaffee , You may be more familiar with what's going on here. I have a hunch it may have to do with the `.click()` function not fully firing, as was the case with the drum-machine test recently.

**Comment by tbushman** [comment]
@nareeratty @tchaffee I found the problem. A PR is pending for this (#384). With this fix, the project passes all #content tests.
