### ISSUE TITLE
Technical Documentation page - test 12 error

### ISSUE THREAD

**Issue by efficientoranges** [freeCodeCamp/testable-projects-fcc#329]
#### Issue Description

I'm getting an error on test 12 for the technical documentation page - the error is

"12. Each element with the class of "nav-link" should contain text that corresponds to the `<header>` text within each `<section>`"
"AssertionError: Check that these headers have corresponding .nav-link elements and be mindful of case! : INTRODUCTION,WHAT YOU SHOULD ALREADY KNOW,JAVASCRIPT AND JAVA,HELLO WORLD,VARIABLES,DECLARING VARIABLES : expected 6 to equal 0"

I have text for each `<header>` tag between the corresponding `<a>` tags so I think this is an error.

It looks like it's expecting text in uppercase even though my `<header>` text is in lowercase with capitals.

The text inside my `<header>` tags is wrapped inside `<h2>s` but I tried removing these and it had no effect on the error.

#### Browser Information

* Browser Name, Version: Chromium Version 64.0.3282.140 (Official Build) Built on Ubuntu (64-bit) 
* Operating System: Ubuntu 16.04
* Mobile, Desktop, or Tablet: Laptop

#### Your Code / Link to Your Pen

https://codepen.io/rearle/pen/ERPMRM?editors=1100
```
 
 
 
```

#### Screenshot

![image](https://user-images.githubusercontent.com/39916702/40926587-6e798ff4-6814-11e8-9c02-a51cd539948c.png)

**Comment by tbushman** [comment]
@efficientoranges Thanks for reporting this.  
@tchaffee I think this is similar to #291 (#292).

**Comment by tbushman** [comment]
@efficientoranges I just ran your Codepen with the updated CDN: `https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js` and all the tests passed! Will you switch out your testable-projects bundle.js url and see if that fixes any errors for you? Thanks.

**Comment by efficientoranges** [comment]
@tbushman Thanks for looking into this.

I switched to the new URL and I'm still getting the same error for some reason.

For what it's worth I also tested with Chrome on Windows 10, and tried creating a new pen and copying the code over, and I still got the same error both times.

**Comment by tbushman** [comment]
@efficientoranges OK I'll keep looking.

**Comment by tbushman** [comment]
@efficientoranges This is a similar issue mentioned by @no-stack-dub-sack in #351 when the test suite is included more than once. You have it in your settings > javascript in addition to the `<script>` element in your html. Please include the script only once. Thanks!

**Comment by tbushman** [comment]
Closing on assumption that this is resolved.
