### ISSUE TITLE
Issue with Responsive Web Design Project

### ISSUE THREAD

**Issue by RafaRochaS91** [freeCodeCamp/testable-projects-fcc#330]
#### Issue Description
Despite having working media queries it displays that the page has none. 

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: MacOS
* Mobile, Desktop, or Tablet: Laptop 

#### Your Code / Link to Your Pen

```
 https://codepen.io/RafaRochaS91/pen/ERPqOy
 
 
```

**Comment by tbushman** [comment]
@RafaRochaS91 Thanks, I tested your pen in Chrome and it passed the media query test. One test that didn't pass was the `#navbar` element remaining in view upon scroll (Layout test 1). Please open a separate issue if you find a problem with that test.
