### ISSUE TITLE
The testable projects template worked for me for about two days and then today it disappeared and I cant seem to get it to work.

### ISSUE THREAD

**Issue by Kitkat101215** [freeCodeCamp/testable-projects-fcc#331]
<script src="https://gitcdn.link/repo/freeCodeCamp/testable-projects-fcc/master/build/bundle.js"></script>
 This is the line of code putting the test up I believe, but it stopped working and I'm wondering why? I have tried closing the browser and restarting my laptop and it just doesnt work. Is there another reason why it isnt working?
 
 
```

#### Screenshot
<!-- Add a screenshot of your issue -->
![screenshot 2018-06-04 at 10 40 20 pm](https://user-images.githubusercontent.com/36011175/40952315-cd0d1994-6848-11e8-8869-e8cc0b65861a.png)

**Comment by tbushman** [comment]
@Kitkat101215 Hi, we very recently moved the bundle.js to the fCC CDN: `https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js`. Give that a try and let us know if it doesn't work! Thanks.
