### ISSUE TITLE
Build a Drum Machine Challenge test

### ISSUE THREAD

**Issue by crazycat9x** [freeCodeCamp/testable-projects-fcc#332]
#### Issue Description

I wasn't able to pass the last test although everything seems to be working

#### Browser Information

* Browser Name, Version: 
* Operating System: MacOS
* Mobile, Desktop, or Tablet: Laptop

#### Your Code / Link to Your Pen

```
 https://codepen.io/NKTien/pen/ZRWead?editors=0111
```

**Comment by tbushman** [comment]
@crazycat9x Thanks! I'm not good with react, but the error says audioTag.current is null. Looking into React.createRef(), it looks like you'll want  
```
let audioTag.current = React.createRef()
```
The error does not originate from our stack.

**Comment by crazycat9x** [comment]
I have that line of code, and it work, just not for the test
`let audioTag = React.createRef()
  
  function playSound(){
    audioTag.current.currentTime = 0
    audioTag.current.play()
    props.setPastKey(props.id)
  }`

**Comment by crazycat9x** [comment]
I used a try statement and passed all of the tests? maybe the test doesn't fair well with react new ref api?
```
function playSound(){
    try{
      audioTag.current.currentTime = 0
      audioTag.current.play()
      props.setPastKey(props.id)
    } catch (e) {
      console.log(e)
    }
  }
```

**Comment by tbushman** [comment]
It's because you need to define `audioTag.current` , not only `audioTag` . This error handler helps for when it hasn't been defined yet. Closing this. Thanks!
