### ISSUE TITLE
Mocha tests Issue

### ISSUE THREAD

**Issue by RafaRochaS91** [freeCodeCamp/testable-projects-fcc#334]
#### Issue Description

> Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
>     at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:7197

This happens because done(); isn't called in the test function(). 

#### Browser Information

* Browser Name, Version: Chrome latest
* Operating System: MacOS latest
* Mobile, Desktop, or Tablet: MacbookPro 2017

#### Your Code / Link to Your Pen
 [https://codepen.io/RafaRochaS91/full/MXyQXj](https://codepen.io/RafaRochaS91/full/MXyQXj)

#### Screenshot

<img width="695" alt="captura de tela 2018-06-05 as 09 47 32" src="https://user-images.githubusercontent.com/7062978/40965701-622aa25a-68a6-11e8-8b40-342830138ce4.png">

**Comment by tbushman** [comment]
@RafaRochaS91 I just tested your pen in Chrome on Windows and it works. Are you still encountering this error?

**Comment by tbushman** [comment]
Closing. Please reopen if you encounter this error again.
