### ISSUE TITLE
Weird Re-Loading Bug in the Personal Portfolio Project

### ISSUE THREAD

**Issue by thegouge** [freeCodeCamp/testable-projects-fcc#336]
#### Issue Description

Whenever I run the test suite in my portfolio project, it gets to 7/12 tests, then completely re-loads the page. I've tried taking out the nav (since I think it's getting hung up on the link following tests). I've tried displaying both custom dropbox menus, and I've set all links to `target="_blank"`

In all honesty, this is probably happening because this is a project I've been working on independently (before free code camp). So the code in general is kinda messy (sorry in advance). But I'm curious about exactly how it's breaking, so I know how to clean my code! :)

#### Browser Information

* Google Chrome, Version:  67.0.3396.62 (Official Build) 
* Operating System: Windows
* Device: Windows Surface Pro
* Coding Environment: Visual Studio Code

it is worth noting that I have a similar problem when I drop the code into codepen (instead of re-loading it turns into a blank page)

#### Link to Your Pen
https://codepen.io/thegouge/pen/QxjdEQ?editors=1100

**Comment by tbushman** [comment]
@thegouge The tests are dispatching clicks on your navigation elements, which contain external links and the codepen iframe gets reloaded. We should make sure the tests only click elements with a `href` that begins with the `#` symbol.   

I have a PR coming up to filter the navbar anchors. If you want to work on your other tests, please move the external anchors (Linkedin, Github links) outside of the #navbar so they don't get programmatically clicked by our tests. Thanks!

**Comment by thegouge** [comment]
Awesome, thank you!
