### ISSUE TITLE
Product Landing Page - Code satisfies all user stories, but fails validation.

### ISSUE THREAD

**Issue by joediliegghio** [freeCodeCamp/testable-projects-fcc#337]
My code satisfies all the user story requirements. It passed validation 16/16 until I updated the header content to use Bootstrap. I added a collapsable nav bar to make the site mobile friendly.

#### Issue Description
12/16 Pass

#### Browser Information
Testing using CodePen using the following .js to validate
https://gitcdn.link/repo/freeCodeCamp/testable-projects-fcc/master/build/bundle.js

* Browser Name, Version: Chrome
* Operating System: Windows 7
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen
https://codepen.io/jdiliegghio/pen/wXMWMg
```
<header id=”header” class="fixed-top">
    <div class="container">
      <nav id="nav-bar" class="navbar navbar-expand-sm navbar-dark bg-dark">
        <a class="navbar-brand branding" href="https://www.stanleytools.com/en-us" target="_blank"><img id="header-img" src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/274865/logo-update.png" alt="Stanley Tools Logo"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#myNav" aria-controls="myNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="myNav">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item"><a class="nav-link" href="#product-link">PRODUCTS</a></li>
          <li class="nav-item"><a class="nav-link" href="#about-link">ABOUT</a></li>
          <li class="nav-item"><a class="nav-link" href="#contact-link">CONTACT</a></li>
        </ul>
      </div>
    </nav>
  </div>
</header>
 
 
```

**Comment by tbushman** [comment]
@joediliegghio Thanks for bringing this to our attention. This may become an issue in any of the projects. It looks like the Bootstrap DOM elements are not ready at the moment the test is run.
I used a `setTimeout` of two seconds and got your tests to pass. 

I can submit a PR, but I don't know if `setTimeout` would be the best way. We can discuss whether other methods like `MutationObserver` or a `try ... catch` would be better.

**Comment by joediliegghio** [comment]
@tbushman I'm really new to most of this, so please forgive my ignorance when it comes to the solutions you mentioned. I'm happy to work with you, and willing to try different approaches, but I don't know how much I can offer in the way of a discussion considering I've only just started the FCC javascript sequence. For now do we want to go with setTimeout, and circle back to this later when I've gained more experience?

**Comment by tbushman** [comment]
@joediliegghio Good idea. My head is spinning with the idea that this is potentially a problem for any of the projects that people would want to use Bootstrap.js with. I'm not sure if it's just the dropdown, but this is the first time I've seen an issue like this with Bootstrap. I'll look into this. Thanks!

**Comment by joediliegghio** [comment]
@tbushman I don't know if this info helps or not, but I also did the survey form project using bootstrap and none of the test cases failed. Here is the `<a href="https://codepen.io/jdiliegghio/pen/mKeYxN" target="_blank">Link</a>`

**Comment by tbushman** [comment]
@joediliegghio Thanks. Turns out you have curly quotes on your id="header". Make sure you are using straight quotes, and that should do it!

**Comment by tbushman** [comment]
@joediliegghio Regarding the setTimeout idea, I noticed I was still getting the error in browser, so that was a false positive. Thanks!
