### ISSUE TITLE
Technical Documentation Issue : My Navbar Is On Left Side And Responsive 

### ISSUE THREAD

**Issue by iibarbari** [freeCodeCamp/testable-projects-fcc#338]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

https://codepen.io/barbari/pen/ERydqv
```
 
 
 
```

**Comment by tbushman** [comment]
@iibarbari Please provide a link to or a sample from your code so we can look into this.

**Comment by iibarbari** [comment]
https://codepen.io/barbari/pen/ERydqv

**Comment by tbushman** [comment]
@iibarbari Awesome. Looks like it's working. I'm closing issues that seem resolved. Will you please reopen this if you see an error?
