### ISSUE TITLE
Survey Form Problem on tests 4 and 5 

### ISSUE THREAD

**Issue by petercr** [freeCodeCamp/testable-projects-fcc#341]
#### Issue Description
After completing all of the user stories for the Build a Survey Form I keep getting the same 2 conditions not passing the tests. Both test number 4 and test number 5 keep failing even though both conditions are met.  Here are the conditions for the tests. 

Test 4: Inside the form element, I am required to enter my name in a field with id="name".
Test 5: Inside the form element, I am required to enter an email in a field with id="email".

I am running a local server on my laptop. 

#### Browser Information
Running local server using VS Code Live Server extension over `port:4000` into Chrome 67

* Browser Name, Version: Google Chrome 67.0.3396.79
* Operating System: Windows 10 
* Mobile, Desktop, or Tablet: Laptop

#### Your Code / Link to Your Pen

```
 <form action="submit" id="survey-form">
      <label for="" id="name-label">Enter Name</label>
      <input type="text" name="name" id="name" placeholder="Enter your name here">
      
      <label for="" id="email-label">Enter your email:</label>
      <input type="email" name="email" id="email" placeholder="Your email address">
      
      <label for="" id="number-label">How excited are you on a scale of 1 to 10? </label>
      <input type="number" name="number" id="number" min="1" max="10" placeholder="10" required>
      
      <label for="">How long have you been coding?</label>
      <select name="dropdown" id="dropdown">
        <option value="1">Less than 1 year</option>
        <option value="2">1 - 2 Years</option>
        <option value="3">3 - 5 Years</option>
        <option value="4">5+ Years</option>
      </select>
</form>
 
```
Also here is a link to the complete [HTML file on GitHub](https://github.com/petercr/html5-survey-form/blob/master/index.html)
#### Screenshot
![2018-06-07](https://user-images.githubusercontent.com/26460352/41111639-85552cbe-6a4a-11e8-872e-22995d8ad9a2.png)
![2018-06-07 1](https://user-images.githubusercontent.com/26460352/41111646-8a15e13a-6a4a-11e8-8092-b3f5c0785010.png)

**Comment by tbushman** [comment]
@petercr Hi, I believe the tests are referring to the HTML5 input `required` attribute. https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Form_validation

**Comment by petercr** [comment]
@tbushman **Thank you so much.** That was it!! 😄 👍 🥇 
I don't know why I missed that one 😿 But thanks again
