### ISSUE TITLE
help me for Build a Tribute Page

### ISSUE THREAD

**Issue by abhiramnaidu03** [freeCodeCamp/testable-projects-fcc#342]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 
 
```

**Comment by tbushman** [comment]
@abhiramnaidu03 Please provide a link to your Codepen and please fill out the form with a little more info: What is the error? etc.

**Comment by abhiramnaidu03** [comment]
https://forum.freecodecamp.org/clicks/track?url=https%3A%2F%2Fcodepen.io%2FABHIRAMNAIDU%2Fpen%2Fvryymx&post_id=436286&topic_id=197949

**Comment by tbushman** [comment]
@abhiramnaidu03 Please switch out your fCC testable-projects bundle url. Use `https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js` please! If you have further questions, let us know.

**Comment by abhiramnaidu03** [comment]
https://forum.freecodecamp.org/clicks/track?url=https%3A%2F%2Fcodepen.io%2FABHIRAMNAIDU%2Fpen%2Fvryymx&post_id=436286&topic_id=197949
On 08-06-2018 12:05:17, Tracey Bushman <notifications@github.com> wrote:
@abhiramnaidu03 [https://github.com/abhiramnaidu03] Please provide a link to your Codepen and please fill out the form with a little more info: What is the error? etc.

**Comment by tbushman** [comment]
Please visit the gitter channels if you have questions after switching out that url. Thank you!
