### ISSUE TITLE
Test Suite Window: "X" button showing even after closing it 

### ISSUE THREAD

**Issue by shibatas** [freeCodeCamp/testable-projects-fcc#343]
#### Issue Description

The "X" button to close the test suite window remains showing even after closing the window, overlapping with the sandwich menu button as result.

This is happening on the unmodified test suite template.

**Comment by tbushman** [comment]
@shibatas Thanks! The localStorage variables that keep the window closed are not persisting. I'm looking into this.

**Comment by tchaffee** [comment]
@tbushman What's the status of this? Anything I can help with? Or try to take it over if you are stumped?

**Comment by tbushman** [comment]
@tchaffee I think this was fixed a while ago and not closed. I haven't seen localStorage problems for a while. Closing.
