### ISSUE TITLE
Can't move test controls

### ISSUE THREAD

**Issue by kennyray** [freeCodeCamp/testable-projects-fcc#346]
#### Issue Description

I am building the Survey Form, and the html is sitting behind the test suite controls. I can't find a way to drag that control out of the way. 
Should be able to duplicate this by starting a new project and adding some html.

It would be nice to be able to drag the control around, out of the way.

#### Browser Information

Mac, Chrome, Desktop

#### Your Code / Link to Your Pen

 Pen was forked from here: http://codepen.io/freeCodeCamp/pen/MJjpwO

**Comment by no-stack-dub-sack** [comment]
Can you show a screenshot? If you click the "X" the controls should get hidden, though it looks like the "fork me" pen has some css issues that didn't exist in older versions. For example:

![image](http://g.recordit.co/hm2fX12Ksr.gif)

Of course, the hamburger is still in the way, but the goal was for it to be as unobtrusive as possible. 

Being able to drag it would be a great feature though! I've mostly stepped away from maintaining this project, but I'm sure other contributors may be willing to pick something like this up.

**Comment by kennyray** [comment]
I just discovered the this a moment ago by clicking the X. I hadn't tried that before. It is fine when minimized. I didn't want to click the X initially because I was thinking "That will close it. How would I reopen it?". Perhaps something other than an X would be more descriptive, and indicate that it will minimize. :o)

Kenny

**Comment by tchaffee** [comment]
@tbushman I notice this is in the "To Do" list? What's the plan for this? It seems to me like this is actually working fine and we can close this?

**Comment by kennyray** [comment]
You can close it.  I just didn’t know how it worked. 

Kenny

**Comment by tbushman** [comment]
@tchaffee I left it open since there was the intriguing suggestion to be able to move the test window around. Not an urgent thing, so closing.
