### ISSUE TITLE
Portfolio Test Error

### ISSUE THREAD

**Issue by EdwardHanlon30** [freeCodeCamp/testable-projects-fcc#347]
#### Issue Description

When testing the portfolio its fails at 7 and exits without any report.
To get the report i must run a different test and then change my selection back to portfolio to see any results relating to the errors

#### Browser Information

* Browser Name, Version: latest Chrome
* Operating System: Win 7 32bit
* Mobile, Desktop, or Tablet: all platforms

#### Your Code / Link to Your Pen

```
 www.solowebdesigner.com
 
```

**Comment by no-stack-dub-sack** [comment]
@EdwardHanlon30 this is kind of an interesting one. The tests specify that at least one nav bar element should link to another part of the page, but it _doesn't_ specify that it shouldn't contain an external link, or a link to the page itself. The tests aren't existing without a report, the tests are actually clicking on every link in your navbar, one of which happens to be a link to your portfolio page &mdash; when that happens, the page is reloaded, and the tests are interrupted. If you take that link out, your tests should pass.

However, can I ask which CDN link you are using? The latest version of these tests [should prevent this very thing](https://github.com/freeCodeCamp/testable-projects-fcc/blob/59cd8776401eb5f921f4663952b09974ef4d092d/src/project-tests/portfolio-tests.js#L84) from happening. 

If you are not using this CDN, please try this instead (before implementing the above suggestion), to see if that does the trick: https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js.

If you are using that CDN, can we see a link to your code?

**Comment by EdwardHanlon30** [comment]
Hi no-stack-dub-sack,

I have provided a link to my code, but it is hosted personally on my hosting package at www.solowebdesigner.com

I will test your solution today and also report back with the link i used to include the tests.

Your diagnostic seems very logical and I feel your solution will negate the errors.
I also appreciate your prompt response thank you.

**Comment by EdwardHanlon30** [comment]
https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js

This is the cdn i used which i copied from the portfolio user-story/objective page

The solution you provided was correct and the test passed 12/12 thank you

**Comment by no-stack-dub-sack** [comment]
@EdwardHanlon30 glad to hear the tests are now passing

@tchaffee @tbushman I would close this as resolved, but it seems like he was using the correct CDN, however the external link in his navbar was causing the page to reload on test 7 despite the protection against this as mentioned above. A quick glance at the code looks like this is pretty simple, not sure why he was experiencing this - since you are both more up to date, thought I'd mention it, but may be safe to close unless it pops up again.
