### ISSUE TITLE
Survey Form Test Results are incorrect

### ISSUE THREAD

**Issue by ibrahimshahkhan** [freeCodeCamp/testable-projects-fcc#348]
#### Issue Description

My code contains a text field with id="name" similarly, email, number, ...but the test result is telling me that it is missing.

#### Browser Information

* Browser Name, Version:  Chrome
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Laptop

#### Your Code / Link to Your Pen

```
 
 https://codepen.io/ibrahimshahkhan/pen/QxGzXa
 
```

**Comment by tbushman** [comment]
@ibrahimshahkhan This is the same issue as #341 . Check out the link there for info HTML5 form validation. Thanks!
