### ISSUE TITLE
Free Code Camp tests popup won't collapse

### ISSUE THREAD

**Issue by irenesmith** [freeCodeCamp/testable-projects-fcc#351]
#### Issue Description

When I try to make the FCC test image collapse out of the way so I can see the whole page, it collapses to reveal the image as I've show from the screen shot.

#### Browser Information

This is happening in all of the pens where I've forked from the free code camp pen.

* Browser Name, Version: Chrome 67.0.3396.79 (Official Build) (64-bit)
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop with 32gb RAM, 4.0 Ghz, 8 core processor

#### Your Code / Link to Your Pen

```
 
 
 
```

#### Screenshot

![2018-06-09](https://user-images.githubusercontent.com/192346/41191963-3be83a54-6bc5-11e8-8b69-8cb02cb38525.png)

**Comment by no-stack-dub-sack** [comment]
@irenesmith I thought I fixed this last night, but it is definitely fixed now (there may be two versions of the "fork me" pen floating around?). See #340. 

Please check https://codepen.io/freeCodeCamp/pen/MJjpwO again. Closing as fixed but please reopen if you find this issue somewhere else.
