### ISSUE TITLE
Image Resize to Window already fulfilled but not passing test case. 

### ISSUE THREAD

**Issue by yuelchen** [freeCodeCamp/testable-projects-fcc#352]
#### Issue Description

Run the test case from your script bundle forked from your project.
Criteria for image to resize based on parents size fulfilled but failing test case. 
If you minimize browser screen and change the width and height of window, the image and content resizes already. 

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: N/A
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
Pen Link: https://codepen.io/yuelchen/full/vrgJQB/
Editor View: https://codepen.io/yuelchen/pen/vrgJQB?editors=0100

 
```

**Comment by tbushman** [comment]
@yuelchen I was unable to reproduce the issue. Your pen passes all tests in Chrome. Please reopen this issue if it's still not working for you. Thank you!

**Comment by yuelchen** [comment]
Hi @tbushman,

I figured out the issue, the test case was fulfilled only when my object has the attribute 'display' equaled to 'block'.

I think this image resize test case may be looking to match specific properties which is why it's failing despite resizing without this attribute. 

Editor View: https://codepen.io/yuelchen/pen/vrgJQB?editors=0100

Thanks for the follow up to my ticket!
