### ISSUE TITLE
Pomodoro countdown elapse hack for external timer modules

### ISSUE THREAD

**Issue by tbushman** [freeCodeCamp/testable-projects-fcc#357]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 
 
```

#### Screenshot

As mentioned in #335 , when students use timer modules, our tests may not have direct access to the setTimeout and setInterval settings required to artificially speed up the countdown, causing tests to reach timeouts before completing.

**Comment by tbushman** [comment]
See also #376

**Comment by tchaffee** [comment]
@tbushman I think we should just add a requirement to the list of tests that students do not use timer modules and use setTimeout and setTimeout directly. This aligns with our philosophy of not trying to support every possible solutions, but to give specifics to guide the students towards a small set of possible solutions.

What do you think?

**Comment by tchaffee** [comment]
@tbushman Any thoughts on this?

**Comment by tbushman** [comment]
@tchaffee I'll close this. @lubodrinka your issue was similar. Open a new issue before submitting a PR and we can discuss it then.
