### ISSUE TITLE
Tribute page free code camp 1st project 

### ISSUE THREAD

**Issue by marounae-hechmi** [freeCodeCamp/testable-projects-fcc#360]
this is the error message displayed after trying to run test 

#Layout
1. The <img> element should responsively resize, relative to the width of its parent element, without exceeding its original size.
img {
  width: 100%;
  display: block;
  height: auto;
  margin: auto;
}
 need your help please 

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 https://codepen.io/marouanehechmi1987/pen/YvVzBE
 
```

**Comment by tchaffee** [comment]
@QuincyLarson is there anyone you could send our way to look at these beginner issues? It would be good in general to get a few more backup people on this project even if they are very part time and need a lot of hand holding.

**Comment by tbushman** [comment]
Also encountered in #440

**Comment by ValeraS** [comment]
The user story says:
The <img> element should responsively resize, relative to the width of its parent element, without exceeding its original size.

But if the width is used instead of the max-width, then <img> can exceed its original size.

**Comment by ValeraS** [comment]
width: 100%
![image](https://user-images.githubusercontent.com/10867286/44356749-e8b65000-a4b8-11e8-83af-3f2eb49ad76b.png)

max-width: 100%
![image](https://user-images.githubusercontent.com/10867286/44357113-e6a0c100-a4b9-11e8-9d94-57898b0c51d4.png)

**Comment by tbushman** [comment]
@ValeraS I see now. I wasn't paying close attention to the user story. You must think I'm stupid. Just been trying to keep up with all of the issues here. Thanks!

**Comment by ValeraS** [comment]
@tbushman Of course, I don't think so. You guys are the best!

**Comment by tbushman** [comment]
@ValeraS YOU are the best. Thanks for the help.
