### ISSUE TITLE
Tests would not detect link between class and id with child element

### ISSUE THREAD

**Issue by JoshuaStover** [freeCodeCamp/testable-projects-fcc#361]
#### Issue Description

When wrapping a div in an anchor, the test did not recognize that the clickable element had the requested class, but works when the anchor itself has the requested class. I would imagine that placing the anchor inside of the div with the requested class on the anchor would work as well, but prevents making the div itself clickable (and a touch more forgiving on mobile screens). Examples below, excluded full 3 nav links as they all function identically.

This issue came up during the Product Landing Page project.
#### Browser Information

* Browser Name, Version: Google Chrome, Version 67.0.3396.62
* Operating System: Windows 10 Home 64-bit
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
<!-- The working segment: -->
<nav id="nav-bar">
      <a class="nav-link" href="#r2">Video Demo</a>
</nav>

<!-- The one that got away: -->
<nav id="nav-bar">
     <a href="#r2">
          <div class="nav-link">Video Demo</div>
     </a>
</nav>
 
 
```

**Comment by tbushman** [comment]
@JoshuaStover This is expected behavior. Try attaching the `nav-link` className to the `<a>` element instead of the `<div>` element. Please reopen if that doesn't work.
