### ISSUE TITLE
Missing 1 test on Tribute Page. img element height is set to auto but still failing

### ISSUE THREAD

**Issue by cdhippen** [freeCodeCamp/testable-projects-fcc#362]
#### Issue Description
I had an old tribute page that I wanted to make pass all the new tests since the recent update, and I put all the IDs in and made the image responsively resize but it's only passing 9/10 tests. It's failing on the responsive image resizing. It says my img element style height should be set to auto, which it is, but the test still failes.

#### Browser Information

* Browser Name, Version: Chrome 67.0.3396.87
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
 img {
  max-width:100%;
  height: auto;
}
```

```
AssertionError: Use the "height" style property with a value of "auto" forresponsive images.: expected '449px' to equal 'auto'
```

https://codepen.io/chase-hippen/pen/yEXYJx

#### Screenshot

![image](https://user-images.githubusercontent.com/34950214/41334283-aa5b605a-6eaa-11e8-8fe1-f0728177c276.png)

**Comment by tbushman** [comment]
@cdhippen It looks like you got it worked out with `!important` ? I don't see where those styles were being overridden. Leaving this open.

**Comment by cdhippen** [comment]
I actually solved it by removing this : class="d-block mx-auto rounded" from bootstrap I believe, and I just did it all in Pure CSS (which the guide says you should do now but didn't use to)
