### ISSUE TITLE
Select Test Suit Personal Portfolio Not working

### ISSUE THREAD

**Issue by kcrisci94** [freeCodeCamp/testable-projects-fcc#367]
#### Issue Description

       I am having an issue running the test app for my portfolio portion of the Responsive Web Design curriculum. I have attempted to run the test code both by forking with codepen.io, and by adding the script with the given src tag "https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js". The tester appears, however when I select "Personal Portfolio" and then hit "Run Test", either it whites out my entire project (in codepen.io), or it runs continuously in my own IDE, so I am unable to view the test cases for this project. I have used this tester in all 4 of the previous projects and it has worked fine.

#### Browser Information

* Browser Name: Google Chrome, Version: 67.0.3396.87 (Official Build) (64-bit) 
* Operating System: Windows 7
* Desktop

#### Your Code / Link to Your Pen

https://codepen.io/kcrisci94/pen/BVZero

**Comment by tbushman** [comment]
@kcrisci94 OK, your pen passes the tests by replacing the `href="index.html"` and `href="resume.html"` with `href="#"` and `href="#resume"`, respectively. Codepen does not have access to a file system, so any `href` attributes need to be either website URLs or hashes. Please reopen this issue if you run into problems with that. Thanks!
