### ISSUE TITLE
[markdown previewer] Wrong Error-Messages from test Nr. 6

### ISSUE THREAD

**Issue by SehrOne** [freeCodeCamp/testable-projects-fcc#37]
#### Issue Description

The last 3 error-messages all say `write some markdown representing an <h1>` instead of the correct messages:
`write some markdown representing an <blockquote>`
`write some markdown representing an <img>` and 
`write some markdown representing bolded text, <strong>...</strong>`

This is quite confusing, I forgot the space between the \> and the actual blockquote text. 
The error I received always said I need to represent an \<h1\>, which I already had.

#### Screenshot

![tests](https://cloud.githubusercontent.com/assets/20795864/22621349/cfbe1f3a-eb21-11e6-8378-8b8481c782e2.jpg)

**Comment by no-stack-dub-sack** [comment]
@SehrOne Ahh! Thanks for pointing this out! Nice catch, I can go ahead and fix this.
