### ISSUE TITLE
Not able to get certificate

### ISSUE THREAD

**Issue by oghusky** [freeCodeCamp/testable-projects-fcc#371]
All my lessons have been completed and checked but i haven't been redirected for the "Responsive Design Certification"

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 
 
```

**Comment by tbushman** [comment]
@oghusky This is related to the core curriculum repository, and might be related to this issue: https://github.com/freeCodeCamp/freeCodeCamp/issues/17522 , or this one maybe: https://github.com/freeCodeCamp/freeCodeCamp/issues/17251

**Comment by tchaffee** [comment]
@oghusky This repo is only for the testable projects. Could you open please an issue over at https://github.com/freeCodeCamp/freeCodeCamp/issues? Or use one of the existing issues that @tbushman pointed out?
