### ISSUE TITLE
Product Landing Page not passing tests

### ISSUE THREAD

**Issue by megantaylor** [freeCodeCamp/testable-projects-fcc#373]
#### Issue Description
codepen link:
https://codepen.io/megantaylor/pen/qKVOYg
using scss and bootstrap 4

2 failed tests are related to the nav html, but i can verify with my eyeballs that the user stories are fulfilled.

test results:
FCC Test Suite: Product Landing Page
Select Test Suite: Run Tests Tests 14/16 Test(s) Failed  Tests Passed  Tests Executing Report Bug
Unit tests
passes: 14failures: 2duration: 0.03s
#Product Landing Page tests
#Technology Stack
1. You can use HTML, JavaScript, and CSS to complete this project. Plain CSS is recommended because that is what the lessons have covered so far and you should get some practice with plain CSS. You can use Bootstrap or SASS if you choose. Additional technologies (just for example jQuery, React, Angular, or Vue) are not recommended for this project, and using them is at your own risk. Other projects will give you a chance to work with different technology stacks like React. We will accept and try to fix all issue reports that use the suggested technology stack for this project. Happy coding!
#Content
1. My product landing page should have a <header> element with corresponding id="header".
2. I can see an image within the #header element with a corresponding id="header-img". A company logo would make a good image here.
3. Within the <header> element I can see a <nav> element with corresponding id="nav-bar".'
4. I can see at least three clickable elements inside the nav element, each with the class "nav-link". AssertionError: There are not at least 3 elements with a class of "nav-link" within the #nav-bar element : expected 0 to be at least 3
    at Function.assert.isAtLeast (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:17737:36)
    at n.<anonymous> (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:21583:23)
    at r (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:7852)
    at r.run (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:8853)
    at i.runTest (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:13553)
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:14192
    at r (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:13024)
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:13000
    at n (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:12791)
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:12855
5. When I click a .nav-link button in the nav element, I am taken to the corresponding section of the landing page.' AssertionError: The #nav-bar contains no .nav-link: expected 0 to be at least 1
    at Function.assert.isAtLeast (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:17737:36)
    at n.<anonymous> (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:21589:23)
    at r (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:7852)
    at r.run (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:8853)
    at i.runTest (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:13553)
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:14192
    at r (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:13024)
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:13000
    at n (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:12791)
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:12855
6. I can watch an embedded product video with id="video".
7. My landing page has a <form> element with a corresponding id="form".'
8. Within the form, there is an <input> field with id="email" where I can enter an email address.
9. The #email input field should have placeholder text to let the user know what the field is for.
10. The #email input field uses HTML5 validation to confirm that the entered text is an email address.
11. Within the form, there is a submit <input> with corresponding id="submit".
12. When I click the #submit element, the email is submitted to a static page (use this mock URL: https://www.freecodecamp.com/email-submit) that confirms the email address was entered (and that it posted successfully).
#Layout
1. The navbar should always be at the top of the viewport.
2. My product landing page should have at least one media query.
3. My product landing page should utilize CSS flexbox at least once.

#### Browser Information

Chrome 67.0.3396.87
MacOS 10.13.5
MacBook Pro

**Comment by tbushman** [comment]
@megantaylor Please designate your `class` attributes only once. You can combine them like this: `class="p-2 text-dark nav-link"` . Other than that, there was a typo: `singup-header` instead of `signup-header` and that should do it! Please reopen this issue if you have questions. Thanks!
