### ISSUE TITLE
test suite not working

### ISSUE THREAD

**Issue by jaitjacob** [freeCodeCamp/testable-projects-fcc#374]
#### Issue Description

The test suite for D3 Heat Map project which is on codepen says 'test passed' for any test suite that you select. From what I understand it should say 'test failed'  when you try to run another test suite on a different project. 

#### Browser Information

* Browser Name, Version: Chrome v67
* Operating System: Win 10
* Mobile, Desktop, or Tablet: Desktop

#### Link to Pen

```
https://codepen.io/freeCodeCamp/full/JEXgeY
```

#### Screenshot

![g1](https://user-images.githubusercontent.com/14340591/41504554-16758af2-7236-11e8-9a2b-fed1b0755215.JPG)

**Comment by tbushman** [comment]
This is fixed in #345 . @raisedadead @tchaffee @Bouncey Are we manually adding the new bundle to the cdn for now and @raisedadead how are we getting that to you?

**Comment by tbushman** [comment]
Hi, this is my fault, fixed in #345. Can you please make sure the cdn has the latest bundle.js from this repo? Very sorry. Thanks @Bouncey @raisedadead

**Comment by raisedadead** [comment]
Hi @tbushman apologies about the delay. 

Ideally you would want to make a PR against this https://github.com/freeCodeCamp/cdn

The folder that the built production bundle goes into is:
`https://github.com/freeCodeCamp/cdn/tree/master/build/testable-projects-fcc/v1`

Thanks.

**Comment by raisedadead** [comment]
Deployment is automated and the bundle is available at `https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js` post deployement.

**Comment by tbushman** [comment]
@raisedadead Thanks. I was wrong. This issue persists. Sorry everyone. Looking into it.

**Comment by raisedadead** [comment]
@tbushman thanks a lot for taking the time to work on this. Let me know if I could be of any assistance.

**Comment by raisedadead** [comment]
Both you and @tchaffee should have write access on the repo shortly.

**Comment by tbushman** [comment]
We need to add a check to the Codepen templates and only set the localStorage variable if it hasn't been set or something like that. See #391 as well.
