### ISSUE TITLE
Does not detect useage of Flexbox and Media Query

### ISSUE THREAD

**Issue by MrFuriousFury** [freeCodeCamp/testable-projects-fcc#378]
#### Issue Description

Even though flexbox was used in the CSS of my website plenty of times it still shows used zero times same issue with the media query. In Product Landing Page Test Suite.
#### Browser Information

* Browser Name, Version: Chrome 67 
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

**Comment by tbushman** [comment]
@MrFuriousFury Hello, are you running your tests through Codepen? If not, this may be similar to #358

**Comment by MrFuriousFury** [comment]
No I was running it in my own system with a separate file for css.
Okay i will try it out in codepen.

Thank you

**Comment by tbushman** [comment]
@MrFuriousFury You can run it locally with a server. Look into running live-server or simple Python server in your project folder.
