### ISSUE TITLE
Problem running test

### ISSUE THREAD

**Issue by Dadebayor** [freeCodeCamp/testable-projects-fcc#381]
#### Issue Description

When running test I either come to the "Build a Personal Portfolio Webpage" or just get a blank page.

#### Browser Information

* Browser Name, Version: Chrome 67
* Operating System: Windows 10 Pro
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
 https://codepen.io/Dadebayor/pen/yEKVoQ
 
 
```

**Comment by tbushman** [comment]
@Dadebayor One of the main problems I see is that you are lacking quotes around your `id` attributes. Please change, for example, `id=welcome-section` to `id="welcome-section"` and that should resolve many problems.

**Comment by Dadebayor** [comment]
@tbushman Hey, thanks for helping. I've done that now. That had never been a problem before, lesson learned. It works now if I wait a minute or so for test execution. Thank you!

**Comment by Dadebayor** [comment]
@tbushman Actually, it is not working: 

"Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:7197" 

is what I get for the 7th test under "#Content".

I think my code should pass that test but it seems like execution of test stops after 10 sec. Do you know what to do?

**Comment by tbushman** [comment]
@Dadebayor One thing is to clean up the nested sections, but that doesn't pass the test. Try adding more content. This may be similar to #278 .

**Comment by tbushman** [comment]
@Dadebayor The test checks to see if the page scrolls as expected to various sections when the associated anchor is clicked. With scrolling inactive due to short content, the tests won't pass.
