### ISSUE TITLE
no info from testing link

### ISSUE THREAD

**Issue by Simonmguajardo** [freeCodeCamp/testable-projects-fcc#383]
#### Issue Description
after i click grade test and the results come back saying 8/10, when i click to see what im missing i only get "1. You can use HTML, JavaScript, and CSS to complete this project. Plain CSS is recommended because that is what the lessons have covered so far and you should get some practice with plain CSS. You can use Bootstrap or SASS if you choose. Additional technologies (just for example jQuery, React, Angular, or Vue) are not recommended for this project, and using them is at your own risk. Other projects will give you a chance to work with different technology stacks like React. We will accept and try to fix all issue reports that use the suggested technology stack for this project. Happy coding!
#Content
#Layout
" 
and it's written in one long vertical line that i can't read. 

#### Browser Information

* Browser Name, Version: chrome
* Operating System: windows 10 64 bit
* Mobile, Desktop, or Tablet: desktop

#### Your Code / Link to Your Pen

```file:///C:/Users/simon/Desktop/portfolio/index.html#projects
 
 
 
```

#### Screenshot

![screenshot 1](https://user-images.githubusercontent.com/40280716/41732566-36740e70-7536-11e8-975b-89f5506d4ccb.png)

**Comment by tbushman** [comment]
@Simonmguajardo One of your styles is overriding the styles for the test window. While we work on improvements to test window containment, will you please assign a `class` or `id` to the elements you wish to style and use those in your css?

**Comment by Simonmguajardo** [comment]
Yes it was my ul {
grid-template-columns: repeat(3, 1fr);
}

**Comment by tbushman** [comment]
@Simonmguajardo Thanks!
