### ISSUE TITLE
CSS Navbar Test Failing 

### ISSUE THREAD

**Issue by alexswiontek** [freeCodeCamp/testable-projects-fcc#387]
#### Issue Description

Technical Documentation Page tests --> Layout -->
On regular sized devices (laptops, desktops), the element with id="navbar" should be shown on the left side of the screen and should always be visible to the user.

^ above test is failing despite navbar present on left side

#### Browser Information

* Browser Name, Version: Chrome Version 67.0.3396.87
* Operating System: Mac OS High Sierra Version 10.13.5
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

 [CodePen with Error](https://codepen.io/alex-swiontek/full/WyyegX/)

Wondering if this may be due to using a CSS-Grid implementation.

#### Screenshot

![Pen Screenshot](https://i.imgur.com/rdUoWS6.png)
![Failed test](https://i.imgur.com/PYMpFj4.png)

**Comment by tbushman** [comment]
@alexswiontek Hello, so the test checks whether the navbar stays aligned with the top of the window while the other content scrolls beside it. Your navbar scrolls upward with the content. If you want to discuss further let me know here.

**Comment by alexswiontek** [comment]
ah that makes sense, thanks for the clarification @tbushman
