### ISSUE TITLE
Portfolio Test #8

### ISSUE THREAD

**Issue by Cander1** [freeCodeCamp/testable-projects-fcc#388]
Issue Description

Whenever I run tests for my porfolio site, test #8 always fails, even though I do have a link to my profile page on GitHub.

Browser Name, Version: Google Chrome Version 67.0.3396.87
Operating System: macOsHighSierra
Mobile, Desktop, or Tablet: Desktop

8. My portfolio should have a link with an id of "profile-link", which opens my GitHub or FCC profile in a new tab. AssertionError: expected 'I' to equal 'A'AssertionError@https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:10986:23
assert@https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:15320:32
equal@https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:17589:17
https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:21385:28
r@https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:7856
run@https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:8854
runTest@https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:13556
https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:14199
r@https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:13025
https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:13001
n@https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:12792
https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:12856
i@https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:1:559

Code with supposed issue: <a href="https://github.com/freecodecamp" class="contact-link" target="_blank"><i class="fa fa-github fa-3x" id="profile-link"></i></a>

Link pen: https://codepen.io/JAM1/pen/ERQKGy

**Comment by tbushman** [comment]
@Cander1 Thanks for reporting  
The test is not finding a valid anchor `id="profile-link"` so we'll look into this.

**Comment by Cander1** [comment]
It passed now. The id="profile-link" has to be the first attribute for the anchor tag.
