### ISSUE TITLE
[Tribute Page] Typo in Test Nr. 6

### ISSUE THREAD

**Issue by SehrOne** [freeCodeCamp/testable-projects-fcc#39]
#### Issue Description

Test Nr. 6 includes the HINT from Test Nr. 7

#### Screenshot

![bug](https://cloud.githubusercontent.com/assets/20795864/22629302/9e37d33a-ebe3-11e6-9ca3-ad00a14e7fba.jpg)

**Comment by no-stack-dub-sack** [comment]
@SehrOne Hey, nice catch yet again! Would you like to take a stab at fixing this?

**Comment by SehrOne** [comment]
@no-stack-dub-sack Thank you, I´d like to fix it myself. 
I`ve never contributed before so I´ll first have to set up everything locally.
