### ISSUE TITLE
FCC Product Landing Page Action Attribute not working.

### ISSUE THREAD

**Issue by judecabodil22** [freeCodeCamp/testable-projects-fcc#390]
#### FCC: Product Landing Page

I have included the link provided by in the user-stories (https://www.freecodecamp.com/email-submit) in my action attribute inside a form.
I have the input (text and submit)inside the form and it's fully functional.
When I click the submit button, it goes to the link user-stories have provided. And it's correct.
There's no problem with this.
However, when I check the tests. It produces an error that I didn't do something right.

I use Firefox in Windows 10 Desktop.

This is the error.

![image](https://user-images.githubusercontent.com/31956023/41806081-25e95600-76e9-11e8-8fe4-94d50c54b89e.png)

And here's my pen
https://codepen.io/CesareDeyo/pen/bKWLWw

**Comment by tbushman** [comment]
@judecabodil22 I couldn't reproduce this particular error, but there has been bugginess we're trying to work out, so please respond if you're still seeing this error still.

**Comment by judecabodil22** [comment]
Don't worry. The problem has already been solved.
