### ISSUE TITLE
Borlaug tribute example passes the test for "D3: Heat Map"

### ISSUE THREAD

**Issue by shenkin** [freeCodeCamp/testable-projects-fcc#391]
[Norman Borlaug tribute page](https://codepen.io/freeCodeCamp/pen/zNqgVx)

I wanted to see how the test suite worked, including test failures. The above template passes all tests for every test suite I have tried -- including, for instance, "D3 Heat Map", which will serve as a specific example.

I expected the suite to fail in this case, since the above template does not meet any of the criteria that should be tested for something as remote from its content as a heat map.

#### Issue Description

1. Go to the sample [Norman Borlaug tribute page](https://codepen.io/freeCodeCamp/pen/zNqgVx)
2. Click on the 3 horizontal bars (hamburger menu) on the upper left.
3. Use the option menu to select "D3: Heat Map.
4. Click on the "Run Tests" button
5. Observe that all (10/10) tests pass.

The test should fail, but it succeeds.

I didn't try all the Test Suites, but all those I tried also succeeded.

#### Browser Information

* Browser Name, Version: Chrome Version 67.0.3396.87 (Official Build) (64-bit)
* Operating System: MacOS Version 10.15.5
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

https://codepen.io/freeCodeCamp/pen/zNqgVx

**Comment by tbushman** [comment]
Known issue alert. Adding help-wanted to #374 . I thought it was fixed in #345 .

**Comment by tbushman** [comment]
@shenkin In this case, the code in the javascript window, `const projectName = 'tribute-page'; ...` sets the localStorage variable to the Tribute page. There might be a better way for us to set that, but if you remove it, the problem should resolve.

**Comment by shenkin** [comment]
@tbushman I understand. Perhaps the best solution is simply to remove the option selector from the hamburger menu, leaving only the "Run tests" button and the result of the test – since the correct test is always called automatically. Then instruct the user to copy the Javascript into their exercise, for each project.

**Comment by tbushman** [comment]
@shenkin If we keep the selector, it would be a matter of checking if the localStorage variable has already been set before setting it in the codepen template. I think we will probably keep the selector.
