### ISSUE TITLE
Survey Form: 2/3 id checks don't work

### ISSUE THREAD

**Issue by FawadWheelDrive** [freeCodeCamp/testable-projects-fcc#393]
Survey Form

#### Issue Description

FAILS TEST 4. Inside the form element, I am required to enter my name in a field with id="name".
FAILS TEST 5. Inside the form element, I am required to enter an email in a field with id="email".
PASSES TEST 7. Inside the form, I can enter a number in a field with id="number".

The format is the same between the three tests, yet it only passes one.

#### Browser Information

* Browser Name, Version: Google Chrome
* Operating System: MacOs High Sierra
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
 
 https://codepen.io/fawadwheeldrive/pen/wXxvXj
 
```

#### Screenshot

![image](https://user-images.githubusercontent.com/38173826/41825710-07201ca0-77d8-11e8-9bd8-eb130bf3ee1f.png)

**Comment by tbushman** [comment]
@FawadWheelDrive The sentence seems carefully worded to indicate that the input should be **required**. Please see HTML form validation documentation: https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Form_validation

**Comment by tbushman** [comment]
Leaving open #400 and closing other related issues.

**Comment by madismi** [comment]
Hello! Having trouble with this and navigating through the answers - was this fixed? Here's part of my code but still getting "fail" test on this user story. 

<form id="survey-form">
	<label for="text" id="name">Name:</label>
		<input type="text" id="name" placeholder="Enter name" required>

**Comment by tbushman** [comment]
Hello @madismi , this pen is passing: https://codepen.io/fawadwheeldrive/pen/wXxvXj  
Do you have an example that shows your code not passing? In the above snippet, please switch out `<label for="text" ...` for `<label for="name" ...` to match the `<label>` element's `for` attribute with its associated `<input>` element.

**Comment by madismi** [comment]
^ Got it! Thanks for your help!
