### ISSUE TITLE
Survey form

### ISSUE THREAD

**Issue by Pellow1234** [freeCodeCamp/testable-projects-fcc#398]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 ttps://codepen.io/pellow/pen/OEBprw
 
```

**Comment by tbushman** [comment]
@Pellow1234 Please see issue #393

**Comment by tbushman** [comment]
Leaving open #400 and closing other related issues.
