### ISSUE TITLE
Pomodoro Clock - regex functions (i.e. getMinutes) should be able to handle/skip React HTML comments in innerHTML

### ISSUE THREAD

**Issue by Rock-son** [freeCodeCamp/testable-projects-fcc#399]
#### Browser Information
* Browser Name, Version:  **Chrome 67.0.3396.99 (64 bit)**
* Operating System:  **Win 10 Pro (build: 17134.112, v1803, updated: 1.5.2018)**
* Mobile, Desktop, or Tablet:  **Desktop**

#### Issue Description

Pomodoro - Timer section, test nr. 8:

TypeError: Cannot read property '1' of null
    at getMinutes (https://gitcdn.link/cdn/freeCodeCamp/testable-projects-fcc/db787522158f886b275cd4852c7bf76c95d9b806/build/bundle.js:20654:20)

#### Test Code
20654 line:
```
  function getMinutes(str) {
    var matches = /^(\d{1,4})\s?([\.:,\/]\s?\d{2}.*)?$/g.exec(str);
    return matches[1];
  }
```

```
 _chai.assert.strictEqual(getMinutes(document.getElementById('time-left').innerHTML), document.getElementById('session-length').innerHTML);
```
#### My Code (innerHTML:)
`<!-- react-text: 22 -->25:00<!-- /react-text --><!-- react-text: 23 --> <!-- /react-text -->`

#### Link To Your Pen
https://codepen.io/Roky/pen/jAKLXO

**Comment by Rock-son** [comment]
it seems this simple change at the beginning would do the job: ^(?:)?   I'll do a PR

**Comment by Rock-son** [comment]
So, I set up Linux and tests and everything, but now I can't recreate the problem as the comments just don't show up in my project anymore. Should I make a PR anyway @tbushman... without the image of the problem?

**Comment by tchaffee** [comment]
@Rock-son I'm having trouble finding where this string appears in your CodePen code:

```
<!-- react-text: 22 -->25:00<!-- /react-text --><!-- react-text: 23 --> <!-- /react-text -->
```

**Comment by Rock-son** [comment]
@tchaffee yeah, I wanted to comment on this, I couldn't find it later on too... unfortunately I didn't take the screenshot, just copied that code from HTML

**Comment by tchaffee** [comment]
I need a way to reproduce the problem, otherwise I can't test it to see if your PR fixes it. Can you create a CodePen or something that reproduces this problem?

**Comment by Rock-son** [comment]
I'll do that... I think the next day those comments were gone even though no changes were made to the pen

**Comment by tchaffee** [comment]
This might help.

https://stackoverflow.com/questions/38133978/reactjs-net-are-react-text-tags-required-when-rendered

**Comment by Rock-son** [comment]
Thanx @tchaffee. I'll start working on it as soon as I can
