### ISSUE TITLE
I made an element with id="name" inside my survey form but still, the test didn't pass.

### ISSUE THREAD

**Issue by MargareV** [freeCodeCamp/testable-projects-fcc#400]
#### Issue Description

I took the test for 100days of HTML and CSS and for the survey form project. I did make an input type of "text" to with an id="name" to enter a name but still, the tests are not accepting even though I am sure it is correct. The same has happened for email field and submit button. Kindly help me. 

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen
https://codepen.io/margarev/pen/NzOepM

 My Codes
<input type="text" id="name" placeholder="Your Name"> - input field for Name
 <input type="email" id="email" placeholder="Your email - input field for email
<button type="button" id="submit">Click Me!</button> - For button
 
 
```

#### Screenshot
<!-- Add a screenshot of your issue -->
![untitled](https://user-images.githubusercontent.com/33339647/41991314-98e21b16-7a62-11e8-847b-577948c94546.png)

**Comment by tbushman** [comment]
@MargareV Thank you. We will probably need to talk about rewording the user stories on this. See similar issues in #341 and #348 re: HTML validation.

**Comment by tbushman** [comment]
Also #393
