### ISSUE TITLE
need to spin off counties.json to freeCodeCamp/cdn

### ISSUE THREAD

**Issue by tbushman** [freeCodeCamp/testable-projects-fcc#401]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 
 
```

**Comment by tbushman** [comment]
As far as I can tell, the counties.json file is referenced from the choropleth example project and not from the test suite. After we merge https://github.com/freeCodeCamp/cdn/pull/2 , we'll have a new url for it and someone with access to the Codepen example project and user stories would need to change the url. Then, we can remove counties.json from freeCodeCamp/testable-projects-fcc bundle.js

**Comment by tchaffee** [comment]
@tbushman It looks like the PR over on the freeCodeCamp repo was merged? Do you need anything else from anyone to move forward with this? No pressure, I'm just trying to help remove any blockers if you are stuck. Thanks!
