### ISSUE TITLE
Automating build deploys  to CDN

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/testable-projects-fcc#402]
Refers: https://github.com/freeCodeCamp/testable-projects-fcc/pull/397#issuecomment-401158124
Refers: https://github.com/freeCodeCamp/cdn/pull/2#issuecomment-401244723

**Comment by tchaffee** [comment]
@raisedadead What's the status on this? Are you still working on it? Are there any blockers? Can I help in some way?

I'm hoping that if we automate the build of `bundle.js` we can eliminate it from the repo? It always causes merge problems, and it's not really source code is it? From my understanding (please correct me if I'm wrong) we shouldn't include anything in the repo that is the output of the build process?

**Comment by raisedadead** [comment]
Hi @tchaffee 

I have been swamped (...yet again, 😓!)
If you are interested, I would love any help I can get.

What we would like is a script that pushes the correct updated version from the source repo over here. I can provide you with the necessary tokens from GitHub

Let me know if you are available for working on this.

Thanks.

**Comment by tbushman** [comment]
@raisedadead I will do manual pull requests at freeCodeCamp/cdn until this gets done. If it's urgent, I can give the push script a shot. There are so many urls flying around. Thanks for clarification.

**Comment by raisedadead** [comment]
Hi @tbushman that's great.. it would be awesome if you can get something ready. We can discuss more over a PR.

Essentially you could put up a bash script that does a `clone -> copy files >  commit -> push` of cdn repo. 
I can help with the GIT credentials from the @camperbot account.

And then we could simply put it as a build step on Travis for master branch.

The actual deploy on netlify is automated already, meaning a push to master on `cdn` repo automatically makes it available on the URL.

**Comment by tbushman** [comment]
@raisedadead Thanks. As this will likely take me some time to figure out, I did a PR at fCC/CDN :)

**Comment by tchaffee** [comment]
@raisedadead Unless @tbushman wants to take this, I am ready to work on this. I'm just a little bit lost on what the overall process should be. I don't know whether it should happen in Travis, as part of the existing build or as a different Travis build, how to get the built bundle out to the CDN, whether or not we delete the bundle from this repo once it is automatically built.... (I hope so).

Anyway, if you can give me some thoughts on how to approach this, I can get on it right away. Might be easier to hop on Gitter instead of going back and forth here. Up to you. Thanks!

**Comment by ValeraS** [comment]
If I understand correctly we need something like this:
```
#!/usr/env
# Clone repos
git clone https://github.com/freeCodeCamp/testable-projects-fcc.git
git clone https://github.com/freeCodeCamp/cdn.git

# Build and copy bundle.js
cd testable-projects-fcc/
yarn install && yarn run build
cp --parents build/testable-projects-fcc/v1/bundle.js ../cdn/

# Commit  and push changes
cd ../cdn
git add . && git commit -m "update bundle.js"
git push https://user:password@github.com/freeCodeCamp/cdn.git master

# Delete all
cd .. && rm -rf testable-projects-fcc cdn
```

**Comment by tchaffee** [comment]
@ValeraS Thanks. That would run on Travis? As a separate Travis job? This script is a big help and I also want to understand the big picture of all the steps involved. I guess we would want any merge to master trigger this.

**Comment by ValeraS** [comment]
In Travis is enabled "Build Branch Updates"
In our .travis.yml add:
```
before_script:
  npm run build

deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy.sh
  on:
    branch: master
```
deploy.sh
```
#!/bin/sh
# Clone CDN repo
git clone https://github.com/freeCodeCamp/cdn.git

# copy bundle.js
cp --parents build/testable-projects-fcc/v1/bundle.js ../cdn/

# Commit  and push changes
cd cdn
git add . && git commit -m "update bundle.js"
git push https://user:password@github.com/freeCodeCamp/cdn.git master
```
