### ISSUE TITLE
test suite crashes - Personal Portfolio project

### ISSUE THREAD

**Issue by supuun** [freeCodeCamp/testable-projects-fcc#404]
#### Issue Description
when I run the test, it crashes.

#### Browser Information

* Browser Name, Version: chrome 67
* Operating System: windows 10
* Mobile, Desktop, or Tablet: desktop

#### Your Code / Link to Your Pen
https://codepen.io/supuun/pen/BVvrgK

**Comment by tbushman** [comment]
@supuun We are updating the CDN with a fix for this. I'll check back with you after to see if the problem persists. Thanks!

**Comment by supuun** [comment]
Problem solved. thanks :)
