### ISSUE TITLE
freeCodeCamp Tribute Project Error - Layout Point#1

### ISSUE THREAD

**Issue by ExoticIris** [freeCodeCamp/testable-projects-fcc#405]
#### Issue Description
Hello,
When I run the test on my Tribute page, the following test keeps failing even though my styling is as taught on freeCodeCamp:
_"The <img> element should responsively resize, relative to the width of its parent element, without exceeding its original size.
AssertionError: Use the "display" style property with a value of "block" forresponsive images.: expected 'inline-block' to equal 'block'"_

Actions: I tried removing everything else in html and css code and just keep it bare minimum, but the problem kept recurring.

I think it might be a problem in the Test Suite.

Please help.

Thanks
Rim
#### Browser Information

* Browser Name, Version:  Chrome Version 67.0.3396.87
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen
```
 
(https://codepen.io/ExoticIris/pen/PaXBvq)
 
```

#### Screenshot

![image](https://user-images.githubusercontent.com/38048623/42107734-7257197a-7ba6-11e8-817e-70a50c392438.png)

**Comment by tbushman** [comment]
@ExoticIris Your test should pass, sorry. Meantime, will you please add the `id` for `image` to your css like so: 
```  
img, #image {
  max-width: 100%; 
  display: block; 
  height: auto;
  margin: auto;
}  
```  
And the test will pass. Thanks!

**Comment by ExoticIris** [comment]
@tbushman That worked! Thanks a lot for the quick response =)
