### ISSUE TITLE
Last TDD for Technical Docs Page throws an error even though my screen shows the truth.

### ISSUE THREAD

**Issue by smlarkin** [freeCodeCamp/testable-projects-fcc#408]
Technical Docs Page

ERROR READS:
#Layout
1. On regular sized devices (laptops, desktops), the element with id="navbar" should be shown on the left side of the screen and should always be visible to the user.

THEN LOWER:
AssertionError: Left of bounding rectangle is not correct.: expected 12 to be close to 0 +/- 10

#### Issue Description

I'm not sure what these number mean ... pixels? ... to the parent ? ... I tried all kinds of CSS tweaks, but that is irrelevant that you can see the sidebar with all the links when the screen is totally enlarged.  So this test is not accounting for how I used flexbox or something like that.

#### Browser Information

* Browser Name, Version: Chrome Version 67.0.3396.99 (Official Build) (64-bit)
* Operating System: MacOS 10.13.5
* Mobile, Desktop, or Tablet: MBP

#### Your Code / Link to Your Pen

```
 https://codepen.io/smlarkin/pen/aKQgJY
 
```
![screen issue](https://user-images.githubusercontent.com/38188005/42114099-ce4222ce-7bbb-11e8-89af-c58d92e51e0d.jpeg)

#### Screenshot

SEE RED HIGHLIGHTS FOR DETAILS.

**Comment by tbushman** [comment]
@smlarkin We have a fix for this but it's not in the CDN yet. I'll check back with you. The previous test measured the distance of the navbar from the top and left of the viewport. If you make those offsets `0` that might fix it.

**Comment by tbushman** [comment]
@smlarkin This appears to be fixed. Thanks!
