### ISSUE TITLE
The navbar should contain at least one link  not working

### ISSUE THREAD

**Issue by marcosriani** [freeCodeCamp/testable-projects-fcc#411]
#### Issue Description

When trying to the test the option "The navbar should contain at least one link" is not passing even though it has more then one link. 

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 HMTL 



<!DOCTYPE html>
<html lang="en">
   <head>
      <title>Riani</title>
      <meta charset="utf-8">
      <meta content="width=device-width,initial-scale=1" name="viewport">
      <link href="css/styles.css" rel="stylesheet" type="text/css">
      <link href="img/logo2.png" rel="icon" type="image/png">
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
   </head>
   <body id="body">

      <header class="header" role="banner" id="welcome-section">
         <div class="container-lrg">
            <div class="col-12 spread aligncenter" >
               <a class="mobile-hide">
               <img class="logo-img" src="img/logo1.png" alt="">
               </a>
               <nav class="nav mobile-col-12 spread" role="navigation" id="navbar">
                  <a class="nav-link" href="#projects">Projects</a>
                  <a class="nav-link" href="https://github.com/marcosriani" target="_blank" id="contact">GitHub</a>
                  <a class="nav-link" href="#about">About</a>
               </nav>
            </div>
         </div>
         <div class="container-lrg">
            <div class="col-12">
               <h1 class="heading text-center">HEY I'M MARCOS RIANI</h1>
               <br />
               <p>I'm a Front-End Developer</p>
            </div>
         </div>
         <div class="container-lrg">
            <div class="centerdevices col-12">
               <div class="computerwrapper">
                <figure>
                  <img class="img" src="img/profile.jpeg" alt="Profile photo">
                </figure>
               </div>
            </div>
         </div>
         <div class="container-sml">
            <div class="col-12 text-center">
               <h2 class="paragraph">

                 I have a bachelor degree in Economics, but I've chosen to work in the tech industry.
                 Being a Developer is my passion because I love the idea of working creating intuitive and dynamic user experiences.
                 <br />
                 <span class="paragraphStrong">Let's make something special.</span>

               </h2>
               <div class="ctas">
                  <button class="ctas-button" href="https://linkedin.com/in/marcosriani" target="_blank">Linkedin profile</button>
               </div>
            </div>
         </div>
      </header>

      <main class="feature3" role="main">
         <div class="container-lrg flex " id=" projects">


            <div class="main" id="projects">
              <h2 class="project-tile">Projects</h2>
             <hr>
              <p>Below you can see some projects I've been working on lately. </p>
              <!-- Portfolio Gallery Grid -->
              <div class="row">
                <div class="column">
                  <div class="content">
                    <a href="https://codepen.io/marcosriani/pen/ZRoNaj" target="_blank">
                      <img src="img/form.png" alt="Form project" style="width:100%">
                      <h3>Form</h3>
                      <p>Project for the FreeCodeCamp</p>
                    </a>
                  </div>
                </div>
                <div class="column">
                  <div class="content">
                    <a href="https://codepen.io/marcosriani/pen/yEKJZJ" target="_blank">
                      <img src="img/tribute_page.png" alt="Tribute page" style="width:100%">
                      <h3>Tribute Page</h3>
                      <p>Project for the FreeCodeCamp</p>
                    </a>
                  </div>
                </div>
                <div class="column">
                  <div class="content">
                    <img src="img/nature.jpg" alt="Nature" style="width:100%">
                    <h3>WORKING</h3>
                    <p>Lorem ipsum..</p>
                  </div>
                </div>
                <div class="column">
                  <div class="content">
                    <img src="img/mountains.jpg" alt="Mountains" style="width:100%">
                    <h3>WORKING</h3>
                    <p>Lorem ipsum..</p>
                  </div>
                </div>
              </div>
              <!-- <button class="ctas-button" href="#contact">See more</button> -->

            </div>


          </div>
      </main>







      <div class="socialproof" id="about">
         <div class="container-sml">
            <div class="flex text-center">
               <div class="col-12 about">
                <h2 class="subheading">About me</h2>
                <p>I recently graduated in Economics at Universidade Federal de Viçosa in Brazil. </p>
                <p>The nature of my degree course has prepared me to work in different areas of knowledge. It involved a great deal of independent research, requiring initiative, self-motivation and a wide range of skills . </p>
                <p>After graduating I decided to change career and become a Front-End Developer</p>
                <p>I'm currently studding at FreeCodeCamp, Team Threehouse, Pluralsight, Udemy and I'm planning to join the Front-End Developer course at OpenClassRooms </p>
                <br>
                <p>Inspiring phrase:</p>

                <blockquote class="quote">
                  &ldquo; The internet is becoming the town square for the global village of tomorrow &rdquo;
                  <cite class="paragraph">Bill Gates</cite>
                </blockquote>
               </div>
            </div>
         </div>
      </div>

      <div class="whatisthis">
         <div class="container-lrg contact"  id="contact">
           <div class="contact-header">
             <h2>Let's work together...</h2>
             <p>How do you take your coffee?</p>
                <div class="icons-box">
                  <a href="https://linkedin.com/in/marcosriani" target="_blank" class="contact-details "> Linkedin <i class="fab fa-linkedin-in"></i></a>
                  <a id='profile-link' href="https://github.com/marcosriani" target="_blank" class="contact-details"> GitHub <i class="fab fa-github"></i></a>
                  <a href="https://facebook.com/marcos_riani" target="_blank" class="contact-details "> Facebook <i class="fab fa-facebook-f"></i></a>
                  <a href="mailto:marcosriani@hotmail.com" class="contact-details"> Email <i class="fas fa-envelope"></i></a>
                   <!-- <button href="https://codepen.io/FreeCodeCamp/" class="ctas-button" target="_blank">Show all</button> -->
                </div>
            </div>
         </div>
      </div>






      <div class="footer">
         <div class="container-lrg flex">
            <div class="col-6 text-center">
               <div class="contribute-copy center vertical text-center">
                  <h3 class="subheading">
                    <a href="#body"><button class="ctas-button">UP</button></a>
               </div>
            </div>
            <div class="col-6 text-center">
               <h2 class="legal">Legal</h2>
               <div class="supporters copyright" id="supporters">
                 <p>  Copyright &copy; 2018 by Marcos Riani. All rights reserved.</p>
               </div>
            </div>
         </div>
      </div>
   </body>
</html>



CSS


 *{
    font-family:-apple-system, BlinkMacSystemFont, segoe ui, Roboto, Helvetica, Arial, sans-serif, apple color emoji, segoe ui emoji, segoe ui symbol;
}
 *,
 *:before,*:after{
    margin:0;
    box-sizing:border-box;
}
 body{
    height:100%;
    width:100%;
    -webkit-font-smoothing:antialiased;
}
/* ----------  HEADER ------  */
.header{
   padding:20px 0 10px;
   height: 100vh;
   overflow:hidden;
}
.header .heading{
   margin:80px 0 0;
}
.header .centerdevices{
   margin:25px 0;
}
.heading{
   font-weight:140;
   font-size:50px;
   line-height:68px;
}


.footer,
.header{
   background-color: #01A7C2;
   color: #FDFFFF;
}



/* ----------  NAVIGATION ------  */

.nav a:link {
  transition: border-bottom 0.3s;
}
.nav a:hover {
  border-bottom: 0.3px solid #A3BAC3;
}
.nav-link{
   text-decoration:none;
   font-size:18px;
   line-height:30px;
   color:inherit;
   padding-bottom: 3px;
}

.nav-link:not(:first-of-type){
   margin-left:25px;

}

/* ----------  BUTTONS ------  */


button:link {
  transition: color 0.3s;
}
button:hover {
  color: #006989;
}




 @media only screen and (max-width:500px){
     .mobile-hide{
        display:none;
    }
}
 .logo-img{
    max-width:100%;
    max-height:100%;
    height:40px;
}
 figure{
    display:flex;
    flex-direction:column;
    align-items:center;
}
 p{
    text-align:center;
}

 .img{
    max-width:200px;
    opacity: 0.99;
    border-radius:50%;
    border:2px solid #006989;
    box-shadow:0 10px 10px -10px rgba(56, 54, 54, 0.5);
    border-color:#006989;
}
.img:hover {
  opacity: 1;
}
.col-12 p {
  margin-bottom: 10px;
}
 @media (max-width:900px){
     .heading{
        font-size:32px;
        line-height:40px;
    }
}
 .subheading{
    font-size:40px;
    line-height:40px;
    font-weight:300;
}
.legal {
  font-size: 20px;
  line-height: 30px;
}

.quote{
  margin-top: 20px;
   font-size:18px;
   line-height:30px;
   font-weight:300;
}

 @media (max-width:900px){
     .subheading{
        font-size:26px;
        line-height:35px;
    }
}

 .paragraph{
    font-size:17px;
    line-height:32px;
    font-weight:100;
}
 .subheading+.paragraph{
    margin-top:10px;
}
.paragraphStrong {
  transition: color 0.3s;
  padding-bottom: 5px;
  padding-top: 5px;
  text-transform: uppercase;
}

 p.paragraph{
    color:#FDFFFF;
}
 .text-center{
    text-align:center;
}
 .flex,
 .spread,
 .center,
 .vertical,
 .aligncenter{
    display:flex;
}
.flex {
  justify-content: center;
  align-content:  center;
}
 /* .baseline{
    align-items:baseline;
} */
 .aligncenter{
    align-items:center;
}
 .spread{
    justify-content: space-between;
}
 .center{
    align-items:center;
    justify-content:center;
}
 .vertical{
    flex-direction: column;
}
 .col-4,
 .col-6,
 .col-12{
    padding:0 20px;
}
 .col-4{
    width:33.333333%;
}
 .col-6{
    width:50%;
}
 .col-12{
    width:100%;
}
.about h2 {
  padding-bottom: 20px;
}
.about p {
  font-size: 15px;
}
 @media only screen and (max-width:500px){
     .mobile-col-12{
        padding:0 20px;
    }
     .mobile-col-12{
        width:100%;
    }
}
 .container-lrg,
 .container-sml{
    margin: auto;
    width: 100%;
}
 .container-lrg{
    display: flex;
    max-width: 1080px;
}
 .container-sml{
    max-width:700px;
}
 .ctas{
    margin:40px 0 0;
}
 .centerdevices{
    position:relative;
}
 @media (max-width:420px){
     .logo{
        font-size:22px;
    }
}
 @media (max-width:370px){
     .nav{
        padding:0 10px;
    }
}
 @media (max-width:350px){
     .nav{
        padding:0;
    }
     .nav-link{
        font-size:16px;
    }
}
 @media (max-width:900px){
     .header .heading{
        margin-top:60px;
    }
}
 @media (max-width:500px){
     .header .heading{
        margin-top:50px;
    }
}
 .ctas-button{
    display:inline-block;
    height:40px;
    line-height:38px;
    padding:0 30px;
    background: #A3BAC3;
    border-radius:3px;
    font-size:15px;
    font-weight:600;
    text-transform:uppercase;
    letter-spacing:.3px;
    border:1px solid #006989;
    text-decoration:none;
    color:  #FDFFFF;
}
 @media (max-width:440px){
     .ctas-button{
        display:block;
        width:100%;
        text-align:center;
    }
}
 .whatisthis{
    padding: 50px 0;
    background-color:  #FDFFFF;
    color:  #007090;
}
 .socialproof{
    padding:90px 0;
    background-color: #007090;
    color: #FDFFFF;
}
 @media (max-width:440px){
     .ctas-button{
        display:block;
        width:100%;
        text-align:center;
    }
}
 .footer{
    padding: 20px 0;
}
 @media (max-width:440px){
     .ctas-button{
        display:block;
        width:100%;
        text-align:center;
    }
}
 .footer .paragraph{
    color:inherit;
}
 .footer .ctas-button{
    margin-top:20px;
}
 .feature3{
    padding: 50px 0 30px;
    border-bottom:1px solid rgba(0, 0, 0, .1);
}
 @media (max-width:750px){
     .feature3 .flex{
        flex-wrap: wrap;
    }
     .feature3 .col-4:nth-of-type(1){
        width: 100%;
        margin-bottom: 30px;
    }
     .feature3 .col-4:not(:nth-of-type(1)){
        width:50%;
    }
    .icons-box {
      display: grid;
      grid-template-columns: 1fr 1fr ;
      grid-auto-rows: 1fr;
      align-items: center;
    }

}
 @media (max-width:500px){
     .feature3 .col-4:nth-of-type(1){
        margin-bottom:0;
    }
     .feature3 .col-4:not(:nth-of-type(1)){
        width:100%;
        margin-top:30px;
    }
}
 @media (max-width:750px){
     .footer .col-6:nth-of-type(1){
        margin-bottom:0;
    }
     .footer .col-6{
        width:100%;
        margin-top:30px;
    }
}
 @media (max-width:750px){
     .footer .flex{
        flex-wrap: wrap;
    }
}
 .copyright{
    padding:10px 0;
    display:flex;
    align-items:center;
    justify-content:center;
    flex-wrap:wrap;
    font-size:15px;

}


/*  */
/*  */
/*  */
/* Test */
/*  */
/*  */
/*  */


/* Center website */
.feature3 {
  display: block;
  background-image: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.6)) ,url('/img/coding.jpeg');
  background-repeat: no-repeat;
  background-size: cover;
  background-attachment: fixed;
}
.main {
    max-width: 1000px;
    margin: auto;
    color: #FDFFFF;
    text-align: center;
}
.project-tile {
    font-size: 50px;
    word-break: break-all;
    padding-bottom: 20px;
    font-weight:300;

}
.main p {
  font-size: 20px;
  padding: 20px;
}

.row {
    margin: 8px -16px;
}

/* Add padding BETWEEN each column (if you want) */
.row,
.row > .column {
    padding: 10px;
}

/* Create four equal columns that floats next to each other */
.column {
    float: left;
    width: 50%;
}
.column img {
border-radius: 1%;
}


/* Clear floats after rows */
.row:after {
    content: "";
    display: table;
    clear: both;
}

/* Content */
.content {
    padding: 20px;
    border-radius: 1%;
}
.content a {
  text-decoration: none;
  color: inherit;
}
.content h3 {
  margin-top: 10px;
}
.content img {
  width: 100%;
  height: 250px;
  opacity: 0.90;
  transition: transform 0.5s, opacity 0.2s;

}
.content img:hover {
  opacity: 1;
  transform: scale(1.09);
}
.subheading a {
  text-decoration: none;
  color: inherit;
}


/*  */
/*  */
/*  */
/* Contact part */


.contact {
  height: auto;
}
.contact-header {
  /* background-color: red; */
  margin: 0 auto;
}
.contact-header h2,
.contact-header p {
  padding: 10px;
  text-align: center;
  line-height:40px;
  font-weight:300;
}
.contact-header h2 {
  font-size:30px;
}
.contact-header p {
  margin-bottom: 20px;
  font-size:20px;

}
.contact-details {
  display: inline-block;
  font-weight: bold;
  margin: 0 35px 45px 35px;
  list-style-type: none;
  /* border: 2px solid #A3BAC3; */
  border-radius: 100%;
  width: 100px;
  height: 100px;
  line-height: 100px;
  background: #A3BAC3;
  color: #FDFFFF;
  text-decoration: none;
  text-align: center;
  opacity: 0.95;
  transition: transform 0.5s, opacity 0.2s;

}

.contact-details:hover {
  background: #FDFFFF;
  color: #006989;
  opacity: 1;
  transform: scale(1.5);
}

/* ICON */





/* Responsive layout - makes the two columns stack on top of each other instead of next to each other */
@media screen and (max-width: 600px) {
    .column {
        width: 100%;
    }
    .header{
       height: 100%;
    }
    .header .heading {
    margin-top: 10px;
    }
    .col-12 p {
        margin-bottom: 5px;
    }
    .paragraph {
    font-size: 15px;
    }
    .header .centerdevices {
    margin: 20px 0;
    }
    .socialproof {
    padding: 30px 0;
    }
    .whatisthis {
    padding: 20px 0;
    }
    .feature3 {
    padding: 30px 0 10px;
    }
    .main p {
    font-size: 20px;
    padding: 10px;
    }
    .row {
    padding: 3px;
    }


    /* .column img {
      padding-left: 10px;
      padding-right: 10px;
    } */
}

 
 
```

**Comment by tbushman** [comment]
@marcosriani I couldn't reproduce this particular error, however, the last test was not passing. Ensure your navbar stays 'fixed' at the top of the viewport during scrolling.  
Ensure you are using the correct CDN for testing: https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js  
If you want to discuss, let us know. :)

**Comment by marcosriani** [comment]
That's very strange, I know that the last test is not passing because of I dind't try to fix it yet, but the test 7 (

 The navbar should contain at least one link) should pass and is not working, I just fork the project on codepen and I'm trying to work it there.


CODE HTML


<html lang="en">
   <head>
      <title>Riani</title>
      <meta charset="utf-8">
      <meta content="width=device-width,initial-scale=1" name="viewport">
      <link href="css/styles.css" rel="stylesheet" type="text/css">
      <link href="img/logo2.png" rel="icon" type="image/png">
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
   </head>
   <body id="body">

      <header class="header" role="banner" id="welcome-section">
         <div class="container-lrg">
            <div class="col-12 spread aligncenter" id="navbar">
               <a class="mobile-hide">
               <img class="logo-img" src="https://s6.postimg.cc/58pywoinl/logo1.png" alt="">
               </a>
                                              <nav class="nav " role="navigation" >
                 <ul class="mobile-col-12 spread" id="navbar">
                  <li><a class="nav-link" href="#projects">Projects</a></li>
                  <li><a class="nav-link" href="https://github.com/marcosriani" target="_blank" id="contact">GitHub</a></li>
                  <li><a class="nav-link" href="#about">About</a></li>
                </ul>
               </nav>



            </div>
         </div>
         <div class="container-lrg">
            <div class="col-12" >
               <h1 class="heading text-center">HEY I'M MARCOS RIANI</h1>
               <br />
               <p>I'm a Front-End Developer</p>
            </div>
         </div>
         <div class="container-lrg">
            <div class="centerdevices col-12">
               <div class="computerwrapper">
                <figure>
                  <img class="img" src="https://s6.postimg.cc/rknrq2phd/profile.jpg" alt="Profile photo">
                </figure>
               </div>
            </div>
         </div>
         <div class="container-sml">
            <div class="col-12 text-center">
               <h2 class="paragraph">

                 I have a bachelor degree in Economics, but I've chosen to work in the tech industry.
                 Being a Developer is my passion because I love the idea of working creating intuitive and dynamic user experiences.
                 <br />
                 <span class="paragraphStrong">Let's make something special.</span>

               </h2>
               <div class="ctas">
                  <button class="ctas-button" href="https://linkedin.com/in/marcosriani" target="_blank">Linkedin profile</button>
               </div>
            </div>
         </div>
      </header>

      <main class="feature3" role="main">
         <div class="container-lrg flex " id=" projects">


            <div class="main" id="projects">
              <h2 class="project-tile">Projects</h2>
             <hr>
              <p>Below you can see some projects I've been working on lately. </p>
              
              <div class="row">
                <div class="column">
                  <div class="content">
                    <a href="https://codepen.io/marcosriani/pen/ZRoNaj" target="_blank">
                      <img src="https://s6.postimg.cc/nbj1nx9dd/form.png" alt="Form project" style="width:100%">
                      <h3>Form</h3>
                      <p>Project for the FreeCodeCamp</p>
                    </a>
                  </div>
                </div>
                <div class="column">
                  <div class="content">
                    <a href="https://codepen.io/marcosriani/pen/yEKJZJ" target="_blank">
                      <img src="https://s6.postimg.cc/sa6k2h0bl/tribute_page.png" alt="Tribute page" style="width:100%">
                      <h3>Tribute Page</h3>
                      <p>Project for the FreeCodeCamp</p>
                    </a>
                  </div>
                </div>
                <div class="column">
                  <div class="content">
                    <img src="https://s6.postimg.cc/d1gmoobs1/mountains.jpg" alt="Nature" style="width:100%">
                    <h3>WORKING</h3>
                    <p>Lorem ipsum..</p>
                  </div>
                </div>
                <div class="column">
                  <div class="content">
                    <img src="https://s6.postimg.cc/myrnhqbo1/nature.jpg" alt="Mountains" style="width:100%">
                    <h3>WORKING</h3>
                    <p>Lorem ipsum..</p>
                  </div>
                </div>
              </div>
              

            </div>


          </div>
      </main>







      <div class="socialproof" id="about">
         <div class="container-sml">
            <div class="flex text-center">
               <div class="col-12 about">
                <h2 class="subheading">About me</h2>
                <p>I recently graduated in Economics at Universidade Federal de Viçosa in Brazil. </p>
                <p>The nature of my degree course has prepared me to work in different areas of knowledge. It involved a great deal of independent research, requiring initiative, self-motivation and a wide range of skills . </p>
                <p>After graduating I decided to change career and become a Front-End Developer</p>
                <p>I'm currently studding at FreeCodeCamp, Team Threehouse, Pluralsight, Udemy and I'm planning to join the Front-End Developer course at OpenClassRooms </p>
                <br>
                <p>Inspiring phrase:</p>

                <blockquote class="quote">
                  &ldquo; The internet is becoming the town square for the global village of tomorrow &rdquo;
                  <cite class="paragraph">Bill Gates</cite>
                </blockquote>
               </div>
            </div>
         </div>
      </div>

      <div class="whatisthis">
         <div class="container-lrg contact"  id="contact">
           <div class="contact-header">
             <h2>Let's work together...</h2>
             <p>How do you take your coffee?</p>
                <div class="icons-box">
                  <a href="https://linkedin.com/in/marcosriani" target="_blank" class="contact-details "> Linkedin <i class="fab fa-linkedin-in"></i></a>
                  <a id='profile-link' href="https://github.com/marcosriani" target="_blank" class="contact-details"> GitHub <i class="fab fa-github"></i></a>
                  <a href="https://facebook.com/marcos_riani" target="_blank" class="contact-details "> Facebook <i class="fab fa-facebook-f"></i></a>
                  <a href="mailto:marcosriani@hotmail.com" class="contact-details"> Email <i class="fas fa-envelope"></i></a>
                   
                </div>
            </div>
         </div>
      </div>


      <div class="footer">
         <div class="container-lrg flex">
            <div class="col-6 text-center">
               <div class="contribute-copy center vertical text-center">
                  <h3 class="subheading">
                    <a href="#body"><button class="ctas-button">UP</button></a>
               </div>
            </div>
            <div class="col-6 text-center">
               <h2 class="legal">Legal</h2>
               <div class="supporters copyright" id="supporters">
                 <p>  Copyright &copy; 2018 by Marcos Riani. All rights reserved.</p>
               </div>
            </div>
         </div>
      </div>
        <script src="https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js"></script>
   </body>
</html>




_--------------------
  --------------------


CODE CSS


 *{
    font-family:-apple-system, BlinkMacSystemFont, segoe ui, Roboto, Helvetica, Arial, sans-serif, apple color emoji, segoe ui emoji, segoe ui symbol;
}
 *,
 *:before,*:after{
    margin:0;
    box-sizing:border-box;
}
 body{
    height:100%;
    width:100%;
    -webkit-font-smoothing:antialiased;
}
/* ----------  HEADER ------  */
.header{
   padding:20px 0 10px;
   height: 100vh;
   overflow:hidden;
}
.header .heading{
   margin:80px 0 0;
}
.header .centerdevices{
   margin:25px 0;
}
.heading{
   font-weight:140;
   font-size:50px;
   line-height:68px;
}


.footer,
.header{
   background-color: #01A7C2;
   color: #FDFFFF;
}



/* ----------  NAVIGATION ------  */
.nav a:link {
  transition: border-bottom 0.3s;
}
.nav a:hover {
  border-bottom: 0.3px solid #A3BAC3;
}
.nav-link{
   text-decoration:none;
   font-size:18px;
   line-height:30px;
   color:inherit;
   padding-bottom: 3px;
}

.nav-link:not(:first-of-type){
   margin-left:25px;

}

/* ----------  BUTTONS ------  */


button:link {
  transition: color 0.3s;
}
button:hover {
  color: #006989;
}




 @media only screen and (max-width:500px){
     .mobile-hide{
        display:none;
    }
}
 .logo-img{
    max-width:100%;
    max-height:100%;
    height:40px;
}
 figure{
    display:flex;
    flex-direction:column;
    align-items:center;
}
 p{
    text-align:center;
}

 .img{
    max-width:200px;
    opacity: 0.99;
    border-radius:50%;
    border:2px solid #006989;
    box-shadow:0 10px 10px -10px rgba(56, 54, 54, 0.5);
    border-color:#006989;
}
.img:hover {
  opacity: 1;
}
.col-12 p {
  margin-bottom: 10px;
}
 @media (max-width:900px){
     .heading{
        font-size:32px;
        line-height:40px;
    }
}
 .subheading{
    font-size:40px;
    line-height:40px;
    font-weight:300;
}
.legal {
  font-size: 20px;
  line-height: 30px;
}

.quote{
  margin-top: 20px;
   font-size:18px;
   line-height:30px;
   font-weight:300;
}

 @media (max-width:900px){
     .subheading{
        font-size:26px;
        line-height:35px;
    }
}

 .paragraph{
    font-size:17px;
    line-height:32px;
    font-weight:100;
}
 .subheading+.paragraph{
    margin-top:10px;
}
.paragraphStrong {
  transition: color 0.3s;
  padding-bottom: 5px;
  padding-top: 5px;
  text-transform: uppercase;
}

 p.paragraph{
    color:#FDFFFF;
}
 .text-center{
    text-align:center;
}
 .flex,
 .spread,
 .center,
 .vertical,
 .aligncenter{
    display:flex;
}
.flex {
  justify-content: center;
  align-content:  center;
}
 /* .baseline{
    align-items:baseline;
} */
 .aligncenter{
    align-items:center;
}
 .spread{
    justify-content: space-between;
}
 .center{
    align-items:center;
    justify-content:center;
}
 .vertical{
    flex-direction: column;
}
 .col-4,
 .col-6,
 .col-12{
    padding:0 20px;
}
 .col-4{
    width:33.333333%;
}
 .col-6{
    width:50%;
}
 .col-12{
    width:100%;
}
.about h2 {
  padding-bottom: 20px;
}
.about p {
  font-size: 15px;
}
 @media only screen and (max-width:500px){
     .mobile-col-12{
        padding:0 20px;
    }
     .mobile-col-12{
        width:100%;
    }
}
 .container-lrg,
 .container-sml{
    margin: auto;
    width: 100%;
}
 .container-lrg{
    display: flex;
    max-width: 1080px;
}
 .container-sml{
    max-width:700px;
}
 .ctas{
    margin:40px 0 0;
}
 .centerdevices{
    position:relative;
}
 @media (max-width:420px){
     .logo{
        font-size:22px;
    }
}
 @media (max-width:370px){
     .nav{
        padding:0 10px;
    }
}
 @media (max-width:350px){
     .nav{
        padding:0;
    }
     .nav-link{
        font-size:16px;
    }
}
 @media (max-width:900px){
     .header .heading{
        margin-top:60px;
    }
}
 @media (max-width:500px){
     .header .heading{
        margin-top:50px;
    }
}
 .ctas-button{
    display:inline-block;
    height:40px;
    line-height:38px;
    padding:0 30px;
    background: #A3BAC3;
    border-radius:3px;
    font-size:15px;
    font-weight:600;
    text-transform:uppercase;
    letter-spacing:.3px;
    border:1px solid #006989;
    text-decoration:none;
    color:  #FDFFFF;
}
 @media (max-width:440px){
     .ctas-button{
        display:block;
        width:100%;
        text-align:center;
    }
}
 .whatisthis{
    padding: 50px 0;
    background-color:  #FDFFFF;
    color:  #007090;
}
 .socialproof{
    padding:90px 0;
    background-color: #007090;
    color: #FDFFFF;
}
 @media (max-width:440px){
     .ctas-button{
        display:block;
        width:100%;
        text-align:center;
    }
}
 .footer{
    padding: 20px 0;
}
 @media (max-width:440px){
     .ctas-button{
        display:block;
        width:100%;
        text-align:center;
    }
}
 .footer .paragraph{
    color:inherit;
}
 .footer .ctas-button{
    margin-top:20px;
}
 .feature3{
    padding: 50px 0 30px;
    border-bottom:1px solid rgba(0, 0, 0, .1);
}
 @media (max-width:750px){
     .feature3 .flex{
        flex-wrap: wrap;
    }
     .feature3 .col-4:nth-of-type(1){
        width: 100%;
        margin-bottom: 30px;
    }
     .feature3 .col-4:not(:nth-of-type(1)){
        width:50%;
    }
    .icons-box {
      display: grid;
      grid-template-columns: 1fr 1fr ;
      grid-auto-rows: 1fr;
      align-items: center;
    }

}
 @media (max-width:500px){
     .feature3 .col-4:nth-of-type(1){
        margin-bottom:0;
    }
     .feature3 .col-4:not(:nth-of-type(1)){
        width:100%;
        margin-top:30px;
    }
}
 @media (max-width:750px){
     .footer .col-6:nth-of-type(1){
        margin-bottom:0;
    }
     .footer .col-6{
        width:100%;
        margin-top:30px;
    }
}
 @media (max-width:750px){
     .footer .flex{
        flex-wrap: wrap;
    }
}
 .copyright{
    padding:10px 0;
    display:flex;
    align-items:center;
    justify-content:center;
    flex-wrap:wrap;
    font-size:15px;

}


/*  */
/*  */
/*  */
/* Test */
/*  */
/*  */
/*  */


/* Center website */
.feature3 {
  display: block;
  background-image: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.6)) ,url('https://s6.postimg.cc/lwhgz7npt/coding.jpg');
  background-repeat: no-repeat;
  background-size: cover;
  background-attachment: fixed;
}
.main {
    max-width: 1000px;
    margin: auto;
    color: #FDFFFF;
    text-align: center;
}
.project-tile {
    font-size: 50px;
    word-break: break-all;
    padding-bottom: 20px;
    font-weight:300;

}
.main p {
  font-size: 20px;
  padding: 20px;
}

.row {
    margin: 8px -16px;
}

/* Add padding BETWEEN each column (if you want) */
.row,
.row > .column {
    padding: 10px;
}

/* Create four equal columns that floats next to each other */
.column {
    float: left;
    width: 50%;
}
.column img {
border-radius: 1%;
}


/* Clear floats after rows */
.row:after {
    content: "";
    display: table;
    clear: both;
}

/* Content */
.content {
    padding: 20px;
    border-radius: 1%;
}
.content a {
  text-decoration: none;
  color: inherit;
}
.content h3 {
  margin-top: 10px;
}
.content img {
  width: 100%;
  height: 250px;
  opacity: 0.90;
  transition: transform 0.5s, opacity 0.2s;

}
.content img:hover {
  opacity: 1;
  transform: scale(1.09);
}
.subheading a {
  text-decoration: none;
  color: inherit;
}


/*  */
/*  */
/*  */
/* Contact part */


.contact {
  height: auto;
}
.contact-header {
  /* background-color: red; */
  margin: 0 auto;
}
.contact-header h2,
.contact-header p {
  padding: 10px;
  text-align: center;
  line-height:40px;
  font-weight:300;
}
.contact-header h2 {
  font-size:30px;
}
.contact-header p {
  margin-bottom: 20px;
  font-size:20px;

}
.contact-details {
  display: inline-block;
  font-weight: bold;
  margin: 0 35px 45px 35px;
  list-style-type: none;
  /* border: 2px solid #A3BAC3; */
  border-radius: 100%;
  width: 100px;
  height: 100px;
  line-height: 100px;
  background: #A3BAC3;
  color: #FDFFFF;
  text-decoration: none;
  text-align: center;
  opacity: 0.95;
  transition: transform 0.5s, opacity 0.2s;

}

.contact-details:hover {
  background: #FDFFFF;
  color: #006989;
  opacity: 1;
  transform: scale(1.5);
}

/* ICON */





/* Responsive layout - makes the two columns stack on top of each other instead of next to each other */
@media screen and (max-width: 600px) {
    .column {
        width: 100%;
    }
    .header{
       height: 100%;
    }
    .header .heading {
    margin-top: 10px;
    }
    .col-12 p {
        margin-bottom: 5px;
    }
    .paragraph {
    font-size: 15px;
    }
    .header .centerdevices {
    margin: 20px 0;
    }
    .socialproof {
    padding: 30px 0;
    }
    .whatisthis {
    padding: 20px 0;
    }
    .feature3 {
    padding: 30px 0 10px;
    }
    .main p {
    font-size: 20px;
    padding: 10px;
    }
    .row {
    padding: 3px;
    }


    /* .column img {
      padding-left: 10px;
      padding-right: 10px;
    } */
}
nav ul {
  list-style: none;
}
nav li {
  margin-left: 25px;
}






________________________________
De: Tracey Bushman <notifications@github.com>
Enviado: sábado, 30 de junho de 2018 21:54
Para: freeCodeCamp/testable-projects-fcc
Cc: Marcos Cabrini Riani dos Reis; Mention
Assunto: Re: [freeCodeCamp/testable-projects-fcc] The navbar should contain at least one link not working (#411)


@marcosriani<https://github.com/marcosriani> I couldn't reproduce this particular error, however, the last test was not passing. Ensure your navbar stays 'fixed' at the top of the viewport during scrolling.
Ensure you are using the correct CDN for testing: https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js
If you want to discuss, let us know. :)

**Comment by tbushman** [comment]
@marcosriani Would you mind sharing the link to your Codepen? Perhaps it's only failing in Codepen...

**Comment by marcosriani** [comment]
Yes, I believe it was only failing in the Codepen, but I’ve changed some code order and now it’s fine.
https://codepen.io/marcosriani/pen/GGzJOy



On 1 Jul 2018, at 16:01, Tracey Bushman <notifications@github.com<mailto:notifications@github.com>> wrote:


@marcosriani<https://github.com/marcosriani> Would you mind sharing the link to your Codepen? Perhaps it's only failing in Codepen...
