### ISSUE TITLE
cannot pass 9.

### ISSUE THREAD

**Issue by lubodrinka** [freeCodeCamp/testable-projects-fcc#412]
I try severals changes even without extend yaxis range
#### Issue Description

9. My heat map should have cells that align with the corresponding month on the y-axis.

#### Browser Information

* Browser Name, Version:  all
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

``` 
 https://codepen.io/vanderdrilu/pen/MXLYpQ
this variant code produce
var parseDateMD = d3.timeParse("%m/%d");
   var dataMonts=[];
for(var x= 0; x<=12;x++)dataMonts.push(parseDateMD(x+"/"+15));
        var scaley = d3.scaleTime()
            .domain([d3.max(dataMonts),d3.min(dataMonts) ])
            .range([height - padding, padding]);
        var axisy = d3.axisLeft(scaley).
        tickFormat(d3.timeFormat("%B")).tickSizeOuter(0) 

TypeError: surroundingTicks is nullareShapesAlignedWithTicks/<@https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:22564:1
var parseDateM = d3.timeParse("%m");

       var dataMonts=[];
for(var x= 1; x<=12;x++)dataMonts.push(parseDateM(x));
        var scaley = d3.scaleTime()
            .domain([d3.min(dataMonts), d3.max(dataMonts)])
            .range([height - padding, padding]);
        var axisy = d3.axisLeft(scaley).
        tickFormat(d3.timeFormat("%B")) 
       ;

 My heat map should have cells that align with the corresponding month on the y-axis. AssertionError: month values don't line up with y locations : expected false to be true
```

**Comment by tbushman** [comment]
@lubodrinka Hello, this was a similar issue to #417 . If you set up your domain and range in ascending order, your tests will pass and still have the visual order you want:  
```
var scaley = d3.scaleTime()
      .domain([d3.min(dataMonts), d3.max(dataMonts)])
      .range([padding,height - padding]);
```  
instead of  
```
var scaley = d3.scaleTime()
      .domain([d3.max(dataMonts), d3.min(dataMonts)])
      .range([height - padding, padding]);  
```

**Comment by lubodrinka** [comment]
first not help
and second the graph goes to angle 3 degree

**Comment by tbushman** [comment]
@lubodrinka I confirmed again that making the specified changes (line 69 - 70) fixes the problem. You'll switch the order of both .domain and .range and that should fix it.

**Comment by lubodrinka** [comment]
I was thinking you change only domain and now I see you swap both and really work.

Sometimes I must check emails first check I found also new one
.domain([new Date(1899, 11, 31), new Date(1900, 11, 31)])
            //.domain([d3.max(dataMonts),d3.min(dataMonts) ])
            .range([padding,height - padding ]);
