### ISSUE TITLE
Product landing page test won't detect layout, on github

### ISSUE THREAD

**Issue by mckelveygreg** [freeCodeCamp/testable-projects-fcc#416]
#### Issue Description

Content Test 2 won't accept a local, non https image

Layout tests
- Doesn't detect my sticky nav-bar
- Doesn't detect my media query
- Doesn't detect my flexbox use in my nav-bar

#### Browser Information

* Browser Name, Version: Chrome, v 67
* Operating System: Win 10
* Mobile, Desktop, or Tablet: Desktop 

#### Your Code / Link to Your Pen

```
live site:
 https://mckelveygreg.github.io/product-landing-page/
Source code:
 https://github.com/mckelveygreg/product-landing-page
 
```

**Comment by tchaffee** [comment]
@mckelveygreg Both the production and dev CND links `bundle.js` are not working right now (getting 404) so I can't test your code using the same bundle as you were using. We have been working at moving away from them and using our own CDN, and that's just about ready so could you change your `index.html` to use the new link?

https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js

If you do this, all the tests should pass except the one regarding the navbar. The wording on that test is unfortunately wrong. It should say "The header element and any of its children such as the navbar should always be at the top of the viewport."

If you can change your code to make sure the entire header stays at the top of the viewport, all the tests should pass. Please let me know.

Thanks.

**Comment by tchaffee** [comment]
@mckelveygreg After I took a closer look at your page, you'll probably want to put that big image above your navbar outside of your header, and then just stick a small logo or something in the navbar to fulfill the requirement that the header have an image. Otherwise your navbar is never going to be close enough to the top to pass the tests. Take a look at the example project in CodePen to see how the header image and navbar are ideally layed out. https://codepen.io/freeCodeCamp/pen/RKRbwL

**Comment by mckelveygreg** [comment]
@tchaffee Thanks for taking a look! I pushed the changes you suggested, smaller header-img and new CDN link. I still had a few issues.
- To pass test Content test 2, I added the letters 'http' to name of the image.
- Despite having a media query and using flexbox, I still can't pass those last 2 Layout tests. 

Are these issues because I'm using github?
Thanks!

**Comment by tchaffee** [comment]
@mckelveygreg I doubt the issues are from using github. But even if we find that it is related to that, the tests are supposed to work outside of CodePen. I'll have another look as soon as I can.

**Comment by tchaffee** [comment]
@mckelveygreg I just ran the tests on your live site and everything passed. 

![selection_150](https://user-images.githubusercontent.com/148813/42710353-14bb55f0-86ba-11e8-898e-c330a0b5aab0.png)

Have you made more fixes? Are you running the tests using Chrome?

I did take a closer look at the header image test. One of the tests is the following:

```
assert.include(
  img.src,
  'http',
  'The src attribute\'s value should be a url (http...) '
);
```

I'm not so sure that's a great test myself. 

@tbushman what do you think about me removing that part of user story 2? It's basically insisting that only an absolute URL can be used (e.g. `src="http://mysite.com/image.png"`). But relative URLs are in common use and are totally valid (e.g. `src="/image.png").

Not to mention the test isn't very robust. You can trick it by just putting the string "http" anywhere in the image name...

**Comment by mckelveygreg** [comment]
@tchaffee Hmmm, well that's encouraging! Yeah, on chrome it isn't detecting my media queries, so I just moved on... 
Thanks for the help!

**Comment by tchaffee** [comment]
@mckelveygreg I don't know why it's not working for you. I looked at your media queries and it looks fine. Could you see if there are any console errors? Chrome does sometimes have some weird security errors when we query the media rules.

**Comment by mckelveygreg** [comment]
There is a mocha error:

bundle.js:271 mocha not loaded yet
runCheck @ bundle.js:271
setTimeout (async)
(anonymous) @ bundle.js:4182
fire @ bundle.js:3810
fireWith @ bundle.js:3940
fire @ bundle.js:3948
fire @ bundle.js:3810
fireWith @ bundle.js:3940
ready @ bundle.js:4420
completed @ bundle.js:4430

**Comment by mckelveygreg** [comment]
@tchaffee  Same as my version

**Comment by tchaffee** [comment]
Console output looks ok. I'm afraid I don't know where to go from here because I can't reproduce the problem. You could fork this repo and try to reproduce and debug it locally if you want something that would be challenging but you might learn a lot from.

@tbushman Any chance you can reproduce this problem? Just go to https://mckelveygreg.github.io/product-landing-page/ and see if the tests pass or not?

**Comment by tbushman** [comment]
@mckelveygreg @tchaffee That passes for me...  
I agree that students should be able to use file system paths for images. It's good practice. Now how to regex that ... ;)

**Comment by tbushman** [comment]
Also if you run your project locally without a server (i.e. launch index.html in a browser), the css media query tests won't work. ...

**Comment by tchaffee** [comment]
> I agree that students should be able to use file system paths for images.

@tbushman Sorry if this comes off as pedantic, but just to be clear it's not really a file system path. It's a relative URL. There is a difference. What looks like a file system path might be translated by the webserver to a completely different file system path.

Not sure how to test it, other than that the src attribute isn't empty. Perhaps I could come up with a test for whether or not it's a broken image? I'll give that a thought.

**Comment by mckelveygreg** [comment]
@tchaffee and @tbushman , Thanks for the help and clearing up how to test properly. 
And thanks for all the work you do! I feel like these test suites are helping me become a much better developer!
