### ISSUE TITLE
I have added y-axis labels ,yet the test fails.

### ISSUE THREAD

**Issue by dee-g** [freeCodeCamp/testable-projects-fcc#417]
#### Issue Description

I run the tests for HeatMap and the y-axis test fails.

#### Browser Information

* Browser Name, Version: chrome
* Operating System: Windows 10.
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

https://codepen.io/deepikag/pen/KeGXLN
```
 
 
 
```

**Comment by tbushman** [comment]
@dee-g Thanks. I will look into this.

**Comment by tbushman** [comment]
Hello @dee-g There were a couple of things I changed to get your tests to pass:  
`yScale = d3.scalePoint().range([height,0])` to `yScale = d3.scalePoint().range([0,height])`  
and  
`yScale.domain([12,11,10,9,8,7,6,5,4,3,2,1,0]);` to `yScale.domain([0,1,2,3,4,5,6,7,8,9,10,11]);`  
  
The test checks whether the axis ticks are in descending or ascending order, but I think it was getting tripped up on the manual settings.

**Comment by dee-g** [comment]
Thanks Tracey , I made changes and got it to pass.
