### ISSUE TITLE
Product Landing Page test unsuccessful when wrapped in media query

### ISSUE THREAD

**Issue by MjRodge** [freeCodeCamp/testable-projects-fcc#418]
#### Issue Description

Layout test number 3 in Product Landing Page ("My product landing page should utilize CSS flexbox at least once.") returns a failure when I have my flexbox display style wrapped in a media query to be applied at a minimum width.
When moving the flexbox styling to a regular class style it is returned as a success.

#### Browser Information

* Browser Name, Version: Chrome v67
* Operating System: macOS v10.13.5
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

 https://codepen.io/MjRodge/pen/GGbJYo/

**Comment by tchaffee** [comment]
Thanks for reporting this. We will try to repeat it as soon as we can and get back to you.

**Comment by tbushman** [comment]
@MjRodge This appears to be resolved. Is that true?

**Comment by tbushman** [comment]
Possible relation to #437
