### ISSUE TITLE
This should work but keeps failing the "not centered" test.

### ISSUE THREAD

**Issue by andyzam** [freeCodeCamp/testable-projects-fcc#419]
https://codepen.io/andyzam/pen/zaVoRL

Pen above fails 1 test but then when I press "run test" again (without any changes), it says the responsive test also fails.  In Chrome, the picture is centered and responsive.  Not sure why tests fail.  May be a bug.

Thanks

**Comment by tbushman** [comment]
@andyzam Thanks for reporting this. The tests are removing your inline styles. D:

**Comment by tbushman** [comment]
@andyzam I think it's acceptable to inline your styles. Also, your case has uncovered an error with our tests.

**Comment by tchaffee** [comment]
@tbushman I would like to work on this. But the CodePen in question no longer fails. Do you have any information about where our code is removing inline styles?

**Comment by tbushman** [comment]
@tchaffee In the second-to-last test, I remember wondering whether this  
```  
img.setAttribute('style', 'display: none !important');  
```  
was erasing other inline styles. Does setting style for one css property in this way leave other inline styles in place?

**Comment by tchaffee** [comment]
Yes, if I remember right that would replace the existing style. Thanks for the tip, I'll get on this.
