### ISSUE TITLE
[Tribute Page] Layout Test 2 fails when the wrapping div (#img-div) is padded more than 5px

### ISSUE THREAD

**Issue by elrolfe** [freeCodeCamp/testable-projects-fcc#42]
#### Issue Description

It appears that the testing code isn't taking left and right padding of the wrapping div (#img-div) into account when checking for a centered image.  The test code allows for +/- 10 px in it's test for centering, so if #img-div is padded by 5px or less, the image position falls within the allowed variance.  However, when the image is padded by more than 5 px, then while the image is still correctly centered, it fails the test.

#### Browser Information

* Browser Name, Version: Chrome 55.0.2883.87 (Official Build) (32-bit)
* Operating System: Windows 7 Professional, Service Pack 1
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

CSS Stylesheet
```

#img-div {
  background-color: #fff;
  box-sizing: border-box;
  padding: 10px 20px;
  width: 100%;
}

#img-div #image {
  display: block;
  height: auto;
  margin: 0 auto;
  max-width: 100%;
}

#img-div #img-caption {
  font-size: 0.8em;
}

```
HTML Code
```
 
     <div id="img-div">
      <img id="image" src="http://s33.postimg.org/v1na5y41b/John_Stewart_USO.jpg" alt="">
      <p id="img-caption">Former Daily Show host Jon Stewart tells jokes behind the president’s lectern as President Barack Obama and First Lady Michelle Obama look on during the comedy show in celebration of the 75th anniversary of the USO and the 5th anniversary of Joining Forces at Joint Base Andrews in Washington, D.C. May 5, 2016. By DoD News Features (160505-D-DB155-002) [Public domain], <a href="https://commons.wikimedia.org/wiki/File%3AJon_Stewart_tells_jokes_behind_the_president%E2%80%99s_lectern_as_President_Obama_and_the_First_Lady_look_on_during_the_comedy_show_in_celebration_of_the_75th_anniversary_of_the_USO_and_the_5th_anniversary_of_Joining_Forces_(26240098743).jpg" target="_blank">via Wikimedia Commons</a></p>
    </div>

 
```

#### Screenshot

Screenshot 1:  Test fails with left and right padding of 20px.
![tribute page bug screenshot 1](https://cloud.githubusercontent.com/assets/25251/22789325/a35a8130-eeb0-11e6-819b-8bc14223b5da.JPG)

Screenshot2:  Test passes with left and right padding of 5px.
![tribute page bug screenshot 2](https://cloud.githubusercontent.com/assets/25251/22789354/b43bd85a-eeb0-11e6-927f-dd99e62f52eb.JPG)

**Comment by no-stack-dub-sack** [comment]
@elrolfe Thanks for reporting this! Someone actually brought this to my attention a while ago and I totally forgot to fix it. Appreciate the reminder, and if you see this more than a few hours from when I'm leaving this comment (the time it will sometimes take for the changes to propagate through the  GitCDN), you should be able to go back to 10px margin and the tests should pass.

Thanks again! 😄
