### ISSUE TITLE
Product Landing Page Test Glitch

### ISSUE THREAD

**Issue by Philosophist** [freeCodeCamp/testable-projects-fcc#420]
#### Issue Description

I found this because I use a style which is consistent but does not seem to be accepted by the test. 
When I embed the video, I get 7 tests passed, perfectly fine.
![screenshot 1](https://user-images.githubusercontent.com/12451365/42361204-08501f76-80a2-11e8-8bf0-e4e3dfeca228.png)

BUT, if I hit ENTER once to put the iframe close element on a new line, two tests are failed, just for that.
![screenshot 2](https://user-images.githubusercontent.com/12451365/42361206-0d48d158-80a2-11e8-9921-8cfd8c8c3430.png)

It seems that tests #5 and #6 are rejected for this simple detail. 
![image](https://user-images.githubusercontent.com/12451365/42361188-ee84f652-80a1-11e8-8e61-87c6d45326e9.png)
I don't know if there's any use case to put things between the open and close of an iframe element, but the code still works just fine with the new line even if the test isn't passing. I hope that pointing this out helps refine the test to be more accurate.

#### Browser Information

* Browser Name, Version: Chrome Version 67.0.3396.99 (Official Build) (64-bit)
* Operating System: Windows 10
* Mobile, Desktop, or Tablet:  Desktop

#### Your Code / Link to Your Pen

https://codepen.io/Philosophist/pen/xzJVLa?editors=1000
 
      `<iframe id="video" width="560" height="315" src="https://www.youtube.com/embed/sr35jPTfjGQ" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>`
 
 
```

#### Screenshot
<!-- Add a screenshot of your issue -->
See screenshots above

**Comment by tbushman** [comment]
Also #441

**Comment by tbushman** [comment]
@Philosophist Thank you for reporting this. :)
