### ISSUE TITLE
I am using 9 colors in my legend but the test fails.

### ISSUE THREAD

**Issue by deepikagunda** [freeCodeCamp/testable-projects-fcc#421]
#### Issue Description

The test  no 9 . i.e "There should be at least 4 different fill colors used for the legend" is failing though the legend has 9 colours.

#### Browser Information

* Browser Name, Version: chrome
* Operating System: windows 10
* Mobile, Desktop, or Tablet: desktop

#### Your Code / Link to Your Pen

```
https://codepen.io/deepikag/pen/qKGxpw
 
 
 
```

**Comment by tbushman** [comment]
@dee-g Hello, the legend will pass if given the `id="legend"` and that should fix it! :) Thanks.

**Comment by tbushman** [comment]
...i.e.  
```  
.attr('class', 'key').attr('id', 'legend')  
```  
Thanks
