### ISSUE TITLE
CDN used to test cases is not working anymore

### ISSUE THREAD

**Issue by mrwanashraf** [freeCodeCamp/testable-projects-fcc#422]
#### Issue Description

whenever i try to use this [link](https://gitcdn.link/repo/freeCodeCamp/testable-projects-fcc/master/build/bundle.js) that's provided in freecodecamp projects to test against the cases provided the link always return 404 Not Found, in the browser console or even when i try to access its URL.

this issue is not related to a browser nor a bug from my side, its a CDN issue.

**Comment by tbushman** [comment]
@mrwanashraf Sorry for the confusion. Will you try this url, please: `https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js` ? Eventually all documentation will use this url instead.

**Comment by mrwanashraf** [comment]
@tbushman  works thanks ^^, i will have to close the issue since its no longer there.
