### ISSUE TITLE
<div id="name"> <label id="name-label">* Name: </label>       <input placeholder="eg.promise" size="15"><br>     </div>

### ISSUE THREAD

**Issue by promiseitamah** [freeCodeCamp/testable-projects-fcc#424]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 
 
```

**Comment by tbushman** [comment]
@promiseitamah Please see comments and references in #400

**Comment by tbushman** [comment]
Leaving open #400 and closing other related issues.
