### ISSUE TITLE
Data Visualization project 1 - Test 9 won't pass. Using Dates as x axis

### ISSUE THREAD

**Issue by juandiegon** [freeCodeCamp/testable-projects-fcc#425]
#### Issue Description

The test 9 won't pass but the graph has the correct bar height and size. I have kept the dates and set up the xScale as a Date element.
The error I get is:
9. Each bar element's height should accurately represent the data's corresponding GDP
AssertionError: The heights of the bars should correspond to the data values : expected 'Infinity' to equal '2494.011'
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:22424:25
    at NodeList.forEach (<anonymous>)
    at n.<anonymous> (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:22420:15)
    at r (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:7852)
    at r.run (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:8853)
    at i.runTest (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:13553)
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:14192
    at r (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:13024)
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:13000
    at n (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:12791)
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:12855
    at i (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:1:559)

#### Browser Information

* Browser Name, Version:  Chrome 67.0.3396.99 
* Operating System: Mac 10.13.5
* Mobile, Desktop, or Tablet: Desktop 

#### Your Code / Link to Your Pen

```
 https://codepen.io/juandiegon/pen/xzovwV?editors=0011
 
 
```
Thank you very much for your help!

**Comment by tbushman** [comment]
@juandiegon Hi, it looks like one or more of the bar's height is 0, and so the test that uses a ratio to compare bar height to GDP ratio comes up with `infinity`. We need to adjust the test to filter out bars with height = 0 so thanks!

**Comment by tbushman** [comment]
Still, the none of the bars should have height = 0 so I'm looking into whether the margins are correct, which I think is the problem with the fCC bar chart example as well.   
https://gist.github.com/mbostock/3019563

**Comment by juandiegon** [comment]
Thanks! I am wondering if it is due to the first item being barely visible? I have tried increasing the height of the codepen but that did not fix it, it could be the way I am handling the margins

**Comment by tbushman** [comment]
@juandiegon Thanks. It will be good to have the tests handle this situation because your graph is accurate.

**Comment by tbushman** [comment]
@juandiegon The only `<rect>` element that is `height=0` is the very first one. I feel like this is an error, but I'm not finding it. Everything seems in order in the code. Did you figure something out?

**Comment by ValeraS** [comment]
resolved
