### ISSUE TITLE
On the product landing page project, I do have an embed video using iframe with an id of video but my iframe don't seem to pass the test

### ISSUE THREAD

**Issue by DominusKelvin** [freeCodeCamp/testable-projects-fcc#429]
#### Browser Information

* Browser Name, Version:  Chrome
* Operating System: Windows
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
  <iframe  id="video" type="text/html" width="420" height="315"
src="https://www.youtube.com/embed/IrPH7H6-efk" frameborder=0>
</iframe>
```

**Comment by tbushman** [comment]
@DominusKelvin Hello, without the full code I can only guess a couple of things. Please remove the `type="text/html"` attribute, and put quotes around the `0` in `frameborder="0"` and see if that helps. I think mainly the 0 needs quotes... If that doesn't help please share a link to your project. Thanks. :)

**Comment by tbushman** [comment]
This could also be related to #445 so once that is merged, check back on this. Thanks!

**Comment by DominusKelvin** [comment]
Thanks for the response
