### ISSUE TITLE
Markdown previewer #Tests 3 failing when using onChange event in local react environment using create-react-app

### ISSUE THREAD

**Issue by ayappa-reddy** [freeCodeCamp/testable-projects-fcc#430]
#### Issue Description

When I use the onChange event to update the textarea values in both the #editor element and the #preview element in markdown previewer project in a local react environment using the create-react-app,  the #Tests 3 is failing even though I am able to satisfy the user story which is to update the #preview element as I type in the #editor element.

#### Browser Information

* Browser Name, Version: Google Chrome, 67.0.3396.99 (Official Build) (64-bit)
* Operating System: Ubuntu 18.04 LTS (64-bit)
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
`import React, { Component } from 'react';

class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      value: '',
    }
    this.handleChange = this.handleChange.bind(this);
  }

  handleChange(e) {
    this.setState({
      value: e.target.value
    });
  }

  render() {
    return (
     <div>
       <textarea id="editor" value={this.state.value} onChange={this.handleChange}></textarea>
       <textarea id="preview" value={this.state.value}></textarea>
     </div>
    );
  }
}

export default App;` 
 
 
```

#### Screenshot

![screenshot from 2018-07-09 18-38-39](https://user-images.githubusercontent.com/5495735/42452331-56f63612-83a7-11e8-8fcc-67a9dd445b9a.png)

**Comment by ayappa-reddy** [comment]
So, I think this might be an isolated issue when working with react locally. I was able to get the tests to pass in codepen. Here's the link [https://codepen.io/aypi/pen/OwLQKP?editors=0010](url). Any help or clarifications regarding this would be great. Thank you.

**Comment by tbushman** [comment]
@ayappa-reddy Hello, the first issue I see is that you have a `<textarea>` element with a value attribute for your #preview element, which will probably give unexpected results. Look into the react `dangerouslySetInnerHTML` function. Also the error mentions that `marked is not defined` so make sure you are importing / requiring or otherwise including the `marked` module / script in your project and let us know how it goes.

**Comment by ayappa-reddy** [comment]
@tbushman Hello, I no longer use the `textarea` element for the `#preview` element. As mentioned before, all the required tests pass when I implement this project in codepen. Here's the link to the [project](https://codepen.io/aypi/full/OwLQKP/) in codepen. The problem arises only in a local react environment with create-react-app. Also, I have imported `marked` using npm and included it at the root of the project. So, I cannot exactly figure out why I am getting the reference error that `marked is not defined`. I am not really sure how / why the `dangerouslySetInnerHTML` is affecting the test results because it works in codepen.

**Comment by tbushman** [comment]
@ayappa-reddy I could be wrong, but I think you'll need to include the Marked module in the App module and not so much the root...

**Comment by ayappa-reddy** [comment]
@tbushman Sorry if I was a little vague there when I said that I included `Marked` at the root of the project. In fact, I included `Marked` in the `App` Module and not the `index` module which is what I think your assumption might be. In fact, I have not split my project into any components. I have used the basic directory structure given by the create-react-app. The thing that's leading me to believe that this is an issue with the test suite is that I am able to parse markdown using `marked` in my local react app and getting the transformed HTML to show in the `preview` element. So, I am still left in the dust as to why the test cases are failing.

**Comment by tbushman** [comment]
I'm stumped too... Some students report failing tests when projects are run directly in the browser without a server, so I recommend launching a simple localhost server with `live-server` or Python to run your project and see if that helps...

**Comment by tchan** [comment]
Seeing this issue too when I created the Markdown Viewer locally with CRA.

**Comment by petercr** [comment]
## Same issue as @ayappa-reddy Failing test 3 on localhost

### Issue Description
When I use the onChange event to update the textarea values in both the #editor element and the #preview element in markdown previewer project in a local react environment using the create-react-app, the #Tests 3 is failing even though I am able to satisfy the user story which is to update the #preview element as I type in the #editor element.

### Browser Information
Browser Name, Version: Google Chrome, 68.0.3440.84(Official Build) (64-bit)
Operating System: Windows 10 Insider's Build 17713
Mobile, Desktop, or Tablet: Laptop

Here's the code: 
```javascript
import React, { Component } from "react";
import "./App.css";
import marked from "marked";

class App extends Component {
  constructor(props) {
    super(props);
    this.mainHtml =
      "# Try this \n" +
      "## Cool Editor \n" +
      "A project from [Free Code Camp](https://learn.freecodecamp.org) \n" +
      "You can use code in-line `console.log('')` \n" +
      "Or Code Blocks \n" +
      "* An image or something \n\n" +
      "**Woah bold text** \n\n" +
      "> A deep quote \n\n" +
      "![React Logo](https://cdn.freebiesupply.com/logos/large/2x/react-1-logo-png-transparent.png)";

    this.state = {
      editorText: this.mainHtml,
      previewText: null
    };
    this.updateEditor = this.updateEditor.bind(this);
  }

  updateEditor() {
    // get MD text from #editor and update editorText
    const _text_ = document.querySelector("#editor").value;
    this.setState({ editorText: _text_ });

    // parse the markdown and update previewText
    const markdown = marked(_text_);
    this.setState({ previewText: markdown, mainHtml: markdown });
    // eslint-disable-next-line
    console.dir(markdown);
  }

  componentDidMount() {
    // call updateEditor() to parse editor markdown
    this.updateEditor();

    // get #editor text, parse it, and log it
    let test = marked(document.querySelector("#editor").value);
    console.log(test);
  }

  render() {
    return (
      <div className="App">
        <div className="editor">
          <h1 className="top">Enter Markdown Here</h1>
          <textarea name="" id="editor" onChange={this.updateEditor}>
            {this.state.editorText}
          </textarea>
        </div>
        <div className="preview">
          <h1 className="top">See Preview Here</h1>
          <div
            id="preview"
            dangerouslySetInnerHTML={{ __html: this.state.previewText }}
          />
        </div>
      </div>
    );
  }
}

export default App;
```
**Also I know that `this.mainHtml` should be an Array and I should iterate through it 😉 😜 **
*I'll fix that later 😄 😆 *

### Here are some screenshots of the problem

![2018-08-07 12](https://user-images.githubusercontent.com/26460352/43811669-b7037b0a-9a8b-11e8-8d56-68cf798a9a54.png)


![2018-08-07 13](https://user-images.githubusercontent.com/26460352/43811688-cc63f948-9a8b-11e8-841b-9ca38341863b.png)

**Comment by petercr** [comment]
## Updated
I have tried switching from `onChange={}` to `onInput={}` and while the program continues to function correctly, it still won't pass **Test 3** 😞 😢

**Comment by tbushman** [comment]
@petercr I got test 3 to pass by including marked in the html head in addition. I wonder if that would help @ayappa-reddy as well. Sorry for the delay.

**Comment by petercr** [comment]
**Thanks @tbushman** 👍  I actually thought of this fix yesterday, but I didn't have time to implement it yet. _Of course_ it makes total sense, the testing suite doesn't have access to marked JS built into the React app. And it shouldn't obviously for security reasons

**Comment by petercr** [comment]
I would love :heart: to take this issue. I think it's just a simple fix of adding the marked package via npm. And then just declaring it in the `import` statements. That should fix the issue all together.
I can go ahead and give it a test run myself :thinking: :smile:

**Comment by tbushman** [comment]
@petercr Yes, thank you for finding the cause!
