### ISSUE TITLE
Product Landing Page Tester Bug

### ISSUE THREAD

**Issue by YunkeXiao** [freeCodeCamp/testable-projects-fcc#431]
#### Issue Description

I have the embedded Youtube video with id="video" and and I have a functional navbar, but the tester fails to recognize them.

#### Your Code / Link to Your Pen

```
 
 https://codepen.io/freeCodeCamp/pen/RKRbwL?editors=1100
 
```

**Comment by tbushman** [comment]
@BrotherYunke Please share a link to your project or a code exerpt. The link you shared was for the fCC example. Thanks.
