### ISSUE TITLE
Unitest does not convert strings to lowercase before comparison

### ISSUE THREAD

**Issue by yarivkohn** [freeCodeCamp/testable-projects-fcc#432]
#### Issue Description
There is a bug in the "Build technical documentation page" project's unit test.
One of the user stories ask for an id that correspond with the text of the header.
During the test, if my header has different capitalization  than the header - the test fails.
For example: my header text is "Support", my id should be "support".
Currently it must be "Support" in order to meet with the test criteria.

#### Browser Information
OS: Ubuntu 18.04 on Desktop.

I was able to to reproduce the bug on both
Chrome v 67.0.3396.99
and Firefox v61.0

#### Your Code / Link to Your Pen
https://codepen.io/Yarivk/pen/qyBNMw?editors=1000
```

**Comment by tbushman** [comment]
@yarivkohn A recent PR should have fixed this. Is it fixed for you?

**Comment by yarivkohn** [comment]
Hi Tracey,
The bug still exist.

Yariv.

**Comment by tbushman** [comment]
Please let me know if you need this reopened.
