### ISSUE TITLE
Technical Documentation Page Test failing on Layout detection

### ISSUE THREAD

**Issue by davidsimoes** [freeCodeCamp/testable-projects-fcc#433]
#### Issue Description

The Technical Documentation Page tests present a bug for the layout:
"On regular sized devices (laptops, desktops), the element with id="navbar" should be shown on the left side of the screen and should always be visible to the user."

On my project the navbar is being showned on the left side for bigger screens, but if I add a 2.5% side padding to have better spacing it fails the tests.

#### Browser Information

* Browser Name, Version:  Chrome 67.0.3396.99
* Operating System: macOS High Sierra 10.13.5
* Mobile, Desktop, or Tablet: 
MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
For more info check the serial number: C02VRPWPHV22
#### Your Code / Link to Your Pen
https://codepen.io/DavidSimoes/full/WKNwwW

```
 //class causing the issue
.basic-padding {
  padding: 0 2%; // if I change 2% to 2.5%, it hits the fan :)
}
 
 
```

#### Screenshot

http://take.ms/nAWR8

**Comment by tbushman** [comment]
@davidsimoes Hello, you can ensure only one vertical scroll bar by adding `overflow: hidden;` to `<body>` and prevent the navbar from scrolling at all. That should fix it! :)

**Comment by KDCinfo** [comment]
Got mine passed (after a few dozen tries) by widening the main CodePen viewing window before running the test. I'm thinking the viewable testing window needs to be at least 850px wide; then run, and test.

**Comment by tbushman** [comment]
@KDCinfo @davidsimoes Also, it helps to ensure the navbar isn't taller than the viewport to prevent this specific issue. Maybe we can just add that wording to the user story. Removing help wanted.
