### ISSUE TITLE
test case 

### ISSUE THREAD

**Issue by Mitesh2611** [freeCodeCamp/testable-projects-fcc#434]
#### Issue Description

the issue is in test case 4 of project 2 (Survey form), i have provided id to the input field ie., id="name", as it was asked to. But still it is not accepting that test case. 

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 <input type="text" class="input-field" id="name"  placeholder="Enter your name..." autofocus>
 
 
```

**Comment by tbushman** [comment]
@Mitesh2611 Please see the comments and references in #400 .

**Comment by tbushman** [comment]
Leaving open #400 and closing other related issues.
