### ISSUE TITLE
build-a-markdown-previewer

### ISSUE THREAD

**Issue by MoatazGitHub** [freeCodeCamp/testable-projects-fcc#435]
Hello,

I did this task
https://learn.freecodecamp.org/front-end-libraries/front-end-libraries-projects/build-a-markdown-previewer

Here is my code  [plnkr](https://next.plnkr.co/plunk/CcUaooQSDcMmyyvF) | [github](https://github.com/MoatazGitHub/Front-End-Libraries-Projects---Build-a-Markdown-Previewer-Learn-freeCodeCamp-)
I tried to use https://cdnjs.com/libraries/marked package but it is not compatible with react 16 

I think it it works well and I want to get my second certification  [First certification](https://www.freecodecamp.org/certification/fcc319f679c/responsive-web-design) so please HELP !!

**Comment by tbushman** [comment]
@MoatazGitHub You will need to import [Marked](https://www.npmjs.com/package/marked) in your `src/components/Mardown.js` file and use as described in the documentation. Did you write your own algorithm or use a different markdown module? If so, you will need to make sure it can pass the specific user stories (i.e. `<blockquotes>` etc.). Another thing is that react has you use https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml so see if those resources help you.

**Comment by MoatazGitHub** [comment]
@tbushman Thanks :+1:
