### ISSUE TITLE
Product landing test not detecting CSS flexbox on ID in CSS

### ISSUE THREAD

**Issue by MMooKow** [freeCodeCamp/testable-projects-fcc#437]
I have 2 css items with display: flex; in my product landing project, but the test set to product landing doesn't detect any display: flex; in my page. These values are on IDs within the CSS not classes or elements.

#### Issue Description

 Issue occurs when an ID in the CSS has the display "property" set to "flex".

#### Browser Information

* Browser Name, Version:  Chrome - Version 67.0.3396.99 (Official Build) (64-bit)
* Operating System: MacOs High Seierra Version 10.13.5
* Mobile, Desktop, or Tablet: MacBook Pro

#### Your Code / Link to Your Pen

```
https://codepen.io/mmookow/pen/zaQKjE?editors=1100

#flex-banner{
  display: flex;
  }

 #flex-container{
  display: flex;
}
```

#### Screenshot

![screen shot 2018-07-10 at 5 25 31 pm](https://user-images.githubusercontent.com/40441070/42541012-5dbbe3c4-8466-11e8-93dd-11d00267a250.png)

**Comment by tbushman** [comment]
@MMooKow Sorry for delay --- but it appears you got it to work. What was it? Thanks!

**Comment by MMooKow** [comment]
With some research. Someone in a FCC forum said that it was the media query messing things up and to just add a bank element with the proper display outside of them.

**Comment by tbushman** [comment]
@MMooKow OK thanks. Keeping this open.
