### ISSUE TITLE
Product Landing Page Project - Test Layout #1 fail

### ISSUE THREAD

**Issue by Jrod36** [freeCodeCamp/testable-projects-fcc#438]
#### Issue Description

I run the test and everything passes except for one (user story #13) --> AssertionError: #header or one of its children should be at the top of the viewport even after scrolling : expected 500 to be close to 0 +/- 15

I've verified that the header is always at the top of the viewport even when scrolling and that I do have a header element with a corresponding id="header". Is there something else I need to do to pass this test? I triple-checked the user stories and I feel like I have everything, but I suppose I could still be missing something.

#### Browser Information

* Browser Name, Version: Google Chrome Version 66.0.3359.181
* Operating System: MAC OS High Sierra version 10.13.5
* Mobile, Desktop, or Tablet: Laptop

#### Your Code / Link to Your Pen

```
 https://codepen.io/Jrod36/full/qKvxoO/
 
 
```

#### Screenshot

![screen shot 2018-07-10 at 6 54 26 pm](https://user-images.githubusercontent.com/29388886/42541982-b4b278bc-8472-11e8-9981-6d1ad74e537f.png)

**Comment by tbushman** [comment]
@Jrod36 The #nav-bar element moves, but the `<ul>` element nested inside stays put. You can add `position: fixed` to the #nav-bar element and that should fix it.

**Comment by Jrod36** [comment]
That did the trick. Thank you!
