### ISSUE TITLE
Codepen for Tribute page #8

### ISSUE THREAD

**Issue by Jan-Timon** [freeCodeCamp/testable-projects-fcc#443]
Here is what the story said:

User Story #8: The img element should responsively resize, relative to the width of its parent element, without exceeding its original size.

If the image is smaller than the #img-div - the test results as false even though this is what was asked.

#img-div{
   width: 400px; 
}
img{
  max-width: 100%; /* the image is only 300px in width */
}

**Comment by tbushman** [comment]
@Jan-Timon There should be no problem with using a smaller image. You're only missing the requirement, `Use the "display" style property with a value of "block" for responsive images`  
That will pass the test. If you want responsive functionality, try using a percentage value for `div#img` `width` along with `display: block` on `img#image` which should scale with changing viewport size.

**Comment by tbushman** [comment]
@Jan-Timon Let us know if there are further issues.
