### ISSUE TITLE
setTimeout for strictEqual function

### ISSUE THREAD

**Issue by MoatazGitHub** [freeCodeCamp/testable-projects-fcc#446]
I'm finalizing " Build a JavaScript Calculator" project using react 
I notices when adding setTimeout to assert.strictEqual  function some teste passed 

```
assert.strictEqual = function (act, exp, msg) {
          window.setTimeout(function(){
              new Assertion(act, msg).to.equal(exp);

          }, 600);

	  };
```

Here is my  [repo](https://github.com/MoatazGitHub/build-a-javascript-calculator) | [plnkr](https://next.plnkr.co/plunk/2GsJNT7MJl8JFoxV)

Edit : Here is used test file with ``` set time out ``` 
[File](https://raw.githubusercontent.com/MoatazGitHub/build-a-javascript-calculator/master/public/freecodecamp.js)

**Comment by tbushman** [comment]
@MoatazGitHub If you force a timeout, you might want to log the result of `document.getElementById('display').innerHTML` in your timeout to ensure mocha isn't skipping anything due to surpassed timeout. Let us know.

**Comment by MoatazGitHub** [comment]
@tbushman I'm using setState function I think it takes a time to update the view if you checked the plnkr all testes passed after make timeout

**Comment by tbushman** [comment]
Did you log the result of `document.getElementById('display').innerHTML` within the test to ensure mocha isn't skipping it or resulting in an inaccurate test result? It should be `.2857...`. If it's working, we can consider adding the timeout.

**Comment by MoatazGitHub** [comment]
@tbushman I was using text input element as #display so I changed it to <ht1>  so I can catch document.getElementById('display').innerHTML I will check and tell you the result , I think we have to change User Story #6: My calculator should contain an element (like ``` <h1 id="display">{this.state.display}</h1> ``` ) to display values with a corresponding id="display". also change 
 ``` https://gitcdn.link/repo/freeCodeCamp/testable-projects-fcc/master/build/bundle.js ```
to be ``` https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js ```

**Comment by MoatazGitHub** [comment]
@tbushman Now all testes works well without any TimeOut please check [plnkr](https://next.plnkr.co/plunk/2GsJNT7MJl8JFoxV)

I'm sorry but is my issue becuase I used input as ``` display ``` element
