### ISSUE TITLE
test cases fail

### ISSUE THREAD

**Issue by Mitesh2611** [freeCodeCamp/testable-projects-fcc#448]
#### Issue Description

project 4 it is not accepting test case 4 and 15

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 
 
```

**Comment by tbushman** [comment]
@Mitesh2611 Will you please share a code sample from your project or a link to your project / code thank you

**Comment by Mitesh2611** [comment]
https://codepen.io/mitesh2611/pen/BPoRQd?editors=1100

above is the link for the project.

**Comment by tbushman** [comment]
@Mitesh2611 Thanks. One of the issues has a pending PR (#451) to fix so I'll check back on that. The other issue of the media queries is from missing brackets in your css:  
change  
```  
@media only screen and (max-width: 815px)
    #main-doc section { 
        ...
    }
```  
to   
```  
@media only screen and (max-width: 815px) {
    #main-doc section { 
        ...
    }
}  
```

**Comment by Mitesh2611** [comment]
ok thanq

**Comment by tbushman** [comment]
@Mitesh2611 Please let me know if you need the issue reopened.
