### ISSUE TITLE
Survey form bug for Unit test number5 id="email"

### ISSUE THREAD

**Issue by Romson** [freeCodeCamp/testable-projects-fcc#453]
Survey form bug for unit test 5:

_5. Inside the form element, I am required to enter an email in a field with id="email"._

Link: https://romson.github.io/Art-Gallery-survey-form/

HTML does have the required #id, which can be seen here:
https://github.com/Romson/Art-Gallery-survey-form/blob/master/index.html

CDN test script used:
<script src="https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js"></script>

**Comment by tbushman** [comment]
@Romson it looks like you have `required` on `input#name` while not on `input#email` so that should do it.

**Comment by Romson** [comment]
Thank you very much @tbushman 

Issue solved.
