### ISSUE TITLE
Product Landing Page should check src attribute or include a separate test that looks for <source> tags.

### ISSUE THREAD

**Issue by nicbovee** [freeCodeCamp/testable-projects-fcc#454]
#### Describe your problem and - if possible - how to reproduce it
Currently, when running the test suite for the "Product Landing Page" project, test 6 is failing even though the code supplied is based on code provided in the [MDN guide for the <video> tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video)

The error one receives is: **"Cannot read property 'hasAttribute' of undefined"**

This is not very helpful since this is coming up even though you're able to play videos without any problems. If for some reason, there is a best practice for using the source tag instead of the attribute, there should be a test that checks for it, and it should be a requirement for completing the challenge.

As far as I'm aware the only advantage is loading multiple sources for accessibility reasons, but that was never mentioned in the project spec so I doubt that's why this is happening.

#### Add a Link to the page with the problem

[My Codepen Project](https://codepen.io/nicbovee/pen/VBezqN)
#### Tell us about your browser and operating system

**Google Chrome**
Version 67.0.3396.99 (Official Build) (64-bit)
Mac OS X: Version 10.11.6 (15G31)

#### If possible, add a screenshot here

<img width="1266" alt="screen shot 2018-07-15 at 10 47 02 am" src="https://user-images.githubusercontent.com/3361752/42736061-71702baa-881c-11e8-9cce-8d32bab087bf.png">

**Comment by tbushman** [comment]
@nicbovee A bug for sure. Sorry! Will look into it.

**Comment by tbushman** [comment]
@nicbovee Thinking it might be the innerText being counted as a child element of video, I ran your snippet through and it passed. Your codepen linked here is empty so I wasn't able to reproduce the error. Recently we fixed this test (#445) so please let us know if it's still not fixed for you.

**Comment by nicbovee** [comment]
Hey @tbushman. I must not have saved the changes. If you take a look again it should show you the issue. [the correct one](https://codepen.io/nicbovee/pen/VBezqN).

It is still failing when I use the code directly from MDN.

**Comment by nicbovee** [comment]
I think it's actually the block starting on line 127. It looks like it's what's requiring <source> children instead of allowing for either the use of defined src attributes on video tag or defined src attributes on the <source> children.

**Comment by tbushman** [comment]
@nicbovee This has more code inside the `<video>` element that counts as children -- an anchor, for example. The test checks _whether_ the `<video>` element has children and only if it does, checks the child element for a `src` attribute. The code you shared before was working if you're fine omitting the anchor.

**Comment by nicbovee** [comment]
That makes total sense. I think improvement on the test would be good since it's been an issue for more than one person at this point. Maybe only reading the src attr on the children elements that match source nodes, instead of on all children. I'm just a student so, do what you think is best. I'm just wanting to help out where I can.

**Comment by tbushman** [comment]
@nicbovee Awesome. Thanks for your direction. That's the best bet and should have thought of that earlier.
