### ISSUE TITLE
Portfolio Project Layout Test #2 Error

### ISSUE THREAD

**Issue by thedtj** [freeCodeCamp/testable-projects-fcc#459]
#### Issue Description

Trying to achieve goal for Personal Portfolio 

Layout test 2 reports back failed unless my Welcome Section has a height of  94.8vh.
Fails with height of 100vh.

#### Browser Information

* Browser Name, Version: Chrome 67.0.3396.99 
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
 https://codepen.io/thedtj/pen/NBGqRy
 
 
```

#### Screenshot

![welcomesectionerror](https://user-images.githubusercontent.com/9098286/42800985-b467a870-8952-11e8-8df7-ebc876cda937.JPG)

**Comment by tbushman** [comment]
@thedtj Hello, I'm still looking into the navbar test, but regarding the #welcome section height, you can enforce viewport size on parent elements.  
```  
html, body, main {
  width: 100%;
  height: 100%;
  margin: 0;
  padding: 0;  
}  
```  
  
as well as adding the box-sizing property to your `<section>`s  
```   
section {
    border-bottom: 2px solid black;  
    box-sizing: border-box;
}   
```  
The `border-bottom` was creating an extra 2px of height after viewport-sizing the parents.
```

**Comment by thedtj** [comment]
Thanks. I missed the height 100%. That fixed everything up.
