### ISSUE TITLE
Possible bug in testing JS calculator

### ISSUE THREAD

**Issue by DamirTesnjak** [freeCodeCamp/testable-projects-fcc#460]
#### Issue Description

Possible bug in testing.
It gives out an error at 14th test, but I manually checked and my calculator works fine. After I pressed '=' and a operator (e.g. '+'), it starts correctly a new calculation based on the result of the previous evaluation.

#### Browser Information

* Browser Name, Version: Firefox
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Description

#### Your Code / Link to Your Pen

```
 link to my code:
 https://codepen.io/Pifko6/pen/qXLvQd?editors=0010
```

#### Screenshot

![issue](https://user-images.githubusercontent.com/36519405/42852287-e40b2420-8a2f-11e8-9cb6-545264ccd75b.PNG)

**Comment by tbushman** [comment]
The error, `str.slice is not a function` originates from your js file. The calculator works though, so at some point the variable, `str` may be null or undefined. Console log `str` before your slicing functions to see where you need to work in checks for `null` or `undefined` `str`
