### ISSUE TITLE
Survey Project - user story 14 bug

### ISSUE THREAD

**Issue by Tarmstrong95a** [freeCodeCamp/testable-projects-fcc#461]
#### Issue Description

complete the user story #14. Appears correct. Test displays it as incorrect :  "SyntaxError (DOM Exception 12): The string did not match the expected pattern"...

also, the given example survey form fails the same user story.

#### Browser Information

* Browser Name, Version: safari v.11
* Operating System: Mac OS high Sierra v10.13
* Mobile, Desktop, or Tablet: MacBook Pro

#### Your Code / Link to Your Pen

```
 ...
<div>
          <ul style="list-style: none;">
            <li><input value="4" name="check" type="checkbox" >Surveyes</li>
            <li><input value="5" name="check" type="checkbox" >Guns</li>
            <li><input value="6" name="check" type="checkbox" >Pazzaz</li>
            <li><input value="7" name="check" type="checkbox" >Moxy</li>
            <li><input value="8" name="check" type="checkbox" >Worms</li>
          </ul>
        </div>
...
 
 
```

#### Screenshot

![screen shot 2018-07-17 at 7 51 59 pm](https://user-images.githubusercontent.com/36495946/42853250-e692e816-89fa-11e8-859f-c12c6320c618.png)

**Comment by tbushman** [comment]
@Tarmstrong95a Could you please try adding a closing tag to each `<input>` or use the `/>` syntax, i.e.  
```  
<li><input value="4" name="check" type="checkbox" ></input>Surveyes</li>
```  
or  
```
<li><input value="4" name="check" type="checkbox" />Surveyes</li>
``` 
and see if that helps the tests pass? That's all I can think from looking at your code snippet...

**Comment by tbushman** [comment]
@Tarmstrong95a Please follow-up with a link to your project if you want the issue investigated further.

**Comment by tbushman** [comment]
@Tarmstrong95a I don't think that was the issue, but we would need more info. Please let us know here if you have any questions.
