### ISSUE TITLE
Random Quote Machine - unexplained tests results (alternating between 12/12 to 10/12)

### ISSUE THREAD

**Issue by Anja18** [freeCodeCamp/testable-projects-fcc#462]
#### Issue Description

The "Run Tests" button leads randomly (it seems) to either 12/12 passed or 11/12 or 10/12. Error message indicates a time issue while running tests. Not sure what this is due to or how to fix the issue.

#### Browser Information

* Browser Name, Version: Google Chrome, Version 67.0.3396.99 (Official Build) (64-bit)
* Operating System: MacOS High Sierra, Version 10.13.6
* Mobile, Desktop, or Tablet: MacBookAir

#### Your Code / Link to Your Pen

```
 https://codepen.io/Anja18/full/BPzOLq/
 
 
```

**Comment by tbushman** [comment]
@Anja18 Hello, please try this:  
```  
<a href={'https://twitter.com/intent/tweet?hashtags=quotes&text="'+encodeURIComponent(this.state.quote)+'" '+encodeURIComponent(this.state.author)} id='tweet-quote' target="_blank" class='btn btn-primary col-md-3'>Tweet me <i class='fa fa-twitter'></i></a>  
```  
In order to use strings in URLs, we need to encode the text to convert things like spaces and special characters to url-encoded characters.

**Comment by Anja18** [comment]
Hi @tbushman, thanks a lot for your quick message - the url was working fine already, I tried modifying but it doesn't solve the problem ... Thanks again though!

**Comment by tbushman** [comment]
@Anja18 The above code fixed the problem when I tested it. I'll keep this open.

**Comment by tchaffee** [comment]
@Anja18 I am looking at this now. The first thing I see is test 9 failing. It says "My quote machine should fetch the new quote's author when the #new-quote button is clicked and display it in the #author element."

And sure enough sometimes when I click your "Another Quote?" button it does not change the quote. So you need to fix that. It's from having only a few quotes. A random selection on such a small number of quotes is pretty likely to pick the same one twice. I'll leave it up to you how you want to fix that, but there is a way to get it to work without adding more quotes.

@tbushman Is there anything we need to fix in our tests wrt the URLs? Or is that a bug in @Anja18 's code that should be fixed.

**Comment by tbushman** [comment]
@tchaffee As far as I could tell, using `encodeURIComponent()` was the fix and the project passes tests consistently now. Closing.
