### ISSUE TITLE
Input Field ID Tag Not Detected

### ISSUE THREAD

**Issue by meills** [freeCodeCamp/testable-projects-fcc#463]
In my code, my input field for name has an ID tag "name" but it doesn't pass the fourth test which is . "Inside the form element, I am required to enter my name in a field with id="name"."

Browser Name: Chrome

Here is my code pen link.
 https://codepen.io/meils/pen/NzyGOG

**Comment by tbushman** [comment]
@meills Hello. We are adding a line to the user story for this test that may help you with this. Until then, here is some more info: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-required

**Comment by tbushman** [comment]
Closing due to #444
