### ISSUE TITLE
Product Landing Page - Media Query not recognized 

### ISSUE THREAD

**Issue by scotnewbury** [freeCodeCamp/testable-projects-fcc#464]
Product Landing Page

#### Issue Description

A product landing page will not pass the media inquiry test if the the query is placed in a CSS file that is linked into the HTML file. The browser does correctly display the query results.

If the code is moved to the HTML file the test will pass.

#### Browser Information

* Browser Name, Version: Version 67.0.3396.99 (Official Build) (64-bit)
* Operating System: Antergos (Arch Linux)
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
The following is in the CSS file (style.css) - DOES NOT PASS
#container {
	background-color: green;
}

@media (min-width: 600px) {
	#container {
		background-color: red;
	}
}

 

The following is placed in the HTML file - DOES PASS
<style>
#container {
	background-color: green;
}

@media (min-width: 600px) {
	#container {
		background-color: red;
	}
}
</style>

```

**Comment by tbushman** [comment]
@scotnewbury For linking relative paths, please run your project with a simple server like `live-server` because there have been similar other issues solved this way. Let me know if this doesn't help.

**Comment by scotnewbury** [comment]
I moved the project to my server and the test passed. This seems a bit odd and while it's a work around for the test not passing, it doesn't resolve the underlying issue. I would expect a relative link to work when running the project locally without a server as well.

**Comment by tbushman** [comment]
You can use a simple server like `python -m SimpleHTTPServer` for development. Sorry.

**Comment by scotnewbury** [comment]
No worries, I setup live-server without any issues and it tested fine there as well. It's just odd and unexpected behavior.

It's a good lessons learned, the need to have a local server setup for testing, I just wasn't expecting the need to hit quite so soon.

**Comment by tbushman** [comment]
:) Yeah, I've seen a lot of issues be resolved by running projects in that manner. I actually don't know why it is. :) One student was suggesting a tutorial for getting a development environment going and I think that's a great idea. 
Did this method help with your other issues / projects?

**Comment by scotnewbury** [comment]
Yes, using live-server did allow for all of the tests to pass.

I would second the tutorial suggestion especially given the fact that so many are now moving outside of CodePen. I know that I did as I don't suspect that I will be using CodePen once I move into the ranks of employed coders. :-)

**Comment by tbushman** [comment]
Sounds nice! :) Thanks!
