### ISSUE TITLE
Minute Difference in GDP Value Causes Test Case Failure

### ISSUE THREAD

**Issue by jrwmacintire** [freeCodeCamp/testable-projects-fcc#467]
#### Issue Description
I've nearly completed the D3 Bar Graph challenge, but I'm unable to get the height value test case to pass. Currently, the test case fails because it receives a value of '30.108', but it expects a value of '30.187'. I've tried a series of adjustments to my code, to no avail. How would you suggest I go about resolving such a minor difference?

* Browser Name, Version: Google Chrome Canary, v.69.0.3494.0
* Operating System: Windows 10
* Mobile, Desktop, or Tablet:  Desktop

Link to Codepen: https://codepen.io/jrwmacintire/pen/KeGKRQ?editors=1010

![bar-graph-error-d3](https://user-images.githubusercontent.com/5394416/42905167-0a8c2412-8a8c-11e8-8885-3bddbf3b06e2.png)

**Comment by tbushman** [comment]
@jrwmacintire Will have to keep looking into this. Sorry and thanks for your patience.

**Comment by jrwmacintire** [comment]
I was able to complete this challenge after I rewrote my code and adjusted my overall SVG layout area. The margins and axes weren't set up as well as I thought. It wound up being more simple than I thought - and probably not related to your test cases. In short, make sure 'you' understand SVG layout conventions.

**Comment by tchaffee** [comment]
@jrwmacintire Thanks for letting us know. I'm closing this since it looks like you are in good shape now.
