### ISSUE TITLE
[Technical Documentation Page] Test 4 passes without content

### ISSUE THREAD

**Issue by christophherr** [freeCodeCamp/testable-projects-fcc#47]
#### Issue Description

Working through the unit test in sequence, I only got test 1 & 2 to pass but test 4 shows as passing as well.
Not having read test 3, I added `<div>s` right after the `<section>s`.
It could be that it just came up because I don't work through all the user stories before testing but use the tests to find out the next user story... 
Maybe the test should explicitly check for `<header>` to pass or, in other words,  not pass without test 3 having passed?

#### Browser Information

* Browser Name, Version:  Chrome, 56.0.2924.87 (64-bit)
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Laptop

#### Your Code

```
I created a separate pen:  http://codepen.io/c-herr/pen/PWXQmE 
```

**Comment by no-stack-dub-sack** [comment]
@christophherr thanks! I've identified the problem and am making a PR, your separate pen was very helpful. I just added a couple other layers of checks, to be sure that the headers are there, that the headers have actual text, and that the sections have IDs before proceeding with the main check, Basically, the tests previously were recording a blank string as id name and inner text, so with nothing there comparing an empty string to an empty string passes the test. But checking that text and ids exist first prevents this. 

This is exactly the sort of thing that can only be uncovered through someone working through the projects so this is very helpful. Thanks!
