### ISSUE TITLE
RUN TESTS is not working

### ISSUE THREAD

**Issue by anaiulia24** [freeCodeCamp/testable-projects-fcc#470]
![screen shot 2018-07-20 at 11 32 12](https://user-images.githubusercontent.com/41470463/42995229-9894b62c-8c10-11e8-8636-d3d4a6b4a7dd.png)

#### Issue Description

When I run the test, I can't see anything on that window. I refreshed the page but nothing, so I can't see the failed or passed tests, nothing.

#### Browser Information

* Browser Name, Version: Chrome Version 67.0.3396.99
* Operating System: macOS High Sierra
* Mobile, Desktop, or Tablet: Desktop

```

#### Screenshot
<!-- Add a screenshot of your issue -->
![screen shot 2018-07-20 at 11 32 12](https://user-images.githubusercontent.com/41470463/42995466-4172a3ee-8c11-11e8-9735-ebdd39542084.png)

**Comment by tbushman** [comment]
@anaiulia24 This could be another of our recurring problems with CSS interference. I can't be sure without looking at the code, but if you have any styling applied directly to tag names, (`<h1>`, `<h2>`, ..., `<p>`, `<code>`), this will cause the test window to inherit those styles. In the future we'll have a better buffer between student projects and the test window. For now, please assign `className` or `id`, i.e. `class="exampleClass"` , to elements and style using `.exampleClass { /* css here*/  }`
