### ISSUE TITLE
Test not recognizing header and id in code

### ISSUE THREAD

**Issue by ethyl2** [freeCodeCamp/testable-projects-fcc#475]
#### Issue Description

My technical documentation page should pass the tests, but 2 are failing. Each of the 8 .main-section sections has the format that the tests should be checking: 
1. The first element within each .main-section should be a <header> element which contains text that describes the topic of that section.
2. Each <section> element with the class of "main-section" should also have an id that corresponds with the text of each <header> contained within it. Any spaces should be replaced with underscores.
My sections follow these requirements, but only 7/8 of the sections pass.
 

#### Browser Information

* Browser Name, Version: Chrome Version 63.0.3239.108 (Official Build) (64-bit)
* Operating System: ubuntu 16.04 LTS
* Mobile, Desktop, or Tablet: Desktop 

#### Your Code / Link to Your Pen

```
 https://codepen.io/ethyl2/pen/ejZWej
 
 
```

#### Screenshot

![screenshot from 2018-07-21 16-57-37](https://user-images.githubusercontent.com/6438167/43040697-caf8c0de-8d07-11e8-9ad9-001483c28315.png)
![screenshot from 2018-07-21 17-01-39](https://user-images.githubusercontent.com/6438167/43040699-d117d5cc-8d07-11e8-8533-df9fb30e4555.png)

**Comment by tbushman** [comment]
@ethyl2 I almost couldn't find this:  
Please change   
```  
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Basic_Concepts_of_Flexbox" target="_blank">flexbox<a>  
```  
to   
```  
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Basic_Concepts_of_Flexbox" target="_blank">flexbox</a>  
```  
(see closing </a> tag)
and that should fix the problem :)

**Comment by ethyl2** [comment]
Thank you! I was focused so much on my nav-links and elements associated with them, that the closing tag escaped my scrutiny. I really appreciate your help.
