### ISSUE TITLE
Responsive Web Design Projects - Build a Personal Portfolio Webpage

### ISSUE THREAD

**Issue by clnquacky** [freeCodeCamp/testable-projects-fcc#476]
Responsive Web Design Projects - Build a Personal Portfolio Webpage

I have created my project and run the tests. I have 11/12 passing. However, when I go to look at the errors I can not see the error. I click on Tests and the box pops up but no text is visible. I have tried closing out codepen, forking a new pen and copying the code back into the new pen 

#### Issue Description

I have completed the programming and am running the tests. The tests run (albeit slow) and shows 11/12 passed. When I open the test to see what the errors are - nothing shows in the box. 

#### Browser Information

* Browser Name, Version: Chrome 67.0.3396.99 (Official Build) (64-bit)
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
 https://codepen.io/clnquacky/pen/VBpaEX
 
```

#### Screenshot

![image](https://user-images.githubusercontent.com/18017142/43049245-6459040e-8dc2-11e8-8d4d-e41a060a8307.png)

**Comment by tbushman** [comment]
@clnquacky This is the same issue as #470 and I'm working on a fix. Will you have a look at the comments there about CSS selectors? Thank you!

**Comment by tchaffee** [comment]
Should be fixed when PR #490 is merged.

**Comment by tbushman** [comment]
Fixed in Chrome and Safari. Closing.
