### ISSUE TITLE
Test Suite is adding space at the top of the webpage in Personal Portfolio

### ISSUE THREAD

**Issue by jake-steele** [freeCodeCamp/testable-projects-fcc#48]
#### Issue Description

I am not quite sure at what point the issue occurred, but for some reason the "the height of the welcome section should be equal to the height of the viewport" test will not pass for me on the Personal Portfolio project. When I hide the navbar (visibility: none), I can see that there is space above the welcome section when there should not be (I had originally done nothing to change the positioning of this section when I first noticed the failure, though I did try translating the welcome section to pass the test to no avail). I believe this issue is being caused by the test suite, as I encountered it in at least one test before and it seemed to have sorted itself out. I cannot recall what fixed the issue last time.

#### Browser Information

* Browser Name, Version: Google Chrome, Version 56.0.2924.87 (64-bit)
* Operating System: Windows 10 Home, 64-bit
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

Error:
`AssertionError: The height of #welcome-section is not equal to the height of the viewport : expected 495 to equal 478
    at n.<anonymous> (https://gitcdn.link/cdn/freeCodeCamp/testable-projects-fcc/b9a6558063e5349870a4123cceeb72f27d6fd9b9/build/bundle.js:20104:36)
    at r (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:7852)
    at r.run (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:8853)
    at i.runTest (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:13553)
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:14192
    at r (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:13024)
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:13000
    at n (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:12791)
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:12855
    at i (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:1:559)`

Relevant HTML:
```
 <html>
  <link href="https://fonts.googleapis.com/css?family=Rubik" rel="stylesheet">
  <body>
    <nav id="navbar">
      <h1>Jake Steele</h1>
      <a href="#welcome-section">Top</a>
      <a href="#projects">Projects</a>
      <a href="#contact">Contact</a>
    </nav>
    <main>
      <div id="welcome-section">
        <h1 class="intro-text">Hi. My name is Jake Steele.</h1>
        <h3 class="intro-text">I dabble in web design.</h3>
      </div>
    </main>
  </body>
</html>
```

Relevant CSS:
```
@media (maxheight: 640) {
  font-size: 12px;
}

*, *:before, *:after {
  box-sizing: inherit;
}

html {
  box-sizing: border-box;
  font-family: 'Rubik', sans-serif;
  background-color: #3C657F;
}

break {
  flex-basis: 100%;
  width: 0px;
  height:0px;
  overflow: hidden;
}

a {
  text-decoration: none;
}

a:hover {
  text-decoration: underline;
}

nav {
  position: fixed;
  top: 0px;
  left: 0px;
  z-index: 1;
  display: flex;
  flex-direction: row;
  justify-content: flex-end;
  align-items: center;
  height: 10vh;
  width: 100vw;
  background-color: #60A2CC;
  border-bottom: solid #3A617A 1px;
  padding: 0vh 10vw;
}

nav > a {
  color: #FFF;
  line-height: 10vh;
  font-weight: 700;
  margin: 0vh 1vw 0vh 0vw;
}

nav > h1 {
  padding-right: 72vw;
}

#welcome-section {
  top: 0px;
  left: 0px;
  height: 100vh;
  width: 100vw;
  background-color: #78CAFF;
  text-align: center;
  border-radius: 10px;
}

.intro-text {
  position: relative;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}
```

If this is just an error with my code, I'm sorry for wasting your time and I'll close the issue! Thank you!

**Comment by no-stack-dub-sack** [comment]
@jake-steele can you post a link to your actual pen? That would be super helpful! Thanks!

**Comment by jake-steele** [comment]
@no-stack-dub-sack Sure thing! [Here](http://codepen.io/jake-steele/pen/RKeeNx) it is!

**Comment by no-stack-dub-sack** [comment]
@jake-steele Have you changed something? I'm seeing 11/11 tests passing beautifully! Nice looking portfolio by the way 😄

**Comment by jake-steele** [comment]
@no-stack-dub-sack Nothing has changed too much, I don't think... I just re-opened to double-check (I've been moving through the other challenges in the mean time) and it still only says 10/11 passed for me! Hmmm.... I was able to "cheese" the test suite in the past to pass the test, where if I set the height of the #welcome-section to something less than 100vh and scaled the viewport to certain sizes, it would pass... But I believe it fails both at my home and work computers. Both of the computers' monitors are 1920x1080... Is your monitor also 1920x1080? I can't think of much else it could be!

Thank you for the compliment! I'm pretty proud of the progress I've been making!

**Comment by Christian-Paul** [comment]
@jake-steele @no-stack-dub-sack 

Are each of you seeing a horizontal scrollbar? I believe that's the source of the issue.

**Comment by no-stack-dub-sack** [comment]
Hey @Christian-Paul! Long time no talk, and thanks for chiming in! Ummm, no I see no horizontal scroll in my version of chrome. 

@jake-steele  my monitor is 15.4-inch (1440 x 900)

**Comment by jake-steele** [comment]
@Christian-Paul Very nice catch! I **AM** seeing a horizontal scrollbar on my monitors, so that seems totally plausible!

All of the sections are set to "width: 100vw;", though, so I'm not quite sure why it's got a horizontal scroll bar? Unless it's a scroll bar to see what's hidden behind the vertical scroll bar. Is it typical that I should have to set width to <100vw total?

**Comment by Christian-Paul** [comment]
@jake-steele Thanks! It looks like you're right about what's happening; the horizontal scroll bar exists to show what's hidden behind the vertical scroll bar. I don't think it's typical to set the width to less than 100vw. In my experience, I usually allow the element width to be set automatically. However, you can set max-width: 100% in each element with width: 100vw and that should fix it. Alternatively, you can use width: 100% instead of width: 100vw, insofar as their ancestors don't overflow

**Comment by Christian-Paul** [comment]
Hi @no-stack-dub-sack. Yeah, it's been a while!

I found a fix for this issue. If we use `window.innerHeight` instead of `document.documentElement.clientHeight`, we'll have the true value of the viewport's height. 

As I said before, `document.documentElement.clientHeight` subtracts the height of the horizontal scrollbar, however, `window.innerHeight` doesn't do that, so it will work whether or not the user has a horizontal scrollbar.

I'll work on a PR for this and the other issues I was mentioned in tomorrow!

**Comment by jake-steele** [comment]
@Christian-Paul @no-stack-dub-sack In case anybody else runs into the same issue: setting width for all full-width objects to 100% instead of 100vw **removed the horizontal scroll bar from the bottom and allowed the tests to pass.** This should suffice for people who don't want (or didn't intend to have) a horizontal scroll bar but do want to pass the test for completion's sake. ;)

Thank you both for looking into this! Have a nice day!

**Comment by no-stack-dub-sack** [comment]
Sounds perfect! Thanks @Christian-Paul!
