### ISSUE TITLE
Product Landing Page video test

### ISSUE THREAD

**Issue by Cap88** [freeCodeCamp/testable-projects-fcc#480]
#### Issue Description

Hey guys,

The video test is not working for me while I have an iframe with the id="video" .

#### Browser Information

* Browser Name, Version: Firefox 61.0.1
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```    
<iframe id="video" width="100%" height="480" controls 
src="https://www.youtube.com/embed/x1bGPqBjtHM"></iframe>
 
```
<a href="https://codepen.io/Cap88/pen/Lrwvzx?editors=1100">https://codepen.io/Cap88/pen/Lrwvzx?editors=1100</a>

#### Screenshot

![afbeelding](https://user-images.githubusercontent.com/22274364/43159106-b3eb9674-8f81-11e8-89a4-c5b9eb234e83.png)

**Comment by tbushman** [comment]
@Cap88 This should have been fixed in a recent PR. Sorry.  
How you can get around it is by putting the `</iframe>` closing tag on the same line as the opening tag. Leaving this open.

**Comment by Cap88** [comment]
Thanks for the quick reply and get around :)

**Comment by superskiers** [comment]
It looks as though this is still happening with the <iframe>.
Below is my workaround:
(I just put a <video> tag with the id="video" after the <iframe>, and it worked).

  <iframe width="560" height="315" src="https://www.youtube.com/embed/j8M5MkuYV7M" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          <video id="video" src="https://www.youtube.com/embed/j8M5MkuYV7M"></video>
