### ISSUE TITLE
Product landing page automatic test bug

### ISSUE THREAD

**Issue by MilosLbr** [freeCodeCamp/testable-projects-fcc#481]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```I have this form inside a div:
 <form id="form" action="https://www.freecodecamp.com/email-submit"> 
                    <label for="email">Enter your e-mail here and recieve special discount cuppon for this program:</label>
                    <input type="email" name="email" id="email" required>

                    <input type="submit" id="submit">GET DISCOUNT</input>
                </form>
 
 and I get folowing errors:
Within the form, there is an <input> field with id="email" where I can enter an email address.
 Within the form, there is a submit <input> with corresponding id="submit".
```

**Comment by tbushman** [comment]
@MilosLbr Your code is correct so we'd need to look into why there are bugs, ideally with a link to the whole project when you get a chance. Thanks!

**Comment by MilosLbr** [comment]
Here is the link from CodePen :
https://codepen.io/miloslbr/pen/oMwXpL ,

i don't have pictures here, but you only need the markup.

Regards,
Miloš


[https://codepen.io/miloslbr/pen/oMwXpL/image/large.png]<https://codepen.io/miloslbr/pen/oMwXpL>

Landing page<https://codepen.io/miloslbr/pen/oMwXpL>
...
codepen.io


________________________________

**Comment by tbushman** [comment]
@MilosLbr Although the code is correct for both forms on the page, the duplicate `id`s create a problem for the tests. If you use two forms on one page, you must use unique `id`s for each, i.e `#email` must not appear twice.

**Comment by tchaffee** [comment]
@MilosLbr I am closing this since @tbushman explained the problem with your code you need to fix. If you still need support on this issue, leave a comment and we can re-open the issue and discuss.
