### ISSUE TITLE
Incorrect link for test suite on Survey Form (Responsive Web Design) project instructions

### ISSUE THREAD

**Issue by lelelew** [freeCodeCamp/testable-projects-fcc#485]
#### Issue Description

This page (https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-projects/build-a-survey-form) has the following issue:
> You can build your project by forking this CodePen pen. Or you can use this CDN link to run the tests in any environment you like: https://gitcdn.link/repo/freeCodeCamp/testable-projects-fcc/master/build/bundle.js

Results in a 404 on the javascript.

The working link from CodePen is: `https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js`

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 
 
```

**Comment by tbushman** [comment]
@lelelew Thanks for reporting this! It looks like it's fixed.
