### ISSUE TITLE
Treemap Diagram is failing test #6

### ISSUE THREAD

**Issue by Maarondesigns** [freeCodeCamp/testable-projects-fcc#488]
#### Issue Description
Failing Treemap Diagram Test "6. The area of each tile should correspond to the data-value amount: tiles with a larger data-value should have a bigger area."

"AssertionError: the relative data-value property does not match tile area: expected NaN to be at most NaN"

data-value attribute and rectangle area are both generated from the formatted json file using d3.hierarchy.

#### Browser Information

Browser Name, Version: Google Chrome, Version 67.0.3396.99 (Official Build) (64-bit)
Operating System: Windows 10, 64 bit
Mobile, Desktop, or Tablet: Asus Laptop

#### Your Code / Link to Your Pen
https://codepen.io/maarondesigns/pen/djzvgr
```
    var treemap = d3
      .treemap()
      .size([width, height])
      .padding(1)
      .round(true);

    var root = d3
      .hierarchy(data)
      .sum(d => d.value)
      .sort((a, b) => b.height - a.height || b.value - a.value);

    treemap(root);

     var tile = svg
      .selectAll("g")
      .data(root.leaves()) .....

 tile
      .append("rect")
      .attr("width", d => d.x1 - d.x0 + "px")
      .attr("height", d => d.y1 - d.y0 + "px")
      .attr("data-value", d => d.data.value)
 
```

**Comment by tbushman** [comment]
@Maarondesigns To resolve `NaN` I removed 'px' in 
``` 
 tile
    ...
    .attr("width", d => d.x1 - d.x0)
    .attr("height", d => d.y1 - d.y0)  
```   
And that yields a more informative error. Somewhere, there is a border or an offset creating slight misalignment.  
  
I'll keep this open because you were fine including `'px'` and we should filter that in the tests.

**Comment by garrickg** [comment]
I was failing the same test, and removed '.round(true)' and it was passing after that.

**Comment by tbushman** [comment]
@garrickg Thanks.   
Generally speaking, we can avoid this error by allowing `px` in position attributes in `utils > alignment-D3-support`.

**Comment by tbushman** [comment]
@tbushman Actually, you're mistaken because the tree-map isn't part of the alignment-D3-support utils. :P  
@garrickg Is correct here. :)
