### ISSUE TITLE
[Front End Libraries Projects - Markdown Previewer] - Tests don't pass, markdown works visually!

### ISSUE THREAD

**Issue by numoonchld** [freeCodeCamp/testable-projects-fcc#489]
#### Issue Description

The pen visually meets all the non-optional user stories mentioned in the [project requirements page](https://learn.freecodecamp.org/front-end-libraries/front-end-libraries-projects/build-a-markdown-previewer)

However, the tests suite doesn't recognise the default input text and the default markdown preview that is initialised when the page loads. 

Tried a fully jQuery approach using a variable to store the text and writing that to the `<textarea>`. Also tried an HTML approach (which is what the pen currently has).

#### Browser Information

* Browser Name, Version: Chrome 67.0.3396.99
* Operating System: macOS
* Mobile, Desktop, or Tablet: laptop

#### Your Code / Link to Your Pen

[See pen here]( https://codepen.io/numoonchld/pen/EpwYNO)

#### Screenshot

![screenshot_2018-07-27 fcc markdown previewer](https://user-images.githubusercontent.com/17598505/43289568-02a2cef4-9149-11e8-9752-fd0b0710bfb1.png)

**Comment by tbushman** [comment]
@numoonchld The error message says to use two examples of markdown syntax currently missing in your default markdown: `<code>` and `<blockquote>`  
Check out https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet  

...but it's not clear why the error on test#6... keeping this open.

**Comment by tchaffee** [comment]
@numoonchld We are working hard at fixing our backlog of issues and will get to this as soon as we can.

**Comment by ValeraS** [comment]
@numoonchld until the test is fixed, you can pass the blockquote test by removing spaces before the '>' symbol in the default markdown.

**Comment by numoonchld** [comment]
Isn’t that cheating/hacking the test to pass it?

**Comment by numoonchld** [comment]
The test suite works for all the non-optional user stories in my codepen without any white space gymnastics and hacking.

Thanks - much appreciated.
