### ISSUE TITLE
Project Landing Page project - Test suite doesn't recognize my nav-link anchors

### ISSUE THREAD

**Issue by candlefish** [freeCodeCamp/testable-projects-fcc#492]
#### Issue Description

I was frustrated with trying to get my nav-links to bring the selected section's anchor tag up into the correct position when the page has a fixed header. The section ends up at the top of the screen, underneath the header. I searched online and found a [clever solution](https://www.caktusgroup.com/blog/2017/10/23/css-tip-fixed-headers-and-section-anchors/).

It works like a charm, but unfortunately it doesn't pass the unit tests. I just want to be sure I'll still get credit for completing the project even though the testing won't give me credit for the way I have the anchor tags set up.

```
<div class="anchor">
  <a name="about-target"> </a>
  <h2>Our Story</h2>
</div>
```

I am targeting the `<a>` tag using the `name` property rather than using an `id` on the `h2` tag. Works perfectly, but doesn't pass unit tests Content #&#8203;5 and Layout #&#8203;1.

And, on a totally unrelated note ... why is it so hard to escape hashtags in Markdown!?

#### Browser Information

* Browser Name, Version: Chrome 67.0
* Operating System: MacOS 10.13.5
* Mobile, Desktop, or Tablet: 2016 MacBook Pro 15"

#### Your Code / Link to Your Pen

```
 https://codepen.io/candlefish/pen/2e17fb9e94ea974282c310113eba4321/?editors=1100
 
```

**Comment by tbushman** [comment]
@candlefish Are you ok with using an `id` on your `<a>` anchors? That will pass the tests. Regarding escaping: I don't think you need to with hashtags because there's no space between the `#` and the String, no?

**Comment by candlefish** [comment]
I don't know how I missed that. I usually use the `id` attribute for anchoring rather than the `name` one, and I just overlooked that. The other issue is that I had the header fixed to the top instead of the navbar. It was pretty easy to fix that since I was using CSS grid. Just updated the grid-template-areas and -- voila! -- it's working. So now I'm passing all tests. Thank you for your help!
