### ISSUE TITLE
Bug in Certificate Project D3 Bar Chart 

### ISSUE THREAD

**Issue by frank-rui** [freeCodeCamp/testable-projects-fcc#493]
#### Issue Description

The D3 Bar Chart example project [at codepen](https://codepen.io/freeCodeCamp/pen/GrZVaM) has an bug that the x-axis representing the data.date is wrong. As the date and x-axis tick is not aligned, and inconsistent throughout the x-axis. This should violate the 
>"User Story #10: The data-date attribute and its corresponding bar element should align with the corresponding value on the x-axis."

The code using a d3 linear scale in a range from smallest year to largest year, i.e. line 57-63
```js
 var yearsDigits = years.map(function(item) {
    return item.substring(0, 4);
  });

var xScale = d3.scaleLinear()
    .domain([d3.min(yearsDigits), d3.max(yearsDigits)])
    .range([0, width]);
```
For example, the last bar, 2015-Q3 ends exactly at 2015 tick,
![image](https://user-images.githubusercontent.com/27864196/43403646-2c4a1120-9448-11e8-8979-db424f6eb2e0.png)

1950-Q1 column is after 1950 x-axis tick, 1955-Q1 is at the middle of 1955 tick, 1960-Q1 is right after 1960 tick, as shown below,
![image](https://user-images.githubusercontent.com/27864196/43403868-cd5b98fe-9448-11e8-8831-4686817566ae.png)
![image](https://user-images.githubusercontent.com/27864196/43403884-d5476cd2-9448-11e8-982d-758a4e65ccea.png)
![image](https://user-images.githubusercontent.com/27864196/43403908-e25e20b4-9448-11e8-8d2e-19469e78542e.png)

**Comment by tbushman** [comment]
@frank-rui The misalignment on the bar chart is unfortunately a known issue. For this reason, the bar chart tests allow a range of alignment +/- 11px until we can replace the Codepen. Once we get that replaced, we'll be able to update the tests.

**Comment by tchaffee** [comment]
@tbushman Do we already have another issue tracking this problem? If so, can we close this one?

**Comment by tbushman** [comment]
@tchaffee There was an issue on freeCodeCamp main repo, but it was closed because it wasn't related to the repo itself. We still need to replace the fCC bar chart example with an aligned example. The other chart issues are when `<rect>` elements either have `0` width/height or extend beyond the axis. I added help wanted to one because I couldn't find why.

**Comment by tchaffee** [comment]
Ok, let's leave this open to track the issue. Thanks.

**Comment by frank-rui** [comment]
To campers: 

Using `Band Scales` to draw bar charts could avoid this issue completely.

https://github.com/d3/d3-scale#scaleBand
