### ISSUE TITLE
Within the form, there is an <input> field with id="email" and id="submit"

### ISSUE THREAD

**Issue by FredAcker** [freeCodeCamp/testable-projects-fcc#496]
#### Issue Description

I've switched it around several ways and can not get the id="email" and id="submit" for the form on the form on the product landing page. I'm pretty certain I'm doing it correctly, but can't get it to pass. 

#### Browser Information

Firefox and Google Chrome (all up to date)
Windows 7 and Ubuntu
Desktop

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 https://codepen.io/codehobo/pen/KBybdL

<form action="https://www.freecodecamp.com/email-submit" id="form">
<input id="email" type="email" name="email" placeholder="Enter Your Email" required>
<button id="submit">Submit</button>
 </form>
 
 
```

#### Screenshot

![errors](https://user-images.githubusercontent.com/32986741/43422080-45d37bf2-940e-11e8-8d31-d0b6aa829166.png)

**Comment by tbushman** [comment]
@FredAcker Hello, this is the same as #481 in which case two `<form>`s are present on the page. That is fine, but give one of the forms and its inputs different `id`s and that will fix the first error. The second error after you do that will be about they type of element you use for the `submit` button. In this case, the test calls for an `input[type="submit"]` button.

**Comment by tchaffee** [comment]
@FredAcker I'm assuming you can get this to work with the extra info @tbushman gave you so I'm closing this issue. If you are still having problems please leave a comment and we can re-open the issue.
