### ISSUE TITLE
Tests completed issue

### ISSUE THREAD

**Issue by KyranSAFC** [freeCodeCamp/testable-projects-fcc#498]
Keeps saying 7/16 tests completed even though im sure i have a minimum of 5 classes etc.

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 https://codepen.io/KyranSAFC/pen/JBrvJO
 
 
```

**Comment by tbushman** [comment]
@KyranSAFC You have since passed all the tests, so I am closing this. Notify me if your browser's tests still do not pass.
