### ISSUE TITLE
In local environment recognizing flex property and media query in product landing page project.

### ISSUE THREAD

**Issue by miguelandresff** [freeCodeCamp/testable-projects-fcc#502]
#### Issue Description

In the project product landing page when i run the test locally in my machine, the test 2(media query) and 3(display:flex ) in the layout section do not past. but the test do not fail when i put the code in Code Pen.  
![screenshot from 2018-08-02 08-32-37](https://user-images.githubusercontent.com/22615906/43583827-a8e513b4-962e-11e8-8af5-caa8510b158c.png)
![screenshot from 2018-08-02 08-32-26](https://user-images.githubusercontent.com/22615906/43583836-ae24439a-962e-11e8-942f-7cff55c990ca.png)

#### Browser Information

* Browser Name, Version: Chrome Version 68.0.3440.75 (Official Build) (64-bit)
* Operating System: Ubuntu 18.01
* Mobile, Desktop, or Tablet:  Laptop

#### Your Code / Link to Your Pen

```
Code pen link: https://codepen.io/miguelandresff/full/ajGBjJ/ 
```

**Comment by tbushman** [comment]
For tests of media queries and css generally, you'll need to run your local project through `localhost` . 
More info here https://developer.mozilla.org/en-US/docs/Learn/Common_questions/set_up_a_local_testing_server

**Comment by miguelandresff** [comment]
It works, thanks!!!!
