### ISSUE TITLE
Can't pass yet filling requirement.

### ISSUE THREAD

**Issue by Juwdohr** [freeCodeCamp/testable-projects-fcc#503]
#### Issue Description

Running tests on portfolio
have a link that has an id of "profile-link"
Keeps returning to false.

#### Browser Information

* Browser Name, Version: Chrome latest
* Operating System: Win10
* Mobile, Desktop, or Table: Desktop

#### Your Code / Link to Your Pen

```
 
 https://codepen.io/juwdohr/pen/QBMewL
 
```

#### Screenshot

![image](https://user-images.githubusercontent.com/16342673/43602779-2f995ff4-964e-11e8-9951-f9bd25366165.png)

**Comment by tbushman** [comment]
@Juwdohr The error mentions a `target` attribute. More info here https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a

**Comment by tchaffee** [comment]
@Juwdohr You should be able to get the tests to pass with the extra info @tbushman gave you so I am closing this. If you are still having problems, please leave a comment and we can re-open the issue.
