### ISSUE TITLE
Product Landing Page Media Query and Flex Not working For Own Environment Testing

### ISSUE THREAD

**Issue by niccololampa** [freeCodeCamp/testable-projects-fcc#506]
#### Issue Description

Testing via my own environment, I can't make the tester work for the media query and css flexbox to work.  No matter how I modify my code,  I can't satisfy the requirement. 

But when I copied and pasted the same html and css code to codepen and used the tester online  and I was able to pass the mentioned requirements. 

I even simplified the code just to have a both flexbox and media query, but the tester won't still work no matter what I do. 

Thanks

#### Browser Information

* Browser Name, Version:  Chrome
* Operating System:  Windows 10
* Mobile, Desktop, or Tablet:  Desktop

 
 
 
```

#### Screenshot
<!-- Add a screenshot of your issue -->

Own Environment:

![image](https://user-images.githubusercontent.com/37615906/43673328-8db2cd9a-97f3-11e8-8498-0437ddf14640.png)

Code Pen:
![image](https://user-images.githubusercontent.com/37615906/43673338-af5903ba-97f3-11e8-82c1-b706b491ea21.png)

**Comment by tbushman** [comment]
@niccololampa Please have a look at issue #502 with the link to MDN documentation on local file service. The media query and flexbox tests require http/https. You can use http://localhost, http://127.0.0.1 run on `live-server` or similar.

**Comment by niccololampa** [comment]
@tbushman Thank you very much! Missed that.
