### ISSUE TITLE
Image responsiveness not recognised by the testing app

### ISSUE THREAD

**Issue by Marie-Carrere** [freeCodeCamp/testable-projects-fcc#507]
Hello !

I'm using `display: block;` in my CSS. The picture is 100% wide and it's responsive, but I can't pass the test for the user stories n°8 :

User Story #8: The img element should responsively resize, relative to the width of its parent element, without exceeding its original size.

Unit Test Result : 
Layout
1. The <img> element should responsively resize, relative to the width of its parent element, without exceeding its original size. AssertionError: Use the "display" style property with a value of "block" forresponsive images.: expected 'inline' to equal 'block'

https://codepen.io/Marie_cm/full/YjaVLj/
 
Thanks for your help 😀

**Comment by tbushman** [comment]
@Marie-Carrere You have the right idea, and display: block was added to `#img` but you've given the `<img>` element the `id="image"` so add it to   
```  
#image {
  display:block;
}
```  
and that will do it.

**Comment by Marie-Carrere** [comment]
Great ! Thanks for your help @tbushman
