### ISSUE TITLE
[Drum Machine] Test 7 - Description typo?

### ISSUE THREAD

**Issue by christophherr** [freeCodeCamp/testable-projects-fcc#51]
#### Issue Description

The description of the test says
 
> the inner text of the .display element

The period in front of display makes it look like it is a class, but display is an id.
(And the test expects it to be an id, too)
I guess the period could just be removed.

**Comment by no-stack-dub-sack** [comment]
I think it was probably meant to be a `#` instead of a `.` like you said... this could be fixed pretty easily. You want it or should I?

**Comment by christophherr** [comment]
@no-stack-dub-sack I can do it later today.

**Comment by no-stack-dub-sack** [comment]
@christophherr Actually, don't worry about it - I'm making the fix for the other issue you opened, so might as well just fix this as only one keystroke

**Comment by christophherr** [comment]
@no-stack-dub-sack Thank you!
