### ISSUE TITLE
Issue with Project Checker - Tech Documentation Page 

### ISSUE THREAD

**Issue by jjharrington90** [freeCodeCamp/testable-projects-fcc#511]
![project_error](https://user-images.githubusercontent.com/34978626/43824882-39380c8c-9ac1-11e8-990c-ba9d33ffa08c.png)

#### Issue Description

The last user story requirement which is failing to pass every time I run the test is because it is expecting a value of -524px or less for the left property of the nav bar. When I set it to that value, it passes but of course, the nav bar is no longer visible on the page. Is this value correct? Am I doing something wrong with the placement of my nav bar? I placed it on the left side of the screen in a fixed position so that it's still visible when the user scrolls the page.

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
<p data-height="265" data-theme-id="0" data-slug-hash="EpRpQw" data-default-tab="html,result" data-user="jjharrington90" data-pen-title="Technical Documentation Page" class="codepen">See the Pen <a href="https://codepen.io/jjharrington90/pen/EpRpQw/">Technical Documentation Page</a> by Jovani J. Harrington (<a href="https://codepen.io/jjharrington90">@jjharrington90</a>) on <a href="https://codepen.io">CodePen</a>.</p>
<script async src="https://static.codepen.io/assets/embed/ei.js"></script>
 
 
```

**Comment by jjharrington90** [comment]
Using Google Chrome Version 68.0.3440.84
OS X 10.11.6 on MacBook Pro

**Comment by tbushman** [comment]
@jjharrington90 If you change the `#navbar` `position: relative;` to `position: absolute;` , the test will pass. It's unclear why at the moment. Sorry!

**Comment by tbushman** [comment]
Could be related to #433
