### ISSUE TITLE
Change our custom mocha test report to use an ordered list.

### ISSUE THREAD

**Issue by tchaffee** [freeCodeCamp/testable-projects-fcc#512]
The mocha test reporter uses an unordered list and if we change that to an ordered list we can remove the manual line numbering from every test suite.

**Comment by tchaffee** [comment]
@ValeraS Thank you for your help, and yes you can take this one. I'll leave it assigned to me because we can only assign issues to the core team members. This way I'll still be responsible for making sure it gets done. But the coding and PR are all yours.

**Comment by ValeraS** [comment]
@tchaffee Is it okay if the signs will stand after the numbers?

![image](https://user-images.githubusercontent.com/10867286/44566869-8be8bd00-a778-11e8-91e2-5ee2f922a2c5.png)
