### ISSUE TITLE
Pomodoro Clock Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.

### ISSUE THREAD

**Issue by glushkov89** [freeCodeCamp/testable-projects-fcc#515]
Hi. I don`t know if it is my 'awesome' code or really a bug, but i`m running out of hair in my armpits.
The app seems to work just as the example. The thing is I don`t know what really is tested, and error messages are not very helpful. Any suggestions will be greatly appreciated.

#### Issue Description
1) I get multiple error messages:
Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.[33]</</r.prototype.resetTimeout/this.timer<@https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:7197

2) AssertionError: Audio element was not stopped when reset was clicked.: expected false to be truer@https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:132:475

#### Browser Information

* Browser Name, Version: Firefox,Chrome
* Operating System: Win 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen
https://glushkov89.github.io/FCC-Pomodoro-Clock/
https://github.com/glushkov89/FCC-Pomodoro-Clock

**Comment by tchaffee** [comment]
@glushkov89 Thank you for reporting this. We have a backlog of issues at the moment so hopefully we can get to this in the next few weeks as we start to catch up. In the meantime, please don't let that stop you from continuing with the curriculum.

**Comment by ValeraS** [comment]
@glushkov89 User story(`#8`) says  value in the `.time-left` field should always be displayed in `mm:ss` format, but if the time-left is less then 10 min you display it in the `m:ss` format.

Also your timer does not stop when`time-left` is `00:00`

**Comment by glushkov89** [comment]
Many thanks mm:ss format was the case.
