### ISSUE TITLE
i have my placeholder but it appears that i have a correction what's this??

### ISSUE THREAD

**Issue by GemzBond** [freeCodeCamp/testable-projects-fcc#519]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 
 
```

#### Screenshot

![image](https://user-images.githubusercontent.com/38213237/44029304-5e503900-9f2f-11e8-906b-748923e6a381.png)

**Comment by tbushman** [comment]
@GemzBond Glancing at your code, I notice that your label texts fall outside your `<label>` elements. The label, `Status: `, for example, should be wrapped in a `<label>` thusly:   
`<label for="Married">Status: </label>`  
I see you have the correct attributes on your elements, so I'm wondering if these labels are tripping up the tests. Please try it out or share a link to your project we can debug.

**Comment by ValeraS** [comment]
@GemzBond Th age input tag has 2 ids, but only the first one is used by the browser. Because of this, the test does not find a field with an id equal to `number` and fails.

**Comment by tbushman** [comment]
@ValeraS Thanks for catching that!
