### ISSUE TITLE
Markdown Previewer Will Not Pass Test # 6

### ISSUE THREAD

**Issue by petercr** [freeCodeCamp/testable-projects-fcc#523]
#### Issue Description
Test 6 returns an Assertion Error saying
> `#preview` does not conatin the H1 element represented by the markdown in the `#editor`
If you look at the screenshots you can see that `#preview` **does** contain and `H1` element from the markdown

#### Browser Information
I am running a local version of `create-react-app` on both Ubuntu and Windows 10 Insider's Build. I receive the same issue either way. I'm not sure if this is happening because I use `componentWillMount() {}` to trigger the parsing of the markdown. But it is fairly standard practice for React. 

* Browser Name, Version: Google Chrome Version 68.0.3440.106 (Official Build) (64-bit) 
* Operating System: Ubuntu 18.04 LTS _Bionic Beaver_ :robot: :bear: 
* Mobile, Desktop, or Tablet: Desktop 

#### Your Code / Link to Your Pen

```javascript
import React, { Component } from "react";
import "./App.css";
import marked from "marked";

class App extends Component {
  constructor(props) {
    super(props);

    // the pre-written markdown to load
    this.mainHtml = 
      `# Try this 
## Cool Editor 
A project from [Free Code Camp](https://learn.freecodecamp.org) 
You can use code in-line \`console.log("")\` 
Or Code Blocks 
* An image or something 
**Woah bold text** 
> A deep quote 

![React Logo](https://cdn.freebiesupply.com/logos/large/2x/react-1-logo-png-transparent.png) 
\`\`\` 
const done = true; 
\`\`\` 
      `

    this.state = {
      editorText: this.mainHtml,
      previewText: null
    };
    this.updateEditor = this.updateEditor.bind(this);
  }

  updateEditor() {
    // get MD text from #editor and update editorText
    const _text_ = document.querySelector("#editor").value;
    this.setState({ editorText: _text_ });

    // parse the markdown and update previewText
    const markdown = marked(_text_);
    this.setState({ previewText: markdown, mainHtml: markdown });
    // eslint-disable-next-line
    console.dir(markdown);
  }

  componentDidMount() {
    marked.setOptions({
      breaks: true,
    });
    // call updateEditor() to parse editor markdown
    this.updateEditor();

  }

  render() {
    return (
      <div className="App">
        <div className="editor">
          <h1 className="top">Enter Markdown Here</h1>
          <textarea name="" id="editor" onInput={this.updateEditor}>
            {this.state.editorText}
          </textarea>
        </div>
        <div className="preview">
          <h1 className="top">See Preview Here</h1>
          <div
            id="preview"
            dangerouslySetInnerHTML={{ __html: this.state.previewText }}
          />
        </div>
      </div>
    );
  }
}

export default App;
```
[Here is a link to the GitHub repo](https://github.com/petercr/markdown-preview)

#### Screenshots
![chrome dev tools](https://user-images.githubusercontent.com/26460352/44056762-2e88cb00-9f17-11e8-9433-972355f377f1.png)
![mocha tests](https://user-images.githubusercontent.com/26460352/44056764-31053620-9f17-11e8-8ec7-c26bdcc00d0a.png)
![vs code](https://user-images.githubusercontent.com/26460352/44056767-33e29ad6-9f17-11e8-856d-9822d3c3ad8e.png)

**Comment by tchaffee** [comment]
@petercr Thanks for reporting this.

You got a space at the end of `# Try this ` at your code here https://github.com/petercr/markdown-preview/blob/master/src/App.js#L11

If you remove the space, the test should pass. The text in the Editor needs to *exactly* match the text in the preview. The markdown conversion looks like it strips the trailing space. Can you please close this issue if it fixes your problem?

**Comment by petercr** [comment]
Thanks so much @tchaffee :+1: :clap: Yes after removing the empty spaces following both the `h1` and `h2` in the markdown template string. Also I had to move the final backtick up a line. 

**But thank you so much** I will close the issue now :+1: :shipit:
