### ISSUE TITLE
Survey Form error

### ISSUE THREAD

**Issue by Parag-Rana** [freeCodeCamp/testable-projects-fcc#524]
<script src="https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js"></script>

<body>
  <div id="main">
  
    <h1 id="title">Demo Survey Form</h1>
  
      <p id="description">A Simple Survey Form</p>

  
  <form action="" id="survey-form">
    
      <label for="name" id="name-label"> Name: </label> <input autofocus="" type="text" name="name" class="textarea" placeholder="Enter Name" required="required" id="name">
    <br>
    <br>
    
     <label for="email" id="email-label">Email: </label> <input type="email" class="textarea" id="email" required pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,3}$"
                    placeholder="Enter Email">
   <br>
    <br>
    <div id="number">
      <label for="number" id="number-label">Number</label><input type="number" class="textarea" id="number-label"   min="10" max="13"required="required" placeholder="Number">
    </div>
    <br>
    <div id="dropdown">
      Select SuperHero: <select>
      <option value="Batman">Batman</option>
      <option value="IronMan">IronMan</option>
      <option value="Superman">Superman</option>
      <option value="Thor">Thor</option>
      <option value="Wonder Woman">Wonder Woman</option>
      </select>
      <br>
      <br>
    </div>
    <div id="radio">
      Select One:
      <input type="radio" name="hero" value="Batman" checked> Batman
      <input type="radio" name="hero" value="IronMan"> Iron Man
      <input type="radio" name="hero" value="Superman"> Superman
    </div>
    <div id="checkbox">
      Favourite Team: <input type="checkbox" name="hero" value="Avengers" checked> Avengers 
      <br>
      <input type="checkbox" name="hero" value="Justice League"> Justice League
      <br>
      <input type="checkbox" name="hero" value="X-Men"> X-Men
      <br>
    </div>
    <br>
    <br>
    <div id="textarea">
    Enter Your Comments:
      <textarea name="Comment" id="textaea" cols="30" rows="10" placeholder="Comments"> </textarea>
    <br>
    <br>
    
    <button id="submit">Submit</button>
  </div>
    </form>
</body>

**Comment by tchaffee** [comment]
@Parag-Rana Thank you for reporting this. Can you please give us a link to your CodePen so we can reproduce the error?

**Comment by Parag-Rana** [comment]
https://codepen.io/raoneparag/pen/WKWMzW

**Comment by tbushman** [comment]
@Parag-Rana I found the issue. There are duplicate `id="number"`s. Sorry for the delay. I changed the number input section so that only the `input[type="number"]` has `id="number"` (not the label or the wrapper `<div>`) and the tests passed:  
```  
<div id="numbersection">
      <label for="number" id="number-label">Number</label><input type="number" class="textarea" id="number" name="number" min="10" max="13" required="" placeholder="Enter your Number">
 </div>  
```

**Comment by tbushman** [comment]
@Parag-Rana Please let us know if you have additional questions.
