### ISSUE TITLE
SVG not accepted as img?

### ISSUE THREAD

**Issue by cnoelle23** [freeCodeCamp/testable-projects-fcc#525]
#### Issue Description

I get an error when running the tests saying the '#header-img' isn't an image element, but rather an SVG. I would expect SVGs to be accepted, particularly because it's recommended to use a company logo here.

#### Browser Information

* Browser Name, Version: Version 68.0.3440.106 (Official Build) (64-bit)
* Operating System: MacOS High Sierra Version 10.13.6
* Mobile, Desktop, or Tablet: Laptop

#### Your Code / Link to Your Pen

```
 https://codepen.io/cnoelle23/pen/oyLwZQ
 
 
```

#### Screenshot

<img width="1025" alt="screen shot 2018-08-15 at 20 53 31" src="https://user-images.githubusercontent.com/25202673/44151885-1449268c-a0ce-11e8-9cd6-d6e9e93851ac.png">

**Comment by web2033** [comment]
This is self-closing tag (not need in `</img>`) and `src` is required

```html
<img src="/media/examples/frog.svg" alt="Frog"/>
```

**Comment by web2033** [comment]
You can use inline SVG and code will look something like
```svg
<svg viewBox="0 0 300 100" xmlns="http://www.w3.org/2000/svg">
  <circle cx="50" cy="50" r="40" stroke="red" fill="grey" />
  <circle cx="150" cy="50" r="4" stroke="red" fill="grey" />

  <svg viewBox="0 0 10 10" x="200" width="100">
    <circle cx="5" cy="5" r="4" stroke="red" fill="grey" />
  </svg>
</svg>
```
Simply swapping `img` tag to `svg` doesn't work. But svg as an image source is ok.

**Comment by cnoelle23** [comment]
Thank you!
