### ISSUE TITLE
D3 Bar Chart Axis-data alignment tests

### ISSUE THREAD

**Issue by glushkov89** [freeCodeCamp/testable-projects-fcc#528]
#### Issue Description
Hello. Cant pass #Content tests 10 and 11. There seems to be a mistake in the example pen IMO (and thus maybe in tests). I think it is logical that ticks on x-axis represent the start of the corresponding year. But the last 3 arrays of provided json.data are for Q123 of 2015 and technically corresponding bars should be positioned to the right of 2015-year-tick. I`ve looked in the example pen code (sorry), and the problem seems to be that the json.data is first parsed into array of years only. So the domain for x-axis scale is from '1947' to '2015' and not from '1947-01-01' to '2015-07-01'.
Y-axis alignment test (11) is not passing either - i don`t know what is the problem-it looks the same as the example one.

#### Browser Information
desktop Firefox Dev. Ed., Chrome
Win 10
#### Your Code / Link to Your Pen
https://github.com/glushkov89/FCC-Bar-Chart

#### Screenshot
Example pen:
[![Inked_FCC_bar_chart_pen_LI.jpg](https://s15.postimg.cc/o6jk0govf/Inked_FCC_bar_chart_pen_LI.jpg)](https://postimg.cc/image/chfkchxwn/)

My chart:
[![Inked_FCC_bar_chart_pen_LI.jpg](https://s15.postimg.cc/6ghvfiqqz/Inked_FCC_bar_chart_pen_LI.jpg)](https://postimg.cc/image/4bxiefp47/)

JSON:
[![json_array.jpg](https://s15.postimg.cc/kbg5xl0h7/json_array.jpg)](https://postimg.cc/image/pa3oc449z/)

**Comment by tbushman** [comment]
@glushkov89 The problem was in adding padding when defining `x` and `y` attributes for the `<rect>` elements. I'm using the margin convention discussed at https://gist.github.com/mbostock/3019563. When I make the following adjustments to your project, it passes alignment tests.  
```  
dh = 500 - pd.top - pd.bottom, //height  
dw = (json.data.length * bw) - pd.left - pd.right, //width
```  
```  
const svg = d3  
...  
.attr("width", dw + pd.left + pd.right)
.attr("height", dh + pd.top + pd.bottom)  
```  
```  
.attr("x", (d) => x(parseTime(d[0])))
.attr("y", (d) => dh - y(d[1]) )  
```

**Comment by tbushman** [comment]
Sorry, forgot to mention another necessary change:  
```  
const svg = d3
...
.append('g')
.attr('transform', 'translate('+pd.left+','+pd.top+')')  
```  
I could be missing something. Main thing is to establish the width and height with padding early on and then avoid using padding when establishing attributes.

**Comment by tbushman** [comment]
Our option for improving the tests is to use `getBoundingClientRect()` to compare tick and shape position! TODO.

**Comment by glushkov89** [comment]
Everything works now. Many thanks.

**Comment by tbushman** [comment]
Reopen to associate with new PR
