### ISSUE TITLE
Product landing page #1 layout test bug

### ISSUE THREAD

**Issue by iTechGaming** [freeCodeCamp/testable-projects-fcc#529]
Hey!

#### Issue Description

I was testing my entires and it said : ''1. The navbar should always be at the top of the viewport.''.
But I was able to pass that by putting a position: fixed; on my logo and not the nav. Sorry I don't know how to do it but I'll look into it. At least I found a bug :D!

#### Browser Information

* Browser Name, Version: Mozilla Firefox (latest version I believe)
* Operating System: Win7
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen
https://codepen.io/Tech_CA_Bro/pen/NBZBPe

#### Screenshot
https://postimg.cc/image/q7li32bt9/

Thanks!
I'll have to finish my project now :D!

**Comment by tbushman** [comment]
@iTechGaming OK thanks!

**Comment by tbushman** [comment]
Also #704

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
