### ISSUE TITLE
Tribute page error

### ISSUE THREAD

**Issue by FloPtitos** [freeCodeCamp/testable-projects-fcc#530]
#### Issue Description
I have a problem with the resize of the image.

#### Browser Information
Macbook pro Late 2016
High Sierra
Using CodePen with Chrome

#### Your Code / Link to Your Pen
https://codepen.io/floptitos/full/vaqjWo

#### Screenshot

<img width="396" alt="capture d ecran 2018-08-16 a 21 36 12" src="https://user-images.githubusercontent.com/32060470/44231054-2a838580-a19d-11e8-8d06-2cffd0da842a.png">
<img width="645" alt="capture d ecran 2018-08-16 a 21 36 23" src="https://user-images.githubusercontent.com/32060470/44231063-2f483980-a19d-11e8-9f0a-b78fc3277143.png">

**Comment by tbushman** [comment]
@FloPtitos It looks like you fixed it? Write back if you have further questions.

**Comment by FloPtitos** [comment]
I didn’t fix it, when I test my tribute page, the test about resizing the image failed and I did’t really understand why ?

**Comment by tbushman** [comment]
@FloPtitos I'm sorry that I can't reproduce this issue... Your tests all pass. Let's see if someone else can reproduce this error.

**Comment by tchaffee** [comment]
@FloPtitos I cannot reproduce this either. All the tests pass for me. Can you make sure your browser is fully maximized when you run the tests? If it's still failing please let us know and we will try to find someone who has the same setup as you and can reproduce the error.

**Comment by FloPtitos** [comment]
Thank you for you response, the problem has been fixed yet. I think it’s because i used safari, I don’t know why. 

Florentino Neves

**Comment by tchaffee** [comment]
@FloPtitos we don't support Safari yet. Can you try with Chrome and let us know if the tests pass? Thanks for your help.

**Comment by FloPtitos** [comment]
I have tried and all the tests passed ! Thanks !
