### ISSUE TITLE
Markdown Previewer and marked.js

### ISSUE THREAD

**Issue by web2033** [freeCodeCamp/testable-projects-fcc#531]
I use marked.js as a dependency in `package.json`

```js
{
  "name": "markdown-previewer",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "marked": "^0.4.0",
    "react": "^16.4.2",
    "react-dom": "^16.4.2",
    "react-scripts": "1.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}
```

and import it into my component

```jsx
import React from "react";
import marked from "marked";

const Preview = props => {
  const result = { __html: marked(props.value) };

  return <div id="preview" dangerouslySetInnerHTML={result} />;
};

export default Preview;
```

The app works but in order to pass tests 3-6 I need to additionally include `marked` file as a `script` tag

**Comment by tbushman** [comment]
@petercr What do you think? I thought about what you said about the test suite not having access to the marked library imported in an exogenous component, but the tests never use marked to make assertions. The tests only check what's rendered.

**Comment by petercr** [comment]
Thanks for thinking of me @tbushman :smile: 
Yes this does appear to be the same issue which I had with the testing scripts not having access to the **marked.js** library. I had no idea that the _test script_ never referenced or called _marked.js_ 
Perhaps if I walk through the tests step by step we can see exactly when marked is called on :thinking: 
I'll look over the test code myself, and see if I can find any correlation.

**Comment by petercr** [comment]
@tbushman **I FOUND IT!!** In the file `/src/project-tests/markdown-previewer-tests.js` on line **47 && 53** the code calls for `marked(str)`. That must be the instance where the test script calls for **marked.js**  to test parsing the markdown :+1: :sunglasses: 
And it is specifically inside `triggerChange(str)` which is for the React tests. 
I can go ahead and just add an import line to the top of the file, and make a pull request. That should fix the issue all-together. Just let me know :+1: :smile_cat:

**Comment by tbushman** [comment]
@petercr I'm glad I asked you!!! WOO!

**Comment by petercr** [comment]
Great I'm still working on a _working_ fix :laughing: 
I've got the updated code being built, I just haven't been able to have the live-server inject the script in
I'll keep you updated when I get further. :thinking: :+1:
