### ISSUE TITLE
Document the regexes in markdown previewer tests

### ISSUE THREAD

**Issue by tchaffee** [freeCodeCamp/testable-projects-fcc#540]
The regular expressions in the markdown previewer tests have become longish and complex. It would help future programmers understand them if there is some documentation about what each part of the regex does.

For example, this regex:

```
^\s*```[^]*[\n\r].*```\s*$|^\s*([ ]{4}|\t).*\S.*
```

It's not clear why the `[^]` is doing. That's a negated set? But there is nothing in the set to match?

Some documentation ion like below would be a big help so future programmers don't have to reverse engineer what it does.

```
// ^     Starts at the beginning of the line.
// \s*   Any number of whitespace characters.
// ```   Matches three backticks - the beginning of markup for inline code.
... etc.
```

**Comment by tchaffee** [comment]
@ValeraS  You just worked on this file. Would you be interested in helping us with this?

Also, do you know why we are matching the tab character in the above regex? Is it possible to even type a tab in the browser?

**Comment by ValeraS** [comment]
@tchaffee `[^]` it's mean any character, including newline. And it was here initially.

It's not so complicated to understand this regex and for understanding you always can use tools like https://regex101.com

![image](https://user-images.githubusercontent.com/10867286/44364939-f8419300-a4d0-11e8-980c-85b35bc54689.png)

Maybe in doc better mention this tool.

**Comment by ValeraS** [comment]
> Also, do you know why we are matching the tab character in the above regex? Is it possible to even type a tab in the browser?

Yes, it is. You can use copy-paste, for example. In addition, we test projects, coded not only in Codopen, but also locally.

**Comment by tchaffee** [comment]
@ValeraS What I'm trying to avoid by adding the docs is making other programmers re-figure it out each time by going to something like https://regex101.com. I've used that site often. It always takes more time that reading inline docs.

If you don't want to document it, I can do it myself. I just think it would be easier for you since you just recently changed them and know what they do. If you have time, could you give it go?

Now I get what `[^]*[\n\r].*` does. It's not just `[^]`. So it means match one character that isn't a bracket, an asterisk, or a newline. I understand the newline, but the brackets and asterisk are confusing. It means the following markup wouldn't match:

```
```*Doesn't match the regex.```
```[Doesn't match the regex.```
```]Doesn't match the regex.```
```

Weird. I have no idea why that's there. I'll see if I can track down the original author and why they put that there. And this is another example of why we need docs. If the original author had explained why it's there, it saves a lot of time.

**Comment by ValeraS** [comment]
@tchaffee one more time, `[^]` - it's mean any character, including newline. `[^]*` - matches between zero and unlimited times, as many times as possible, giving back as needed any character, including newline.

Such documentation is more like a regular expression textbook than documenting the code.

**Comment by tchaffee** [comment]
@ValeraS Now I understand the problem. At https://regex101.com I had PHP selected instead of javacript :-(

It's ok if you don't want to document the code, I'll document it. The problem with not documenting it is that someone could intend their regex to do one thing, but get it wrong. So it's important to know what they intended each part of the regex to do. Make debugging far easier instead of thinking (like I just did) that "Oh well, it works but I can't figure out why, so I better not touch it".

**Comment by tchaffee** [comment]
@ValeraS I appreciate your opinion. I've been coding for 30+ years now and documenting regex expressions helps me maintain them faster instead of figuring it out again each time. I'm responsible for this repo right now so I need to make the code as easy for me to maintain as possible. In any case it might not matter. I found a way we can eliminate almost all the regular expressions by just using the markedjs library itself. It will parse the markup for us and we can use the parsed markup tokens to check for header, codeblock, etc.
