### ISSUE TITLE
pomodoro test suite is too strict when checking for break-length, session-length and reset content

### ISSUE THREAD

**Issue by ValeraS** [freeCodeCamp/testable-projects-fcc#548]
@hbar1st commented on [Tue Aug 21 2018](https://github.com/freeCodeCamp/freeCodeCamp/issues/18036)

#### Describe your problem and - if possible - how to reproduce it
in this sample codepen created for the pomodoro clock challenge, the test suite fails to identify input fields that are being used to hold the break-length, session-length and to house the reset button.
https://codepen.io/hbar1st/pen/XPJKKo?editors=1100

This tells me the suite checks are too narrow in scope as they do not allow the use of form input fields which seem to be a natural fit for the pomodoro clock requirements.

The error for break-length for eg. states it cannot find a value of 5 even though *literally* the value attribute of the input tag is set:
Here's the start of one of the errors:
I can see an element, with corresponding id="break-length", which by default (on load) displays a value of 5. A value of 5 is not displayed by default: expected '' to equal '5' 
AssertionError: A value of 5 is not displayed by default: expected '' to equal '5'
    at o.c (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:205:1134)

#### Add a Link to the page with the problem
https://codepen.io/hbar1st/pen/XPJKKo?editors=1100

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: Version 68.0.3440.106
* Operating System: Windows 10

**Comment by tbushman** [comment]
Could be reason for #515 maybe...  
Thanks!

**Comment by ValeraS** [comment]
@tbushman in this case, the `input` field is used for` break-length` and `session-length`, and this is a problem.
