### ISSUE TITLE
Replace jsdom with Selenium for the D3 Alignment unit tests

### ISSUE THREAD

**Issue by tchaffee** [freeCodeCamp/testable-projects-fcc#550]
Until now our D3 Alignment testing utilities only looked at HTML attributes for the layout calculations. In PR #546 @tbushman would like to use `getBoundingClientRect()` which will be more accurate. Since jsdom does not support layout, we should do the tests in a real browser. By moving replacing jsdom with Selenium we can do that.

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
