### ISSUE TITLE
got a script error when testing my Calculator solution 

### ISSUE THREAD

**Issue by versatal** [freeCodeCamp/testable-projects-fcc#554]
#### Issue Description

When running the test suite on my solution for the Calculator challenge a script error for test number 12 was reported.

"Script error. (:0)"

#### Browser Information

* Browser Name, Version: Chrome Version 68.0.3440.106 (Official Build) (64-bit)
* Operating System: Windows 10 Home
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
https://codepen.io/volcivar/pen/vzNONR
 
```

#### Screenshot

![calculatortesting](https://user-images.githubusercontent.com/5733324/44579449-710c4d80-a764-11e8-812b-eeba2d8fb308.PNG)

**Comment by ValeraS** [comment]
@versatal In your Pen, if press `5` , `*` and `-` your code throws an exception on line 80: `Unexpected end of input`.
```
var answer = parseFloat(eval(this.state.expression).toFixed(4));
```

**Comment by tbushman** [comment]
@versatal It looks like you got it all sorted. Happy coding.
