### ISSUE TITLE
Product Landing Page Test 5 

### ISSUE THREAD

**Issue by causticcommentz** [freeCodeCamp/testable-projects-fcc#555]
#### Issue Description

The 5th test that runs on the product landing page challenge fails when it does not find a "href" tag within each .nav-link element.  The user stories do not state that an "href" tag needs to be used to take the user to the corresponding section of the page.  I wrote a javascript function that accomplishes the same task.

#### Browser Information

I am using vscode with the Live Server extension.  I ran the tests in Chrome.
* Browser Name, Version: 
             Google Chrome is up to date
             Version 68.0.3440.106 (Official Build) (64-bit)
* Operating System: 
              Windows 10
* Mobile, Desktop, or Tablet: 
            Desktop

#### Your Code / Link to Your Pen

```
function scrollIt(element) {
  window.scrollTo({
    'behavior': 'smooth',
    'left': 0,
    'top': element.offsetTop - 175,
  });
}

const btns = document.querySelectorAll(".js-btn");
const sections = document.querySelectorAll(".section");


btns[0].addEventListener('click', () => {
  scrollIt(sections[0]);
});

btns[1].addEventListener('click', () => {
  scrollIt(sections[1]);
});

btns[2].addEventListener('click', () => {
  scrollIt(sections[2]);
});
 
 
 
```

**Comment by tbushman** [comment]
@causticcommentz Thanks for the suggestion. We should probably change the wording on the user story to indicate the use of `href` as the intended means toward completing the project.

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
