### ISSUE TITLE
SURVEY

### ISSUE THREAD

**Issue by holmedw** [freeCodeCamp/testable-projects-fcc#562]
![html](https://user-images.githubusercontent.com/15205267/44692401-9c6a9300-aa17-11e8-9d76-0524a6a93536.png)

#### Issue Description

My Survey FCC  project failed the #4, #5, and #6 tests for validation errors. Based off of this https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5/Constraint_validation/ …  I have a required attribute at the end of the input id on lines 11, 13, & 15. Any idea as to why?

#### Browser Information

My Survey FCC  project failed the #4, #5, and #6 tests for validation errors. Based off of this https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5/Constraint_validation/ …  I have a required attribute at the end of the input id on lines 11, 13, & 15. Any idea as to why?

* Browser Name, Version: IE9
* Operating System:  windows
* Mobile, Desktop, or Tablet: 
desktop
#### Your Code / Link to Your Pen

```
 <input id="name" type="text" placeholder="Enter your name" required> 
 
```

![html](https://user-images.githubusercontent.com/15205267/44692566-5bbf4980-aa18-11e8-9d94-0f2ee59c9cff.png)
![html](https://user-images.githubusercontent.com/15205267/44692591-71cd0a00-aa18-11e8-8f51-f204269b69d2.jpg)
![html](https://user-images.githubusercontent.com/15205267/44692597-78f41800-aa18-11e8-974c-25e991d32852.jpg)
![html](https://user-images.githubusercontent.com/15205267/44692604-814c5300-aa18-11e8-9d2f-1691f1429e1a.jpg)

**Comment by tbushman** [comment]
@holmedw Yes, please change the ids from `<input id="name-label" ...` and `<input id="email-label" ...` to `<input id="name" ... ` and `<input id="email" ...` , respectively.  
You will also want to change the `for` attributes on the associated labels:  
`<label for="name" ...` and `<label for="email" ...`  
The `for` attribute refers to the `id` attribute of the `<input>` element associated with the label. 
Let us know if you need more help.

**Comment by holmedw** [comment]
Hello,
 The above advise isn't working. I still get an error when I replace the
<input id="email-label">with <input id="email"> Please see attachment and
code.

https://codepen.io/holmedw/pen/dqpYNz?editors=1010

**Comment by ValeraS** [comment]
@holmedw Your HTML contains `form` elements with the same `id`. But the `id` must be unique in the whole document (https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id).

Leave only first one `form` tag and place it before `div`.

**Comment by holmedw** [comment]
Hello,
   I am working on the Landing Page project and do not understand why the
logo within my nav bar is not the same height as the one in the example on
FCC. I'm also unsure why but it seems over sized. What is in my code that
is responsible for this.

Edward

**Comment by tbushman** [comment]
@holmedw Will you please open a separate issue for the Product Landing page if you are still experiencing errors? Thank you.
