### ISSUE TITLE
No any media quarries detected in spite I have them in code. 

### ISSUE THREAD

**Issue by ZarinaZ** [freeCodeCamp/testable-projects-fcc#563]
#### Issue Description
The issue happens when I run tests in Codepen.
1 test doesn't pass because it doesn't see any media quarries, but I have them in my code.
1. Add at least one media quarry in the code;
2. Run tests.

#### Browser Information

* Browser Name, Version: Google Chrome, Version 68.0.3440.106 (Official Build) (64-bit) 
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen
My pen: https://codepen.io/zarinaz/pen/XPXGZz 

#### Screenshot
A screenshot of the issue :
![2018-08-28_1232](https://user-images.githubusercontent.com/20436174/44704800-8532b080-aabe-11e8-997e-ced558be91c4.png)

**Comment by ValeraS** [comment]
@ZarinaZ In case you use pure CSS, all of your media queries are coded wrong and ignored by the browser.

**Comment by jeremyhoutz** [comment]
Hello Zarina,

You can read up on media queries here: https://www.w3schools.com/css/css_rwd_mediaqueries.asp

If you copy the first example and paste it into your css it will pass. The key is understanding what the media query is doing.

**Comment by tbushman** [comment]
Could also be related to #568
