### ISSUE TITLE
Tooltip test fails

### ISSUE THREAD

**Issue by JohnnyBizzel** [freeCodeCamp/testable-projects-fcc#566]
As reported by Klemen, the bar chart is working as required
https://forum.freecodecamp.org/t/d3-bar-chart-problem/221505
codepen: https://codepen.io/Klemen/pen/dqompE

#### Issue Description
Running the tests it always fails on the tooltip mouseover test.
I also attempted to change it to `display:none` instead of using visibility. Same problem.

#### Browser Information

* Browser Name, Version: Chromium
* Operating System: Pop Linux
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen
https://codepen.io/JohnnyBizzel/pen/KxMxpg (forked version using display instead of visibility)

**Comment by ValeraS** [comment]
@JohnnyBizzel @CoderKlemen for now, you can use `display` instead of `visibility` and `mouseout` instead of `mouseleave`. And you'll pass the test.
