### ISSUE TITLE
Random failure, unsure why

### ISSUE THREAD

**Issue by ale8k** [freeCodeCamp/testable-projects-fcc#569]
Portfolio project

The navbar user story ensuring it is fixed to the top of the page is failing without giving any reason as to why.

#### Issue Description

Random failure.

#### Browser Information

* Browser Name, Version:  Google chrome, latest as of 31/08/2018 (I believe)
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
 https://codepen.io/Ale8k/pen/rZjKRZ?editors=1100
 
 
```

#### Screenshot

![capture](https://user-images.githubusercontent.com/42068202/44918467-f2e71280-ad32-11e8-8890-e11e6e244e62.PNG)

**Comment by ValeraS** [comment]
@ale8k You fixed `#navbar ul` but the user story says `navbar should be fixed`

Extract
```
 position: fixed;
 width: 100%;
```
from `#navbar ul` into `#navbar` and you'll pass the test.

**Comment by tbushman** [comment]
@ale8k I will be closing this issue soon. Please let us know if @ValeraS suggestion didn't work.
