### ISSUE TITLE
Not passing user story#7 I have created 6 <li> but still not passing..

### ISSUE THREAD

**Issue by shanibaba786** [freeCodeCamp/testable-projects-fcc#570]
#### Browser Information

* Browser Name, Version:  Opera
* Operating System: Win 10

 

#### Your Code / Link to Your Pen

```
 https://codepen.io/Zeeshan_Noor/pen/pORpEo
 
 
```

#### Screenshot

![capture](https://user-images.githubusercontent.com/28742084/44944822-708e3b00-ad92-11e8-9172-f0010c6492e3.PNG)

**Comment by tbushman** [comment]
@shanibaba786 It appears you have resolved the issue. :)
