### ISSUE TITLE
Strange behavior bundle.js

### ISSUE THREAD

**Issue by SerhiiK** [freeCodeCamp/testable-projects-fcc#571]
Responsive Web Design Projects - Build a Survey Form

#### Issue Description
 After first testing and all tests green , next push on button Run Tests result to running tests without end.

#### Browser Information

* Browser Name, Version: Chrome Version 68.0.3440.106 (Official Build) (64-bit)
* Operating System: Ubuntu 16.04 x64
* Mobile, Desktop, or Tablet:  Dekstop

#### Screenshot
![screenshot from 2018-09-01 18-16-46](https://user-images.githubusercontent.com/6170876/44947283-9dcefd80-ae13-11e8-9b66-28c547ba3acd.png)

**Comment by tbushman** [comment]
@SerhiiK Thanks for reporting this. The issue is not isolated to the Survey Form project.
