### ISSUE TITLE
Test suite doesn't recognize input tag JavaScript Calculator

### ISSUE THREAD

**Issue by adrianwix** [freeCodeCamp/testable-projects-fcc#573]
#### Issue Description

Good day,
I am currently using an input HTML tag for the JavaScript calculator. It uses the ID display the test suit recognize it but when trying to prove User Story from 7 ahead. It throws error basically because it can not detect the input.value.
Using Jquery for that project. It was actually from the old curriculum came back to try to make it work in the new version.

#### Browser Information

* Browser Name, Version: Chrome Version 68.0.3440.106 (Official Build) (64-bit)
* Operating System: Windows 8.1
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

[Codepen Project](https://codepen.io/adrianwix/pen/MGZObd )

#### Screenshot

![screenshot-codepen io-2018 09 02-23-42-00](https://user-images.githubusercontent.com/37629556/44961007-db15b700-af09-11e8-8fd1-d9b8deb7e2b4.png)

**Comment by tbushman** [comment]
@adrianwix Hello, one of the problems is that the tests test the `innerHTML` of the `#display` element. You could change your `<input>` element to a `<textarea>` element and that would require the fewest changes to your code...
