### ISSUE TITLE
[TEST_SUITE] Browser incompatibility 

### ISSUE THREAD

**Issue by no-stack-dub-sack** [freeCodeCamp/testable-projects-fcc#58]
A **major** issue right now with this project is that the test suite only runs in Chrome. This is not cool. If any visitors have any ideas on how to fix this, please feel free to check out the repo and comment here. 

# Thanks!!!

**Comment by christophherr** [comment]
Microsoft Edge (and IE 11) error out on line 268 of bundle.js.
![edge error](https://cloud.githubusercontent.com/assets/8683126/23288562/67cff268-fa12-11e6-954b-faf37a5d7347.png)
Commenting out the line `button.classList = ['fcc_foldout_buttons'];` resolves the error and doesn't seem to have an impact on the display of `fcc_test_button` in either Edge, Firefox or Chrome locally.

**Comment by no-stack-dub-sack** [comment]
@christophherr so removing that will have an impact if you try to rerun the tests - the class names for the button won't reset, and even if some tests fail (or pass) the next time around, the button will retain the indicator color of whatever it was at the finish of the first run through of the suite

This also does seem to be the problem in Safari as well. However, I think there will be other problems elsewhere in the test suite - namely with the Pomodoro Clock - even once this is resolved. But I'm not sure. I have to look at the docs but I think the Mutation Observer web api is not supported in some browsers.

Although, even getting this fixed will be a big step in the right direction. Let me look a little closer now that I know what the problem is.

Thanks for pointing this out!

**Comment by christophherr** [comment]
@no-stack-dub-sack 
Wow! The class / color changes of the button never really registered in my brain before. 
Sorry about that.
Nice, elegant solution with the helper function. 
I like it much better than my first idea of using classList.remove()
