### ISSUE TITLE
Crossbrowser testing

### ISSUE THREAD

**Issue by ValeraS** [freeCodeCamp/testable-projects-fcc#584]
Here some services that offer free cross-browser testing for open source projects.

https://crossbrowsertesting.com/open-source/request

https://www.browserstack.com/open-source?ref=pricing

https://saucelabs.com/open-source/open-sauce

How about trying this or maybe you use other solutions?

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
