### ISSUE TITLE
Issue with the product landing page project.

### ISSUE THREAD

**Issue by theAsthana** [freeCodeCamp/testable-projects-fcc#585]
Hello there,
    I amhaving a issue with the landing page project in responsive design projects.
I build a page after following all the user stories and my project passed all the test using the CDN provided on the local machine, but when i load the project into codepen it get failed. I don't know why, I tried everything I can but the issue stays the same. I read the user stories again and again but no luck.
Please have a look at my project here: https://codepen.io/theAsthana/full/jvLNqo/

**Comment by ValeraS** [comment]
@theAsthana If you press `tests` button you'll see detailed errors. In the first case, an element with `id=img-header` not found. In the second case, the attribute `name = "email"` does not exist in the email input element.

**Comment by tbushman** [comment]
@theAsthana I am closing this issue. Please let us know here if you have further questions.
