### ISSUE TITLE
Build a Survey Form/14th

### ISSUE THREAD

**Issue by Anastasiia0905** [freeCodeCamp/testable-projects-fcc#586]
Hi
The project doesn't pass one test.
But it responds to all conditions 
https://codepen.io/AnastasiiaT/pen/vzeNvw

**Comment by tbushman** [comment]
@Anastasiia0905 Are you running Codepen in Chrome? Your tests all pass in Chrome! :)

**Comment by tbushman** [comment]
Also tested in Firefox. @Anastasiia0905 please let us know here if you have further questions.
