### ISSUE TITLE
Test Cases for personal portfolio contains typo

### ISSUE THREAD

**Issue by lohchoonhuah** [freeCodeCamp/testable-projects-fcc#587]
#### Issue Description

Test Cases for personal portfolio contains spelling error

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 4. The projects section should contain at least one element with a class of "project-tile" to hold a project.

it should be "project-title" according to the specification given.
 
 
```

**Comment by tbushman** [comment]
@lohchoonhuah Thank you!
