### ISSUE TITLE
Product Landing Page: user story #5

### ISSUE THREAD

**Issue by shwetharv** [freeCodeCamp/testable-projects-fcc#589]
#### Issue Description

It says link with href of "features" is not linked to that section of the page. I have pasted the correct link but still this error persists.

#### Browser Information

Chrome
* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 https://codepen.io/shwesoo7/pen/MqmoNZ
 
 
```

**Comment by tbushman** [comment]
@shwetharv You're on the right track with your location hashes, but you don't need the full url if you are linking within the page.  
Change these  
```  
<li><a class="nav-link" href="https://s.codepen.io/freeCodeCamp/fullpage/RKRbwL#features">Features</a></li>
<li><a class="nav-link" href="https://s.codepen.io/freeCodeCamp/fullpage/RKRbwL#how-it-works">How it works</a></li>
<li><a id="pricing" class="nav-link" href="https://s.codepen.io/freeCodeCamp/fullpage/RKRbwL#pricing">Pricing</a></li>  
```  
to  
```  
<li><a class="nav-link" href="#features">Features</a></li>
<li><a class="nav-link" href="#how-it-works">How it works</a></li>
<li><a id="pricing" class="nav-link" href="#pricing">Pricing</a></li>  
```

**Comment by shwetharv** [comment]
Thank you. I made the changes but it still says "#features" does not link!

**Comment by ValeraS** [comment]
@shwetharv Your link is not linked to a corresponding element on the page. For each link, you should add a corresponding element, for example `<section id="features">....</section>`

**Comment by shwetharv** [comment]
Thank you so much @ValeraS Its working! ;)
