### ISSUE TITLE
Testing but not showing bug

### ISSUE THREAD

**Issue by ghost** [freeCodeCamp/testable-projects-fcc#592]
#### Issue Description

When I put the code for checking the project Product landing page. Date 9/7/18 at 6:47 PM

#### Browser Information

* Browser Name, Version: Chrome Version 68.0.3440.106 
* Operating System: Windows 7 64bit
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
 https://codepen.io/sunilsh922/pen/JaORpz
 
 
```

#### Screenshot

![image](https://user-images.githubusercontent.com/40673955/45221361-c56c0d00-b2ce-11e8-9180-445e8dcb2b46.png)

![image](https://user-images.githubusercontent.com/40673955/45221391-e2084500-b2ce-11e8-911b-08a20a0e6322.png)

**Comment by ValeraS** [comment]
@ravanasur It is a known issue. Rerun your pen and you will able to run tests and view results. For manual rerun the pen, in Settings - Behavior uncheck Auto-Updating Preview and press an appeared Run button.

**Comment by PhoenixAscension** [comment]
Ran into this several times. Save progress then reload page

**Comment by ValeraS** [comment]
resolved
