### ISSUE TITLE
A nav-link button leading to a correspondig section on the page

### ISSUE THREAD

**Issue by greaterpat** [freeCodeCamp/testable-projects-fcc#595]
#### Browser Information

* Browser Name, Version: Google Chrome, Version 68.0.3440.106 (Official Build) (64-bit)
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
 <div class="video-frame" id="videos">
  <iframe id="video" width="450" height="315" src="https://www.youtube-nocookie.com/embed/y8Yv4pnO7qc? rel=0&amp;controls=0&amp;showinfo=0" frameborder="0" allowfullscreen="">
  </iframe>
</div>

https://codepen.io/greaterpat/pen/dqZpwy
 
 
```

#### Screenshot

![product_landing_page](https://user-images.githubusercontent.com/41129845/45258326-8b256d00-b3ad-11e8-838e-3de36b14df1c.PNG)

**Comment by tbushman** [comment]
@greaterpat Hello! At first I couldn't see the issue, but the test is looking for the `href` attribute on the `.nav-link` element itself (`<a>`), so change it to:  
```  
<li><a href="#videos" class="nav-link">Video</a></li>
<li><a href="#functions" class="nav-link">Functions</a></li>
<li ><a href="#pricing" class="nav-link">Pricing</a></li>  
```

**Comment by greaterpat** [comment]
OK, Mr Tracy, thanks so much. I appreciate
