### ISSUE TITLE
Survey Form test 1 is incorrect 

### ISSUE THREAD

**Issue by AerospaceEngineerBadAss** [freeCodeCamp/testable-projects-fcc#596]
Survey Form

#### Issue Description

when running the "Survey Form" test suit, the first test keeps failing. 
I believe it is wrong because it is expecting the "<title></title>" element to contain a <h1></h1> 
title inside. This does not seem right as the <title> tag is for the tab that shows up in the browser

#### Browser Information

* Browser Name, Version: google Chrome Version 68.0.3440.106 (Official Build) (64-bit)
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
 https://codepen.io/AerospaceBadAss/pen/LJQgzK
 
 
```

**Comment by ValeraS** [comment]
@AerospaceEngineerBadAss You have two elements with `id="title"` but a value of the `id` attribute must be unique in the whole document. Remove `id="title"` from the `title` element and you'll pass this test. For further reading https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id.

**Comment by tbushman** [comment]
@AerospaceEngineerBadAss Please let us know here if you have further questions.

**Comment by tchaffee** [comment]
@tbushman @ValeraS Thanks for helping get so many of these older issues closed yesterday. We were overdue for reviewing and closing older issues.
