### ISSUE TITLE
We could not find a user by the name of "email-submit"

### ISSUE THREAD

**Issue by DevLinh** [freeCodeCamp/testable-projects-fcc#597]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 
 
```

**Comment by tbushman** [comment]
@DevLinh Could you please share some more information? Which test gives this error? It would be helpful to be able to test your code as well if you don't mind sharing it.

**Comment by DevLinh** [comment]
oh thank you so much, I solved this problem, in the submit button must have
the "name" property, I tried and fixed it, thank you so much again !

Vào Th 5, 13 thg 9, 2018 vào lúc 04:15 Tracey Bushman <
notifications@github.com> đã viết:

**Comment by tbushman** [comment]
@DevLinh I wasn't any help on this! Glad you figured it out!
