### ISSUE TITLE
pomodoro clock testing errors

### ISSUE THREAD

**Issue by versatal** [freeCodeCamp/testable-projects-fcc#598]
#### Issue Description

When testing my pomodoro project 3 errors are reported.
1: 14. When a break countdown reaches zero (NOTE: timer MUST reach 00:00), and a new countdown begins, the element with the id of "timer-label" should display a string indicating a session has begun
2: 15. When a break countdown reaches zero (NOTE: timer MUST reach 00:00), a new session countdown should begin, counting down from the value currently displayed in the id="session-length" element.
3: The audio element with id="beep" must be 1 second or longer.

These errors are incorrect.  When the timer reaches zero it displays "00:00" and switches from "session" to "break" and back displaying the text "session" and "break" respectively.

Also the audio is definitely more than one second.  It is a base64 text file converted to audio.  So that may be the issue.  I have the free license for codepen so I cannot upload media. 

#### Browser Information

* Browser Name, Version: Chrome Version 68.0.3440.106 (Official Build) (64-bit) 
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
https://codepen.io/volcivar/full/KVwLBe/ 
 
 
```

**Comment by versatal** [comment]
So I fixed the errors 1 and 2 listed above.  Still have the audio problem.

**Comment by ValeraS** [comment]
@versatal you don't need to `load` audio to reset it instead `pause` the audio and set `currentTime` to 0.

**Comment by geoffreyirungu** [comment]
please verastal could you help me with your logic of playing and pause the time in pomodoro clock I'm stuck on the project for a week because of just not figuring out how the logic works, I've tried a couple of logic and the error was time has not reached 00:00
