### ISSUE TITLE
Test doesn't run properly on subsequent click

### ISSUE THREAD

**Issue by picklu** [freeCodeCamp/testable-projects-fcc#600]
#### Issue Description

The bowser needs to be refreshed everytime I run the test. Test doesn't run properly on subsequent click. The result button shows "Testing 1/17" in yellow color.

#### Browser Information

* Browser Name, Version: Chrome, Version 68.0.3440.106 (Official Build)(64-bit)
* Operating System: Android and Windows10
* Mobile, Desktop, or Tablet:  Mobile, Tablet, and Desktop

#### Your Code / Link to Your Pen

https://codepen.io/picklu/full/OopbbL

**Comment by tbushman** [comment]
Related to #571 This will be fixed as soon as the new bundle is merged at the CDN. @picklu Thanks for reporting.
