### ISSUE TITLE
Fork Me! FCC: Test Suite Template is Empty

### ISSUE THREAD

**Issue by AnyaLinley** [freeCodeCamp/testable-projects-fcc#601]
Fork Me! FCC: Test Suite Template

When clicking on the link in the project instruction page, I am taken to the following page which has an empty project.
https://codepen.io/freeCodeCamp/pen/MJjpwO
 I would expect this to be a full, working project that passes all the tests.

#### Issue Description

The issue is that the linked project is empty and I would expect to see a full, working project here. It was working correctly for me yesterday. Could I or someone else have somehow deleted the content?

#### Browser Information

Using Chrome and Windows 10 on a desktop PC

* Browser Name, Version: Chrome, 68.0.3440.106 (Official Build) (64-bit)
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

![templateisemptybug](https://user-images.githubusercontent.com/17203542/45496971-79a5e180-b76e-11e8-912c-f92984097db5.jpg)

**Comment by AnyaLinley** [comment]
Seems that none of the template projects are working for me. They all come up empty.

**Comment by tbushman** [comment]
Hello, @AnyaLinley -- there should be two Codepen links on most of the curriculum pages for projects. One is for a blank template like these -- intended to be empty and filled in by students. The other link is a finished example.

**Comment by AnyaLinley** [comment]
Oh my goodness, I'm such an idiot. Thank you. Think I was a bit tired yesterday.
