### ISSUE TITLE
CDN not auto-updating

### ISSUE THREAD

**Issue by tbushman** [freeCodeCamp/testable-projects-fcc#602]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 
 
```

#### Screenshot

We need to create credentials, `CDN_USER` and `CDN_API_KEY` and see if that fixes the CDN deploying process. I'll do a PR at fCC/CDN after the current batch of fCC/testable-projects-fcc PRs are merged. The last merge was three days ago.

**Comment by tbushman** [comment]
@raisedadead Awesome. Thanks.   
Keeping this open in case the auto-deploy still doesn't work.

**Comment by ValeraS** [comment]
@tbushman Can you restart a build job on Travis-CI for the last merge commit in the master branch https://travis-ci.org/freeCodeCamp/testable-projects-fcc/builds/429633731? Then we will see it works or not.

**Comment by tbushman** [comment]
@ValeraS I did this last night, forgot to mention to you... it doesn't seem to be working, still. :/

**Comment by ValeraS** [comment]
@tbushman I have checked it on my GitHub account and it works.
It may not work if current CDN_USER with CDN_API_KEY doesn't have permission to write in CDN repo.

Let's merge # 610, then # 611 and see what happens.

**Comment by raisedadead** [comment]
> It may not work if current CDN_USER with CDN_API_KEY doesn't have permission...

Sorry. That's totally my bad, I forgot to add @camperbot to the collaborator list. This should be OK now. Can you please re-check.

**Comment by tbushman** [comment]
@raisedadead I'll do a new PR at fCC/cdn soon and until we can resolve this.

**Comment by tbushman** [comment]
@ValeraS @raisedadead The deploy isn't working. I will be manually submitting a new bundle.js to fCC/CDN soon. Please let me know if I can help fix this -- it's not clear to me. We can test a deploy with the currently open PR, https://github.com/freeCodeCamp/testable-projects-fcc/pull/667 .

**Comment by ValeraS** [comment]
@tbushman It's an issue with credentials

With this PR you can't test deploy. Deploy runs only if `src/**/*` has been changed.

To test deploy you can:
1. clone the `CDN` repo;
2. in Travis change Environment Variables:
```
CDN_USER=tbushman
CDN_API_KEY=password
CDN_REPO_SLUG=tbushman/cdn.git
```
3. restart build for last merge commit;
4. look at a result
![image](https://user-images.githubusercontent.com/10867286/48284717-454e5900-e471-11e8-8f1b-78f04e1718fd.png)

**Comment by raisedadead** [comment]
I am available later in about 7-8 hours from now, if anyone is interested to pair and debug this.

**Comment by ValeraS** [comment]
for example, merge # 744.

**Comment by ValeraS** [comment]
It works
