### ISSUE TITLE
Front-End Project #3 (Drum Machine)

### ISSUE THREAD

**Issue by etoler1841** [freeCodeCamp/testable-projects-fcc#603]
#### Issue Description
App fails to pass test 6, even though all requirements are met:

>>When I press the trigger key associated with each .drum-pad, the audio clip contained in its child <audio> element should be triggered (e.g. pressing the Q key should trigger the drum pad which contains the string "Q", pressing the W key should trigger the drum pad which contains the string "W", etc.).

#### Browser Information

* Browser Name, Version: Google Chrome ^69.0.3497.92 (64-bit)
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen
[CodePen Link](https://codepen.io/etoler1841/full/vzaRyq/)
The problem was initially discovered when running through NPM on my local machine and persisted into deployment on CodePen.

**Comment by ValeraS** [comment]
@etoler1841 add a listener on `keydown` event instead of `keyup`. Test dispatches only `keydown` event.

**Comment by etoler1841** [comment]
That fixed it. Thanks!
