### ISSUE TITLE
Code should pass all the tests in Technical Documentation Project

### ISSUE THREAD

**Issue by footios** [freeCodeCamp/testable-projects-fcc#605]
Technical Docs Page

#### Issue Description

I get 13/16 on the tests but the code is good. 
Bugs:
1) 
"4. Each <section> element with the class of "main-section" should also have an id that corresponds with the text of each <header> contained within it. Any spaces should be replaced with underscores (e.g. The <section> that contains the header "Javascript and Java" should have a corresponding id="Javascript_and_Java")".
code:
<section class="main-section" id="About_Swift">...
<section class="main-section" id="Features">...
 <section  class="main-section" id="Swift.org_and_Open_Source">...
<section class="main-section" id="Platform_Support">...
<section  class="main-section" id="Extra_Info">...

2)
"10. Additionally, the navbar should contain link (<a>) elements with the class of "nav-link". There should be one for every element with the class "main-section"."
code: (e.g.)
<a class="nav-link" href="#About_Swift" rel="internal">
            <li><h3>About Swift</h3></li></a>
... the rest is like this... all good.

3)
"12. Each element with the class of "nav-link" should contain text that corresponds to the <header> text within each <section> (e.g. if you have a "Hello world" section/header, your navbar should have an element which contains the text "Hello world")."
code: (e.g.)
<a class="nav-link" href="#About_Swift" rel="internal">
            <li><h3>About Swift</h3></li></a>
...
<section class="main-section" id="About_Swift">
        <header><h2>About Swift</h2></header>
... and the res is all the same.

#### Browser Information

* Browser Name, Version:  Chrome Version 68.0.3440.106 (Official Build) (64-bit)
* Operating System: Window 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
 https://codepen.io/fooTios/pen/eLPvaX
 
 
```

**Comment by tbushman** [comment]
@footios Hello. There are two things that will help you pass the tests. For test 4, please move the `<article>` element outside of the `<header>` element because it is being counted in the `innerText` query from the test.  
The second thing is that there are anchor references that are not linked to additional elements within the main sections (sub-sections like `#Safe #Fast #Expressive`). This is valid, except that the test is comparing anchored `.main-section` links only. For the purposes of this test, please have only `.main-section` elements linked to the `.nav-link` elements.

**Comment by footios** [comment]
@tbushman 
Thank you so much for your reply.
It passes all the tests.
I implemented the changes you suggested.
As about the <code><article></code> I moved it completely because it wasn't even asked for.
And if you don't mind me saying, after <code><section></code> should come a <code><header></code>, having <code><article></code> was still erroneous.
As about the <code> <.nav-link></code> I did all the changes you suggested. But it still didn't pass.
It was just a <code></br></code> that I had in at the title of the <code>.navbar</code>
this one <code> <li><h3>Swift.org</br>and Open Source</h3></li></a></code>.
I remove it because it couldn't see the space.
Thanks again for your help.
I really appreciate it.

**Comment by tbushman** [comment]
@footios OK great.
