### ISSUE TITLE
Portfolio test is not working correctly

### ISSUE THREAD

**Issue by PhoenixAscension** [freeCodeCamp/testable-projects-fcc#606]
#### Issue Description

<p>Currently working on personal portfolio project for fcc. When i run test, the match the viewport  height objective says failed. I tried to correct for several hours till i realized the sample project page is also failing the same objective. I believe there is an issue with the test.</p>

#### Browser Information

* Browser Name, Version: Chrome Version 69.0.3497.92 (Official Build) (64-bit)
* Operating System:  windows 10 enterprise
* Mobile, Desktop, or Tablet: laptop and desktop

#### Your Code / Link to Your Pen

#welcome-section{
  text-align: center;
  top: 0;
  min-height: 55vh;
  padding-top: 30vh;
  background-color: #C6FA82;
  color: black;
  height: 100vh;
  overflow: auto;
}

 https://codepen.io/PhoenixAscension/pen/LJbBxZ  <--link
 
 
```

#### Screenshot
<!-- Add a screenshot of your issue -->

**Comment by PhoenixAscension** [comment]
Thank you for the update.

**Comment by ValeraS** [comment]
@PhoenixAscension by default element has `box-sizing: context-box`, if you set `height: 100vh` and `padding-top: 30vh`, actual size of element will be `130vh`. You can fix it by setting `box-sizing: border-box` or `height: 70vh`.

**Comment by tbushman** [comment]
The same test failed on https://codepen.io/freeCodeCamp/pen/zNBOYG in Windows10 Chrome when I tested it earlier.

**Comment by PhoenixAscension** [comment]
Ran test in windows 10. Passed!

**Comment by tbushman** [comment]
@ValeraS This is Chrome / Windows 10 right now... strange indeed.
![capture](https://user-images.githubusercontent.com/7049294/45763966-e138b280-bbee-11e8-8aeb-87c7264cbc16.JPG)

**Comment by nathanhannig** [comment]
I have this issue. The issue from my findings occur when the window zoom settings are less than 100% (hit ctrl + - on keyboard to zoom out)

My example 
https://codepen.io/breakpoint/full/bpeRRM/

**Comment by tbushman** [comment]
@nathanhannig OK! Thank you!

**Comment by capybar** [comment]
I know this is a long time ago but thank you! This helped. I was banging my head trying to figure out what I was doing wrong (because I did have height:100vh) but yup this was the answer.
