### ISSUE TITLE
D3 Scatter Plot: 2 of 16 tests fail for the example project.

### ISSUE THREAD

**Issue by numoonchld** [freeCodeCamp/testable-projects-fcc#609]
#### Issue Description

Copy pasted form test result's log on the project codepen:

> 6. The data-xvalue and data-yvalue of each dot should be within the range of the actual data and in the correct data format. For data-xvalue, integers (full years) or Date objects are acceptable for test evaluation. For data-yvalue (minutes), use Date objects.

> 12. I can see that the range of the y-axis labels are within the range of the actual y-axis data.

#### Browser Information

* Browser Name, Version: chrome Version 69.0.3497.100 (Official Build) (64-bit)
* Operating System: high sierra 10.13.6
* Mobile, Desktop, or Tablet: notebook

#### Your Code / Link to Your Pen

Example project: https://codepen.io/freeCodeCamp/full/bgpXyK

Project description: https://learn.freecodecamp.org/data-visualization/data-visualization-projects/visualize-data-with-a-scatterplot-graph

#### Screenshot

![image](https://user-images.githubusercontent.com/17598505/45756207-f1c44980-bc3d-11e8-945e-56e5f626d601.png)

![image](https://user-images.githubusercontent.com/17598505/45755887-24217700-bc3d-11e8-80cb-c77e3247b535.png)

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
