### ISSUE TITLE
Error when testing JS Calculator

### ISSUE THREAD

**Issue by Juwdohr** [freeCodeCamp/testable-projects-fcc#612]
#### Issue Description

Trying to run tests on the Javascript calculator.

#### Browser Information

* Browser Name, Version: Chrome, Latest
* Operating System: Win10 Pro
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

https://s.codepen.io/juwdohr/debug/aaKGPB/yYryLOVXmVxM
#### Screenshot

![image](https://user-images.githubusercontent.com/16342673/45828546-05ab9200-bcb6-11e8-9910-0b72297e942c.png)

**Comment by tbushman** [comment]
@Juwdohr Looks like you got this sorted out?
