### ISSUE TITLE
Pomodoro Clock in React - Failing 6 tests

### ISSUE THREAD

**Issue by deepintocode** [freeCodeCamp/testable-projects-fcc#613]
#### Issue Description

My Pomodoro clock project, written in React, is failing 6 tests, while it looks and acts like it is supposed to.

#### Browser Information

* Browser Name, Version: Chrome 69
* Operating System: Mac OS 10.13
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

http://mindless-step.surge.sh/
https://github.com/deepintocode/pomodoro_clock

**Comment by ValeraS** [comment]
@deepintocode your timer does not show time `00:00`, tests need it for work.

**Comment by deepintocode** [comment]
> @deepintocode your timer does not show time `00:00`, tests need it for work.

Thanks, it was an easy fix.
