### ISSUE TITLE
Pomodoro clock - Tests are failing despite clock functioning as it should

### ISSUE THREAD

**Issue by jpacsai** [freeCodeCamp/testable-projects-fcc#614]
#### Issue Description

I have created a pomodoro clock app with react + redux, works as it should but still failing on tests which has to do with the countdown function, which are: 11, 22, 23, 24, 25, 26
Can anybody look at my code and give me direction how to fix this?

error message is the same at all the failing tests:
```
“Timeout of 5000ms exceeded. For async tests and hooks, ensure “done()” is called; if returning a Promise, ensure it resolves.
Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure “done()” is called; if returning a Promise, ensure it resolves.
at o.f._timeoutError (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:570:32569 1)
at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:570:30700”
```
My question on fcc forum: https://forum.freecodecamp.org/t/pomodoro-clock-setinterval-problem/229202

#### Browser Information

* Browser Name, Version: Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36.
* Operating System: Windows NT 10.0; Win64; x64
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

 https://codepen.io/jutzee/pen/KxYoYb

#### Link to challenge
https://learn.freecodecamp.org/front-end-libraries/front-end-libraries-projects/build-a-pomodoro-clock/

#### Screenshot

![capture](https://user-images.githubusercontent.com/34191321/45933374-94a4fc80-bf8b-11e8-81a7-a4123b557ce8.JPG)

**Comment by jpacsai** [comment]
_...massive facepalm..._
 @tbushman I could kiss you right now 😅 Thank you so much, I feel so stupid but so so happy, I can get my certificate now thanks to you 😘

**Comment by tbushman** [comment]
@jpacsai :D You shouldn't feel stupid since your project was otherwise tip-top and you love cats. :)
