### ISSUE TITLE
Add a warning that some browser extensions may intefere with the test suite.

### ISSUE THREAD

**Issue by tchaffee** [freeCodeCamp/testable-projects-fcc#618]
See issue https://github.com/freeCodeCamp/freeCodeCamp/issues/18183 for details.

It might be tricky to find a good spot to add this warning, because it can't be in the test suite itself. Perhaps directly in the CodePen that is forked.

**Comment by tchaffee** [comment]
Note that it's also recommended "we submit feedback though the extension letting the Privacy Badger team know they are blocking a file that is critical for freeCodeCamp users."

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
