### ISSUE TITLE
Tooltip not passing bar chart test 

### ISSUE THREAD

**Issue by djjwengler** [freeCodeCamp/testable-projects-fcc#619]
#### Issue Description

I'm trying to pass the bar chart FCC test suite. So far I've managed to jump through all the hoops necessary in order to pass 12/14 tests, the last two remaining being the tooltips. As far as I can tell I have completed the required user stories (tooltip shows up, has the proper id, showing the same data-date info) but it still won't pass. Perhaps I need to use another way besides svg.title? I have seen several different methods online, but since the FCC tutorials use title in order to teach about tooltips, I thought using it was kosher enough to pass the test. 

#### Browser Information

* Browser Name, Version: Chrome, 68.0.3440.118
* Operating System:  Chromebook
* Mobile, Desktop, or Tablet: chromebook

#### Your Code / Link to Your Pen

```
svg
    .selectAll("rect")
    .data(dataset)
    .attr("data-date", (d, i) => d[0])
    //.attr("data-date", (d, i) => d[0])
    
    .attr("data-gdp", (d, i) => d[1])
    .append("title")
    .attr("id", "tooltip")
    .attr("data-date", (d) => d[0])
    .text(d => "GDP $" + d[1] + " billion \n" + d[0])
    .on('mouseover', "#tooltip");
 
 codepen link:
https://codepen.io/djjwengler/pen/LBqgEj
```

#### Screenshot

![img_1689](https://user-images.githubusercontent.com/17834836/46113745-9a822400-c1bd-11e8-88da-1d2b84337179.JPG)

**Comment by tbushman** [comment]
@djjwengler The project tests don't currently support this tooltip method. The tests look for changes in css properties to ensure the tooltip is visible on hover. There doesn't seem to be a way of testing the visibility of the svg `<title>` element, and the `data-date` test isn't distinguishing the correct element. Very sorry.

**Comment by tbushman** [comment]
Discuss possibility of testing `<title>` element visibility.

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
