### ISSUE TITLE
Build a Tribute Page issue with User Story #8

### ISSUE THREAD

**Issue by DemitriFelder** [freeCodeCamp/testable-projects-fcc#620]
My css is just not working and I don't know why. 

I'm doing the first project and can't seem to get line #8 right.
"The img element should responsively resize, relative to the width of its parent element, without exceeding its original size."

* Browser Name, Version: Firefox
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

```
 	<style>
  #img-div { 
    width: 2000px;}
  img {display: block;
  max-width: 100%;
  height: auto;}
  </style>
 
```

**Comment by tbushman** [comment]
@DemitriFelder This looks right. Can you please share your html for context?

**Comment by DemitriFelder** [comment]
> 
> 
> @DemitriFelder This looks right. Can you please share your html for context?

<main id="main">

  <style scoped>
    #img {
      display: block;
      max-width: 100%;
      height: auto;
    }
  </style>
  <title id="title">Tribute page to Lain</title>

  <header>
    <div id="img-div">

      <h1 id="image"> <img alt src="https://ai.fancaps.net/galleries/Serial_Experiments_Lain/ep02/Serial_Experiments_Lain_Screenshot_0114.jpg"></h1>
      <h2 id="img-caption">
        Lain of Serial Experiments Lain</h2>
    </div>
  </header>

  <p> Serial Experiments Lain was a pioneer anime in the genere of Cyberpunk. It is often a visual feast of the eyes to any adult or child that watches. Its Iconic imagery ranging from flashing 90's crt monitors to rooms filled with bundles of wires and computers
    is still what many think of when the word Hacker. </p>

  <p id="tribute-info">If you want to learn more about Lain and her journey in to the world of technophilia go</p> <a id=tribute-link href="https://lainchan.org" target="_blank"> here.</a>

**Comment by DemitriFelder** [comment]
<header>
    <div id="img-div">

      <h1 id="image"> <img alt src="https://ai.fancaps.net/galleries/Serial_Experiments_Lain/ep02/Serial_Experiments_Lain_Screenshot_0114.jpg"></h1>
      <h2 id="img-caption">
        Lain of Serial Experiments Lain</h2>
    </div>
  </header>

**Comment by DemitriFelder** [comment]
<div id="img-div">

      <h1 id="image"> <img alt src="https://ai.fancaps.net/galleries/Serial_Experiments_Lain/ep02/Serial_Experiments_Lain_Screenshot_0114.jpg"></h1>
      <h2 id="img-caption">
        Lain of Serial Experiments Lain</h2>
    </div>

**Comment by tbushman** [comment]
@DemitriFelder Make sure the `id="image"` is on the `<img>` element. Change your code to:    
```      
<div id="img-div">
      <img  id="image" src="https://ai.fancaps.net/galleries/Serial_Experiments_Lain/ep02/Serial_Experiments_Lain_Screenshot_0114.jpg">
      <h2 id="img-caption">
        Lain of Serial Experiments Lain</h2>
    </div>  
```
