### ISSUE TITLE
When my markdown previewer first loads, the default markdown in the #editor field should be rendered as HTML in the #preview element

### ISSUE THREAD

**Issue by rubendmatos1985** [freeCodeCamp/testable-projects-fcc#622]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 https://codepen.io/Ruben1985/pen/ZMOZRr?editors=0110
 
 
```

**Comment by rubendmatos1985** [comment]
i dont know if i maybe i am wrong. I am making all what it says but the script dont recognize it

**Comment by tbushman** [comment]
@rubendmatos1985 While using html tags is valid in Markdown, the exercise is testing for Markdown syntax in heading elements.  
Please have a look at the two options for forming Markdown headings:  
https://www.markdownguide.org/basic-syntax/#headings
