### ISSUE TITLE
Build a JavaScript Calculator

### ISSUE THREAD

**Issue by SAnschutz** [freeCodeCamp/testable-projects-fcc#623]
#### Issue Description
I've completed my Front End Library Project "Build a JavaScript Calculator", but two tests are failing, which I believe shouldn't be:

Test 11. When the decimal element is clicked, a "." should append to the currently displayed value; two "." in one number should not be accepted 

  This shows:  "AssertionError:  An input of "5 . 5 . 5" should display 5.55"
  though my display does show 5.55 after an input of 5.5.5

Test 12. I should be able to perform any operation (+, -, *, /) on numbers containing decimal points 

  This shows "AssertionError: The expression "10.5 - 5.5" should produce an output of "5" "
  though during my manual tests, 10.5 - 5.5 does produce an output of 5

#### Browser Information

* Browser Name, Version: 69.0.3497.100
* Operating System:  macOS High Sierra -- Version 10.13.6
* Mobile, Desktop, or Tablet:   Desktop

#### Your Code / Link to Your Pen

Link to my code on CodePen:   https://codepen.io/szqny/pen/ZqzBOd?editors=0010

**Comment by ValeraS** [comment]
@SAnschutz next sequence of inputs gives the wrong answer `5` `.` `.` `0` `AC` `5` `.` `5` `.` `5`

**Comment by SAnschutz** [comment]
THANK YOU!!  I should have caught that -- what can I say, I'm very new to testing, also new to Github...still learning.  When you pointed that out I realized exactly what I had missed, have now fixed it, and all tests passing.   Many thanks.
