### ISSUE TITLE
Flex box issues - Technical documentation issue

### ISSUE THREAD

**Issue by nt-michael** [freeCodeCamp/testable-projects-fcc#627]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 form{
  postion:flex;
  flex:column;
  width:600px;
}
form div{
  width:100%;
  position:flex;
  flex:row;
}
 
 
```
Detector says there's no flexbox item whereas there's!
#### Screenshot

![1](https://user-images.githubusercontent.com/13780028/46363786-e32d5780-c66b-11e8-97be-3b1f0261fdf3.PNG)
![2](https://user-images.githubusercontent.com/13780028/46363787-e3c5ee00-c66b-11e8-9853-8cde5ece7ed5.PNG)

**Comment by ValeraS** [comment]
@nt-michael value of a `position` property can't be flex https://developer.mozilla.org/en-US/docs/Web/CSS/position
You need to use a `display` CSS property https://developer.mozilla.org/en-US/docs/Web/CSS/display
