### ISSUE TITLE
Error or not on submit button?

### ISSUE THREAD

**Issue by jachiu89** [freeCodeCamp/testable-projects-fcc#628]
#### Issue Description

I believe I have done this correct but it keeps saying...
16. Inside the form element, I am presented with a button with id="submit" to submit all my inputs.
The button with id="submit" is not inside the form element : expected 0 to be above 0
AssertionError: The button with id="submit" is not inside the form element : expected 0 to be above 0
    at s.c (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:521:1704)
    at s.e.(anonymous function) [as above] (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:457:126)
    at Function.n.isAbove (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:546:789)
    at r.<anonymous> (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:622:139423)
    at c (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:570:31654)
    at o.f.run (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:570:31590)
    at m.runTest (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:570:37160)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:570:38022
    at s (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:570:36472)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:570:36541

Am I doing something incorrect or is this an error?

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 https://codepen.io/jachiu89/pen/gBrpEp
 
```

#### Screenshot

<html>
  <head>
    <title>Survey Form</title>
  </head>
  <body>
        
<h1 id="title">Survey Form</h1>
        
    <p id="description"> Responsive Web Design Survey</p>
    <div>
        
      <form id="survey-form">
        
        <div>
        <label id="name-label">* Name:</label>
        <input id="name" placeholder="Enter your name" required>
        </div>
        
        <div>
        <label id="email-label">* Email:</label>
        <input id="email" placeholder="Enter your email" type="email" required>
        </div>
        
        
        <div>
        <label id="number-label">* Age:</label>
        <input id="number" type="number" placeholder="Age" min="1" max="200" required>
        </div>
        
        
        
        
        
        <div>
        <label id="gender-label">Gender</label>
        <select name="gender" id="dropdown">
        <option value="none">Select</option>
        <option value="male">Male</option>
        <option value="female">Female</option>
        </select>
        </div>
        
        <div>
        <label id="radio-label">How many years of experiencing in coding do you have?</label><br>
          <label for="0-1"><input id="0-1 year" type="radio" value=" 0" name="years-exp">0-1 year</label><br>
          <label for="1-3"><input id="1-3 years" type="radio" value="1" name="years-exp">1-3 years</label><br>
          <label for="3-5"><input id="3-5 years" type="radio" value="2"  name="years-exp">3-5 years</label><br>
          <label for="5+"><input id="5+" type="radio" value="3"  name="years-exp">5+ years</label>
        </div>
        
        <div>
        <label id="checkbox-label">Things to improve on</label><br>
          <label for="html"><input id="html" type="checkbox" value="0" name="improve">HTML</label><br>
          <label for="css"><input id="css" type="checkbox" value="1" name="improve">CSS</label><br>
          <label for="vd"><input id="vd" type="checkbox" value="2" name="inprove">Visual Design</label><br>
         <label for="a"><input id="a" type="checkbox" value="3" name="improve">Accessbility</label><br>
          <label for="rwd"><input id="rwd" type="checkbox" value="4" name="improve">Responsive Web Designing<label>
            </div>
        
            <div>
              <label id="textarea">Comments or Suggestions?</label>
            </div>
              <textarea name="message" rows="10" cols="50">Enter your comment here... </textarea><br>
            </div>
        
          <div>
            <button id="submit" type="submit">Submit</button>
          </div>
            </form>
        </body>
        </html>

**Comment by ValeraS** [comment]
@jachiu89 You have the following structure of your code:
```html
<div>
  <form>
    ...
    </div> <!-- This is an issue. -->
    <div><button id="submit" type="submit">Submit</button></div>
  </form>
```
