### ISSUE TITLE
[Test Suites] Cross-browser issue - Safari - test modal won't open

### ISSUE THREAD

**Issue by no-stack-dub-sack** [freeCodeCamp/testable-projects-fcc#63]
Safari Version 9.1.2 (11601.7.7)

This is an issue across several (most) test suites - some of the suites that it affects have other problems, and some pass all tests, except for this: **the test modal that displays the individual unit tests and their statuses DOES NOT open**. 

This is definitely the case in pre-10 Safari, but not sure about FF or IE or Edge. 

Occasionally, it will work, but most times, the modal just won't open, no errors in console, and works fine in Chrome. Here are the suites that I have found this to affect so far:
- Pomodoro Clock (all tests pass, only issue is this)
- Scatter Plot (other issues, see #64) 
- Choropleth (all tests passing, only issue is this)
- Tree Map (other issues, see #61) 
- Survey Form (no other issues)
- Random Quote Machine (no other issues)
- Tribute Page (no other issues)
- Drum Machine (other issues, see #65)
- Markdown Previewer (other issues, see #66)
- Calculator (no other issues & sometimes modal opens fine)

Luckily, this does not affect the boilerplate empty test pen, so somehow the projects built around them is causing this.

CC'ing @Christian-Paul && @paycoguy here in case this is somehow related to D3 in those projects, but I doubt this is the case because oddly enough, the Heat Map and Bar Chart pass all tests and the modal opens as intended - very strange, not sure yet what is causing this. 

**EDIT:** For all suites where the modal does not open, if you click the Tests button, then close the test suite interface by pressing the "X" in the top left, the modal will open! I'm still stumped as to why this is, but at least now other errors can be troubleshot

**Comment by christophherr** [comment]
I had no issues with the modal in the latest versions of Firefox (51.0.1 (64-bit)) and Edge (38.14393.0.0).

**Comment by tchaffee** [comment]
Closing because this is outdated. For now we only support Chrome. We will look at supporting other browsers in an upcoming phase.
