### ISSUE TITLE
FCC Drum Machine - TestCase 6 

### ISSUE THREAD

**Issue by mkavadias** [freeCodeCamp/testable-projects-fcc#630]
#### Issue Description

FCC Drum Machine project

Using Framework: React+Redux
Running the code ( see codepen link below) both locally and on codepen, an audio is triggered to play when the key 'Q' is pressed. 
Running test: Test case 6 fails. 
With message: No audio plays when the Q key is pressed : expected true to be false

#### Browser Information

* Browser Name, Version: Chrome Version 69.0.3497.100 (Official Build) (64-bit)
* Operating System: MAC OS 10.13.6
* Mobile, Desktop, or Tablet: Dektop (iMac)

#### Your Code / Link to Your Pen

[Codepen Link]( https://codepen.io/e42/pen/WaxNKZ)

```
// ============ Key Down  ===================
const padsObj = {}
pads.forEach(element => {
    const key = element.id.toLowerCase()
    padsObj[key] = element;
});
console.log(padsObj)

const play = (pad) => {
    document.getElementById(pad.id).play()
    store.dispatch(setPad(pad.id, pad.name))
}
// ============ KeyHandler  =================
const keyHandler = (e) => {
    console.log(e.keyCode, e.key)
    const pad = padsObj[e.key]
    if (pad) {
        play(pad)
    }
}
document.addEventListener("keydown", keyHandler)

// ============ DRUM Pad  ===================

 
```

**Comment by ValeraS** [comment]
@mkavadias you handle lowercase keys, but the user story says to handle uppercase keys.

**Comment by petercr** [comment]
@mkavadias If you go ahead and use `event.keyCode` in React then both the uppercase and lowercase letter keys return the exact same keyCode 👍 
That's what I did with mine 😃

**Comment by mkavadias** [comment]
Thanks for the reply.
I originally used keyCode; however I found on MDN
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode
Here they suggest not to use it anymore. The tests worked fine initially, I
overlooked the lowercase. Using key.toLowerCase worked also.

**Comment by Shubhambatham** [comment]
Many thanks !
