### ISSUE TITLE
Tribute Page

### ISSUE THREAD

**Issue by superfungirl** [freeCodeCamp/testable-projects-fcc#631]
#### Issue Description

I do not understand why the tests are different when I resize my browser. When I make my browser smaller, I'm getting a 10/10 and when I make it larger, it is a 9.

#### Browser Information

Chrome
Windows
Desktop

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 https://codepen.io/aynanufi/pen/qJRBXx
 
 
```

#### Screenshot

![image](https://user-images.githubusercontent.com/31410737/46636688-eedbbb00-cb50-11e8-99d1-0aebb60e2f57.png)
![image](https://user-images.githubusercontent.com/31410737/46636697-fc914080-cb50-11e8-8095-e4dfe51a1f27.png)

**Comment by tbushman** [comment]
@Aynanufi When the viewport is smaller, the image is as wide as the parent element that contains it, and is counted as centered. When the viewport is larger, the image sits on the left side and fails the centered test. One simple fix is to add `margin: 0 auto;` to your `<img>` element, and as long as `<img>` has `display: block;` , that will center it. :)
