### ISSUE TITLE
Cannot read property 'length' of null - Scaterplot Graph

### ISSUE THREAD

**Issue by GiaFil7** [freeCodeCamp/testable-projects-fcc#637]
#### Issue Description
Test #8 fails despite the dots visually aligning with the points on the y-axis.
#### Browser Information
* Browser Name, Version: Google Chrome Version 69.0.3497.100 (Official Build) (64-bit)
* Operating System: Windows 10

#### Your Code / Link to Your Pen
https://codepen.io/GiaFil/pen/qJqzWX
#### Screenshot

![2018-10-13 01_22_18-window](https://user-images.githubusercontent.com/32345224/46896599-878e7580-ce86-11e8-8860-b1d1e09b337d.png)

**Comment by GiaFil7** [comment]
@tbushman This didn't work for me... I'm still failing the test...

**Comment by ValeraS** [comment]
I confirm, it fails in Chrome and passes in Firefox.

**Comment by GiaFil7** [comment]
Just tested it on Microsoft Edge and it passes alli tests.

**Comment by tbushman** [comment]
@GiaFil7 This passed in Chrome, FF on mac... Since we support Firefox now, it's good to submit. Thank you!
