### ISSUE TITLE
Problem with Calculator Test Suite

### ISSUE THREAD

**Issue by luciomcamargo** [freeCodeCamp/testable-projects-fcc#638]
#### Issue Description

8 failures reporting on your calculator test suite that don't match with the output of this website:
http://luciocamargo.com/FCC_Calculator/

#### Browser Information

* Chrome Version 69.0.3497.100 
* Microsoft Windows 10 Prop
*Desktop

#### Your Code / Link to Your Pen

```
 http://luciocamargo.com/FCC_Calculator/

![error](https://user-images.githubusercontent.com/43600979/46916187-64171800-cfb7-11e8-8a10-d2bbcdcbbe0d.PNG)

 
 
```

**Comment by ValeraS** [comment]
@luciomcamargo your elements with needed `id`s not clickable. For example, an element with `id=5` doesn't listen for `click` event. Try to move `id`s to inner elements of your `fcc` tags as it has done for `id=decimal`.

**Comment by tbushman** [comment]
@luciomcamargo I hope the solution from @ValeraS reached you! Let us know in another issue if you have further questions.
