### ISSUE TITLE
Pomodoro Clock Tests not passing when they work 

### ISSUE THREAD

**Issue by aljf** [freeCodeCamp/testable-projects-fcc#639]
#### Issue Description

When running the tests for this app, the test will not pass but if manually checked work. 

#### Browser Information

* Browser Name, Version: Chrome 69
* Operating System: Windows 10 
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
 https://codepen.io/believeinthebees/pen/NLaBLG
 
 
```

#### Screenshot

![image](https://user-images.githubusercontent.com/38641143/46922735-14464a00-cfd3-11e8-8f54-4b9c19f49738.png)

**Comment by ValeraS** [comment]
@aljf if set session length 1 and break length 1 and press start then `time-left` shows a strange value.
![image](https://user-images.githubusercontent.com/10867286/46933854-641e2300-d05e-11e8-9d16-5fa5bdf7f8d0.png)

**Comment by aljf** [comment]
Also in the Chrome Dev Console I am receiving an error message 'SyntaxError: Unexpected token :' this hasn't affected the codes performance but perhaps has something to do with the issue.

**Comment by Moto42** [comment]
The timeout error is caused by the  hackey way the test suite trys to 'speed up time' not working.
Basically, it tries to force every instance of setTimeout() and setInterval() to fire at 30ms and doesn't always work.

At line 106, if you change 1000 to 30 you can make your clock run at the speed the tests are expecting.

**Comment by aljf** [comment]
Okay thanks for letting me know! Should I keep the issue open or should we close it?

**Comment by ValeraS** [comment]
@aljf In your case, It's not a problem of the tests. Your Pen still has issues. For example:
- in the break time, if press `reset`, `timer-label` does not reset to `session`;
- after finish session time, timer shows break length and, only after it, shows time and countdowns.

Maybe, it is not all the issues.

**Comment by Moto42** [comment]
I'd keep it open. 
The test wants the clock to run at 33x speed, and fails to force it to do so.
This doesn't fix all the problems in your pen, but it does give the test what it expects to see.

**Comment by ValeraS** [comment]
> The test wants the clock to run at 33x speed, and fails to force it to do so.

@Moto42 why do you think so? In this Pen tests successfully force the timer to run faster. And you'll see it if you run the tests.

**Comment by Moto42** [comment]
When I wrote that, the 1000 ms for each second was defined on line 106 and it was failing.
Now it's on 107 and the test is working.  I dunno what they changed.

You are correct that it still fails test for the reset button and session-ending tests; the question wasn't about those though.
For the tests not clicking your reset button, try changing the <p> elements to <button>s, or something else inherently clickable.
