### ISSUE TITLE
[Scatter Plot] Cross-browser issue - tests failing - Safari

### ISSUE THREAD

**Issue by no-stack-dub-sack** [freeCodeCamp/testable-projects-fcc#64]
Safari Version 9.1.2 (11601.7.7)

@paycoguy, @Christian-Paul Passing 11/15 tests, no errors being thrown, cannot troubleshoot issue because test modal won't open (see #63)

**Comment by Christian-Paul** [comment]
@no-stack-dub-sack Passes all tests on Edge (38.14393.0.0)

Passes 13/15 on IE11 (11.576.14393.0). It appears that our mouseover solution doesn't work properly on IE. The mouseover tests on this and other D3 projects are failing.
