### ISSUE TITLE
validation error

### ISSUE THREAD

**Issue by 0silverback0** [freeCodeCamp/testable-projects-fcc#640]
#### Issue Description

im getting the validation error in my code when i type a number over 120 and click submit but when i run the test it still say i failed it?

#### Browser Information

im using google chrome
* Browser Name, Version: 
* Operating System: windows
* Mobile, Desktop, or Tablet: laptop

#### Your Code / Link to Your Pen

```
 <label id="number-label">*Age:</label>
      <input id="age" type="number" name="age"  min="1" max="120"  placeholder="Age">
 
 
```
https://codepen.io/0SilverBack0/pen/ePGBeE

**Comment by ValeraS** [comment]
@0silverback0 `min` and `max` should be defined for an element with `id=number`.

**Comment by 0silverback0** [comment]
Hey thanks! i would of never figured that out!
