### ISSUE TITLE
markdown previewer not rendered

### ISSUE THREAD

**Issue by paulTchaa8** [freeCodeCamp/testable-projects-fcc#641]
My markdown previewer project proposal can be found here: [my markdown previewer](https://codepen.io/paulTchaa8/pen/Xxjevg)

I've succeeded to make it locally with nodeJs, and i pasted my codes on codepen and imported the `react, react-dom and remarkable` packages with the `setting button` on the js side, but here there is no render as i got locally with nodeJs.

#### Browser Information

* Firefox, Version: 62.0.3
* Operating System: windows 7 home premium
* Mobile, Desktop, or Tablet: PC

#### Your Code / Link to Your Pen

[my markdown previewer](https://codepen.io/paulTchaa8/pen/Xxjevg)

#### Screenshot

![image](https://user-images.githubusercontent.com/40181181/46924202-1c75a800-d01a-11e8-8a3b-6c2e4017a0b1.png)

**Comment by ValeraS** [comment]
@paulTchaa8 remove line
```javascript
const Remarkable = require('remarkable');
```

**Comment by paulTchaa8** [comment]
THANKS my dear @ValeraS  you're right. Now it renders exactly as expected. thanks. Now, why is it said the markdown is not well interpreted in the #editor and/or not well rendered in the #preview?? Could you check this please? i thought it was perfect ,but the FCC checker doesn't agree:
https://codepen.io/paulTchaa8/pen/Xxjevg

**Comment by tbushman** [comment]
@paulTchaa8 Thanks for your patience while we wait for the updated code to sync with the fCC CDN.
