### ISSUE TITLE
HELP - the BackgroundColor doesn't variate as expected

### ISSUE THREAD

**Issue by paulTchaa8** [freeCodeCamp/testable-projects-fcc#642]
#### Issue Description

The **Random Quote** Machine project is validated by the FCC, though the background-color and the text color doesn't variate at all as expected. What could be the problem PLEASE ?

#### Browser Information

* Browser Name, Version: Firefox 62.0.3
* Operating System:  windows 7 home premium
* Mobile, Desktop, or Tablet: PC

#### Your Code / Link to Your Pen
https://codepen.io/paulTchaa8/pen/BqKNJy

**Comment by ValeraS** [comment]
http://api.jquery.com/animate/ `background-color` and `color` cannot be animated unless the [jQuery.Color plugin](https://github.com/jquery/jquery-color) is used.

**Comment by paulTchaa8** [comment]
THANKS A LOT dear @ValeraS you're right. As i included the jquery.Color plugin, the color animation got started. thanks..
