### ISSUE TITLE
can't test code

### ISSUE THREAD

**Issue by ansharmuhammad** [freeCodeCamp/testable-projects-fcc#645]
#### Issue Description

I can't test my code.

#### Browser Information

* Browser Name, Version: chrome,
* Operating System: windows 7 home.
* Mobile, Desktop, or Tablet: Desktop, sony vaio sve14118fgb.

#### Your Code / Link to Your Pen

```
 
 https://codepen.io/anshar/pen/BqdGmd/
 
```

#### Screenshot

![image](https://user-images.githubusercontent.com/39853838/46988609-05bf7600-d12c-11e8-8173-acf8ae2f895c.png)

**Comment by tbushman** [comment]
@ansharmuhammad Hello, @ValeraS may be better at answering react questions, because I've been wrong advising on this. The example at https://stackoverflow.com/a/43942653/3530394 shows a way to link the media state to the react state...

**Comment by ValeraS** [comment]
@ansharmuhammad an `audio` element doesn't have a method `stop` which you try to use:
```javascript
document.getElementById('beep').stop()
```
for stop audio you can use a method `pause()`, and if you need, reset `currentTime` to `0`

**Comment by tbushman** [comment]
@ansharmuhammad I hope you received the solution provided here by @ValeraS . If you have other issues, please let us know!

**Comment by ansharmuhammad** [comment]
thankyou for the response. So sorry for the mistake I made

Pada tanggal Kam, 8 Nov 2018 00.06, Tracey Bushman <notifications@github.com>
menulis:
