### ISSUE TITLE
React-Redux Pomodoro Clock 

### ISSUE THREAD

**Issue by rubendmatos1985** [freeCodeCamp/testable-projects-fcc#646]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
https://codesandbox.io/s/pmlo2py64j
 
 
 
```

**Comment by rubendmatos1985** [comment]
Thanks for answer but if you look better in the Bundle js Audio Section it
says The audio element with id= "beep" must be 1 second or longer. If I
take of the 5 seconds pause i will not able to pass.

And why then i can not pass the other option wich says. The element with id
of beep must stop playing and be rewound to the begining when the element
with id of reset is clicked. I have this one. The problem it's that i used
maybe redux and the behavior it's not exactly the same of the example but
what is the point then?. I must copy and paste?. I dont understand

I think that this script it's a little bit strict. I have made twice this
challenge and never can receive all the points. 😒

**Comment by ValeraS** [comment]
@rubendmatos1985 
1. in `UserInfo`
```javascript
    // setTimeout(()=>{
      this.props.actions.clockIsOn()
    // },5000);
```
2. in `Reducers`
```javascript
    case 'RESET' :{
      return {
        ...
        clockOn: false
        }
    }
```
3. in `actions`
```javascript
export function Reset(){
  return function (dispatch, getState) {
    const audio = document.getElementById('beep')
    audio.currentTime = 0;
    audio.pause()
    return dispatch({
      type: 'RESET',
      
    });
  }
}
```
4. in `Audio` 
```javascript
   if(this.props.timer === 0 && this.props.counter === 0 ){
     audio.play()
  //  }else if(this.props.reset){
  //    audio.currentTime = 0;
  //    audio.pause()
   }
```
And you need to solve only one test.

**Comment by rubendmatos1985** [comment]
Wow 😊!!! You are awesome... could you please explain me the logic of the
curry functions in action??. I thought they were usefull just to make async
actions... like fetching or something like that. I am trying to fix the
other problem. Thanks a lot. I am learning alone and sometimes it is so
hard. If you could give me some recomendations or any book to read i will
appreciate that. Thanks

**Comment by rubendmatos1985** [comment]
that was easy to find!!! thaaaaanks and thaaaaanks!!!

https://codesandbox.io/s/pmlo2py64j

**Comment by ValeraS** [comment]
@rubendmatos1985 You are right in 3. it was overhead, it may be written as:
```javascript
export function Reset(){
    const audio = document.getElementById('beep')
    audio.currentTime = 0
    audio.pause()
    return {
      type: 'RESET',
    }
}
```

In most case, I use documentation and of course Google.
