### ISSUE TITLE
Markdown previewer using other library

### ISSUE THREAD

**Issue by Sh7ne** [freeCodeCamp/testable-projects-fcc#648]
#### Issue Description

The test basically will only pass the html result parsed by 'Marked'. I tried 'Remarkable' but some of the interpretation is not exactly the same like:

In Marked,

```markdown
# h1 
## h2
```

will be parsed to 

```
<h1 id="h1">h1</h1>
<h2 id="h2">h2</h2> 
```

for the other library, like 'remarkable' I am using,

will be parsed to

```
<h1>h1</h1>
<h2>h2</h2>

```

Due to this difference, the test won't passed.

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 https://codepen.io/Sh7ne/pen/EdoBKb
 
 
```

#### Screenshot

<img width="1121" alt="wx20181016-222824 2x" src="https://user-images.githubusercontent.com/10164825/47059115-e826f680-d195-11e8-9683-2cd6f1c8b607.png">

**Comment by ValeraS** [comment]
@Sh7ne Thank you for reporting this. This issue has been fixed in #643 and a new bundle will be deployed soon.
