### ISSUE TITLE
[Drum Machine] Cross-browser issue - Safari / IE - tests failing

### ISSUE THREAD

**Issue by no-stack-dub-sack** [freeCodeCamp/testable-projects-fcc#65]
Safari Version 9.1.2 (11601.7.7)

There's 2 issues here - first, the test modal does not open (see #63), second, similar to #62, we have NodeLists returned by `querySelectorAll()` that we are trying to iterate over with `forEach()`. This method is not supported on NodeLists in pre version 10.X.X Safari browsers or ANY Internet Explorer browser versions (not sure about Edge). 

We will likely have to turn the NodeList into a true Array before iterating, this should solve the second part of this issue.

**Comment by no-stack-dub-sack** [comment]
Added a polyfill which takes care of one part of this issue, although now there are new issues unrelated to NodeList forEach. Seem to be timeout issues on Safari - I think this might have to do with the audio WebApp API because the reaction time from when you trigger a drum pad to when the audio plays is a little slow. Tried just increasing the timeout but that does not seem to do it

**Comment by tchaffee** [comment]
Closing because this is outdated. For now we only support Chrome. We will look at supporting other browsers in an upcoming phase.
