### ISSUE TITLE
Drum Machine - Q-key "Not Working"

### ISSUE THREAD

**Issue by sheedSVNTH** [freeCodeCamp/testable-projects-fcc#654]
#### Browser Information

one of the 8 tests is not passing. the error is claiming that my keypress for audio is not working for letter 'Q'. It works on my end (using Chrome).

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 https://codepen.io/sheedsvnth/pen/GYdZay
 
 
```

**Comment by ValeraS** [comment]
@sheedSVNTH test sends a `Q` key, but you handle a `q` key.
