### ISSUE TITLE
"Personal Portfolio" can't go through the test in the chrome, while the same code can pass through all the test in the chrome.

### ISSUE THREAD

**Issue by AriaDou** [freeCodeCamp/testable-projects-fcc#658]
#### Issue Description

When I finished my project "Personal Portfolio", my code can't go through the test in the chrome, while the same code can pass through all the test in the chrome.
The failed test is: "2. The height of the welcome section should be equal to the height of the viewport."
My height is set to 100 vh but the test says I am off by 1 px.
You can see the detail in the screen shoot.

#### Browser Information

 Windows, Desktop
Chrome 70.0.3538.67,
Firefox 62.0.3 

#### Your Code / Link to Your Pen

```
 https://codepen.io/ariadou/pen/QZBqem
 
```

#### Screenshot

runs on the chrome:
![chrome](https://user-images.githubusercontent.com/18673439/47284051-619c6a00-d618-11e8-98ca-1c28a40a61e4.png)

runs on the firefox:
![firefox](https://user-images.githubusercontent.com/18673439/47284055-65c88780-d618-11e8-8345-18cfdba4112a.png)

**Comment by tbushman** [comment]
@AriaDou This is a known issue in Chrome. Can you try ensuring the browser zoom setting is 100% and see if that helps?

**Comment by tbushman** [comment]
@AriaDou Please see the comment from @ValeraS in #676 for a possible solution!
