### ISSUE TITLE
Drum machine test 8 not passing - please help! 

### ISSUE THREAD

**Issue by numoonchld** [freeCodeCamp/testable-projects-fcc#661]
#### Issue Description

In the linked drum machine project, the sound for each drum element plays when:

- corresponding key is pressed and 
- when the button on the screen is clicked on.

However, the test fails for keypress. Please help. 

#### Browser Information
* Browser Name, Version: Chrome,  69.0.3497.100
* Operating System: macOS
* Mobile, Desktop, or Tablet: notebook

#### Your Code / Link to Your Pen
https://codepen.io/numoonchld/pen/ejGywG?editors=1011

#### Screenshot
![image](https://user-images.githubusercontent.com/17598505/47376374-19607300-d710-11e8-8366-a9eb9dd2a54b.png)

**Comment by ValeraS** [comment]
@numoonchld test doesn't send `keypress` event. Change it to `keydown` and you'll pass the test.

**Comment by numoonchld** [comment]
@ValeraS thanks! all parts of test passed!
