### ISSUE TITLE
Not passing even though the solution is correct

### ISSUE THREAD

**Issue by jmaldia** [freeCodeCamp/testable-projects-fcc#664]
#### Browser Information

* Browser Name, Version: Chrome 70.0.3538.67 
* Operating System: Mac OS Mojave
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

 https://codepen.io/jonmaldia/pen/NOEzgQ

#### Screenshot

![image](https://user-images.githubusercontent.com/1197551/47465169-b9260b80-d7b9-11e8-8a58-fcc4b0b41e28.png)

![image](https://user-images.githubusercontent.com/1197551/47465200-f25e7b80-d7b9-11e8-9ee1-37f3d893327e.png)

**Comment by tbushman** [comment]
@jmaldia Looks like you fixed this. What was causing it?

**Comment by ValeraS** [comment]
@jmaldia place your `a` tags into `li` tags.
