### ISSUE TITLE
BUILDING PORTFOLIO PAGE

### ISSUE THREAD

**Issue by Delux007** [freeCodeCamp/testable-projects-fcc#665]
#### Issue Description
By basically trying to run the test

#### Browser Information
That I have done the code properly, repeatedly doing what everyone has said to do. But still cannot pass the project.

*Anonymous
* MAC OS
* DESKTOP

BUILDING A PORTFOLIO PAGE
https://codepen.io/Delux003/pen/zmygVY
 
 
 
```

#### Screenshot
<!-- Add a screenshot of your issue -->

**Comment by tbushman** [comment]
@Delux007 In order to have the `#welcome-section` be the same height as the viewport, use a relative height, like:   
```  
#welcome-section{
  height: 100vh;
 }  
```
