### ISSUE TITLE
Drum Machine test 6

### ISSUE THREAD

**Issue by zachdog6** [freeCodeCamp/testable-projects-fcc#666]
#### Issue Description
Test 6 of drum machine fails saying no audio was triggered, but pressing the keys clearly triggers the audio.

#### Browser Information
Chrome

* Operating System: Windows
* Mobile, Desktop, or Tablet: Laptop

#### Your Code / Link to Your Pen
https://codepen.io/zachdog6/pen/RevjoE

#### Screenshot
![image](https://user-images.githubusercontent.com/23748179/47583405-fe168300-d91c-11e8-86e3-53710e35bb32.png)

**Comment by ValeraS** [comment]
@zachdog6 replace `keypress` with `keydown`
@DiegoAlexanderManjarres on line 208 use `e.key.toLowerCase()`

**Comment by zachdog6** [comment]
Thanks for the help!
