### ISSUE TITLE
H2 tags

### ISSUE THREAD

**Issue by MarkMcDaniels** [freeCodeCamp/testable-projects-fcc#669]
#### Issue Description

It doesn't always recognize the h2 tags. The one on the bottom of my editor works when it's simple, but if I add a sentence to it, it will fail.

#### Browser Information

* Browser Name, Version: Chrome current
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: desktop

#### Your Code / Link to Your Pen

https://codepen.io/MarkMcDaniels/pen/wYOWLK
```
this.state = {
      input: "\n# This is a markdown previewer\n## It's uses the marked.js library.\n\nHere's a link to the documentation, [links](https://marked.js.org/#/README.md#README.md).\n\n\n\n\n\n\n\n>You can bock quotes.\n\n\n\n\n\n- Or make lists\n\n - They come in all the best **decorations**\n\n\n\n\n\n```\nfunction getIt(){\n\treturn 'that thing';\n}```\n\n\n\n\n\n\n\n# Have a Hedgehog!!\n\n\n\n\n\n\n\n![A hedghog](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkaE8ENrEZ_S5BQtqRiADhbgf-bfOt1an3Q4F_AkUox3FgszHt5w)\n\n\nInline code to finish it off, `<span>Huzzah!</span>`\n\n\n\n## test"
    };
 ```

**Comment by tbushman** [comment]
@MarkMcDaniels Your tests pass in Firefox, so you can consider your project completed. Bug reproduced in Chrome. Thanks for reporting this.
