### ISSUE TITLE
Random Quote Machine Horizontal Centering Test Failed

### ISSUE THREAD

**Issue by esmith1412** [freeCodeCamp/testable-projects-fcc#670]
#### Issue Description

I created a 3 x 3 CSS Grid, and placed my quote-box element in the center cell. I thought that this would be enough for the horizontal alignment test to pass, but every time I run it, I get the message that the element is not horizontally centered. Does horizontal centering mean something else that I'm not aware of? I'm not sure why this wouldn't pass this test. It's currently passing all the other tests.

#### Browser Information

* Browser Name, Version: Google Chrome, 70.0
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Laptop

#### Your Code / Link to Your Pen

```
 https://codepen.io/esmith1412-the-encoder/pen/LgJRJQ
 
```

#### Screenshot

![screenshot 2018-10-30 09 09 17](https://user-images.githubusercontent.com/42571700/47720175-a8dfb780-dc23-11e8-8f0f-d2083a1fe712.png)

**Comment by ValeraS** [comment]
@esmith1412 Your `#quote-box` does not in the center of the cell. To center it, add next to `#quote-box` CSS:
```css
  align-self: center;
  justify-self: center;
```

**Comment by esmith1412** [comment]
Thanks! I didn't realize it had to be centered within the cell itself.
