### ISSUE TITLE
different results when running tests twice in a row

### ISSUE THREAD

**Issue by pulamusic** [freeCodeCamp/testable-projects-fcc#671]
#### Issue Description

When I run the tests on the data vis: bar chart I get a certain number of tests passed (e.g., 10/14 passed). Without changing my code, if I refresh the page and run the tests again I get a different number of tests passed (e.g., 12/14 passed).

#### Browser Information

* Browser Name, Version: Chrome version 70.0.3538.77
* Operating System: MacOS Mojave
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

I am coding this project locally and posting it to GitHub Pages
* [Link to GitHub Page](https://pulamusic.github.io/barGraph/)
* [Link to GitHub repo](https://github.com/pulamusic/barGraph)

**Comment by tbushman** [comment]
@pulamusic This is a known problem with the tooltip tests for cases where the viewport crops the graph. The tests query a random `<rect>` and test the `mouseover` event. If that rect isn't in view, the tests fail. We minimize this error by using a very wide viewport setting in the automated tests. Try expaning the window width and let us know if that helps.
