### ISSUE TITLE
Chrome displays differently than Firefox or Vivaldi

### ISSUE THREAD

**Issue by nimaipandit** [freeCodeCamp/testable-projects-fcc#673]
#### Issue Description

Chrome displays huge gap at top between header and image 
the site looks great in Vivaldi and Firefox

#### Browser Information

* Browser Name, Version: Chrome version 70.xxx 
* Operating System: Mac OSX 10.13
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
 
 link to my codepen here: 

 https://codepen.io/dominick_designs_websites/pen/OBYJeG
```

#### Screenshot

see huge gap here in chrome: https://share-inspiration.d.pr/s59qVQ

it's not here in Vivaldi:

**Comment by tbushman** [comment]
@nimaipandit I couldn't reproduce the issue in Chrome (mac) -- no gap seen. If your tests pass, you may consider your project completed.  
<img width="983" alt="screen shot 2018-11-01 at 1 12 37 am" src="https://user-images.githubusercontent.com/7049294/47837922-501f3480-dd73-11e8-8684-cd185bfb0e08.png">

**Comment by ValeraS** [comment]
@nimaipandit try changing to `grid-template-rows: auto;`
