### ISSUE TITLE
cant submit an email for Product landing page

### ISSUE THREAD

**Issue by hinero2017** [freeCodeCamp/testable-projects-fcc#674]
#### Issue Description

can't pass by the test #12 "When I click the #submit element, the email is submitted to a static page (use this mock URL: https://www.freecodecamp.com/email-submit) that confirms the email address was entered (and that it posted successfully)."

#### Browser Information

i use VS Code and freeCodeCamp CDN link

* Browser Name, Version: Chrome
* Operating System: 
* Mobile, Desktop, or Tablet: macpro

#### Your Code / Link to Your Pen

```
 <form id="form" action="https://www.freecodecamp.com/email-submit">
  <input name="email" id="email" type="email" placeholder="Enter your email address" required>
  <input id="submit" type="submit" value="Get Started">
</form>
 
 
```

**Comment by tbushman** [comment]
Also a problem in #635 
@Bouncey @raisedadead I realized my suggestion in #635 is invalid for this method because I don't know how to use access-control settings in the form element, or if there's something wrong with the endpoint. ...

**Comment by ValeraS** [comment]
@tbushman the test does not submit a form it only checks attributes of tags.
@hinero2017, please provide a full text of the error.

**Comment by hinero2017** [comment]
> @tbushman the test does not submit a form it only checks attributes of tags.
> @hinero2017, please provide a full text of the error.

hi @tbushman here is my code below. thank you in advance.

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="style.css">
    <title>Product Landing Page</title>
</head>
<body>




<div class="container-header">
     <header id="header">
        <nav class="navbar navbar-default" id="nav-bar">
           <div class="container-fluid">
               <form class="navbar-form navbar-left">
                 <div class="logo">
                   LOGO
                 </div>
               </form>
               <ul class="nav navbar-nav navbar-right">
                   <li><a href="#features" class="nav-link">Features</a></li>
                   <li><a href="#how it works" class="nav-link">How it works</a></li>
                   <li><a href="#pricing" class="nav-link">Pricing</a></li>
               </ul>
           </div>
         </nav>


      
      <div class="img">
            <img src="style_lins.jpeg" alt="header image" id="header-img">
      </div> 

    </header>
</div>
<br>

<div class="form">
    <form id="form">
       <iframe id="video" width="560" height="315" 
           src="https://www.youtube.com/embed/ANJTuSiMH7E" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" vallowfullscreen>
       </iframe>
    </form>

    
        <div id="features">Features</div>
        <div id="how it works">How it works</div>
        <div id="pricing">Pricing</div>

</div>
    
    <div class="container-submit">
            <form id="form" action="https://www.freecodecamp.com/email-submit">
                <input name="email" id="email" type="email" placeholder="Enter your email address" required>
                <input id="submit" type="submit" value="Get Started">
          </form>
    </div>
   

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js"></script>
</body>
</html>

**Comment by tbushman** [comment]
@hinero2017 , @ValeraS is right. I can check in a bit, but I think the tests look for a `<button>` element for "submit" and a `method="POST"` on `<form>` ...

**Comment by hinero2017** [comment]
> @hinero2017 , @ValeraS is right. I can check in a bit, but I think the tests look for a `<button>` element for "submit" and a `method="POST"` on `<form>` ...

i actually redone all page and its just start working LOL
