### ISSUE TITLE
Personal Portfolio User Story #10 

### ISSUE THREAD

**Issue by rachel2muller** [freeCodeCamp/testable-projects-fcc#676]
#### Issue Description

User Story #10: The height of the welcome section should be equal to the height of the viewport.

Help! I can't figure out what is going on with it. I have tried making it 100vh and still it isn't working. I don't know if I am changing the right one for this. I have even added class intro to the welcome section in css that didn't work. . I have add an id of welcome section to css. this is the last test that I am having trouble with.

#### Browser Information

* Browser Name, Version: Chrome, Version 70.0.3538.77 
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: laptop

#### Your Code / Link to Your Pen
https://codepen.io/Rachel2muller/pen/KGYKyw
```
 
Thank you! Your all awesome!

**Comment by ValeraS** [comment]
@rachel2muller by default elements have `box-sizing: context-box` and an actual height is calculated as `border-top + padding-top + height + padding-bottom + border-top`. For further reading https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing.
You can either set `box-sizing: border-box` and `height: 100vh` or change `height` according to the above formula.

**Comment by tbushman** [comment]
@ValeraS Thank you! This also addresses #658 .
