### ISSUE TITLE
Test failed (media queries and flexbox tests)

### ISSUE THREAD

**Issue by fratule** [freeCodeCamp/testable-projects-fcc#679]
#### Issue Description

Project name: [ "Build a Product Landing Page" ](https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-projects/build-a-product-landing-page/)

Hello!

I have media queries and flexbox in my project, but tests on these points are failed in Chrome (only when files are local). When I opened a link from GitHub Pages - all tests are passed. 

The issue exist in Chrome, but in Firefox all is good.

[ Link to my project ](https://magic-in.space/FreeCodeCamp/html-tasks/Product-Landing-Page/index.html)

#### Browser Information

* Google Chrome / Version 70.0.3538.77 (Official Build) (64-bit)
* Windows 10 x64
* Desktop

#### Your Code / Link to Your Pen

 [ Link to my project files on GitHub ](https://github.com/fratule/fratule.github.io/tree/master/FreeCodeCamp/html-tasks/Product-Landing-Page)

#### Screenshot

![image](https://user-images.githubusercontent.com/20722952/47925609-4e668580-dec7-11e8-8cff-8209c7a7024f.png)

**Comment by tbushman** [comment]
@fratule Please set up your project with a local server, such as `live-server` or Python simple server. Here is some more information:  https://www.npmjs.com/package/live-server
In order for the tests to detect CSS in external files, a server of some kind is needed. You may also put your code into Codepen.

**Comment by fratule** [comment]
Thank you!
