### ISSUE TITLE
Scatter Plot Graph

### ISSUE THREAD

**Issue by rubendmatos1985** [freeCodeCamp/testable-projects-fcc#684]
#### Issue Description

Hi my graph has the element with id tooltip and the requiered property. Any idea why i can not pass the test???

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 https://codepen.io/Ruben1985/pen/qJMLNR?editors=0110
 
 
```

**Comment by ValeraS** [comment]
@rubendmatos1985 You have a `tooltip` variable which is bound to `text` element inside `div` with `id="tooltip". And you work with `text` element instead of `div`.

**Comment by rubendmatos1985** [comment]
thanks!!!! 🤗
