### ISSUE TITLE
D3 Heat Map Project, test #9 not passing

### ISSUE THREAD

**Issue by fendermaniac** [freeCodeCamp/testable-projects-fcc#685]
#### Issue Description

I have passed every other test in this project, but am stuck on test 9.

My heat map should have cells that align with the corresponding month on the y-axis.

month values don't line up with y locations : expected false to be true

I don't seem to understand what this test is looking for in order to resolve as true.  

I followed other issues with this same test such as issue #412.  I made sure the domain and range were ascending, I set up the range starting at zero as suggested in the FreeCodeCamp forum.  https://www.freecodecamp.org/forum/t/visualize-data-with-a-heat-map/230440/4.

What am I missing here?

#### Browser Information

* Browser Name, Version: Version 70.0.3538.77 (Official Build) (64-bit) 
* Operating System: Windows 10 
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

``` https://codepen.io/fendermaniac/pen/GYzBaR ```

#### Screenshot

![image](https://user-images.githubusercontent.com/1470569/47972205-00d54e80-e068-11e8-9979-aeebff350b27.png)

**Comment by ValeraS** [comment]
@fendermaniac Don't hide your y-axis.

**Comment by fendermaniac** [comment]
@ValeraS That was exactly it.  Thanks!
