### ISSUE TITLE
HELP ON GETTING THE FULL render of my React Calculator 

### ISSUE THREAD

**Issue by paulTchaa8** [freeCodeCamp/testable-projects-fcc#688]
#### Issue Description

Hi. Please why can’t i get the codepen [full render](https://codepen.io/paulTchaa8/full/NOmbwM) of my react calculator while the [codepen render](https://codepen.io/paulTchaa8/pen/NOmbwM) is correctly rendered.? I mean until now, i just had to replace the **pen** on the url of my code with the **full** to get a complete render, but nothing is rendered for my calculator. Any idea please??

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 
 
```

**Comment by ValeraS** [comment]
@paulTchaa8 Try in the Pen setting change JavaScript Preprocessor to `Babel`
