### ISSUE TITLE
same test suite for different projects

### ISSUE THREAD

**Issue by elementh11** [freeCodeCamp/testable-projects-fcc#690]
#### Issue Description

When I am forking the CodePen for the "Survey Form" project (2nd project) it comes with the same test suite as for the "Tribute page" project (1st project).

#### Browser Information

CodePen
* Browser Name, Version: Chrome
* Operating System: Win10
* Mobile, Desktop, or Tablet: Desktop

**Comment by tbushman** [comment]
@elementh11 Thanks for bringing this to our attention. The dropdown menu to select the project seems to be inoperable at the moment.

**Comment by tbushman** [comment]
@elementh11 In the Javascript window in codepen, there are two lines that set the default test suite on load. The first line starts with `const projectName = ` and the second starts with `localStorage.setItem(...`  
If you remove those two lines and re-load you can select whichever test suite you wish.
