### ISSUE TITLE
System doesn't seem to capture my input elements inside the form

### ISSUE THREAD

**Issue by ashefree** [freeCodeCamp/testable-projects-fcc#699]
I have created my radio buttons and my drop down menu inside my <form> </form> element tags but 
I get an error message saying my elements are not in the form
#### Browser Information

* Chrome, 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

https://codepen.io/soter-tristan/pen/OaRzma

 
 
 
```

#### Screenshot
<!-- Add a screenshot of your issue -->

**Comment by tbushman** [comment]
@ashefree Please remove the closing `</div>` tag on this line:  
```  
<label id="number-label" for="number">Age:
    <input type="number" id="number" min="18" max="120" placeholder="How old are you?">
  </label>
 </div>   //this one
```  
...and then a new error will remind you to use a `value` attribute on your radio buttons.
