### ISSUE TITLE
Product Landing Page: ifame not being accepted.

### ISSUE THREAD

**Issue by Norv52** [freeCodeCamp/testable-projects-fcc#701]
#### Browser Information

I am attempting to complete the Product Landing Page Challenge.  The iframe portion of the test is not being accepted.
* Browser Name, Version:  I use Google Chrome, Version 70.0.3538.102 (Official Build) (64-bit)
* Operating System:  Windows 10 (64 bit)
* Mobile, Desktop, or Tablet: 
I use a laptop (Dell Inspiron 15000)
#### Your Code / Link to Your Pen

```
 Below is the link to my Pen.  
 https://codepen.io/Norv/pen/YRQPay
 
```

#### Screenshot

[Problem with Product Landing Page.pdf](https://github.com/freeCodeCamp/testable-projects-fcc/files/2587462/Problem.with.Product.Landing.Page.pdf)

**Comment by tbushman** [comment]
@Norv52 Your video will pass if it has `id="video"` so add that to your `iframe` and that should do it. :)  
```  
<iframe id="video" ...  
```

**Comment by Norv52** [comment]
Got it!!!!   On to the next one.  Again, thanks for suggestion.  It made me review every line of html and css.  Found a couple of "hanging <divs>.
