### ISSUE TITLE
Technical documentation page | Tests 15/16  | bug on not fullscreen run | not duplicate!  

### ISSUE THREAD

**Issue by dagolinuxoid** [freeCodeCamp/testable-projects-fcc#702]
Source: Responsive web design certification / Responsive Web Design Projects / Build a Technical Documentation Page

* Browser Name, Version: latest Firefox and Chromium
* Operating System: Linux (Elementary OS but it doesn't matter)
* Mobile, Desktop, or Tablet: Desktop

> 1. On regular sized devices (laptops, desktops), the element with id="navbar" should be shown on the left half of the screen. It should always be visible to the user and should remain stationary. You may need to enlarge the viewport or zoom out to ensure the navbar doesn't scroll with the page content.

When viewport is wide enough I see all green 16/16 tests passed but when I narrow it and run tests again I receive only 15/16. I tried different media queries combinations but didn't pass it. I've checked other closed issues on the topic but no luck either. Is it a bug in tests or I've missed something?

Link to my [codepen project](https://codepen.io/dagolinuxoid/pen/WvRXKR)

**Comment by ValeraS** [comment]
@dagolinuxoid It's correct behavior and error says: `Please run this test in a larger window (before any media queries)`. If you press the `Tests` button, you'll see detailed errors.

**Comment by dagolinuxoid** [comment]
@ValeraS,  спасибо!
