### ISSUE TITLE
Product Landing Page - Test 2

### ISSUE THREAD

**Issue by terry-sydaus** [freeCodeCamp/testable-projects-fcc#707]
#### Issue Description
When I run the Product Landing Page Test, test number 2 is failing due to the src attribute in my img element not being a url (ie. http://....).

I am using a locally stored file for the img element and my page is working fine.

It would appear that the test is setup to test pages built using codepen or some other on-line development environment.

I am developing locally on my own machine in my own development environment.

#### Browser Information

* Browser Name, Version: Firefox 63.0
* Operating System: Ubuntu 18.04
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
<img id='header-img' src="plp.png" alt='My Product Logo'/>
 
```

#### Screenshot

![2018-11-19-122512_3840x1080_scrot](https://user-images.githubusercontent.com/19356480/48681395-5b3ce600-ebf6-11e8-9c38-c0cd6f0f4f31.png)

**Comment by terry-sydaus** [comment]
Thank you very much Tracey.
That sorted the issue.
I love the live-server and the way it automatically updates the web page
when it detects a change in the source. Just awesome.

Do you know how I can submit my projects to FreeCodeCamp when they are
complete
I do not have a URL for my projects as the files reside on my local machine
and I have not set up a webserver.
I don't want to paste the code into codepen just to submit them to FCC.

**Comment by terry-sydaus** [comment]
Awesome Tracey. Thank you again.
I have set up a single GitHub repository for all my FCC projects.
I have used Heroku as part of The Odin Project that I am also working my
way through.
So, I will explore both the options you have suggested.

**Comment by tbushman** [comment]
@terry-sydaus I was looking more at GitHub Pages and it looks like a good bet for html/css/js . OK, great!
