### ISSUE TITLE
 2. The height of the welcome section should be equal to the height of the viewport.

### ISSUE THREAD

**Issue by rickvian** [freeCodeCamp/testable-projects-fcc#708]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 
 
```

**Comment by ValeraS** [comment]
duplicate #709

**Comment by tbushman** [comment]
Awaiting merge of https://github.com/freeCodeCamp/cdn/pull/17 but fixed in #710   
Thank you @ValeraS
