### ISSUE TITLE
D3 Heat Map - Test #9 Edge Case

### ISSUE THREAD

**Issue by tom-p-uk** [freeCodeCamp/testable-projects-fcc#71]
#### Issue Description
I raised a similar issue yesterday with the scatter plot project, but the same problem appears to be happening with the heat map project I built today, too. It's failing a test because apparently the cells don't line up with the appropriate y-axis values, when they clearly do just by looking at the graph, or by checking out the attributes of the relevant svg elements using Chrome's dev tools. Might be worth having a look at that test and maybe seeing if there is a more flexible way of checking if a project has satisfied the particular user story. The current test logic is a bit too restrictive IMO!

#### Your Code / Link to Your Pen

Codepen: http://codepen.io/tom-p-uk/pen/ZeQEaE?editors=1010

Failing test code:

```
 it('9. My heat map should have cells that align with the corresponding month on the y-axis.', function () {
	                var cellsCollection = document.querySelectorAll('.cell');
	                FCC_Global.assert.isAbove(cellsCollection.length, 0, "Could not find any elements with a class=\"cell\" ");

	                //convert to array
	                var cells = [].slice.call(cellsCollection);
	                var sortedCells = cells.sort(function (a, b) {
	                    return a.getAttribute("data-month") - b.getAttribute("data-month");
	                });

	                //check to see if the y locations of the new sorted array are in ascending order
	                for (var i = 0; i < sortedCells.length - 1; ++i) {
	                    FCC_Global.assert.isAtMost(+sortedCells[i].getAttribute("y"), +sortedCells[i + 1].getAttribute("y"), "month values don't line up with y locations ");
	                }
	            });
```

**Comment by Lakston** [comment]
I did not encounter this problem, finished project can be seen here : https://lakston.github.io/d3-heatmap/

**Comment by tchaffee** [comment]
@paycoguy @Christian-Paul @QuincyLarson @tbushman @no-stack-dub-sack I suggest the same solution for this as for issue #70. I would just change the test text to better reflect what it is actually testing:

"The heat map cells must have a data-month attribute, and cells with a month earlier in the year must appear above cells with a later month in the year"

If possible I would like some feedback before moving ahead.

**Comment by paycoguy** [comment]
Yes, we should impose a sort order on the axis.  As you can see, some campers find the tests too restrictive, but I think it's too hard to create flexible tests to account for every possible variation.

**Comment by tchaffee** [comment]
@paycoguy Thanks for your quick response and your input. It looks like @tbushman actually dug into this and came up with a solution to check that the axis align with the data points, and it should work no matter how the camper sorts the data. PR #127.
