### ISSUE TITLE
FCC: Personal Portfolio | User Story #11: The navbar should always be at the top of the viewport.

### ISSUE THREAD

**Issue by Angelosne** [freeCodeCamp/testable-projects-fcc#712]
#### Issue Description
My solution has the nav bar at the top always but there is the error

3. The navbar should always be at the top of the viewport.
Navbar's parent should be body and it should be at the top of the viewport : expected 50 to be close to 0 +/- 15
AssertionError: Navbar's parent should be body and it should be at the top of the viewport : expected 50 to be close to 0 +/- 15
    at s.H (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:262:7459)
    at s.e.(anonymous function) [as approximately] (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:325:126)
    at Function.n.approximately (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:224:4043)
    at r.<anonymous> (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:154:332349)
    at O (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:154:326023)
    at Generator._invoke (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:154:325811)
    at Generator.e.(anonymous function) [as next] (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:154:326202)
    at r (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:45:84770)
    at i (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:45:84980)
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:45:85039

https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-projects/build-a-personal-portfolio-webpage

#### Browser Information
Chrome 70.0.3538.102 64bit windows 7

#### Your Code / Link to Your Pen

https://codepen.io/angelosn/pen/WYdVRm

```
 <script src="https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js"></script>
<style>
  header{
    
  }
  #navbar ul{
    list-style-type: none;
    margin: 0;
    padding: 0;
    background-color: red;
    position: fixed;
    overflow: hidden;
    top: 0;
    width: 100%;
  }
  #navbar li  {
    float:left;
    
}
  #navbar li a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}
  #navbar li a:hover {
    background-color: #111;
}
  
  @media (max-width:500px){
    #welcome-section{color:red;}
  }
  
  main {
    margin-top:50px
  }
  #welcome-section {
    background-color:yellow;
    height:100vh;
  }
  #projects {
    background-color:blue;
    height:100vh;
  }
</style>
<header>
  <nav id="navbar">
  <ul>
    <li><a href="#welcome-section">Welcome</a></li>
    <li><a href="#projects">Projects</a></li>
  </ul>
</nav>
</header>
<main>
<section id="welcome-section">
  <h1>Hi this is my portfolio</h1>
</section>
<section id="projects">
  <div class="project-tile">Hi this is my portfolio</div>
  <a href="https://codepen.io/freeCodeCamp/full/zNBOYG" target="_blank" id="profile-link">This is what I should look like</a>
</section>
</main>


 
 
```

**Comment by tbushman** [comment]
@Angelosne Although the navbar is technically behaving correctly because the `<ul>` element is positioned correctly, please ensure that the navbar element itself has the css properties that position it at the top. I tried adding this to the css, and the project passed the tests:  
```  
#navbar {
    position: fixed;
    top: 0;
  }  
```

**Comment by TesaRocks** [comment]
Hi I am having the same problem but cannot make it work for some reason...

Can anyone please give me a hand? thanks in advance!!!!

https://codepen.io/TesaDietl/full/wvvxWJg
