### ISSUE TITLE
Landing Page IFrame problem

### ISSUE THREAD

**Issue by mazation** [freeCodeCamp/testable-projects-fcc#715]
#### Issue Description
The test shows a mistake `#video should be an <iframe> or <video> element`. While I definitely included iframe tag in my html file.

#### Browser Information

* Browser Name, Version: Firefox 63
* Operating System: Ubuntu 18.04
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
https://codepen.io/mazation/pen/OavNMq

 
 
 
```

#### Screenshot
I've deleted `</video>` but it still doesn't work
![default](https://user-images.githubusercontent.com/44902742/49033731-bf047780-f1d1-11e8-9148-aa01a5c56ff3.png)

**Comment by ValeraS** [comment]
@mazation Two elements can't have the same `id`. Your code contains another element with `id=video`.
