### ISSUE TITLE
The .nav-link with href="#" is not linked to a corresponding element on the page : expected null to not equal null

### ISSUE THREAD

**Issue by meera-c123** [freeCodeCamp/testable-projects-fcc#716]
<script src="https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js"></script>

<header id="header">  
  <nav id="nav-bar">
    <div class="nav-container">
      <div class="logo">
        <img src="https://images.pexels.com/photos/1162361/pexels-photo-1162361.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260" id="header-img">
      </div>
      <div class="logo">
        <ul>
        <li><a class="nav-link" href="#destination">Destination</a></li>
        <li><a href="#vacation" class="nav-link">Vacation</a></li>
        <li><a href="#cruise" class="nav-link">Cruise</a></li>
        <li><a href="#" class="nav-link" id="ph" style="text-decoration:none"> Ph : 343.345.8653</a></li>
        </ul>
      </div>
    </div>
  </nav>
</header>

<p><p><p>
    
<div class="container">   
  <div class="flex1">
    <p><img src="https://images.unsplash.com/photo-1543166803-f0309083d510?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=52a64bcb0be4089bea5ccb1e80463618&auto=format&fit=crop&w=634&q=80" class="travel-img"></p>    
  </div>
  
  <div class="flex1" id="flex2"> 
      <h2><em>"Live with  no excuses and travel with no regrets."</em></h2>
      <video  id="video" width="320" height="240" controls>
      <source        src="https://www.videvo.net/videvo_files/converted/2016_05/preview/524013672.mp456058.webm" type="video/mp4">  
</video>
   
<section id="vacation">
  <p >    
    <h3><strong><em><u>Vacation Types at a Glance</u></em></strong></h3><p>
    <strong>All-Inclusive:</strong> Accommodations, meals, drinks, entertainment, and activities are all included.<p>
<strong>Family:</strong> Experience a vacation with kids, teens, and parents in mind.<p>
    <strong>Casino:</strong>
Toss the dice or spin the wheel at one of our thrilling casino destinations.
</section>
      
<section id="destination"> 
 
    <h3><strong><em><u>Top Destinations in the World</u></em></strong></h3><p> 
<strong>Africa : </strong>Explore numerous cultural experiences, vibrant cities, stunning landscapes and a diverse range of wildlife.<p>
<strong>Asia</strong>Explore Cambodia, China, Hong Kong and Japan to Singapore, Thailand and Indonesia.<p>
<strong>Australia</strong>
From Sydney and the Great Barrier Reef, to the Outback, explore it all.<p>  
</section>
    
<section id="cruise">
     <h3><u><strong><em>
     Cruise </em></strong><p></u></h3>
        See a variety of destinations like, Alaska, Cuba, the Pacific Northwest, the Transatlantic and more with Royal Caribbean International Cruises.
</section>
 
 </div>

</div>

  <form id="form" action="https://www.freecodecamp.com/email-submit" >
      <label id="label"><strong><em>Subscribe to get 10% off your first trip!</strong></em></label><p>
      <input type="email" id="email" placeholder="Enter Email"  required />         
      <input  type="submit" value="Submit" id="submit" >
    </form>  
</body>

**Comment by mano95** [comment]
he .nav-link with href="#" is not linked to a corresponding element on the page : expected null to not equal
