### ISSUE TITLE
RE: id="project-tlte"

### ISSUE THREAD

**Issue by Sehbaz** [freeCodeCamp/testable-projects-fcc#719]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 
 
```

**Comment by Sehbaz** [comment]
For the test of the porfolio page it shows error in the id called "project-tile" which is wrong as it has an spelling error.

**Comment by tbushman** [comment]
Hi, thanks for the reminder. This was fixed #706 and then wasn't merged into the CDN file. This will be remedied soon.

**Comment by tbushman** [comment]
Closing this as confirmed expected behavior.
