### ISSUE TITLE
Checkbox-value, user story 14 bug

### ISSUE THREAD

**Issue by jose1134** [freeCodeCamp/testable-projects-fcc#722]
#### Issue Description

I just did everything described to pass for all of the user stories and for some reason I still get a check box "value" problem even though all my checkboxes have value.****

#### Browser Information

* Browser Name, Version: Safari/ most up to date
* Operating System: Mac Osx
* Mobile, Desktop, or Tablet: laptop 

#### Your Code / Link to Your Pen

```
 
 https://codepen.io/jose1134/pen/Oajpgy

in my codeine it shows that I have multiple check boxes and still gives that it did not pass the test.
 
```

#### Screenshot

<img width="861" alt="screen shot 2018-12-07 at 11 05 11 am" src="https://user-images.githubusercontent.com/37092658/49658553-58246100-fa10-11e8-99e4-1e51d33a005c.png">

**Comment by tbushman** [comment]
@jose1134 Your tests appear to be passing without errors in Chrome :). We're not officially supporting Safari yet. Thank you.

**Comment by jose1134** [comment]
Thank you
