### ISSUE TITLE
Technical Documentation Page: User Story #14

### ISSUE THREAD

**Issue by leaf2fire** [freeCodeCamp/testable-projects-fcc#723]
#### Issue Description

> On regular sized devices (laptops, desktops), the element with id="navbar" should be shown on the left side of the screen and should always be visible to the user.

Sometimes fails depending on display dimensions and implementation in codepen. It seems to work consistently if the page fills the whole screen.

#### Browser Information

* Browser Name, Version: Google Chrome Version 70.0.3538.110 (Official Build) (64-bit)
* Operating System: Windows 10 
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

Implemented using grids and overflow.

[https://codepen.io/evnl/pen/ebOWpj](pen)

**Comment by ValeraS** [comment]
@leaf2fire It is correct behavior, tests should be run on a window with `width` greater 850px. It is said in an error message:
> Please run this test in a larger window (before any media queries): expected 664 to be above 850
