### ISSUE TITLE
Made this a bug post by mistake

### ISSUE THREAD

**Issue by Code3759** [freeCodeCamp/testable-projects-fcc#724]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 
 
```

**Comment by tbushman** [comment]
@Code3759 Should I close this issue? Let us know.  
Hello, please provide some more information about the error you are experiencing. Indicate which test is failing and provide a screenshot, a code sample, or a link to your project.
