### ISSUE TITLE
Uncaught TypeError: Cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by seansangh** [freeCodeCamp/testable-projects-fcc#725]
#### Issue Description

I am working on a Pomodoro Clock, and I don't understand how to correct the error below when it appears as though my output is accurate. (this error is shown for several tests)

Uncaught TypeError: Cannot read property 'bind' of undefined (pen.js:180)
Error: Uncaught TypeError: Cannot read property 'bind' of undefined (pen.js:180)
    at uncaughtException.a.onerror (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:154:436853)

#### Browser Information

* Google Chrome, Version: 70.0.3538.110 (Official Build) (32-bit)
* Operating System: Windows 7 Enterprise
* Desktop

#### Your Code / Link to Your Pen

```
 
https://codepen.io/seansangh/pen/BvaQEw
 This should not pass all of the tests, as it is not the final version, but it should pass more tests than it currently is shown as passing.
```

**Comment by ValeraS** [comment]
@seansangh Please provide a link to your Pen.

from the error message, it is caused by a code of a Pen. Look at line 180.
```
Uncaught TypeError: Cannot read property 'bind' of undefined (pen.js:180)
```

**Comment by seansangh** [comment]
https://codepen.io/seansangh/pen/BvaQEw

I still can't  seem to find the problem, because it appears as though line 180 isn't the problem.

**Comment by ValeraS** [comment]
when I press a start button I see next errors in the console:
![image](https://user-images.githubusercontent.com/10867286/49698180-59e95280-fbd1-11e8-8527-08f1daa360e9.png)

try to fix them
