### ISSUE TITLE
Responsive Web Design - Portfolio

### ISSUE THREAD

**Issue by X-ritch** [freeCodeCamp/testable-projects-fcc#727]
The code on the below have not passed the requirement #8 which is seen below. Although, there are the profile-link id and  on new Github page is directed, requirements could not completed yet. Is there any mistakes which I have not seen before?

#8 My portfolio should have a link with an id of profile-link, which opens my GitHub or FCC profile in a new tab.

#### Issue Description
 When the test script sometimes run, there is no response and white page occurs. It was tested also on Chrome and Opera ones. 

#### Browser Information

* Browser Name, Version: Firefox 63.0.3 (64 bit)
* Operating System: Windows10 1809 (17763.134)
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
 

<script src="https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js"></script>



<meta name="viewport" content="width=device-width, initial-scale=1.0">

<nav id="navbar">
  
<a href="#Antyr">If you are sure to click, let's go!</a>
</nav>




<section id="welcome-section">
  <h1>Hello Motorcycle!</h1>
</section>
<section id="projects"> <div class="project-tile">
  <h1>This job is ridiculous!</h1>
  <a href="http://www.google.com">At the end of the way is the Paris</a>
</div>
</section>

<section>
    <a id="profile-link">
      <p>CONTENT</p>
    </a>
</section>






<p>Hi, my name is Jo Jo. I am a delicious juicy fruit that came from a very cold country with 3 months of winter. Every spring I am born from a pear flower on the oldest pear tree in the city and every fall I am ready for my journey. I am sweet, juicy, soft but firm and full of flavor.

My favorite thing to do is to hang from the tree and observe the world.

When I am not hanging from the tree and observing the world, I am working as an analyst at a huge Construction Management Company and in my free time learning the coding. </p>
<div>
  Why do you ask questions about how you do not want to do?</div>

<div id="Antyr"> Question Mark</div>




<div id"contact"> 
    <a id="profile-link" href="https://github.com/X-ritch" target="_blank" title="My Github Account">Github</a>
</div>



  
 
 
```

**Comment by tbushman** [comment]
@X-ritch Can you please try it after first removing the `id="profile-link"` from this section  
```  
<section>
    <a id="profile-link">
      <p>CONTENT</p>
    </a>
</section>  
```  
The `id=`  attribute must be unique to the whole script. Use it only in the second instance, with the `href="https://...` one. Thanks.

**Comment by X-ritch** [comment]
I got it. Thank you for your interest @tbushman
