### ISSUE TITLE
The tester's Select tag is disabled after adding the CDN in via settings

### ISSUE THREAD

**Issue by fighder** [freeCodeCamp/testable-projects-fcc#728]
I added the tester cdn as an external script in the settings option, but I was not able to change what I am testing. I checked the element in the browser as shown in the screen shot, and saw the select tag was disabled. I was able to manually remove that attribute and it worked, but after I change any code it refreshes and of course the disable attribute is back in the select tag.

![capture](https://user-images.githubusercontent.com/16496395/49758137-3b945d00-fc8c-11e8-9c7e-3c07c9feac21.PNG)

**Comment by tbushman** [comment]
@fighder If you have this code  
```  
const projectName = "markdown-previewer";
localStorage.setItem('example_project', 'Markdown Previewer');  
```  
in the JS window, please remove it. If that's not it, please share a link. Thanks.
