### ISSUE TITLE
Build a Tribute Page - Bootstrap Issue

### ISSUE THREAD

**Issue by SUD0-LEE** [freeCodeCamp/testable-projects-fcc#73]
**Issue Description:** 

Bootstrap add-in from CodePen will not give the same results as the tribute page example provided by Free Code Camp

In the Codepen tribute page example of Dr. Norman Borlaug, the Bootstrap add-in you have is:

-  https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css

Which is not the default bootstrap add-in that Codepen provides, which is:

- https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.6/css/bootstrap.min.css

The video shown in: https://www.freecodecamp.com/challenges/build-a-tribute-page did not specify this difference, which led me to waste a couple of hours to troubleshoot why certain elements were not being responsive - even with the bootstrap add-in that was provided by codepen.

The minute I added the same bootstrap url found in the Dr. Norman Borlaug tribute page, my tribute page became responsive.   
___
**Environment Info**

Browser: Chrome
OS: Windows 10
___
**Link to My Pen**

https://www.freecodecamp.com/challenges/build-a-tribute-page

FYI - I shared the link with the Bootstrap URL that is provided with Codepen.
___
![screenshot-codepen io-2017-03-05-19-22-10](https://cloud.githubusercontent.com/assets/25422477/23593184/6e470680-01d9-11e7-9ae2-108556faa715.png)
___
![screenshot-codepen io-2017-03-05-19-26-19](https://cloud.githubusercontent.com/assets/25422477/23593210/c34b1cac-01d9-11e7-9d3b-e90697275464.png)
___
![screenshot-codepen io-2017-03-05-19-27-48](https://cloud.githubusercontent.com/assets/25422477/23593226/f9ea22c6-01d9-11e7-9429-ac3d79c71307.png)

**Comment by no-stack-dub-sack** [comment]
@SUD0-LEE Thanks for your comment, things are changing pretty rapidly in the tech world though, and there is no way for us to update the video each time codepen moves to a new bootstrap release. A very important skill in software dev is troubleshooting, so it's great you figured it out on your own though! On the other hand, freeCodeCamp has a pretty solid support community, so please check out our gitter chat rooms if you have not already, in which you can often find help for problems like these: gitter.im/FreeCodeCamp/FreeCodeCamp

Also, it does not seem like this issue has anything to do with the new testable projects, which are found from accessing freeCodeCamp's beta site: https://beta.freeCodeCamp.com. This repo pertains specifically to that project - the tribute page for which is found [here](http://codepen.io/freeCodeCamp/pen/zNqgVx), and does not use Bootstrap at all, as we are moving towards teaching responsiveness in other ways, using less reliance on outside libraries. Feel free to check out the new project and guidelines, which will give you some insight in to creating a responsive page without Bootstrap.

**Comment by no-stack-dub-sack** [comment]
@SUD0-LEE Also, we didn't specify the difference in the video, becuase the difference did not exist when the video was made. Again, these things change very quickly, and a big point of these projects is to go out there, research the libraries, learn about what's current, and trouble shoot. That being said, a hint might not be a bad idea. Since this issue applies to the main production FCC, please feel free to reopen that issue on the main repo. But for now, closing this issue here.

Thanks again, and happy coding!
