### ISSUE TITLE
Place testable projects form CodePen into this repo

### ISSUE THREAD

**Issue by ValeraS** [freeCodeCamp/testable-projects-fcc#731]
pros:
- not depend on CodePen (if they change something our tests will be broken)
- quicker and simpler automated tests
- the standard process of changes (through a PR)
- history of changes

/cc @QuincyLarson @tbushman @raisedadead @tchaffee

**Comment by tchaffee** [comment]
Seems like a good idea. What would be ideal is if we can somehow publish the source code from here to CodePen so users can still view the solutions in the environment they are familiar with for coding solutions.
If we do this, I would suggest doing it with just one project first and then leaving it for a month or so to see if there are any cons we haven't thought of.

**Comment by raisedadead** [comment]
I am in favor of moving away from CodePen to our platform actually, we have some ideas planned in the future which will let us use `learn` to be able to build projects right within freeCodeCamp.

Right now, I think it would be just good to bring in the source code into version control here.

**Comment by QuincyLarson** [comment]
@ValeraS Agreed! We will soon have a full-fledged code editor and won't need to send everyone to CodePen for this process. Moving the code over to hear is a good first step.
