### ISSUE TITLE
CarrJ_No Results from Typed Code

### ISSUE THREAD

**Issue by Joakima-Carr** [freeCodeCamp/testable-projects-fcc#735]
#### Issue Description
All of the coding I put in after my section that links to a YouTube video does not show up. I can write the code and see it in the HTML and CSS windows, but nothing is generated below that shows what I created from the code. I keep checking what I wrote, but nothing helps. I am extremely new to coding so I am not sure what is going on. I have had no issues up to this point.

#### Browser Information
I browse on Chrome. 
Google Chrome OS.
Acer Chromebook 14. 

#### Your Code / Link to Your Pen

Here is a link to my Pen: http://codepen.io/JoakimaCarr/live/vvNVYR

Anything typed after the code for the YouTube video link does not show up. The following code does not produce anything. I am stuck here because when I try to link to this area I cannot pass the test that shows I linked all 3 of my nav-links. I get a message that says I have not linked the "pricing" nav-link:
 <div id="pricing">
       <div id="standard">                                           
<h3>Basic Design</h3>
                   <ul>
                   <li>Template Design</li>
                   <li>3-5 day Processing</li>
                   <li>$19.99</li>
                   </ul>
                         </div>
                         </div>
          
              
Thank you in advance for any help. 

Sincerely,
Joakima Carr
```
 
 
 
```

**Comment by ValeraS** [comment]
@Joakima-Carr As I can see the issue was resolved. Congrats!!!
