### ISSUE TITLE
5. When I click a .nav-link button in the nav element, I am taken to the corresponding section of the landing page.'

### ISSUE THREAD

**Issue by jakewebdevolper** [freeCodeCamp/testable-projects-fcc#736]
https://codepen.io/jakeelliott123/pen/aPNQzy
need help please.
<nav id="nav-bar">
      <ul>
        <li><a class="nav-link" href="#features">features</></li>
        <li><a class="nav-link" href="#components">components</>
          <li>
            <li><a class="nav-link" href="#music">Music</></li>
            <ul>
please help me on codepen

**Comment by ValeraS** [comment]
@jakewebdevolper The .nav-link with href="#features" is not linked to a corresponding element on the page. Your code contains link with `href=#features` but does not contain a `section` with `id="features"`.

**Comment by the-MMAtrix** [comment]
why not just think of a page of your own instead of "ctrl+c+v" that thing? lol
