### ISSUE TITLE
I don't pass the drum machine test and my project works correctly...

### ISSUE THREAD

**Issue by Akiv1965** [freeCodeCamp/testable-projects-fcc#737]
#### Issue Description
The test result is... _"When I click on a .drum-pad element, the audio clip contained in its child <audio> element should be triggered"_ and _"When I press the trigger key associated with each .drum-pad, the audio clip contained in its child <audio> element should be triggered (e.g. pressing the Q key should trigger the drum pad which contains the string "Q", pressing the W key should trigger the drum pad which contains the string "W", etc.)"_.
However when I click or press the correct keys  the project work. I hear the sound and display the text description.

#### Browser Information

* Browser Name, Version:  Chrome 71.0.3578.98 
* Operating System: Windows 10
* Mobile, Desktop, or Tablet:  Desktop

#### Your Code / Link to Your Pen
https://codepen.io/Akiv/full/YdKvZX
```
 
 
 
```

**Comment by ValeraS** [comment]
@Akiv1965 You set the audio source each time the `.drum-pad` element is clicked. Audio is loading and playing. Loading phase takes a time. Instead of setting sources each time, set them in HTML audio tags without `autoplay` and trigger playing on click and press events. To start to play an audio you can use
```js
document.getElementById("Q").play();
```
or with jQuery
```js
$("#Q").trigger("play");
```

**Comment by Akiv1965** [comment]
> @Akiv1965 You set the audio source each time the `.drum-pad` element is clicked. Audio is loading and playing. Loading phase takes a time. Instead of setting sources each time, set them in HTML audio tags without `autoplay` and trigger playing on click and press events. To start to play an audio you can use
> 
> ```js
> document.getElementById("Q").play();
> ```
> 
> or with jQuery
> 
> ```js
> $("#Q").trigger("play");
> ```

Thank you very much....!
 I passed the test.....
