### ISSUE TITLE
Issue with test 7 personal portfolio

### ISSUE THREAD

**Issue by missstaff** [freeCodeCamp/testable-projects-fcc#739]
#### Issue Description

I am failing test 7, The navbar should contain at least one link that I can click on to navigate to different sections of the page. I have three links and they are not working. I am new to coding and admit I could be wrong but I have been over the a tags in the navbar and the id names for each section..I think there is an issue with the tester?

#### Browser Information

Chrome
Windows 10
laptop

#### Your Code / Link to Your Pen

```
 https://codepen.io/missstaff/pen/qLNRvJ
 
 
```

**Comment by ValeraS** [comment]
@missstaff your code contains a wrong close tag `<a/>`. Amend it and you'll pass the test.
Also, link to a welcome section broken.
