### ISSUE TITLE
Bug in Test Suite Template for Build a Personal Portfolio Webpage

### ISSUE THREAD

**Issue by rsquaredwb** [freeCodeCamp/testable-projects-fcc#741]
#### Issue Description
Test complains that there should be a link with an id of "profile-link" that opens Github or FCC profile in a new tab.

#### Browser Information
* Browser Name, Version:  Google Chrome. Version 71.0.3578.98 (Official Build) (64-bit)
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen
https://codepen.io/rsquaredwb/pen/pqeJbw

#### Screenshot

![image](https://user-images.githubusercontent.com/42418751/50325810-f6a2ce80-04b4-11e9-8aa4-e9936a86e736.png)

**Comment by tbushman** [comment]
@rsquaredwb You have a duplicate `id='profile-link'` here:  
`<a href="#welcome-section" id="profile-link">about</a>` and the test is probably clicking the one at the top of the dom tree first.

**Comment by rsquaredwb** [comment]
Hi Tracey,

Thanks for the quick response. That is indeed the issue. I guess I have to
double-check my code first whether I am doing the correct "find" procedure.
I did that at first before submitting the issue and I did not find
duplicates.  I probably did not do it correctly.

Thanks again for your help.
