### ISSUE TITLE
FCC Drum machine : The test 6 fails saying the sound is not triggered when q is pressed.Though it is working.

### ISSUE THREAD

**Issue by deepikagunda** [freeCodeCamp/testable-projects-fcc#742]
#### Issue Description

press q and you can hear the sound.
https://codepen.io/deepikag/full/EGNXbg

#### Browser Information

* Browser Name, Version: chrome
* Operating System: windows 10
* Mobile, Desktop, or Tablet: desktop

#### Your Code / Link to You
6. When I press the trigger key associated with each .drum-pad, the audio clip contained in its child <audio> element should be triggered (e.g. pressing the Q key should trigger the drum pad which contains the string "Q", pressing the W key should trigger the drum pad which contains the string "W", etc.)

https://codepen.io/deepikag/full/EGNXbg

```
 the sound plays but the test is failing.
 
```

**Comment by ValeraS** [comment]
@deepikagunda Test does not send a `keyup` event. Try using a `keydown` event instead of `keyup`.

**Comment by deepikagunda** [comment]
Thanks Tracey.That helped.
