### ISSUE TITLE
Fix invalid HTML in technical documentation example project

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/testable-projects-fcc#745]
**Describe your problem and how to reproduce it:**

The technical documentation example project has (a lot of) invalid HTML. It really needs to be fixed.

Note: I'm not sure what the best approach for fixing the Codepen example projects are. At first, I wanted to document all the changes but I was not sure how best to do that, I can make a repo with the changes if needed.

This Codepen is a fixed version.
https://codepen.io/lasjorg/pen/MZavON

1. Changed the HTML to be valid HTML.
2. Changed CSS to make it look the same with the new HTML structure for the nav. Slightly changed the look, giving the nav links a bit more padding and better left-alignment to the nav header.
3. Cleanup CSS and formatting.

**Add a Link to the page with the problem:**
Original version
https://codepen.io/freeCodeCamp/full/NdrKKL

---
Note this is a dub of this issue https://github.com/freeCodeCamp/freeCodeCamp/issues/34661 in the freeCodeCamp/freeCodeCamp repo, not sure if i should close it or what.

**Comment by ValeraS** [comment]
@lasjorg Could you make a PR? Source code now in this repo https://github.com/freeCodeCamp/testable-projects-fcc/blob/master/src/projects/technical-documentation-page/index.html.

**Comment by ValeraS** [comment]
Fixed by #750
