### ISSUE TITLE
pomodoro-clock test fails (and should pass)

### ISSUE THREAD

**Issue by thembones79** [freeCodeCamp/testable-projects-fcc#748]
#### Issue Description
Hello!  :)
I've build Pomodoro App with React.
It is working like it supposed to, but fails three tests:
Timer: 2, Timer: 4, Timer: 6

Looks like it has some issues with decreasing values.
It is weird. 

#### Browser Information
* Browser Name, Version: Chrome 71.0.3578.98 64-bit
* Operating System: Windows 10 64-bit
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen
https://codepen.io/thembones79/pen/wRqMxx

#### Screenshot
![zrzut ekranu 61](https://user-images.githubusercontent.com/14159941/50477380-6db3f780-09cc-11e9-86f4-22b0bb01033e.png)

**Comment by ValeraS** [comment]
@thembones79 Your code sets the same `id` on two elements.
![image](https://user-images.githubusercontent.com/10867286/50479121-0c991d80-09e6-11e9-9eb2-b1a033c7bcba.png)
Correct this, and you'll pass the tests.

**Comment by thembones79** [comment]
@ValeraS - thank you very much :)  

How could I missed this. Thank you :)
