### ISSUE TITLE
Tried the code with media query still its not detected

### ISSUE THREAD

**Issue by jagadeeshgudise92** [freeCodeCamp/testable-projects-fcc#749]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 
 
```

**Comment by tbushman** [comment]
Hello, please provide some more information about the error you are experiencing. Indicate which test is failing and provide a screenshot, a code sample, or a link to your project.  
@jagadeeshgudise92 There are a couple of common reasons for this error: missing or unnecessary brackets in the CSS, or viewing index.html from a local file without a localhost. You can run a localhost server using `live-server` or similar, or simply use CodePen. Let us know if those things don't help, or if you have other questions.

**Comment by tbushman** [comment]
@jagadeeshgudise92 Sorry for the delay. You may share your project link. Also please try running the project through a localhost port -- using `live-server` or Python simpleHTTPServer.
