### ISSUE TITLE
Tribute Test Passes With Virtually No Content

### ISSUE THREAD

**Issue by calendee** [freeCodeCamp/testable-projects-fcc#752]
#### Issue Description

When testing the "Tribute" challenge, it's possible to pass the test with a CodePen that is virtually empty.

Steps To Recreate:
- Browse to the challenge page : https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-projects/build-a-tribute-page/
- Enter this CodePen URL in the Solution field : https://codepen.io/anon/pen/xmXamb?editors=1100
- Tap the "I've Completed This Challenge" submit button
- Notice that the test apparently passes despite the CodePen having only this code:

```
<main></main>
```

#### Browser Information

* Browser Name, Version: Safari 12.0.2
* Operating System: macOS 10.14.2
* Mobile, Desktop, or Tablet:  Desktop

#### Your Code / Link to Your Pen
https://codepen.io/anon/pen/xmXamb?editors=1100

```
<main></main>
```

#### Screenshot

<img width="990" alt="tribute-challenge-issue" src="https://user-images.githubusercontent.com/57374/50537923-a1bf2200-0b5e-11e9-87b3-8f9a1b94e549.png">

**Comment by tbushman** [comment]
@calendee We have not yet implemented a check in the curriculum for completed projects. These tests should pass on the front-end before submitting your project URL, on the honor system at this point. The project urls will be listed on your portfolio page.
