### ISSUE TITLE
There are no tests available

### ISSUE THREAD

**Issue by YjangWynter** [freeCodeCamp/testable-projects-fcc#753]
#### Issue Description

There are no tests to check my work for tech document challenge in the the responsive design projects section.

#### Browser Information

* Browser Name, Version:  Firefox 64
* Operating System: Ubuntu: GNU/Linux
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
 
 
 
```

**Comment by tbushman** [comment]
@YjangWynter Please add this script to your html file: `<script src="https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js"></script>`
