### ISSUE TITLE
not testing layout right

### ISSUE THREAD

**Issue by osuulola** [freeCodeCamp/testable-projects-fcc#754]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```https://codepen.io/osuulola/pen/JwrbEE
 
 
 
```

**Comment by lynxlynxlynx** [comment]
Please follow the template and add a description etc.  Now it is impossible to know what you are reporting.
