### ISSUE TITLE
random quote generator in react

### ISSUE THREAD

**Issue by astron97** [freeCodeCamp/testable-projects-fcc#757]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 
 
```

**Comment by astron97** [comment]
This is just a simple quote generator i wrote in jsx and transpiled it to regular js using Babel.
I cant see any output when i use the following files in codepen.

**Comment by astron97** [comment]
https://codepen.io/astron97/pen/vvRzPM

**Comment by ValeraS** [comment]
Do not transpile your code, paste as is. From your code remove import of React and ReactDOM. In settings, add links to React and ReactDOM.

![image](https://user-images.githubusercontent.com/10867286/50733485-685e6600-119f-11e9-984d-8308b171ee82.png)

**Comment by astron97** [comment]
Thanksy . . @ValeraS
