### ISSUE TITLE
Multiply shown as "." instead of "x" in the calculator

### ISSUE THREAD

**Issue by akash-more** [freeCodeCamp/testable-projects-fcc#758]
#### Issue Description

when I type the multiply button in the calculator, it is shown as a "." instead of "x"

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: Windows 7
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
 
 
 
```

#### Screenshot

![image](https://user-images.githubusercontent.com/30334579/50737591-370e8600-11f1-11e9-9b7c-9ab048200df0.png)

**Comment by lynxlynxlynx** [comment]
Both centered dot and cross (not x) are symbols of multiplication, the dot being slightly more readable.

Non-issue to me.
