### ISSUE TITLE
Question about updating tribute page project

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/testable-projects-fcc#759]
Just saw in another issue https://github.com/freeCodeCamp/testable-projects-fcc/issues/752 that testing apparently is not yet in place, so that kind of changes things. I don't know what the plans are for the tests though. I will just post my original question anyway.

I wanted to update the project and fix a few things. However, I ran into an issue. I really want to change the #img-div to a figure element and #img-caption to a figcaption, just for the semantics. I'm just not sure how to do this without breaking backward compatibility.

If I keep the id name, it seems confusing. If I change the name, I have to change the test and that will break backward compatibility with projects made before the change. I know just not doing it would be the easiest, but I wanted to hear if anyone had a good solution for this. I can only really think of two solutions, keep the name or test for both the old and new name.

**Comment by tbushman** [comment]
Closed by #760
