### ISSUE TITLE
Bar Chart--Test Passed and Fails 

### ISSUE THREAD

**Issue by zootechdrum** [freeCodeCamp/testable-projects-fcc#761]
My project seems to pass all test but only sometimes. The problem is with the tool-tip we have to create. The user story we have to pass is to have the tooltip have have a data-date property. I created one but for whatever reason it re-formats it and it takes away the zero in-front of the single digit. I don’t know why the re-formatting happens but i have taken the liberty of looking at the code provided in the example and it seems to work very similarly.

#### Issue Description

By testing my project multiple times. I can sometimes pass it and it sometimes fails. I think its just the luck of the draw. Sometimes it will pick a date like 12-12-2011 and it will pass because there is no leading zeros in that date. However if it randomly chooses 01-01-2011 it will not pass because it will re-format at it  to 1-1-2011 hence it's not the same. 

#### Browser Information

* Browser Name, Version:  Chrome Version 71.0.3578.98 (Official Build) (64-bit)
* Operating System: Windows

#### Your Code / Link to Your Pen

```
https://codepen.io/zootechdrum/
 
 
 
```

#### Screenshot

This is the first time this happened. That should not be green.
![freecode](https://user-images.githubusercontent.com/28512399/50801613-57464f80-129a-11e9-8987-f7cf9f4c429c.png)

**Comment by tbushman** [comment]
Tests pass now.
