### ISSUE TITLE
React's built-in Markdown interpreter

### ISSUE THREAD

**Issue by IAmMyself** [freeCodeCamp/testable-projects-fcc#762]
#### Issue Description

On markdown, if using Marked.js Markdown interpreter, the test to see if you are demonstrating Markdown will not accept the code block.

#### Browser Information

* Browser Name, Version:  Google Chrome Version 71.0.3578.98 (Official Build) (64-bit) and Microsoft Edge 42.17134.1.0
* Operating System: Windows 10 64-bit Home
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

[My Pen](https://codepen.io/IAmMyself/pen/MZXmqO)

**Comment by ValeraS** [comment]
@IAmMyself In a default text, an HTML `<pre>` tag is used. If using a special markdown syntax for a code block, your code will pass the test.

**Comment by IAmMyself** [comment]
I figured it out... I completely forgot that the backticks (`) need to be on their own line
