### ISSUE TITLE
React Calculator

### ISSUE THREAD

**Issue by MilePaor** [freeCodeCamp/testable-projects-fcc#763]
#### Issue Description

I am failing at test 8. I am sure that i gave id of display to my input. Check it out please.

PS: Can u give me further explanation of test num. 11. Thanks.

#### Browser Information

Chrome 71, Mac, Desktop, 

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 https://codepen.io/milepaor/full/rqdVrV
 
```

#### Screenshot

![screen shot 2019-01-08 at 12 39 17 pm](https://user-images.githubusercontent.com/20985604/50828724-7ac4d500-1342-11e9-9f52-484026c3e6c9.png)

**Comment by ValeraS** [comment]
@MilePaor Your `div` element with `id='display'` shows a clicked button. But tests expect to see a result in it.

**Comment by MilePaor** [comment]
> @MilePaor Your `div` element with `id='display'` shows a clicked button. But tests expect to see a result in it.

It shows results when u do calculation (press equal sign).

**Comment by ValeraS** [comment]
@MilePaor Test checks: 

> As I input numbers, I should be able to see my input in the element with the id of "display"

But when I press `1`, `2` and `3`, I see `3` instead of `123`. Because of this the test fails.

Also, check input `5.5.5`.

**Comment by MilePaor** [comment]
> @MilePaor Test checks:
> 
> > As I input numbers, I should be able to see my input in the element with the id of "display"
> 
> But when I press `1`, `2` and `3`, I see `3` instead of `123`. Because of this the test fails.
> 
> Also, check input `5.5.5`.

Okay, now i understand. Thank you!
