### ISSUE TITLE
Survey Form Error of #4 and #5 ; added id but 

### ISSUE THREAD

**Issue by meanyMina** [freeCodeCamp/testable-projects-fcc#766]
#### Issue Description

I added "name" and "email" as id but test doesn't count it.
Please check it.
Thank you in advance.

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: Window
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

[Link] https://codepen.io/Meanymina/pen/jXpPYr?editors=1100

============CODE===============

 <body>
  <header>
    <h1 id="title">OCEANS Member Survey</h1>
    <p id="description">We would like to know more about OCEANS members!</p>
  </header>
  <main>
    <div class="container">

        <div class="box1_1">
          <form id="survey-form"><label for="name">Name : </label></div>
        <div class="box1_2">
        <input type="text" name="name" id="name" placeholder="Enter your name in English" required></form>
        </div>
      
        <div class="box1_1">
          <form id="survey-form"><label for="email">E-mail : </label></div>
        <div class="box1_2">
        <input type="text" name="email" id="email" placeholder="Enter your email address" required></form>
        </div>
      
    </div>
  </main>
  <footer></footer>
</body>
 
 
```

#### Screenshot
<!-- Add a screenshot of your issue -->
![image](https://user-images.githubusercontent.com/42491537/50858199-0749b480-1390-11e9-9006-818ab3ea38a1.png)

**Comment by tbushman** [comment]
@meanyMina There should be only one `<form>` containing all of the inputs and their associated labels.  
```  
<form id="survey-form">
    <div class="box1_1">
        <label for="name">Name : </label></div>
    <div class="box1_2">
        <input type="text" name="name" id="name" placeholder="Enter your name in English" required>
    </div> 
    <div class="box1_1">
        <label for="email">E-mail : </label></div>
     <div class="box1_2">
          <input type="text" name="email" id="email" placeholder="Enter your email address" required>
     </div>
</form>  
```

**Comment by meanyMina** [comment]
Dear "tbushman",
Thank you for your reply!
If I code as you commented, grid looks disorganized.
Could you check it again please?
![1](https://user-images.githubusercontent.com/42491537/50927599-8f938c80-1458-11e9-835c-4512d7897332.PNG)

**Comment by tbushman** [comment]
@meanyMina You can do something like this (give the `<form>` element the className `"container"`:  
```  
<main>
      <form id="survey-form" class="container">
        <div class="column">
            <div class="box1_1">
              <label for="name">Name : </label>
            </div>
            <div class="box1_2">
               <input type="text" name="name" id="name" placeholder="Enter your name in English" required>
            </div> 
        </div>
        <div class="column">
            <div class="box1_1">
                <label for="email">E-mail : </label>
            </div>
            <div class="box1_2">
                <input type="text" name="email" id="email" placeholder="Enter your email address" required>
             </div>
         </div>
      </form>  
      
  </main>   
```

**Comment by ValeraS** [comment]
It seems you have solved the problem.
