### ISSUE TITLE
User Test numbers 10 and 12 keeps failing but all users met

### ISSUE THREAD

**Issue by philrussel21** [freeCodeCamp/testable-projects-fcc#768]
#### Issue Description
User tests numbers 10 and 12 were met but keeps failing.

#### Browser Information
I am using the latest version of Google Chrome

#### Your Code / Link to Your Pen
```
 
 https://codepen.io/philrussel21/pen/gZdyag
 
```

**Comment by tbushman** [comment]
@philrussel21 Thanks for bringing this to our attention. The tests do not accommodate the question mark in the innerText for `.nav-link`  
  
```  
<ul class="headings">
        <li><a href="#Introduction_to_HTML" class="nav-link">Introduction to HTML</a></li>
        <li><a href="#Prerequisites" class="nav-link">Prerequisites</a></li>
        <li><a href="#What_is_HTML" class="nav-link">What is HTML</a></li>
        <li><a href="#Anatomy_of_an_HTML_Element" class="nav-link">Anatomy of an HTML Element</a> </li>
          <ul>
            <li><a href="#Parts_of_an_Element" class="nav-link">Parts of an element</a></li>
            <li><a href="#Nesting_Elements" class="nav-link">Nesting Elements</a></li>
            <li><a href="#Block_versus_Inline_Elements" class="nav-link">Block versus Inline Elements</a></li>
            <li><a href="#HTML_Boilerplate" class="nav-link">HTML Boilerplate</a></li>
          </ul></li>
        <li><a href="#Attributes" class="nav-link">Attributes</a></li>
        <li><a href="#HTML_Comments" class="nav-link">HTML Comments</a></li>
        <li><a href="#Summary" class="nav-link">Summary</a></li>
        <li><a href="#Reference" class="nav-link">Reference</a></li>
</ul>  
```  
It might be bad practice to include a question mark in the `href`, but go ahead and try it out if you want to keep it. This code was modified to fix some of the nesting order.

**Comment by ValeraS** [comment]
@philrussel21 
1. for test 10, correct the nesting order of some elements as suggested by @tbushman 
2. for test 12, check `href`s and corresponding names of links, not all of them are equal. For example, `href="#Anatomy_of_an_HTML_Element"` and name `Anatomy of an HTML`
