### ISSUE TITLE
survey

### ISSUE THREAD

**Issue by poonam1994** [freeCodeCamp/testable-projects-fcc#769]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 
 
```

**Comment by tbushman** [comment]
Hello @poonam1994, please provide some more information about the error you are experiencing. Indicate which test is failing and provide a screenshot, a code sample, or a link to your project.

**Comment by tbushman** [comment]
Closing as inactive.
