### ISSUE TITLE
Test №7 for a Tribute Page project doesn't pass for a flexbox layout.

### ISSUE THREAD

**Issue by ponyborn** [freeCodeCamp/testable-projects-fcc#770]
#### Issue Description

Test №7 for a Tribute Page project

> The <img> element should responsively resize, relative to the width of its parent element, without exceeding its original size

expects "display" style property of image to have a value of "block" and therefore doesn't pass for a flexbox layout.

#### Browser Information

* Browser Name, Version: Firefox 64.0.2
* Operating System: Windows
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

https://codepen.io/ponyborn/pen/WLLgYO

#### Screenshot
![image](https://user-images.githubusercontent.com/13294102/51116397-17441700-181c-11e9-9b56-cb89e85af641.png)

**Comment by petercr** [comment]
@ponyborn You are correct. The test itself tests for `display: block` property of the `<img>` element. 
Also it tests for `margin: auto`. If you add those 2 lines to the `#image` CSS then it will pass the final test. 

This does however, seem to be a flaw in the testing code. As I just answered an almost exactly same problem 5 minutes ago. 
**Same thing** it does not pass the tests if you use Flexbox to center the `<img>` element. 

I hope this help answer your question. For more info see #782
