### ISSUE TITLE
Test does not read caption tag as a textual content tag

### ISSUE THREAD

**Issue by bishmiBradshaw** [freeCodeCamp/testable-projects-fcc#774]
#### Issue Description

Under the tribute project requirement # 5 reads as such:
"User Story #5: Within the img-div element, I should see an element with a corresponding id="img-caption" that contains textual content describing the image shown in img-div."
Yet when I place my id "img-caption" within my caption tag in my image div and run the test it fails. although if i change my caption element to  a "p" element it passes.

#### Browser Information

chrome, Version 71.0.3578.98 (Official Build) (32-bit)
windows 10+
Desktop

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 
 
```

**Comment by tbushman** [comment]
@bishmiBradshaw Please provide the corresponding `html` and `css` so we can look at the configuration. Sorry to delay.
