### ISSUE TITLE
D3 Bar Chart tooltip tests pass in Firefox but not Chrome

### ISSUE THREAD

**Issue by SirRobLyon** [freeCodeCamp/testable-projects-fcc#776]
#### Issue Description

Test 14 doesn't pass in Chrome, but does pass in Firefox.

#### Browser Information

* Browser Name, Version: Firefox 64.0.2
Chrome Version 71.0.3578.98 (Official Build) (64-bit)
* Operating System: MacOS Mojave 10.14.2
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

https://codepen.io/captrob/full/qLeEpN
 
 
 
![screen shot 2019-01-19 at 1 17 07 pm](https://user-images.githubusercontent.com/10045273/51422623-8e96f380-1bec-11e9-95c1-782df4509131.png)
![screen shot 2019-01-19 at 1 18 05 pm](https://user-images.githubusercontent.com/10045273/51422630-b1c1a300-1bec-11e9-9ba2-0f9a865ebd3d.png)

**Comment by ValeraS** [comment]
@SirRobLyon It's not a tooltip. Your code does not pass a test:
> 10. The data-date attribute and its corresponding bar element should align with the corresponding value on the x-axis.

1. `xScale` and `width` do not take into account `margin.left`
2. calculating the `x` coordinate does not use `xScale` and tries to calculate it itself.

You can do next:
```js
xScale.range([margin.left, width-margin.right]);
```
```js
.attr("width", (width - margin.right - margin.left) / dataset.length )
```
```js
.attr("x", (d,i) => {
    return xScale(new Date(d[0]))
  })
```

and need to fix `transform` of x-axis

**Comment by SirRobLyon** [comment]
Thank you! 

I fixed my bugs with your corrections. 

Much appreciated!

I’m still curious why it passed all tests in Firefox as it was before. But of course, glad all tests passing for my code in both browsers now. 

Have a wonderful day!

Kind regards,
Rob
