### ISSUE TITLE
Inside the form element, I can select a field from one or more groups of radio buttons. Each group should be grouped using the name attribute.

### ISSUE THREAD

**Issue by pragya1248** [freeCodeCamp/testable-projects-fcc#777]
I'm not able to pass the  test because of the issue mentioned above.

#### Your Code / Link to Your Pen

```https://codepen.io/pragyapriya/pen/BvXpJL?editors=1100

**Comment by pragya1248** [comment]
https://codepen.io/pragyapriya/pen/BvXpJL?editors=1100
code link is mentioned above

**Comment by ValeraS** [comment]
@pragya1248 in the detailed description of the error said:
```
All your radio-buttons must have a value attribute
```

**Comment by tbushman** [comment]
Closing as inactive.
