### ISSUE TITLE
Tribute Page not seeing image resize

### ISSUE THREAD

**Issue by travis87** [freeCodeCamp/testable-projects-fcc#778]
#### Issue Description

The test is failing the responsive image item, however it works properly and is coded the way that the error states is wrong.  The project is using Bootstrap and some native CSS.

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: Windows 7
* Mobile, Desktop, or Tablet: NA 

![image](https://user-images.githubusercontent.com/28845661/51488167-71882f00-1d6a-11e9-951a-fc665df3728e.png)

![image](https://user-images.githubusercontent.com/28845661/51488260-b6ac6100-1d6a-11e9-81f8-361758c10764.png)

**Comment by justindstauffer** [comment]
![image](https://user-images.githubusercontent.com/23200846/51654909-1ae84400-1f68-11e9-8d6e-7e0621fc5221.png)

**Comment by glamrock** [comment]
I found the same issue. However, it is looking for the `image` class, so for the original Tribute page demo, adding the following css solves the issue:

```
img{
  max-width: 100%; 
  display: block; 
  height: auto;
  margin: auto;
}
```
