### ISSUE TITLE
Media Query Missing

### ISSUE THREAD

**Issue by EliasMontsho** [freeCodeCamp/testable-projects-fcc#779]
#### Issue Description

When ever I run the test, it seems it does not 'pick up' my media query in the CSS panel.

#### Browser Information

* Browser Name, Version: Google Chrome, Version 71.0.3578.98 (Official Build) (64-bit)
* Operating System: Apple MacBook Pro
* Mobile, Desktop, or Tablet: Laptop

#### Your Code / Link to Your Pen

```
 https://codepen.io/Kebone/pen/GPboZO
![screen shot 2019-01-22 at 13 20 07 2](https://user-images.githubusercontent.com/29477626/51541909-b1324200-1e62-11e9-8e9d-4b588d176427.png)

 
 
```

#### Screenshot

![Uploading Screen Shot 2019-01-22 at 13.20.07 (2).png…]()

**Comment by ValeraS** [comment]
@EliasMontsho In plain CSS, media queries can't be inside a declaration block. It seems you are using SCSS, if this is true, then in a code pen settings choose a CSS preprocessor.
![image](https://user-images.githubusercontent.com/10867286/51571904-a3a5a800-1eb4-11e9-8a8f-5e963bbef1d5.png)

**Comment by tbushman** [comment]
@EliasMontsho If you're not using scss, you will need to un-nest your media query:  
from:  
```  
#Pricing{
  height:300px;
  background-color:#1BE5D6;
  
  @media (max-width: 800px) {
    flex-direction: column;
    
    #tenor, #bass, #valve { max-width: 300px; width: 100%; margin: 0 auto; margin-bottom: 10px; }
  }
}  
```   
to:   
```  
#Pricing{
  height:300px;
  background-color:#1BE5D6;
}  
@media (max-width: 800px) {
    #Pricing{  
        flex-direction: column;
    }
    #tenor, #bass, #valve { max-width: 300px; width: 100%; margin: 0 auto; margin-bottom: 10px; }
  }
```   
If you experience further issues, please open a new issue or ask in the forums.
