### ISSUE TITLE
 5. When I click a .nav-link button in the nav element, I am taken to the corresponding section of the landing page.'

### ISSUE THREAD

**Issue by fermarinsanchez** [freeCodeCamp/testable-projects-fcc#780]
Product Landing Page

#### Issue Description

I think it´s ok but don´t work! help please!!!

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 https://codepen.io/fernandomarinsanchez/pen/KbbmEL
 
 
```

**Comment by ValeraS** [comment]
@fermarinsanchez move `class="nav-link"` from `li` to `a` tags.

**Comment by fermarinsanchez** [comment]
@ValerS thank you but still don´t work.

**Comment by fermarinsanchez** [comment]
@ValeraS thank you but still don´t work moving the class from li to a tags

**Comment by ValeraS** [comment]
I've opened your pen and the class still set on `li` tags. If you move class from `li` to `a` and run tests you will get new error. Press `Tests` button, look at detailed description and you'll understand the problem.

**Comment by fermarinsanchez** [comment]
Now I get the class="nav-link" to a tag and clear the class from the li tags. Still don´t work. I´ve look at detailed description and don´t understand the problem... my little brain hurts! :-)

**Comment by fermarinsanchez** [comment]
and open my pen now and you will see it... thank you again!!!

**Comment by fermarinsanchez** [comment]
I have removed from the <ul>, the <li> corresponding to nav-bar. Each button of the nav-bar takes to its corresponding site of the page. I do not know if the error is given because I link the href to a <a name='Servicios' for example''> tag instead of referring to an ID ... can that be the problem?

**Comment by fermarinsanchez** [comment]
I have removed from the ul, the li corresponding to nav-bar. Each button of the nav-bar takes to its corresponding site of the page. I do not know if the error is given because I link the href to a:
 <a name='Servicios' for example''> tag instead of referring to an ID ... can that be the problem?

**Comment by fermarinsanchez** [comment]
I have removed from the **ul**, the **li** corresponding to inicio to **nav-bar**. Each button of the nav-bar takes to its corresponding site of the page. I do not know if the error is given because I link the **href** to a **<a name='Servicios' for example''>** tag instead of referring to an ID ... can that be the problem?

**Comment by ValeraS** [comment]
Yes, you are right. The test searches for an element with `id` equal to the value of href without the` # `.

**Comment by fermarinsanchez** [comment]
YESSSSSS! IT WORKS!!!!!! THANKS A LOT @ValeraS !!!!
