### ISSUE TITLE
Tribute page /product landing

### ISSUE THREAD

**Issue by habagat007** [freeCodeCamp/testable-projects-fcc#783]
already completed as seen on my screenshot for both Product landing and Tribute page projects but after submitting it couple of times, my project status did not updated as finish or done.

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
1.  [https://codepen.io/Habagat007/pen/OrBJBX(url) // for tribute page
 2. [https://codepen.io/Habagat007/pen/vvVJGN
![screen shot 2019-01-24 at 7 42 58 pm](url) // for product landing

#### Screenshot
<!-- Add a screenshot of your issue -->


![screen shot 2019-01-24 at 7 32 24 pm](https://user-images.githubusercontent.com/44786928/51719384-e5e2fc80-200e-11e9-9ce6-3f614d717152.png)
![screen shot 2019-01-24 at 7 42 58 pm](https://user-images.githubusercontent.com/44786928/51719813-9271ae00-2010-11e9-95f6-0737b821404d.png)

**Comment by tbushman** [comment]
@habagat007 Can you please submit this issue at https://github.com/freeCodeCamp/freeCodeCamp/issues and reference this issue (https://github.com/freeCodeCamp/testable-projects-fcc/issues/783) ? Please include a screenshot of your curriculum page for each project that is not resolving.

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
