### ISSUE TITLE
Test 12 on D3 Choropleth Not Passing

### ISSUE THREAD

**Issue by SirRobLyon** [freeCodeCamp/testable-projects-fcc#785]
#### Issue Description

1. Run Tests
2. Observe that test 12 for showing data-education attribute corresponding to the active county shown by the tooltip is matching 
3. Hover over any county on my choropleth map and manually validate that the data shown by the tooltip is correct. The test should pass, yes?

#### Browser Information

* Browser Name, Version: Chrome Version 71.0.3578.98 (Official Build) (64-bit)
* Operating System: OS X Mojave 10.14.2
* Mobile, Desktop, or Tablet:  Mac Laptop

#### Your Code / Link to Your Pen
https://codepen.io/captrob/full/exJJBd

#### Screenshot

![screen shot 2019-01-26 at 4 58 36 pm](https://user-images.githubusercontent.com/10045273/51784959-ab529e80-218b-11e9-98d5-a46b9f685b45.png)

**Comment by ValeraS** [comment]
@SirRobLyon in your code I see 2 issues:
1. to get data for a map, your code uses an `infoset[i]` but for a tooltip, it uses a `FindRecord`. And it gets different results.
2. to set `data-education` a function is used. But it is not needed because the current area gets into a handler of `mouseover`.

**Comment by SirRobLyon** [comment]
Hi Valeriy,

Please see my inline responses below

> On Jan 26, 2019, at 6:36 PM, Valeriy <notifications@github.com> wrote:
> 
> @SirRobLyon <https://github.com/SirRobLyon> in your code I see 2 issues:
> 
> to get data for a map, your code uses an infoset[i] but for a tooltip, it uses a FindRecord. And it gets different results.
			I’ve modified the code to only use my lookup function FindRecord now for the map and for the tooltip. All the attributes and data are being set the same way now.
> to set data-education a function is used. But it is not needed because the current area gets into a handler of mouseover.
			While there may be a better way to write this functionality (I’d love to know it) - my solution is not incorrect, right? So why should it fail the tests if I choose to use a lookup function?

**Comment by SirRobLyon** [comment]
Please disregard my last email. I just figured out what you meant in your first message. Doh!

Thank you for your help!!! :)

Wishing you a wonderful day!

Kind regards,
Rob
