### ISSUE TITLE
Document gulpfile.js

### ISSUE THREAD

**Issue by tchaffee** [freeCodeCamp/testable-projects-fcc#786]
The `gulpfile.js' file needs inline documentation to help new contributors more easily understand what the file does. A high level overview at the top of the file along with inline comments for each section would be helpful because not everyone who might contribute is familiar with gulp.

**Comment by tchaffee** [comment]
@ValeraS could you take a look at this when you get a chance? If I have time I might try to replace the gulpfile with just npm steps. And the inline docs would help me. If I don't find time to do that, the inline docs will help anyone who is trying to understand what the gulpfile does. So it's a win either way.

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
