### ISSUE TITLE
Can't Pass User Stories 4 and 13 Technical Document Page FCC

### ISSUE THREAD

**Issue by jessberr** [freeCodeCamp/testable-projects-fcc#787]
#### Issue Description

I can't seem to pass the requirements for User Story 4 and 13(see below) for the Technical Documentation Page Project for Free Code Camp.

4. Each <section> element with the class of "main-section" should also have an id that corresponds with the text of each <header> contained within it. Any spaces should be replaced with underscores (e.g. The <section> that contains the header "Javascript and Java" should have a corresponding id="Javascript_and_Java").
13. When I click on a navbar element, the page should navigate to the corresponding section of the "main-doc" element (e.g. If I click on a "nav-link" element that contains the text "Hello world", the page navigates to a <section> element that has that id and contains the corresponding <header>

I've gone through it very thoroughly and found a typo with the word Initializing, which I fixed, but still no passing on those user stories. I went through all the links and they navigate to the correct section, so I must be missing something.

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: Mac
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
 
 https://codepen.io/jessberr/pen/jdrxvo
 
```

#### Screenshot

<img width="415" alt="screen shot 2019-01-28 at 1 58 54 pm" src="https://user-images.githubusercontent.com/41270355/51865993-f6dc8800-2304-11e9-8cfb-da51f01c88c8.png">
<img width="434" alt="screen shot 2019-01-28 at 1 59 29 pm" src="https://user-images.githubusercontent.com/41270355/51866001-fb08a580-2304-11e9-8549-9eef5953eb09.png">

**Comment by ValeraS** [comment]
@jessberr
1. `id="Declaring_variables"` is set on a `header`
1. in `href` and `id`, `What_are_variables_?` should be `What_are_variables?`

**Comment by jessberr** [comment]
Thank you so much, that fixed it!
