### ISSUE TITLE
Tests showing there are 2 issues in which I can't see

### ISSUE THREAD

**Issue by elamuhombe** [freeCodeCamp/testable-projects-fcc#788]
I think my code is Ok but the tests are showing me the following issues:
1.  I should see an <a> element with a corresponding id="tribute-link", which links to an outside site that contains additional information about the subject of the tribute page. HINT: You must give your element an attribute of target and set it to "_blank" in order for your link to open in a new tab (i.e. target="_blank").

2.  The <img> element should responsively resize, relative to the width of its parent element, without exceeding its original size.
Help me correct the code if the problem is on my end

**Comment by tbushman** [comment]
Hello @elamuhombe , please provide a code sample or a link to your project for inspection.

**Comment by elamuhombe** [comment]
https://gist.github.com/elamuhombe/911b2eea741c153656aa266a0abd78cb

**Comment by ValeraS** [comment]
@elamuhombe 
1. `id="tribute-link"` should be on the `a` tag
2. `id="image"` should be on the `img` tag

**Comment by tbushman** [comment]
Closing issues due to inactivity.
