### ISSUE TITLE
Tests wont run on Pomodoro

### ISSUE THREAD

**Issue by nicolasmdf** [freeCodeCamp/testable-projects-fcc#79]
#### Issue Description
The test suite does not run on the forked pen for the Pomodoro Clock. I tried forking it several different times and it never runs, no matter what is written into the editor. Testing other projects works fine for me and the tests on the example pomodoro also work fine.

#### Browser Information

* Browser Name, Version: Chrome 56.0
* Operating System: Windows 7
* Mobile, Desktop, or Tablet: Desktop

**Comment by no-stack-dub-sack** [comment]
@nicolasmdf just to be clear, you're forking this pen  http://codepen.io/no_stack_dub_sack/pen/peLdwR
and tests will not run? Do they run on the example before you fork it? This is very odd, certainly a new one, and I am not having the same problem. Can you reproduce today?

**Comment by nicolasmdf** [comment]
@no-stack-dub-sack I will do it tonight and see what happens from the same computer and a different one. They do run on the example before forking, but not on the forked empty template OR the forked example when emptied out.

**Comment by no-stack-dub-sack** [comment]
@nicolasmdf Ahhh, I see what you mean now. Nice catch! Let me look into this, I think I know what the problem is

**Comment by no-stack-dub-sack** [comment]
@nicolasmdf Yup! I broke it inadvertently in one of my last PRs - thanks for pointing this out! Fixing now

**Comment by nicolasmdf** [comment]
@no-stack-dub-sack Very glad to be helpful, thanks a lot for your hard work!
