### ISSUE TITLE
Random quote machine / not detecting that wrapper is in the center

### ISSUE THREAD

**Issue by RXstoinkboy** [freeCodeCamp/testable-projects-fcc#793]
#### Issue Description
Problems with hirizontal centering. I might have missed something, but it seems to me that wrapper is in the center.
To reproduce the issue just please visit the project under below link and run the test. Everything should be green besides horizontal centering:

https://codepen.io/rxstoinkboy/full/Odpvbr

#### Browser Information
Codepen running on Chrome 71

* Browser Name, Version: Chrome 71
* Operating System: Windows 10 with latest update
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen
 https://codepen.io/rxstoinkboy/full/Odpvbr
```

 
 
```

**Comment by abdusabri** [comment]
Hi @RXstoinkboy ,

The styles for the `quote-box` needed a minor tweak. Following is the fix I applied. The fixed margins and padding were causing the issue.

```javascript
const wrapperStyle = {
			position: "absolute",
			left: '50%',
			top: '50%',
			transform: 'translate(-50%, -50%)',
			maxWidth: 600,
			marginRight: '-50%',
			/*padding: 50,*/
			borderRadius: 5,
			boxShadow: '0 5px 20px grey',
			display: 'flex',
			flexDirection: 'column',
			alignItems: 'center',
		}
```

Here is a link to a working fork of your project: https://codepen.io/abdusabri/full/LqLNpo

Well done completing the project! 🙂

**Comment by RXstoinkboy** [comment]
Awsome! Thank yuo so much for helping with that. Much appreciated! What a stupid mistake. I do not even know why I put this margin there :)

**Comment by abdusabri** [comment]
You are very much welcome! Glad I could help 🙂
