### ISSUE TITLE
FreeCodeCamp - Product landing page bugs

### ISSUE THREAD

**Issue by radifantaufik** [freeCodeCamp/testable-projects-fcc#795]
#### Issue Description

I just finished Responsive Web Design Projects - Product Landing Page. I think the system didn't recognize my media query and CSS flex-box, because I already did in my CSS.

#### Browser Information

* Browser Name, Version: Google Chrome 72
* Operating System: windows 10 
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
 https://codepen.io/radifantaufik/pen/omeVJB
 
 
```

**Comment by ValeraS** [comment]
@radifantaufik choose the right CSS preprocessor and you will pass the test.
![image](https://user-images.githubusercontent.com/10867286/52282442-7c99ac80-2971-11e9-817d-3cc862b9a3c5.png)

**Comment by radifantaufik** [comment]
Thank you for the answer!

**Comment by Dahimi** [comment]
thanks for your web site
