### ISSUE TITLE
Personal Portfolio Nav Issues

### ISSUE THREAD

**Issue by purKhaos** [freeCodeCamp/testable-projects-fcc#797]
#### Issue Description

My nav bar is position fixed and remaining at the top of the page upon scrolling, just like in the example. When I run the test, it says it fails for not staying at the top of the page. 

#### Browser Information

* Browser Name, Version: All browsers
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Laptop

#### Your Code / Link to Your Pen

 https://codepen.io/purKhaos/pen/rPGaoy

**Comment by ValeraS** [comment]
@purKhaos In your project, elements of `navbar` are fixed but not `navbar` itself.

**Comment by purKhaos** [comment]
@ValeraS you are correct. I have adjusted that and have passed the tests. Always nice to have a fresh set of eyes look over things. Thank you for your input.
