### ISSUE TITLE
Test Case Failed

### ISSUE THREAD

**Issue by dannyleeds** [freeCodeCamp/testable-projects-fcc#799]
#### Issue Description

When running tests on the tribute page test, no matter what code I use I cannot get the responsive image size test to complete.

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: Windows 7 Enterprise
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
 https://codepen.io/dannyleeds/pen/jdYRwv
 
 
```

#### Screenshot

![image](https://user-images.githubusercontent.com/47245784/52475151-83ebd080-2b92-11e9-9c33-ff510106365a.png)

**Comment by tbushman** [comment]
@dannyleeds The discussion at #778 may help you. The responsive-resize test looks for certain css properties.
