### ISSUE TITLE
Technical Document Page: User Story #11

### ISSUE THREAD

**Issue by akiko-pusu** [freeCodeCamp/testable-projects-fcc#800]
#### Issue Description

Thanks for this awesome learning contents.

I'm not sure this is a bug or not. So this is just a suggestion. 
If my html source code has no a (link) element the 11th test corresponding with User Story #11 passed.

``User Story #11: The header element in the navbar must come before any link (a) elements in the navbar.``

#### Browser Information

* Browser Name, Version: 
  * Google Chrome 72.0.3626.96
* Operating System: 
  * MacOS Mojava (10.14.3)
* Mobile, Desktop, or Tablet: 
  * Desktop (MacBook 12.5 inch)

#### Your Code / Link to Your Pen

CodePen: 
https://codepen.io/akiko-pusu/pen/exVrKo

Though #navber header element has no a(link) element, test 11th has passed.

```
<nav id="navbar">
  <header>JS Documentation</header>
    <!-- Remove ul and the list items --> 
</nav>
```

```
it("The <header> element in the navbar must come before any\n      link (<a>) elements in the navbar.", function() {
    var e = document.querySelectorAll("#navbar a.nav-link"),
        t = document.querySelectorAll("#navbar header").item(0),
        r = !0;
    e.forEach(function(e) {
            t.compareDocumentPosition(e) & Node.DOCUMENT_POSITION_FOLLOWING || (r = !1)
        }),
        s.assert.strictEqual(r, !0, "The <header> element contained by the navbar must be come before any link (<a>) elements contained by the navbar")
}),
```
IMO, var r is assigned as !0 and s.assert.strictEqual(r, !0...) is always true, in case there is no a (link).

Of course just before this test case, nav-link's count is examined and in case there is no link test failed as following:  https://github.com/freeCodeCamp/testable-projects-fcc/blob/9b93dd4a8795801eefd924994a9643cd193e1208/src/project-tests/technical-docs-tests.js#L220-L225

#### Screenshot

![technical-document-page-user-story-11](https://user-images.githubusercontent.com/122621/52517890-c93cfa80-2c85-11e9-8b55-751ce6344afe.png)

**Comment by tbushman** [comment]
@akiko-pusu Thank you. :)

**Comment by ValeraS** [comment]
@akiko-pusu IMO, not an issue. Test says `The header element in the navbar must come before any link (a) elements in the navbar.` and this is true if we have a `header` and do not have any link elements.
