### ISSUE TITLE
Remove use of SCSS from product landing page example project

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/testable-projects-fcc#804]
#### Issue Description

I think we should remove the use of SCSS from the product landing page example project.

A lot of campers do not understand it is using SCSS, or even know how it works. They are copying the CSS without using SCSS so all the nesting fails. Considering SCSS/SASS is first introduced in the Front End Libraries Certification part of the curriculum it seems counterintuitive to have a project using it in the Responsive Web Design Projects part of the curriculum.

/cc @tbushman @ValeraS Thoughts?

**Comment by tbushman** [comment]
@lasjorg That should be fine. We're a bit behind in reviewing #781. It has the opposite problem, wherein the proposed changes are improvements not mentioned in the curriculum (?). I don't have a strong opinion about this and have dragged my feet. I would sooner merge this idea.

**Comment by lasjorg** [comment]
@tbushman What exactly is the problem in https://github.com/freeCodeCamp/testable-projects-fcc/pull/781 if you don't mind me asking?

I can just change whatever is needed, I'd just like to know. The only think I can think of is the rem sizing that isn't explicitly covered in the curriculum.

**Comment by tbushman** [comment]
@lasjorg I should clarify that the motivation for changing the example project, the caption tags, is not a requirement nor mentioned in the curriculum up to that point. If I'm wrong let me know. I'm fine with merging it. Sorry for dragging my feet.

**Comment by lasjorg** [comment]
figure and figcaption is shown in this challenge.
https://learn.freecodecamp.org/responsive-web-design/applied-accessibility/improve-chart-accessibility-with-the-figure-element/

Not sure what you mean about the requirements?

The test has an requirement of: https://github.com/freeCodeCamp/testable-projects-fcc/blob/abdc19c6f2db68c3b0e3435156604c833a8bca70/src/project-tests/tribute-page-tests.js#L62

**Comment by tbushman** [comment]
@lasjorg You're right. I hadn't run it locally, and now I'm seeing a problem with the master branch styles not matching the codepen example (not your contribution). ... sorry for the delay.

**Comment by tbushman** [comment]
NVM I was in the unbuilt directory. Oops. I will merge #781. Thanks, @lasjorg .

**Comment by lasjorg** [comment]
@tbushman 

I have the PR for the product landing page ready, I just have one problem. The Codepen version is using font awesome but the version in this repo is not. Should it be added and if so where/how would I add font awesome?

If it needs to go in the head, then looking at the gulp and pug files, it looks like it has to be part of the build process. Not sure if that is true, or how I would do it.

**Comment by lasjorg** [comment]
/cc @tbushman @ValeraS 

Can I get an answer to my question about how to include font awesome?

**Comment by lasjorg** [comment]
@tbushman Why did you close this issue? I never got an answer to my questions.

1. Should I make a PR for this or not?
2. How should I handle the use of font awesome?

**Comment by tbushman** [comment]
@lasjorg I'm not sure how font-awesome works now, so I was thinking someone else might chime in. If it's a CDN URL, you can include it in the `<head>`.

**Comment by tbushman** [comment]
@lasjorg Go ahead with a PR if you still wish.

**Comment by lasjorg** [comment]
@tbushman The problem is there is no head element on the page or html/body for that matter. The code is like you have it on Codepen with just the main content. So I have nowhere to put the link to font awesome. @ValeraS Can you help answer this question?

I will just push what I have as is for now.
