### ISSUE TITLE
Technical page

### ISSUE THREAD

**Issue by rickybass** [freeCodeCamp/testable-projects-fcc#805]
I am not passing items 10,12, and 13 related to a class of "nav-link", its header, and movement. It seems that I have nav-link, a header and it moves when navigation is clicked. I am not sure if it is a testing issue or my code.

Here is a link to my codepen:
https://codepen.io/pbassi/pen/QYNoam

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 
 
```

**Comment by tbushman** [comment]
@rickybass Hi. The error mentions that you were missing the nav-link for `Minimal Risk Review`. Include that in your navigation and you will pass.  
Another problem I saw was a missing quotation mark for your className property:  
change:  
`<ul class="nav flex-column id="navbar">`   
to:  
`<ul class="nav flex-column" id="navbar">`

**Comment by rickybass** [comment]
Thank you so much. Any suggestions or references on how to debug to see things like this?

**Comment by tbushman** [comment]
The html tags turned green, so I looked for where that started. I don't think it was a breaking problem, though. Mainly it was the missing navigation item, and you can expand the test results and let us know if the error message doesn't make sense so we can improve it.
