### ISSUE TITLE
Navigation bar overlap

### ISSUE THREAD

**Issue by Murlokk** [freeCodeCamp/testable-projects-fcc#807]
May navigation bar is overlap next <p> wen i do position: fixed;

#### Browser Information

* Browser Name, Version:  Google Chrome version 72
* Operating System: Windos 8.1 pro
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```https://codepen.io/Murlok/pen/JxWezL
 
 
 
```

**Comment by Murlokk** [comment]
The link to may pen: 
https://codepen.io/Murlok/pen/JxWezL

**Comment by tbushman** [comment]
@Murlokk If you put all of your main content inside of the `<div class="container"> {all main content minus nav header here} </div>`  , then you could do:  
```  
.container {
  ...
  margin: 100px auto;
}  
```
