### ISSUE TITLE
[Tribute Page] Problems with grid/block and center the image

### ISSUE THREAD

**Issue by Dawienchi** [freeCodeCamp/testable-projects-fcc#809]
#### Browser Information
* Browser Name, Version: Firefox, 65.0.1 (64-Bit)
* Operating System: Win 10 (64-Bit)
* Mobile, Desktop, or Tablet: Desktop

Hey! 

I just finished the Tribute-Page project, by I had problems with the following user stories: 

**User-Story 8: "The `img` element should responsively resize, relative to the width of its parent element, without exceeding its original size."**

First I used for the whole page display: grid. For the image the code looked like that:

img {
  width: 55%;
  justify-self: center;
}

#img-div {

  color: black;
  margin-bottom: 10px;

  display: grid;
  grid-template-columns: 1fr;
  grid-template-rows: auto;
}

    <div id="img-div">
      <figure>
        <img id="image" src="placeholder" alt="Mary Wilkes at a computer">
[details="Summary"]
This text will be hidden
[/details]

        <figcaption id="img-caption">Mary Allen Wilkes in front off one of the first computers.</figcaption>
      </figure>
    </div>

In my browser it was responsive, but I couldn`t pass the test.
Not until I changed the code like that: 

#image {
  display: block;
  margin-left: auto;
  margin-right: auto;
  max-width: 100%;
  width: 100%;
}

#img-div {
  margin-bottom: 10px;

  display: grid;
  grid-template-columns: 1fr;
  grid-template-rows: auto;
}

So in my eyes, the solution was to change display: grid to display: block. 
But I don`t understand the difference between grid and block?

and:

**User-Story 9: " The `img` element should be centered within its parent element."**

I only managed setting the image centered by adding justify-self to the image class:

img {
  width: 55%;
  justify-self: center;
}

But the img is in this parent container. I would like to set all elements of this container to center, but I couldn`t find a way..

#img-div {
  color: black;
  margin-bottom: 10px;

  display: grid;
  grid-template-columns: 1fr;
  grid-template-rows: auto;
}

What would be the elegent solution for this?

Thank you very much!! :slight_smile:

Best wishes,
Matthias

**Comment by tbushman** [comment]
@Dawienchi The `display: block;` property is one of the properties the test looks for to determine whether an image is responsive. `display: grid;` is great and supported by most browsers now to help lay out DOM objects more easily. For this lesson, students get an understanding of the `display: block;` property in relation to other properties.  
To center your image, try adding `margin: auto;` to `img` with `display: block;`
