### ISSUE TITLE
Error in #Layout of Product Landing project 

### ISSUE THREAD

**Issue by GeeteshSingh** [freeCodeCamp/testable-projects-fcc#810]
I've been editing my product web page but its not working.
Following  errors shows up every time I correct it even after I had been meeting there requirements

1. My product landing page should have at least one media query.
2.My product landing page should utilize CSS flexbox at least once.

<img width="960" alt="error" src="https://user-images.githubusercontent.com/14001562/53283686-e38bd380-376f-11e9-8760-a9c561e0eaa1.png">
[index.txt](https://github.com/freeCodeCamp/testable-projects-fcc/files/2896608/index.txt)
[css.txt](https://github.com/freeCodeCamp/testable-projects-fcc/files/2896609/css.txt)

`

**Comment by tbushman** [comment]
@GeeteshSingh You will need a simple local server to run your project. Please see https://www.npmjs.com/package/live-server and let me know if you have any questions.
The other option is to use Codepen.
