### ISSUE TITLE
Project will NOT pass Test

### ISSUE THREAD

**Issue by moniquerenecoates** [freeCodeCamp/testable-projects-fcc#811]
#### Issue Description

We were to use template via link below to create our first TRIBUTE PAGE for FCC:
**https://codepen.io/freeCodeCamp/full/zNqgVx**

However code created 4 - 5 errors OK, I fixed them. But then the page code created 10 MORE errors after that!  I started reading them, and realized there were too many errors that were just NOT related to the page I was trying to create,, but that were more related to the ORIGINAL Tribute Page link & the code that was given to us from FreeCodeCamp.com to begin with.

#### Browser Information

* Browser Name, Version: Google Chrome Version 72.0.3626.109
* Operating System: Windows 8.1
* Mobile, Desktop, or Tablet: Desktop

**Comment by moniquerenecoates** [comment]
https://codepen.io/Moni-Rene/pen/XGrmLb

**Comment by petercr** [comment]
@moniquerenecoates I just took a look 👀 at your pen to see if there were any problems with the testing suite _the program which runs the tests_
I was actually able to get your CodePen pen to pass all 10 tests, so they are definitely working. 

Here's some hints, combine both `<img>` tags in `#img-div` into 1 tag and make sure to add an `id="image"` property in the combined `img` tag.

Secondly you closed the `#img-div` a little too early... if you move it's closing tag further down, then the page will pass all the tests.

Hope this helps, have a great day 😄 👍 

Peter Cr

**Comment by moniquerenecoates** [comment]
Thank you Peter, I appreciate the help. I am not sure the folks at FCC
really want me there.
They are hacking my coding attempts and my Pixabay image links and putting
stupid scary faces in instead. .

This was my first project and I was overwhelmed with the coding info I put
into my system,
so sorting it all out was EASIER completing a project without an FCC code
link actually! LOL 😉

We'll see if we continue or not. Anyway, thank you again!
I appreciate it
-Monqiue

*Monique Rene Coates*

*New England (RI)401-209-8498*

**Comment by tbushman** [comment]
@moniquerenecoates  
```  
<div id="img-div"> 
<img class="thumbnail text-center nature-img" src="https://www.pixabay.com/photo/2018/04/04/13/38/nature-3289812_640.jpg"><div id="imgsrc"  alt="nature-img."></div>  
```

**Comment by petercr** [comment]
@moniquerenecoates I sorry if you feel like anyone at Free Code Camp would  not want you there. The people are wonderful, and always promote diversity. 

With regards to the Pixabay image not loading, that is due to the fact that CodePen is being served over `https` and Pixabay is trying to serve the image over `http. You most likely need a free developer API key in order to use it over `https`

Best of luck 😄 👍

**Comment by moniquerenecoates** [comment]
Hi Peter,
I think we jumped to quickly, we are at peace with freecodecamp folks.
They were just getting frustrated with me bugging them too much.
We also got the page to work and pass the test! YAY! 😀
Along with the Pixabay image too !!

Thank you!
*Monique Rene Coates*

*New England (RI)401-209-8498*
