### ISSUE TITLE
promodoro clock

### ISSUE THREAD

**Issue by lamiaael** [freeCodeCamp/testable-projects-fcc#812]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 
 
```

**Comment by tbushman** [comment]
Hello @lamiaael , please open a new issue with some more information about the error you are experiencing. Indicate which test is failing and provide a screenshot, a code sample, or a link to your project.
