### ISSUE TITLE
Test bug: green button but 0/0

### ISSUE THREAD

**Issue by SadCaterpillar** [freeCodeCamp/testable-projects-fcc#816]
#### Issue Description
I've used the FCC Test Suite successfully for 2 projects. When I forked it for the 3rd project, the button turns green but shows 0/0. I tested it for the 2 older projects, it also turns green and 0/0 (previously all tests were shown as completed, like 17/17). 

#### Browser Information
* Browser Name, Version: Google Chrome Version 72.0.3626.119 (Official Build) (32-bit)
* Operating System: Windows 7 Starter
* Mobile, Desktop, or Tablet: Desktop (laptop)

#### Your Code / Link to Your Pen
https://codepen.io/sad_caterpillar/pen/rPgNBV - my 1st project, before the bug all tests were completed successfully

#### Screenshot

![fcc test_bug_02 03 19](https://user-images.githubusercontent.com/33433876/53682959-44854f80-3d0c-11e9-8b98-64593e612156.jpg)

**Comment by ValeraS** [comment]
@SadCaterpillar You did not choose a test suite.

**Comment by SadCaterpillar** [comment]
@ValeraS  Thanks for your comment, that indeed was the issue.
