### ISSUE TITLE
userStory #5 is failing but my anchor is linking to a section of the page and working properly

### ISSUE THREAD

**Issue by marcsanchez1** [freeCodeCamp/testable-projects-fcc#818]
userStory #5 is failing but my anchor is linking to a section of the page and working properly

#### Steps to Repro

# Navigate to https://codepen.io/manchez/full/pYNOQj
# Click on 'Products' or 'Featured Products' link in top nav

#### Browser Information

Google Chrome
Version 72.0.3626.96
MacOS Mojave
Desktop

#### Your Code / Link to Your Pen

```
 https://codepen.io/manchez/full/pYNOQj
 
 
```

**Comment by tbushman** [comment]
@marcsanchez1 it may not be an ideal solution, but to pass the test, include an empty anchor at the top of the dom tree, `<div id="home"></div>`
and then remove the `href` in 
```   
<a class="navbar-brand">
```  
and give the `home` section the `home` `id`  
```   
<a class="nav-link" href="#home">Home <span  ...  
```   
  
the instances of `href="#"` are tripping up the tests. I'll keep this open.

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
