### ISSUE TITLE
Product Landing page layout tests #2 & #3 not recognizing CSS rules in local development

### ISSUE THREAD

**Issue by aaronRhodebeck** [freeCodeCamp/testable-projects-fcc#82]
#### Issue Description

Tests pass on [CodePen](http://codepen.io/arhodebeck/pen/oZEEPd), but do not pass with the same code in local environment. CSS stylesheet is linked and working, same code in both places, and those two tests are the only tests not passing. GitHub repo of page is [here](https://github.com/aaronRhodebeck/FCCampProductLandingPage)

#### Browser Information

* Browser Name, Version: Chrome Version 56.0.2924.87 (64-bit), Firefox 52.0 (32-bit)
* Operating System: Windows 10, 10.0.14393
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
 @media (min-width: 600px) {
    .mobile-stack {
        flex-direction: row;
    }
}

.flex {
    display: flex;
}
```
**Relevant tests** 
```
 it('2. My product landing page should have at least one media query.', function() {
                let queryRules = [];
                // loop through all associated stylesheets and look for media query
                for (var i = 0; i < document.styleSheets.length; i++) {
                    if (document.styleSheets[i].cssRules !== null) {
                        for (var j = 0; j < document.styleSheets[i].cssRules.length; j++) {
                            if (document.styleSheets[i].cssRules[j].type === 4) {
                                // push query rules to empty array
                                queryRules.push(document.styleSheets[i].cssRules[j]);
                            }
                        }
                    }
                }
                // there is one media query in Mocha.css, so must detect more than 1 query
                FCC_Global.assert.isAbove(queryRules.length, 1, 'No media queries detected ');
            });

            it('3. My product landing page should utilize CSS flexbox at least once.', function() {
                // loop through all associated stylesheets and look for display of flex
                const flexCount = [];
                for (var i = 0; i < document.styleSheets.length; i++) {
                    if (document.styleSheets[i].cssRules !== null) {
                        for (var j = 0; j < document.styleSheets[i].cssRules.length; j++) {
                            if (document.styleSheets[i].cssRules[j].style !== undefined &&
                                document.styleSheets[i].cssRules[j].style.display === 'flex' ||
                                document.styleSheets[i].cssRules[j].style !== undefined &&
                                document.styleSheets[i].cssRules[j].style.display === 'inline-flex') {
                                flexCount.push(1);
                            }
                        }
                    }
                }
                // our test suite uses a display of flex, so we need to count how many times its used
                // and confirm that its more than once. If we just detect one instance, its ours.
                FCC_Global.assert.isAbove(flexCount.length, 1, 'We do not detect a display property set to flex or inline-flex anywhere in your CSS ')
            });
```

**Comment by CollinPerkins** [comment]
@aaronRhodebeck I am having the same problem. I have no issues with the rest of the tests.

**Comment by no-stack-dub-sack** [comment]
@aaronRhodebeck @CollinPerkins Just curious - if you add a second flex rule and a second media query in your local environment, do the tests pass?

This could be something to do with the way the total css is ultimately looped through in codepen vs. locally. We are testing that 2 rules exist, because at least in the codepen environment it also loops through mochas css rules.

p.s. glad you are testing these out locally, we haven't had too many people do this yet. I've done it myself with most projects, but not all, and that was within the dev environment of this project, so not sure how that might affect it.

**Comment by Christian-Paul** [comment]
@no-stack-dub-sack Just did some probing and I think I found the problem.

The CSSStyleSheet object's cssRules property has a value of null when testing locally. Interestingly, the cssRules property fills out properly when testing it in the development environment.

I believe this is happening because of this security feature:
https://bugs.chromium.org/p/chromium/issues/detail?id=143626

I'm not sure how we can work around this.

**Comment by Christian-Paul** [comment]
@no-stack-dub-sack If the user puts the styles in the same file as their html, the tests can access the css and work properly. They could either use a bundler (probably overkill for such a small/early project) or include the css in a style tag in the html (not the best practice).

Barring that, I think we'd have to scrap those tests and check for responsiveness some other way.

**Comment by aaronRhodebeck** [comment]
After doing a little more testing, it is definitely due to the cross-site scripting security features in chrome.  Ironically, you can use Firefox and the cssRules come through for any local stylesheets, however, the external stylesheets throw security errors.  And it's a mute point because at the moment, none of the layout tests work in Firefox.

This code will push media queries to the array in Firefox, from a local stylesheet
```
function getStylesheets() {
    var stylesheets = [];
    for (var i = 0; i < document.styleSheets.length; i++) {
        stylesheets.push(document.styleSheets[i]);
    }
    return stylesheets;
}

function getStylesFromStylesheet(stylesheet) {
    var mediaRules = [];
    for (var i = 0, len = stylesheet.cssRules.length; i < len; i++) {
        if (stylesheet.cssRules[i].type === 4) {
            mediaRules.push(stylesheet.cssRules[i]);
        }
    }
    return mediaRules;
}
```
It appears you can [get around the error with a try/catch block](http://stackoverflow.com/questions/21642277/security-error-the-operation-is-insecure-in-firefox-document-stylesheets), but I don't know how helpful anything in Firefox is going to be.

**Comment by no-stack-dub-sack** [comment]
@Christian-Paul ughhh... this project is turning out to be a nightmare in some ways. Accounting for everything is going to be like nearly impossible. Not sure what the best fix is here. Perhaps your suggestion from above about putting the css in the HTML itself for those specific projects - not sure where the best place to indicate that would be. 

Have any other thoughts on testing responsiveness without these tests?

**Comment by tchaffee** [comment]
@no-stack-dub-sack @aaronRhodebeck @CollinPerkins I cloned this repo and tested locally and all tests passed. Perhaps something has been fixed since this issue was opened? Can one of you test locally to see if you can still repeat the problem?

**Comment by tchaffee** [comment]
@no-stack-dub-sack @aaronRhodebeck @CollinPerkins  I'm closing this since I haven't heard back from anyone about reproducing the problem. If one of you can reproduce, please feel free to reopen.

**Comment by leonard246** [comment]
Had the same issue HTML file does not recognised linked CSS file. 
Adding this to the HTML head section fixed it for me.
`	<style type="text/css"> 
		@media (max-width: 500px) {
		#header { display: flex; }
	}
	</style>`

**Comment by leonard246** [comment]
Had the same issue HTML file does not want to recognise the linked CSS file.
Adding style tags to the HTML fixed it for me.
<style type="text/css"> @media (max-width: 500px) { #header { display: flex; } } </style>

**Comment by leonard246** [comment]
Had the same issue HTML file does not want to recognise the linked CSS file.
Adding style tags to the HTML fixed it for me.
`<style type="text/css"> @media (max-width: 500px) { #header { display: flex; } } </style> `

**Comment by akiko-pusu** [comment]
This is just a FYI:
I saw the same issue on my local machine.  My workaround is see the contents via local http server.

I think this is caused from Chrome’s security policy, CORS,  in case trying to see local contents via file:// protocol.

```bash
# example
$ open -a Google\ Chrome terget-page.html
```

And all the tests are passed in case access the contents through http server locally.
In my case,  run the php’s build-in server.

```bash
# example
$ php -S 127.0.0.1:3000 &
$ open -a Google\ Chrome http://127.0.0.1:3000/landing-page.html
```
(You can use ``python -m SimpleHTTPServer 3000`` or node.js http-server)

Here is a screenshot when I accessed the contents via file:// protocol.
Tests except dealing with CSSStyleSheets object are passed.
In my debug console, DOMException happened when CSSStyleSheets.cssRules ( t.cssRules ) was called.

![cssrules-error](https://user-images.githubusercontent.com/122621/52170990-f37b4d80-2797-11e9-8cd5-2d5d862c9ca5.png)

```
   // Related function
    var U = r(1)
      , V = r.n(U)
      , K = r(2)
      , Y = r.n(K)
      , z = r(4)
      , X = r.n(z)
      , J = function(e) {
        return [].slice.call(e).reduce(function(e, t) {
            try {
                if (t.cssRules) {
                    var r = [].slice.call(t.cssRules).filter(function(e) {
                        return e.type === CSSRule.STYLE_RULE || e.type === CSSRule.MEDIA_RULE
                    });
                    e.push.apply(e, X()(r))
                }
            } catch (e) {
                if (!(e instanceof DOMException)) // this exception raised.
                    throw e
            }
            return e
        }, [])
    }
```


Example project is: https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-projects/build-a-product-landing-page/

- First, I could passed all the tests of my project on CODEPEN, which is cloned from https://codepen.io/freeCodeCamp/full/RKRbwL
  - As you know, the browser I use is Chrome and all the contents are on the **server side**. (Through
 https protocol)

- Second, I store the same files and wrote codes on my local machine.
  - Also I copied test script on CDN locally.
  - I could see almost the same look and feel in my local browser, and run the FCC’s test.

But some of tests related to layout tests were failed.
 
Hope this comment would be any help :)
