### ISSUE TITLE
Broken link in PULL_REQUEST_TEMPLATE

### ISSUE THREAD

**Issue by WofWca** [freeCodeCamp/testable-projects-fcc#821]
#### Issue Description

First link here is no longer valid:

https://github.com/freeCodeCamp/testable-projects-fcc/blob/cfe4f236b0217afb6fd3a996b72b7e9333b976ef/.github/PULL_REQUEST_TEMPLATE.md#L4

**Comment by thecodingaviator** [comment]
Fixed it, so closing the issue
