### ISSUE TITLE
personal portfolio

### ISSUE THREAD

**Issue by ranjitha1709** [freeCodeCamp/testable-projects-fcc#823]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 
 
```

**Comment by ranjitha1709** [comment]
> #### Issue Description
> #### Browser Information
> * Browser Name, Version:
> * Operating System:
> * Mobile, Desktop, or Tablet:
> 
> #### Your Code / Link to Your Pen
> ```
>  
>  
>  
> ```
> #### Screenshot

https://codepen.io/Ranjitha17/pen/rRyvdN

**Comment by thecodingaviator** [comment]
@ranjitha1709 I do not understand what's going wrong i.e. why you've opened this issue, could you elaborate?
