### ISSUE TITLE
Keyboard shortcuts intersect with browser shortcuts

### ISSUE THREAD

**Issue by WofWca** [freeCodeCamp/testable-projects-fcc#824]
#### Issue Description

In Chrome, `CTRL` + `SHIFT` + `O` is "Bookmarks".
In Chrome and Firefox `CTRL` + `SHIFT` + `T` is "Undo Close Tab".

https://github.com/freeCodeCamp/testable-projects-fcc/blob/70d29de1648ac7df8235c56798d2f12cc2b1f161/src/index.js#L232-L253

**Comment by tbushman** [comment]
I think we should remove this part. I don't ever use it (selenium doesn't even use it), and conflicts like this are annoying. Thanks @WofWca . Can we wait to see what other moderators think?

**Comment by tbushman** [comment]
We should probably come up with alternative keys to maintain accessibility. Thank you.

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
