### ISSUE TITLE
Survey Form

### ISSUE THREAD

**Issue by natab00** [freeCodeCamp/testable-projects-fcc#827]
I am having issues passing tests 8, 9 and 11. 

#### Issue Description

For test 8: I have ensured these fields are "required" and my form is getting a validation error, however the test is not passing. 
For test 9: I am seeing the validation error on the form when a enter a number outside of the max, however the test is not passing. 
For test 11: I have added placeholders to each field and the test is not passing. 

#### Browser Information

* Browser Name, Version:  Chrome
* Operating System: Mac
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
 https://codepen.io/natalie-hart/pen/drNEZq
 
 
```

**Comment by thecodingaviator** [comment]
Test 8 does not ask you to do what you've done, read it again, you'll know what's up

**Comment by natab00** [comment]
![Screen Shot 2019-03-11 at 5 14 03 PM](https://user-images.githubusercontent.com/48087348/54164224-7b044e00-4421-11e9-99b2-7d72d4f1860b.png)


For test 6 this is the validation error I see when I enter non-numbers into the field. Should I get getting a different error?

**Comment by ValeraS** [comment]
@natab00 Your code contains more than one element with `id="number"`.

**Comment by natab00** [comment]
Thank you ValeraS!
