### ISSUE TITLE
nav-link issues documentation page

### ISSUE THREAD

**Issue by gxc346** [freeCodeCamp/testable-projects-fcc#828]
#### Issue Description

When you run the tests it claims in my pen it fails three tests. All three tests have to do with my links or <a> tags. 

#### Browser Information

* Browser Name, Version: Google Chrome, Version 72.0.3626.121 (Official Build) (64-bit)
* Operating System: Windows 10
* Mobile, Desktop, or Tablet:  Desktop

#### Your Code / Link to Your Pen

```
 https://codepen.io/gcervantes/pen/JzEQwP?editors=1000
 

```

**Comment by gxc346** [comment]
@ValeraS wow, that's embarrassing. Thank you!

**Comment by thecodingaviator** [comment]
@gxc346 Close the issue if fixed
