### ISSUE TITLE
ithink idone it all

### ISSUE THREAD

**Issue by MohamedBasueny** [freeCodeCamp/testable-projects-fcc#829]
#### Browser Information

* Browser Name, Version: google chrome
* Operating System:  windows
* Mobile, Desktop, or Tablet: desktop

#### Your Code / Link to Your Pen

```
  https://codepen.io/basueny/pen/aMVvgy
 
 
```

**Comment by tbushman** [comment]
@MohamedBasueny Thanks. The welcome-section issue is a bug.  
@MohamedBasueny has used a legitimate method (`padding-top`) for centering text vertically inside the `welcome-section` `div` but this causes the test to fail.  
You can pass that test if you remove `padding-top` from the welcome section and adjust the text vertically inside of it by other means until we can improve the test.  
The `nav` issue can be solved by adding `nav { position: fixed; }` to your css.

**Comment by ValeraS** [comment]
@MohamedBasueny for welcome-section with `height:100vh` use `box-sizing: border-box`.
