### ISSUE TITLE
Random Quote -- short quote lists and timeout

### ISSUE THREAD

**Issue by tbushman** [freeCodeCamp/testable-projects-fcc#830]
https://github.com/freeCodeCamp/testable-projects-fcc/blob/72c85c45bb6717db48812a8b8b103fb9bcbc39c3/src/project-tests/quote-machine-tests.js#L154  
we need a loop or something to cycle through quotes if the authors match, or a better test ensuring unique quotes are generated sequentially.   
  
These pens are failing this test occasionally:  
https://codepen.io/rmdawson/pen/vPRQGE  
https://codepen.io/verde79/pen/bZvRyM

**Comment by RandellDawson** [comment]
Another issue related to this (see #879) is that if the user has some or all quotes from the same author, then the chances of test number 9 failing are much higher.

Once way of resolving the issue with a user having the same author is to change the test to just make sure there is a value in the author field from one click to the next.  Then, in test number 8, it would be changed to concatenate the author and the quote and test that the previous author/quote combo is different the next author/quote combo.

None of the above resolve the main issue which is if the number of quotes is small.  I see two ways of "fixing" this issue.  

1. Either change the test description for test number 8 to:
> When the #new-quote button is clicked, my quote machine should fetch a new and different quote than the previous and display it in the #text element.

This forces the user to use some different logic in their project, which is not necessarily a bad thing.  Also, somewhere in the challenge instructions, it should be state somewhere that "the number of different quotes has to be at least 2 or the tests may not pass".  

2. Have the test run 3-4 times and as long as it finds a different quote combo than the previous within 3-4 clicks, the test would pass.  This is not guarantee it will pass, but will increase the odds of passing.  In general, I believe there should be a note on this challenge explaining if the user plans to use a manually created list of quotes, that they should have at least 10 quotes to increase the chances of passing all the tests.

**Comment by tbushman** [comment]
> make sure there is a value in the author field from one click to the next. Then, in test number 8, it would be changed to concatenate the author and the quote and test that the previous author/quote combo is different the next author/quote combo.   

Good strategy.  
> "the number of different quotes has to be at least 2 or the tests may not pass"  

Same.   
> that they should have at least 10 quotes to increase the chances of passing all the tests.  

...this should be the first thing we can do to close the issues at the least, if someone wants to make a quick fix to the user story until we can fix the test logic.

**Comment by abhishekakade** [comment]
I'd like to fix the requirements. I just have to add a user story saying "if you are not `fetch`ing quotes from a server, then you should have at least 10 quotes" right?

**Comment by tbushman** [comment]
@abhishekakade Thanks very much. :) Please don't conditionalize `fetch`ing quote lists vs. local quote lists, since we want a longer list in either case.

**Comment by abhishekakade** [comment]
Btw this should be on the `freeCodeCamp/freeCodeCamp` repo, right? How do we reference an issue from here over there? Or do we need to raise a new issue on `freeCodeCamp/freeCodeCamp` repo?

This is the file that needs to be edited for adding that user story for at least 10 quotes -
`https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/03-front-end-libraries/front-end-libraries-projects/build-a-random-quote-machine.english.md`

And do I also need to update the fcc-test-suite to check for that user story? I don't know much about testing yet so I don't know how to go about with that.
This file will need to be updated for adding tests for the new user story (although I'm not sure if this is the only one) -
`https://github.com/freeCodeCamp/testable-projects-fcc/blob/master/src/project-tests/quote-machine-tests.js`

**Comment by tbushman** [comment]
@abhishekakade That, too. :) We can open an issue over there after we solidify the language in your PR here.  
Regarding the test-suite, we can keep this issue open maybe until we develop a test that checks the list length, but for now your PR may be user-story text only so students using shorter lists know why their test fails occasionally.

**Comment by RandellDawson** [comment]
@abhishekakade If you want to add the text changes on a PR, I can create a separate PR which addresses the needed tests.  If you want to do both, then that is fine too.  Just let me know.

**Comment by abhishekakade** [comment]
@RandellDawson, yes, that would be great because I don't know much about testing yet. Thank you!

**Comment by abhishekakade** [comment]
@tbushman, for the user story, is it fine if I change it as @RandellDawson has suggested? -

> I believe there should be a note on this challenge explaining if the user plans to use a manually created list of quotes, that they should have at least 10 quotes to increase the chances of passing all the tests.

So will it be fine if I modified user story `#8` to -
**`User Story #8: When the #new-quote button is clicked, my quote machine should fetch a new quote and display it in the #text element. If you want to use manually created list of quotes, then make sure the list has more than 10 quotes at least to increase your chances of clearing all the tests.`**

Please let me know if this is fine or if it requires any changes. Thank you!

**Comment by tbushman** [comment]
@abhishekakade I would change it to:  
```  
When the #new-quote button is clicked, my quote machine should fetch a new quote and display it in the #text element. Make sure the list has at least 10 quotes to increase your chances of clearing all the tests.  
```   
Thank you!

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
