### ISSUE TITLE
Story #4 Technical Documentation Page error

### ISSUE THREAD

**Issue by jaeyson** [freeCodeCamp/testable-projects-fcc#831]
im scratching my head for 2 days now. i was looking for same issues here in order to avoid duplicate threads, except that its closed.

Here's my problem:

- user story no. 4: each `<section>` element with the class of “main-section” should also have an id that corresponds with the text of each `<header>` contained within it. Any spaces should be replaced with underscores (e.g. The `<section>` that contains the header “Javascript and Java” should have a corresponding id=“Javascript_and_Java”).

when i click run test:
`Some "main-section" elements are missing the following ids (don't forget to replace spaces with underscores!) : GOBAL_VARIABLES : expected 1 to equal 0`

still scratching my head for 2 days now.

* Browser Name, Version: Chrome x64, 73.0.3
* Operating System: Win 10 x64
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

[codepen](https://codepen.io/jaeyson/pen/Lambjm)

#### Screenshot

![image](https://user-images.githubusercontent.com/22448332/54574662-1dc55980-4a2c-11e9-971f-e600543ea548.png)

**Comment by ValeraS** [comment]
@jaeyson check the spelling of a header `G ->l<- obal variable`.
