### ISSUE TITLE
Update Codepens

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/testable-projects-fcc#832]
Is it possible for someone to update the example project Codepens?

We have some fixes but they are all just in this repo. I think it would be a good idea to at least update the technical documentation project with the new code from this PR https://github.com/freeCodeCamp/testable-projects-fcc/pull/750 as it is pretty bad. People are using the invalid HTML in their projects and we also get issues https://github.com/freeCodeCamp/freeCodeCamp/issues/35624 on it.

**Comment by raisedadead** [comment]
I can update the pens, can either of you fork the pen, make fixes and share a link here for the below:

- Link to the original challenge.
- Link to the original pen in the challenge.
- Link to the forked/fixed pen.

Thanks a lot.

**Comment by lasjorg** [comment]
## Fixed projects that has been merged into the testable-projects-fcc repo:

### Challenge: Responsive Web Design Projects - Build a Tribute Page

Challenge: Responsive Web Design Projects - Build a Tribute Page
https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-projects/build-a-tribute-page/

Original Codepen:
https://codepen.io/freeCodeCamp/full/zNqgVx

Fixed Forked Codepen
https://codepen.io/lasjorg/pen/ROKQvp

testable-projects-fcc: fixed version
https://github.com/freeCodeCamp/testable-projects-fcc/tree/master/src/projects/tribute-page



### Challenge: Responsive Web Design Projects - Build a Technical Documentation Page

Challenge: Responsive Web Design Projects - Build a Technical Documentation Page
https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-projects/build-a-technical-documentation-page/

Original Codepen:
https://codepen.io/freeCodeCamp/full/NdrKKL

Fixed Forked Codepen
https://codepen.io/lasjorg/pen/QPdmbJ

testable-projects-fcc: fixed version
https://github.com/freeCodeCamp/testable-projects-fcc/tree/master/src/projects/technical-documentation-page

## Projects _not_ merged into testable-projects-fcc repo:


### Challenge: Responsive Web Design Projects - Build a Product Landing Page

I never really got a answer to my questions in the issue https://github.com/freeCodeCamp/testable-projects-fcc/issues/804 for this project, the issue was closed, not sure why. I think we should update the project.

1. The project is using SCSS before it has been taught in the curriculum and is confusing people.

2. It is using some ill-advised selectors.

Challenge: Responsive Web Design Projects - Build a Product Landing Page
https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-projects/build-a-product-landing-page/

Original Codepen:
https://codepen.io/freeCodeCamp/full/RKRbwL

Fixed Forked Codepen:
https://codepen.io/lasjorg/pen/qwRoRR


### Challenge: Responsive Web Design Projects - Build a Personal Portfolio Webpage

There are a few issues with this project, instead of cluttering this issue I will open an new issue for it and link to here.

Challenge: Responsive Web Design Projects - Build a Personal Portfolio Webpage
https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-projects/build-a-tribute-page/

Original Codepen:
https://codepen.io/freeCodeCamp/pen/zNBOYG

Fixed Forked Codepen WIP TBD:
https://codepen.io/lasjorg/pen/ROKMBJ

**Comment by thecodingaviator** [comment]
@lasjorg Also have a look at #880 and please make the required changes on the pen

**Comment by lasjorg** [comment]
@thecodingaviator Sure Codepen updated. I also noticed that it is missing a determiner (from _the_ left).

So I changed it from this:

> second from left

To this:

> third from the left


Should I open a new PR with the change? If I use my old branch for the change I get "Can’t automatically merge", is it better to make a new branch for the change?

**Comment by thecodingaviator** [comment]
I guess you should do that if you're having problems doing it on one branch

**Comment by lasjorg** [comment]
@thecodingaviator Just to be clear. I have updated my fixed version of the Codepen project. I have no power to update the FCC Codepens. Not sure why they are not getting updated.

@raisedadead Is there any progress on getting the Codepens updated?

**Comment by raisedadead** [comment]
@scissorsneedfoodtoo one more pen that you could validate, please? Thanks.

**Comment by scissorsneedfoodtoo** [comment]
No problem, I'm on it.

**Comment by scissorsneedfoodtoo** [comment]
@lasjorg, thank you for all of your hard work and documentation here! I read through your comments in this issue and in the others you listed, and updated fCC's pens for both the Tribute Page and Technical Documentation Page based on your fixed versions that were merged into this repo.

I'll hold off on updating the Product Landing Page and Personal Portfolio until they've both been reviewed and merged here.

**Comment by lasjorg** [comment]
@scissorsneedfoodtoo Cool, thanks.

By the way, I didn't add any attribution to the updated code. I would think the original coder is OK with the project being changed, I just want to make sure if we need to add a comment about me having updated it or is it fine like it is? I'm not looking for credit or anything, I just want to make sure I'm not changing someone's work without it being acknowledged if needed.

**Comment by scissorsneedfoodtoo** [comment]
@lasjorg, no problem! Please just let me know when your other issues/PRs are merged so I can update those pens, too, just in case I miss the notification.

About the attribution, I think it's fine. There were quite a few other fCC pens that don't have any sort of attribution, so I'm sure we don't need to worry about it. If the original creator leaves a comment later asking for credit, I can go in later and leave a comment on the pen.

**Comment by lasjorg** [comment]
@scissorsneedfoodtoo Sorry I had forgotten to update my post in this thread. The Product Landing Page update has already been merged https://github.com/freeCodeCamp/testable-projects-fcc/pull/884


Just to be clear about the attribution, I didn't remove the original credit, it is in the JS as a comment. I just didn't add a notice that the code had been changed by me.

**Comment by thecodingaviator** [comment]
@lasjorg I'm not exactly familiar with how the pens work, where their code and their corresponding tests live, so, I'd like Mrugest and Kris to take over from here

**Comment by scissorsneedfoodtoo** [comment]
@lasjorg, thanks for the clarification. I see the attribution in the JS file now. Would you like to add a notice of the change? Either way is totally fine.

**Comment by lasjorg** [comment]
@scissorsneedfoodtoo Just in case you missed it the Build a Product Landing Page was merged and is ready for the Codepen update.

Once that Codepen is updated we will also be a bit closer to being able to update the Build a Personal Portfolio Webpage. It needs the new Codepen links for the projects section.

**Comment by raisedadead** [comment]
Hi, I think it's best to break up this issues (and create new ones) for each pen that needs the update. This improve traceability than one long thread.

@lasjorg if its' all the same can you please do the same and close this in favor of multiple specific issues?

**Comment by scissorsneedfoodtoo** [comment]
@lasjorg, thanks for the heads up! Could you create a short new issue for the Landing Page and @ mention me there?

**Comment by lasjorg** [comment]
@raisedadead Do you want me to make issues for all the project including the ones already updated on Codepen, or just for the last two projects? I will close this issue when I know.

**Comment by lasjorg** [comment]
@scissorsneedfoodtoo New issue added for the Product Landing Page https://github.com/freeCodeCamp/testable-projects-fcc/issues/899

**Comment by scissorsneedfoodtoo** [comment]
@lasjorg, I'm sure it's fine if you just make issues for the last two projects. Later we can add a note here about which projects were closed in this issue.

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
