### ISSUE TITLE
THE CDN FOR TEST THE TRIBUTE PAGE IS NOT WORKING

### ISSUE THREAD

**Issue by alfredo00sd** [freeCodeCamp/testable-projects-fcc#833]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 
 
```

**Comment by thecodingaviator** [comment]
Can you please add a link to your codepen where it is not working?

**Comment by alfredo00sd** [comment]
Oh i already solved!

...I took the one from the codepen example...

Thank you for the support anyway

Alfredo Acosta Peña
