### ISSUE TITLE
Please... I think it's work correctly. I don't know what's wrong

### ISSUE THREAD

**Issue by Akiv1965** [freeCodeCamp/testable-projects-fcc#834]
I think  my project, D3 Bar Chart, works correctly but it don`t pass the  point tenth of the test.

#### Issue Description
The data-date attribute and its corresponding bar element should align with the corresponding value on the x-axis.

#### Browser Information

* Browser Name, Chrome v.72.0.3626.121: 
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen
https://codepen.io/Akiv/full/rRMexv

#### Screenshot

![image](https://user-images.githubusercontent.com/45926470/54729355-63486a80-4b83-11e9-97cb-d11999b67af1.png)

**Comment by tbushman** [comment]
@Akiv1965 The main issue is the missing 'width' property on your `rect` elements.  
```  
.attr('width', '3px')  
```  
Other things that will help:  
```  
const valoresX = datos.map(d => new Date(d[0]))   
```  
... so that you can use:  `const Xaxis = d3.axisBottom(escalaXtime);` alone.  
Additionally, by using   
```   
svg.selectAll("rect")
  .data(datos)  
```  
the line, `.data(datos)` yields `d` in the chain, so that you can use:  
```  
.attr("x", (d) => escalaXtime(new Date(d[0])) )   
```   
...likewise:  
```  
.attr("y", (d) => escalaY(d[1]) )
.attr("height", (d) => (h - escalaY(d[1])) )  
```

**Comment by Akiv1965** [comment]
Thank you so so much...!!
I've followed your recommendations and now it works correctly... Even more I learned new stuff... Great!

Thank you again and sorry for my english...
Greetings from Spain.
