### ISSUE TITLE
Responsive Web Design Projects - Build a Tribute Page

### ISSUE THREAD

**Issue by chochoc10** [freeCodeCamp/testable-projects-fcc#835]
Im doing the Responsive Web Design Projects - Build a Tribute Page
but i think the run test panel is still on the privious challenge.
It gives me error messages  to the previous challenges  which is the tribute page
when i'm already on the tribute page. or i think i got the wrong idea

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 
 
```

**Comment by petercr** [comment]
You need to include a link to your code in either something like a CodePen or at the very least copy and paste your code here inside a code block. 

**Otherwise** it's impossible to tell what is happening 🤔 🤷‍♂️ 

Thanks 😄

**Comment by chochoc10** [comment]
In where exactly? All of the challenges in freecodecamp are in the codepen
Thank you

**Comment by tbushman** [comment]
@chochoc10 Please reply here with the URL associated with your codepen project, which follows this format:    
```  
`https://codepen.io/{your_username}/pen/abcdef`  
```

**Comment by chochoc10** [comment]
Here are my codepen projects that are based on FreeCodeCamps Curriculum.
Specifically on Responsive Web Design Projects.

1. Build a tribute page. URL: https://codepen.io/chochoc10/pen/zbJqWr
2. Build a Survey Form. URL: https://codepen.io/chochoc10/pen/JzmerJ
3. Build a Product Landing Page. URL:
https://codepen.io/chochoc10/pen/xBmzXM
4. Build a Technical Documentation Page URL:
https://codepen.io/chochoc10/pen/wOZaZM
5. Build a Personal Portfolio Webpage. Soon to tackle

I just have minor problem doing projects on codepen, and that is the media
query won't apply in the codepen's text editor.
Or i think thats just me, not quite understanding about "@media" query.
Thank you for the notice.

**Comment by petercr** [comment]
@chochoc10 Great news, you project passes all the tests 😎 👍 
If you click the Green X at the top left hand corner, you will get a menu that says "Select Test Suite:"
It has a drop down menu which you use to select which project you would like to run the tests for. Simply select which project you are currently looking to run the tests for. 

**All of the project tests** are included in the one testing link. 

Best of luck 👍

**Comment by chochoc10** [comment]
Thank you. This curriculum challenges me and I loved every lesson of it.
I've been studying front-end languages since the last month. I already
start creating my
first portfolio(still on-going). And hopefully, I can get an intern or
luckily a full-time job. These coming months.
Appreciated, Good day.
 ☺
