### ISSUE TITLE
Drum Machine Keypress test Failure

### ISSUE THREAD

**Issue by TimothyCates** [freeCodeCamp/testable-projects-fcc#836]
#### Issue Description
My projects functionality should meet the test, It plays sound on click and on keypress, however it fails the keypress check in the test.

I have tried keyUp keyPress and KeyDown to no avail

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: Win 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen
Pen has no styles but should pass all the tests
https://codepen.io/timothycates/pen/oVQaYK

**Comment by RandellDawson** [comment]
Please ask these types of questions on the forum first.  If the forum users determine there is a bug in the test, then feel free to open an issue here.

I am closing this for now.

Thank you.
