### ISSUE TITLE
Markdown Previewer Test #4

### ISSUE THREAD

**Issue by Bus42** [freeCodeCamp/testable-projects-fcc#840]
Test #4 is faulty. I did everything short of cutting and pasting the example pen. Everything works as it should, but test 4 fails no matter what I do. I've read dozens of threads, no one seems to have a clear answer, most involve some hacky workaround like changing double to single quotes.

#### Issue Description

When I run the tests, run the tests

#### Browser Information

* Browser Name, Version: Chromium, 73.0.3683.75  
* Operating System: Ubuntu 18.04
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
 
 class Previewer extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      defaultContent: `# H1

## H2

[Link Text](#)

code:
\`<div></div>\`

\`\`\`
Codeblock:

const abba = (a) => {
function(b){
return b + a;
}
}
\`\`\`

You want a list?
1. Here's a list.
+ A list item.
2. Here's another.
+ another list item
+ and another

> Block Quotes!
> block quotes, man

**Bold Text**

![React Logo](https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg)
`,
      content: null
    };
    this.handleChange = content => {
      this.setState({ content });
    };
  }
  render() {
    marked.setOptions({
      breaks: true
    });
    const renderer = new marked.Renderer();
    renderer.link = (href, title, text) => {
      return `<a target="_blank" href="${href}">${text}` + "</a>";
    };
    return (
      <div id="App">
        <textArea
          id="editor"
          placeHolder={this.state.content || this.state.defaultContent}
          onChange={e => this.handleChange(e.target.value)}
          >
          {this.state.content || this.state.defaultContent}
        </textArea>
        <div
          id="preview"
          dangerouslySetInnerHTML={{
            __html: marked(this.state.content || this.state.defaultContent, {
              renderer,
              sanitize: false
            })
          }}
          />
      </div>
    );
  }
}
ReactDOM.render(<Previewer />, document.getElementById("root"));

 
```

**Comment by petercr** [comment]
@Bus42 Do you have a link to a CodePen, or CodeSandBox, or even a Git repository to clone. It would be easier to debug if I had a copy of the entire project.
Thanks 😄 👍

**Comment by Bus42** [comment]
Sorry, I thought I included it. Here you go.

https://codepen.io/Bus42/pen/BbPQjV

**Comment by Bus42** [comment]
All my code is there, but here's the link.
https://codepen.io/Bus42/pen/BbPQjV

**Comment by petercr** [comment]
@Bus42 I took a look over the project, and I can't find what's wrong with it. It does seem to be running correctly. I did add one line of CSS to make it easier to read. 
```css
#editor {
  height: 500px;
}
```

Hopefully somebody else will come along like @ValeraS and take a look. Maybe they can figure out what's wrong 🤔

**Comment by Bus42** [comment]
Thanks for giving it a shot

**Comment by ValeraS** [comment]
@Bus42 If you delete all the text in the editor, then the preview should be empty. But it shows a default content render.

**Comment by Bus42** [comment]
I'm failing to see what that has to do with test #4. Can you tell me why
that's making me fail test #4?

**Comment by ValeraS** [comment]
@Bus42 The test clears the editor field and expects to get an empty preview.

**Comment by Bus42** [comment]
Aha! Thank you. I'll do that tonight and hopefully it works this time.

**Comment by petercr** [comment]
Thanks @ValeraS see **I knew** you would figure it out 💯 🥇
