### ISSUE TITLE
I create my page Survey Form and uses Materialize for validation but not recognized.

### ISSUE THREAD

**Issue by LyhTeixeirah** [freeCodeCamp/testable-projects-fcc#842]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 
 
```

**Comment by petercr** [comment]
The form does not require any validation in order to pass the tests. Any validation is not tested by Free Code Camp. 😄 

Also you should always include a link to a running version of your project, or the source code when opening an issue.
Thanks
