### ISSUE TITLE
Project already complete.

### ISSUE THREAD

**Issue by superdave970** [freeCodeCamp/testable-projects-fcc#843]
#### Issue Description

When I click on the link for codepen.io the entire project is already complete.

#### Browser Information

* Browser Name, Version: Google Chrome Version 73.0.3683.86
* Operating System: Mac OSX 10.14.3
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```https://codepen.io/superdave970/pen/PLrdQp
 
 
 
```

#### Screenshot

![Screen Shot 2019-03-27 at 8 56 38 PM (2)](https://user-images.githubusercontent.com/40956886/55126536-efeaaf80-50d2-11e9-9a83-5511caf1b1b5.png)

**Comment by petercr** [comment]
That looks to be the finished version of the project. You want to fork the starter project template. 
[Here is a link to the CodePen you fork to start your project](https://codepen.io/freeCodeCamp/pen/MJjpwO)
