### ISSUE TITLE
where can i direct to personal portfolio challenge? i couldn't find in the drop down selections 

### ISSUE THREAD

**Issue by chochoc10** [freeCodeCamp/testable-projects-fcc#844]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 
 
```

**Comment by petercr** [comment]
If you include the Free Code Camp testing suite script into your project, or use one of the starter projects then the drop down selection box will be in the upper left hand corner of project.

It can also appear as a small green X if the menu is minimized. Simply click the green X and the Testing Menu will appear. Then use the drop down to select which test to run.

**Comment by chochoc10** [comment]
I figured that out and thank you for the response and here is my last
challenge of Responsive Web Design Certificate.
https://codepen.io/chochoc10/pen/aMepOW
Hope you examine my work and hopefully get my first certification on
freeCodeCamp
Thank you.

**Comment by petercr** [comment]
@chochoc10 Actually you go and submit links to all of your projects on Free Code Camp. 
Then you will be able to collect your certificate in the Settings section 👍
