### ISSUE TITLE
https://codepen.io/clarancefarley/pen/NmWoWd?editors=1100

### ISSUE THREAD

**Issue by clarancefarley** [freeCodeCamp/testable-projects-fcc#847]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 
 
```

**Comment by petercr** [comment]
Please describe your issue, and how to reproduce it. Otherwise we will be unable to help you with your issue. 
Thanks 😄
