### ISSUE TITLE
Test suite does not recognise # 2 as a pass unless tag is ID rather than class.

### ISSUE THREAD

**Issue by Samtodd250** [freeCodeCamp/testable-projects-fcc#848]
Personal portfolio project.

#2 of the test suite states ' 2. The welcome section should have an h1 element that contains text.'.

For a very long time I was unable to figure out why the system would not accept my code. Eventually i found out that by changing the 'class' to an 'id' the test would pass. This happened across both Chrome and Safari.

#### Issue Description

Issue can be recreated by running the below code and changing 'id' for 'class'.

#### Browser Information

* Browser Name, Version: Safari/Chrome
* Operating System: OSX Mojave
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
 https://codepen.io/samtodd/pen/zXxmOW?editors=1100
 
<div id="welcome-section">
        <div class="row">
          <div class="col-md-12 text-center">
            <h1>Hi, I'm your next developer.</h1>
          </div>
        </div>
    </div>
 
```

**Comment by RandellDawson** [comment]
@Samtodd250 This is not a bug, because user story number 1 already tells you the the welcome section should have an id of "welcome-section".
