### ISSUE TITLE
no se

### ISSUE THREAD

**Issue by bluezin** [freeCodeCamp/testable-projects-fcc#849]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 
 
```

**Comment by petercr** [comment]
In order to get help, we would need to know what kind of issue you are experiencing. 
You have given us no information.
Thank you 😄 

Para obtener ayuda, necesitamos saber qué tipo de problema está experimentando.
No nos has dado ninguna información.
Gracias
