### ISSUE TITLE
Test score does not work...I took out CCS, test score remained 9/10.

### ISSUE THREAD

**Issue by burakbingol** [freeCodeCamp/testable-projects-fcc#850]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 
 
```

**Comment by burakbingol** [comment]
https://codepen.io/burakbingol/pen/bJpjgp

**Comment by thecodingaviator** [comment]
Check https://codepen.io/anon/pen/ZZxqeM . Am I missing something or has it been fixed?IT if has not, leave a comment and I'll reopen the issue
