### ISSUE TITLE
Media queris doesn't work on Product Landing Page

### ISSUE THREAD

**Issue by akakiev** [freeCodeCamp/testable-projects-fcc#851]
#### Issue Description

Product Landing Page Project - media queris doesn't work. I write it 3 different ways and no one doesn't work: 

1. in the end of all css rules:
 @media screen and (min-width: 376px) { 
		.nav-bar{
		flex-direction: row;
		padding-right: 5em;
		}
	}
2.  in the style of the class:
.nav-bar{
		display: -webkit-box;
  	display: -moz-box;
  	display: -ms-flexbox;
  	display: -webkit-flex;
		display: flex;
		flex-direction: column;
    @media (min-width: 376px) {
		flex-direction: row;
		padding-right: 5em;
		}
	}

3. in the html tag style:
<style type="text/css">
 .nav-bar{
		@media (min-width: 376px) {
		flex-direction: row;
		padding-right: 5em;
		}
	}
  </style>

But no one doesn't work.

#### Browser Information

* Google Chrome, latest: 
* Windows 7: 
* Desktop: 

#### Your Code / Link to Your Pen

```
https://codepen.io/barabanchik/pen/pGyjBB
 
 
 
```

**Comment by ValeraS** [comment]
@akakiev In pure CSS `@media` cannot be used inside declaration blocks for selectors.  Only the first example is valid. Also, your css code has an error at 317 line.

**Comment by akakiev** [comment]
@ValeraS Thank you! It solves my problem. But one more question: how to align "Education" to the center of  logo image "baraban" in footer ?
