### ISSUE TITLE
Hannibal

### ISSUE THREAD

**Issue by HamdiNawfel** [freeCodeCamp/testable-projects-fcc#852]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen
https://codepen.io/hamdinawfel/pen/dLOdZX
```
 
 
 
```

**Comment by SkipHendriks** [comment]
All the tests seem to pass, what is the issue here?

**Comment by thecodingaviator** [comment]
To submit your project, put that CodePen link into the freecodecamp challenge page at https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-projects/build-a-tribute-page
