### ISSUE TITLE
Build a Tribute Page

### ISSUE THREAD

**Issue by HamdiNawfel** [freeCodeCamp/testable-projects-fcc#853]
https://codepen.io/hamdinawfel/pen/dLOdZX

**Comment by HamdiNawfel** [comment]
![FIGURE1](https://user-images.githubusercontent.com/47576444/55762911-c7609f00-5a5c-11e9-924f-4ea0b5ac09e2.JPG)

**Comment by HamdiNawfel** [comment]
Objective: Build a CodePen.io app

**Comment by HamdiNawfel** [comment]
![FIGURE3](https://user-images.githubusercontent.com/47576444/55763248-0c390580-5a5e-11e9-9aab-adb185700570.JPG)

**Comment by HamdiNawfel** [comment]
![FIGURE2](https://user-images.githubusercontent.com/47576444/55763284-2c68c480-5a5e-11e9-98d2-daa0601a0c8a.JPG)

**Comment by tbushman** [comment]
@HamdiNawfel Really great work. Submit the link to this codepen in the curriculum for the Build A Tribute Page lesson to receive credit for it.
