### ISSUE TITLE
Update example project: Build a Personal Portfolio Webpage

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/testable-projects-fcc#854]
List of some issues in the project.

1. Some of the projects that are linked to in the Portfolio are broken and needs to be fixed. I can fix the links but I'm not sure how to update the project images. Right now they are linked to using "cloud.githubusercontent". Not sure what to do about the images?

### Projects linked to in portfolio that need to be fixed are:
---
**Original:** freeCodeCamp : Build a Tribute Page
https://codepen.io/freeCodeCamp/pen/NNvBQW

**Issue:** Missing alt attribute on the image, is using bootstrap before taught in the curriculum

**Fixed _Forked_ Codepen:** freeCodeCamp : Build a Tribute Page (same as linked to in this issue https://github.com/freeCodeCamp/testable-projects-fcc/issues/832)
https://codepen.io/lasjorg/pen/ROKQvp

---

**Original:** freeCodeCamp : Random Quote Machine
https://codepen.io/freeCodeCamp/pen/ONjoLe

**Issue:** Broken

**Working** FCC : Random Quote Machine
https://codepen.io/freeCodeCamp/full/qRZeGZ

---

**Original:** freeCodeCamp : Build a JavaScript Calculator
https://codepen.io/freeCodeCamp/pen/PNKdjo

**Issue:** Does not pass the tests

**Working** FCC: Javascript Calculator
https://codepen.io/freeCodeCamp/pen/wgGVVX

---

2. Typo, i'am should be I'm or I am

3. Remove commented out CSS.

4. The Codepen is set to use SCSS but there is no SCSS in the project.

Challenge: Responsive Web Design Projects - Build a Personal Portfolio Webpage
https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-projects/build-a-personal-portfolio-webpage

Original Codepen:
https://codepen.io/freeCodeCamp/pen/zNBOYG

Fixed Forked Codepen WIP TBD:
https://codepen.io/lasjorg/pen/ROKMBJ

I can make a PR for this project once the question about what to do about the images has been answered.

**Comment by tbushman** [comment]
@lasjorg Thanks for your help. Images can be hosted at the fCC CDN repo by forking the repo and submitting a pull-request with your images in an images folder, probably in this directory, or in the data folder:  https://github.com/freeCodeCamp/cdn/tree/master/build/testable-projects-fcc .
