### ISSUE TITLE
Technical Documentation Tests 3 and 4

### ISSUE THREAD

**Issue by Ne0nWinds** [freeCodeCamp/testable-projects-fcc#855]
#### Issue Description
Putting anchor tags (links) in the unordered list in the following main-section made tests 3 and 4 fail for no apparent reason.

Test 3: The first element within each .main-section should be a <header> element which contains text that describes the topic of that section.

Test 4: Each <section> element with the class of "main-section" should also have an id that corresponds with the text of each <header> contained within it. Any spaces should be replaced with underscores (e.g. The <section> that contains the header "Javascript and Java" should have a corresponding id="Javascript_and_Java").

#### Browser Information

* Browser Name, Version: Have tried on Chrome and Firefox
* Operating System: Have tried on Windows 10 and Ubuntu
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
Link to my project: https://codepen.io/ne0nwinds/pen/pBNZmb

Here is my last main section
This passes:
   <section class="main-section" id="Learn_More">
    <header>Learn More</header>
    <ul>
      <li>Official Microsoft Documentation</li>
      <li>SS64 - a third-party reference for all things command line</li>
    </ul>
  </section>

 This fails tests 3 and 4:
   <section class="main-section" id="Learn_More">
    <header>Learn More</header>
    <ul>
      <li><a href="https://docs.microsoft.com/en-us/powershell/" target="_blank">Official Microsoft Documentation</a></li>
      <li>SS64 - a third-party reference for all things command line</li>
    </ul>
  </section>
 
```

**Comment by djolesusername** [comment]
I've just ran the tests, and it's all green
https://screenshots.firefox.com/VyNVfylD9dej9WF7/codepen.io

**Comment by Ne0nWinds** [comment]
I changed the project, so that way it would pass for the certification. Did you copy the part that says "this fails tests 3 and 4" and replace it with the last main section?

**Comment by ValeraS** [comment]
@Ne0nWinds Your code contains a typo at line 153 `<a\>`. Because of this, you get these errors.
