### ISSUE TITLE
tests faailed to run

### ISSUE THREAD

**Issue by leomuko** [freeCodeCamp/testable-projects-fcc#856]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 
 
```

**Comment by leomuko** [comment]
https://codepen.io/Kyz_Leo/pen/oOjqRL

**Comment by tbushman** [comment]
@leomuko It looks to be in order. Take care.
