### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by djolesusername** [freeCodeCamp/testable-projects-fcc#857]
Drum machine

 Failing tests 6 and 7 - playing onclick and click. 

#### Issue Description
 Run the tests.

#### Browser Information
 
I've tried multiple OS and browsers. Prime - LInux mint 19.1 with Firefox, Option Win   10 with Chrome

* Browser Name, Version: Firefox, latest
* Operating System:  Linux
* Mobile, Desktop, or Tablet:  Desktop

#### Your Code / Link to Your Pen

```https://codepen.io/djolesusername/pen/vMxNee
 
 
 
```

#### Screenshot

https://i.postimg.cc/tyZyhN0P/Freecodecamp.png

**Comment by djolesusername** [comment]
Link" https://codepen.io/djolesusername/pen/vMxNee

**Comment by tbushman** [comment]
@djolesusername I'm seeing passing tests for your project. Looks neat!

**Comment by petercr** [comment]
@djolesusername The `D` key does not seems to make any noise when you click or press the key. 
I'm not sure why as the link looks to be working. But there's no sound on this key, and that's the test that's failing. 
If you just switch the `<audio>` elements with an id of `D` to even be another one of the same sounds from the project, it passes all the tests. 👍 😄

**Comment by tbushman** [comment]
@djolesusername Sorry to delay. I was just checking out your code and wanted to point something out. If you have a variable that changes conditionally (like `audio`), you'll want to use the `let` constructor. Change:  
```  
function playaudio(e) {
    if (event.code == 'KeyQ' || this.id == 1) {
        const audio = document.getElementById("Q");  
    ...   
```  
to:  
```  
function playaudio(e) {
    let audio;   
    // declare the audio variable, then, each time it changes, omit the declaration and simply re-define the variable (omit 'const', 'var'):
    if (event.code == 'KeyQ' || this.id == 1) {
        audio = document.getElementById("Q");   
```
