### ISSUE TITLE
CDN link not working 

### ISSUE THREAD

**Issue by sniperglass** [freeCodeCamp/testable-projects-fcc#858]
The cdn link that I used was https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js and it doesn't work in my codepen project. I added the cdn link to the JavaScript panel in my codepen settings, ignoring the babel preprocessor setting. That is specific to my codepen.

#### Issue Description

When I run the test, it shows a 'mocha div is missing' msg.

#### Browser Information

* Browser Name, Version: Chrome Version 73.0.3683.103
* Operating System: Mac OS Mojave Version 10.14.3 
* Mobile, Desktop, or Tablet: Laptop

#### Your Code / Link to Your Pen

```
 https://codepen.io/imanhuter/pen/PLeLEN
 
 
```

**Comment by tbushman** [comment]
@sniperglass I think you got the test suite loaded. The remaining error is because of an extra space in `href="#What_ is_HTML?"` (before 'is').
