### ISSUE TITLE
rule 3. header

### ISSUE THREAD

**Issue by bobbidigi** [freeCodeCamp/testable-projects-fcc#86]
#### Issue Description

3. The first element within each .main-section should be a <header> element which contains text that describes the topic of that section.
wc3 validation problems section lacks heading. Consider using "h2"-"h6" elements to add identifying headings to all sections. 
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 http://codepen.io/bobbidigi34/pen/PmYgmx
 
 
```

#### Screenshot
![header](https://cloud.githubusercontent.com/assets/20561145/24989627/eeb36cd0-1fdb-11e7-8f58-688a472f30c9.png)

**Comment by no-stack-dub-sack** [comment]
@bobbidigi Thanks for reporting this issue, however, I would fundamentally disagree with the W3C Validator in this case. Perhaps it has not been updated to reflect the new HTML5 standard, but considering the element that in question is a `<header>` element, I would say that the section most certainly does not lack a heading, it just lacks a heading that the validator expects. 

Part of the purpose of this particular exercise, is to encourage the use of such HTML5 tags like header, section, main, etc. so at this time, I don't feel like this is something we need to change. 

We are open to suggestions though, and the help is appreciated! So if you find anything else, please feel free to come back and let us know. 

For now I will be closing this issue, if you disagree, please reopen and provide additional details. Thanks!
