### ISSUE TITLE
Is there a bug with the Userstory#6 - Surveyform Test

### ISSUE THREAD

**Issue by yanns1** [freeCodeCamp/testable-projects-fcc#861]
Impossible to validate the Userstory#6:"If I enter an email that is not formatted correctly, I will see an HTML5 validation error." but it seems to work on the browser.

Here's my code:
![image](https://user-images.githubusercontent.com/49593516/56082925-f1301200-5e1e-11e9-8b33-f98f09130e78.png)

Thanks for help.

**Comment by thecodingaviator** [comment]
Add a link to your codepen please

**Comment by ValeraS** [comment]
@yanns1 type of input should be `email` but in your code, it's `e-mail`.

**Comment by yanns1** [comment]
Thanks !
