### ISSUE TITLE
test suite gives green on phone and one error on pc

### ISSUE THREAD

**Issue by Emil-Valentin-Toma** [freeCodeCamp/testable-projects-fcc#862]
test suite gives green on phone and one error on pc.

#### Browser Information
 test suite

* Browser Name, Version: firefox 67.0b9 on pc, firefox on android
* Operating System:  w10 home/ android
* Mobile, Desktop, or Tablet: laptop/note9

#### Your Code / Link to Your Pen

https://codepen.io/evtoma/pen/VNzJXw
```
 
 
 
```

**Comment by tbushman** [comment]
@Emil-Valentin-Toma I couldn't reproduce the error on PC. In your CSS, make sure you use `:` instead of `=` in your declarations.  
Instead of  
```  
background-color = yellow; 
```  
use  
```  
background-color: yellow;  
```

**Comment by Emil-Valentin-Toma** [comment]
@tbushman Thank you for feedback. 
I've got the certificate in the meantime. Thanks again for the advice and code correction.
