### ISSUE TITLE
Product Landing Page - Email Form Submission

### ISSUE THREAD

**Issue by bviengineer** [freeCodeCamp/testable-projects-fcc#864]
#### Issue Description
When I click on the GET STARTED button it submits successfully to the form located here: https://www.freecodecamp.org/email-submit. However, when I run the test, it fails. The submit button is an `input` element as required, with all the specified attributes. 

**Link to the GitHub repo**: https://github.com/bviengineer/build-a-product-landing-page
**GitHub URL for live viewing**: https://bviengineer.github.io/build-a-product-landing-page/index.html

Below is the error:
12. When I click the #submit element, the email is submitted to a static page (use this mock URL: https://www.freecodecamp.com/email-submit) that confirms the email address was entered (and that it posted successfully).

The #email input should have a name attribute : expected false to equal true
a@https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:139:475
FCC_Global</e.exports/s.prototype.assert@https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:284:1304
l@https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:262:1129
FCC_Global</e.exports/e[t]@https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:325:124
FCC_Global</e.exports/n.strictEqual@https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:224:568
test/</</<@https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:154:53343
c@https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:159:31606
FCC_Global</</<[32]</</f.prototype.run@https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:159:31544
FCC_Global</</<[33]</</m.prototype.runTest@https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:159:37112
i/<@https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:159:37974
s@https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:159:36426
s/<@https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:159:36495
o@https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:159:35901
FCC_Global</</<[33]</</m.prototype.hook/<@https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:159:35872
f@https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:154:205793

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 
 
```

**Comment by ValeraS** [comment]
@bviengineer The #email input should have a name attribute. Add `name="email"` to your input element.

**Comment by bviengineer** [comment]
@ValeraS thank you so much for your response! Adding the name attribute worked!
