### ISSUE TITLE
How about this FCC, Everything looks ok but why 8/10

### ISSUE THREAD

**Issue by yanjanendra** [freeCodeCamp/testable-projects-fcc#867]
https://codepen.io/yanjanendra/full/ROMWVM

**Comment by ValeraS** [comment]
@yanjanendra If you press the "Tests" button you'll see what is wrong.

**Comment by yanjanendra** [comment]
thanks.

**Comment by yanjanendra** [comment]
thank you now its 10/10 https://codepen.io/yanjanendra/pen/ROMWVM
