### ISSUE TITLE
ProductLandingPage

### ISSUE THREAD

**Issue by HamdiNawfel** [freeCodeCamp/testable-projects-fcc#868]
freeCodeCamp Challenge:
https://codepen.io/hamdinawfel/pen/gyePmY

![21](https://user-images.githubusercontent.com/47576444/56342236-597c4c00-61af-11e9-9caa-ce61500c5431.JPG)
![23](https://user-images.githubusercontent.com/47576444/56342247-639e4a80-61af-11e9-910d-6c8bd8a50029.JPG)
![24](https://user-images.githubusercontent.com/47576444/56342256-6862fe80-61af-11e9-886c-4c9180b4e83d.JPG)

HAMDI Nawfel

**Comment by ValeraS** [comment]
@HamdiNawfel If you press the "Tests" button you'll see what is wrong.
