### ISSUE TITLE
Build a Technical Documentation Page

### ISSUE THREAD

**Issue by HamdiNawfel** [freeCodeCamp/testable-projects-fcc#870]
https://codepen.io/hamdinawfel/pen/PgRBQd
![50](https://user-images.githubusercontent.com/47576444/56372699-66249280-61f7-11e9-9e2a-ec5f4604e191.JPG)

**Comment by tbushman** [comment]
@HamdiNawfel You can submit your completed projects at freeCodeCamp's website. For example, enter your Codepen link in the Solution input at the bottom of this page: https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-projects/build-a-technical-documentation-page
