### ISSUE TITLE
Timer has not reached 00:00

### ISSUE THREAD

**Issue by xayden** [freeCodeCamp/testable-projects-fcc#871]
#### Issue Description
Time reaches 00:00 and the tester doesn't see it, also I don't understand the issue of number 9.

#### Browser Information
* Browser Name, Version: Google Chrome, 73.0.3683.103
* Operating System: Ubuntu 18.04.2
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen
https://codepen.io/xayden/pen/rbpLop

#### Screenshot
![image](https://user-images.githubusercontent.com/23618008/56427112-ef50cd80-62ba-11e9-8914-268bf0f5b863.png)

**Comment by abhishekakade** [comment]
@xayden, in your app, try starting the timer, wait 5 seconds, then hit pause, then hit reset, then hit play again. You will see that it starts from t-5 seconds. Try fixing that. You will probably need to add some `if` checks to play/pause/reset handlers.
