### ISSUE TITLE
Personal Portfolio

### ISSUE THREAD

**Issue by HamdiNawfel** [freeCodeCamp/testable-projects-fcc#872]
https://codepen.io/hamdinawfel/pen/qwYwQK
![01 - Copie](https://user-images.githubusercontent.com/47576444/56449927-48028380-6318-11e9-9156-45b0e024e75b.JPG)
![04](https://user-images.githubusercontent.com/47576444/56449924-4769ed00-6318-11e9-9737-c581455abc85.JPG)
![03 - Copie](https://user-images.githubusercontent.com/47576444/56449926-48028380-6318-11e9-9f46-784412da33e4.JPG)
![test](https://user-images.githubusercontent.com/47576444/56449925-4769ed00-6318-11e9-8ca2-13f476f9f400.JPG)

**Comment by RandellDawson** [comment]
What is your issue?
