### ISSUE TITLE
Random Quote Machine - Tests 8/9 inconsistent, Tests 6/7 inaccurate

### ISSUE THREAD

**Issue by jamieAurora** [freeCodeCamp/testable-projects-fcc#879]
#### Issue Description
This is when testing for the Quote Machine. The success/failure of the test is wildly inconsistent. After no changes in the code, the tests passed will show as anywhere from 9/10 to 12/12. I am also passing tests that I should not be; merely having a value in my "text" header element passes tests 6 and 7, despite not drawing from the quotes whatsoever. Tests 8 and 9 for some reason can fail, despite my code working fine when actually being used.

#### Browser Information
Google Chrome
Version 74.0.3729.108 (Official Build) (64-bit)

#### Your Code / Link to Your Pen
 https://codepen.io/geisty/pen/vMbeKX?editors=1111

**Comment by RandellDawson** [comment]
@tbushman This is partially related to Issue #830.

**Comment by RandellDawson** [comment]
I left a comment on issue #879 with a couple of ways to resolve the issues you are seeing.

**Comment by jamieAurora** [comment]
Thank you, @RandellDawson ! I can get the tests to pass if I run them often enough, but I just wanted to make sure you were all aware of the problem. Thanks for all your work on freecodecamp!!

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
