### ISSUE TITLE
Minor: Dr. Norman Borlaug Tribute Page / image caption: 3rd, not 2nd from left

### ISSUE THREAD

**Issue by benomatis** [freeCodeCamp/testable-projects-fcc#880]
#### Issue Description
On the [FCC: Tribute Page for Dr. Norman Borlaug](https://codepen.io/freeCodeCamp/full/zNqgVx), the image caption says he is 2nd, while in reality, he's 3rd from left.

#### Screenshot
![image](https://user-images.githubusercontent.com/5822748/56867433-70a80e80-69e5-11e9-9c8a-e8c72c9bd1e6.png)

**Comment by thecodingaviator** [comment]
@lasjorg I believe you were working on updating CodePens, have a look

**Comment by tbushman** [comment]
Closed by #897
