### ISSUE TITLE
Build a tribute page, user story # 8 fails

### ISSUE THREAD

**Issue by ghost** [freeCodeCamp/testable-projects-fcc#883]
#### Issue Description

  I am facing issue in user story # 8, depsite the fact that i have included profile-link and target attribute into a tag

#### Browser Information

* Browser Name, Version: Version 73.0.3683.103
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

https://codepen.io/anon/pen/vMwqyK
 
 
 
```

#### Screenshot
<!-- Add a screenshot of your issue -->

**Comment by abhishekakade** [comment]
Isn't this supposed to be a personal portfolio project? (And not a tribute page)

So I ran the tests (Personal Portfolio tests) on your project and saw that there are multiple elements using the same `id="profile-link". `id`s are supposed to be unique and you cannot use them more than twice. You should use css classes (class="profiles") instead if you want to use it on more than one element. That fixed the #8 test/user story.

Then adding a [media query](https://www.w3schools.com/css/css3_mediaqueries_ex.asp) to your project, setting the `height` of `#welcome-section` equal to the height of viewport and changing your `#navbar` styles so it always remains at the top cleared all the remaining tests.

**Comment by abhishekakade** [comment]
I think this issue can be closed now
