### ISSUE TITLE
Survey Form Test Results are incorrect

### ISSUE THREAD

**Issue by cravojosh** [freeCodeCamp/testable-projects-fcc#885]
#### Issue Description

I have completed Tests 14-17 but they keep coming up incorrect even though the Tests have been completed. I used the FCC: Survey Form to compare my code to FreeCodeCamps and it is very similar if not identical! I dont understand how my code is not passing this test other than the explanation that their is a bug? 

#### Browser Information

* Browser Name, Version:  Google Chrome
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Asus Laptop

#### Your Code / Link to Your Pen

 https://codepen.io/Cravojosh/pen/KYOGmV?editors=1000

**Comment by abhishekakade** [comment]
@cravojosh, I just checked and it cleared all the tests. Don't see any problem. Can you try again and post some screenshots if you are still getting any errors?
