### ISSUE TITLE
problem in Responsive Web Design Projects - Build a Product Landing Page,no content 2,3,4

### ISSUE THREAD

**Issue by MrRangga** [freeCodeCamp/testable-projects-fcc#887]
#### Issue Description

i think that i have passed the test number 2 in the product landing page project, but the tester still shows this" I can see an image within the #header element with a corresponding id="header-img". A company logo would make a good image here. " even though i have the element with the corresponding like that,the issue also applies to content number 3 and 4 

#### Browser Information

* Browser Name, Version: mozila firefox,66.0.3 
* Operating System: windows 10 pro
* Mobile, Desktop, or Tablet: desktop

#### Your Code / Link to Your Pen

```
 https://codepen.io/firmansmoh/pen/dEbjEy
 
```

#### Screenshot

![d](https://user-images.githubusercontent.com/40726290/57176941-ca4a8600-6e88-11e9-9054-ebd5fdfe949a.png)
![sasa](https://user-images.githubusercontent.com/40726290/57176943-cb7bb300-6e88-11e9-904c-6287f1abad18.png)

**Comment by abhishekakade** [comment]
In your HTML (from screenshot), line no. 12, you are expected to use `img` tag for the company logo image and not `div` element. If you make the changes accordingly, it will clear this test. Even if you read the error message you got, it says, `#header-img is not an <img> element : expected 'DIV' to equal 'IMG'`.

**Comment by MrRangga** [comment]
ok thanks  I don't read it completely

**Comment by MrRangga** [comment]
> 
> 
> @MrRangga, in your HTML (from screenshot), line no. 12, you are expected to use `img` tag for the company logo image and not `div` element. If you make the changes accordingly, it will clear this test. Even if you read the error message you got, it says, `#header-img is not an <img> element : expected 'DIV' to equal 'IMG'`.

but it still doesnt work

**Comment by abhishekakade** [comment]
@MrRangga, of course it doesn't work. `img` tag requires you to include the source/url (`src` attribute) to the image that you want to use with `img` element. And it is a self closing tag. And you should also add alternative text to the image which appears in case the intended image fails to load. Check out [this link](https://www.w3schools.com/tags/tag_img.asp) to read more about `img` element .

Here is an example of `img` tag in use taken from the same link -
`<img src="smiley.gif" alt="Smiley face" height="42" width="42">`

You will need to replace the value of `src` attribute to image URL from some free image hosting site or your local directory. Check out [this link](https://www.w3schools.com/html/html_filepaths.asp) to read up more on that.

If you are using local images then I'd suggest uploading your images to some free image hosting sites like `postimages.org` and then using that link in your codepen/project.
