### ISSUE TITLE
I am having to refresh the page each time I save a new change to Codepen

### ISSUE THREAD

**Issue by rockstarcreativestudio** [freeCodeCamp/testable-projects-fcc#889]
#### Issue Description
I write my React test projects locally and then transfer to Codepen (it allows me to more easily push to Github as part of my portfolio). I just finished up most of the calculator project and wanted to move to Codepen for final testing. 

I added the .js file for testing in the Settings > Javascript loader section. 

When I first open the tester, I can select the project and run tests. Normally, something fails and I have to go in and adjust my code. 

When I change my code and hit save, the tester box select inputs clear and selecting the project and clicking "Run Tests" causes both buttons to grey out, the bottom button text changes to "Load Tests" and it adds `#mocha div missing, add it to your document` this to the bottom of the project preview pane.

I have to completely reload the page in order to test again.

#### Browser Information

* Browser Name, Version:  Chrome Version 74.0.3729.131 (Official Build) (64-bit)
* Operating System:  Windows 10 Home 64 bit
* Mobile, Desktop, or Tablet:  Desktop

#### Your Code / Link to Your Pen
https://codepen.io/mbailey83/pen/LoNBQZ?editors=0010!

#### Screenshot
![screenshot-codepen io-2019 05 10-13-41-59](https://user-images.githubusercontent.com/44074522/57547266-1d5e8600-732c-11e9-976d-9a3ad45509ec.png)

**Comment by tbushman** [comment]
@rockstarcreativestudio Hi, thanks for reporting this. I couldn't reproduce this mocha div missing error. Are you still seeing it? When it occurs, which part of your code are you changing? The only other time I've seen this error is when a student was using an element with an `id=#mocha` ...

**Comment by rockstarcreativestudio** [comment]
I don't have any elements with the `id=mocha`. I'm working on it today and not getting the issue. I was just updating methods in the main React component.

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
