### ISSUE TITLE
Pomodoro Async Test Question

### ISSUE THREAD

**Issue by sa-mm** [freeCodeCamp/testable-projects-fcc#89]
#### Issue Description

My Pomodoro Clock project is failing all of the async tests at the moment. I'm sure there are problems with my code, as it's in very rough shape at the moment. However, it's odd that it's failing all and only the async tests (11, 19-26).

I'll focus on tests 11 and 19.

11. This test gives the following error:

```
Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:7197
```

I'm not sure what to say about that. Looking at the [test source](https://github.com/freeCodeCamp/testable-projects-fcc/blob/master/src/project-tests/pomodoro-clock-tests.js), it seems like there are plenty of helpful errors in the promise. I'm just not seeing any of them.

19. This test gives the following error:

```
TypeError: Cannot read property '1' of null
    at getSeconds (https://rawgit.com/freeCodeCamp/testable-projects-fcc/master/build/bundle.js:19461:24)
    at n.<anonymous> (https://rawgit.com/freeCodeCamp/testable-projects-fcc/master/build/bundle.js:19675:38)
    at r (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:7852)
    at r.run (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:8853)
    at i.runTest (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:13553)
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:14192
    at r (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:13024)
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:13000
    at n (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:12791)
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:12855
```

That indicates that when `getSeconds` tries to return `matches[1]`, it's getting `null` instead of an array. However, when I play with things in the console, matches are returned.

```javascript
// suppose "time-left" displays "24:44"
var time = document.getElementById("time-left").innerHTML
var matches = /^\d{1,4}\s?:\s?(\d{2})/g.exec(time)
matches[1] // returns "44"
```

Can anyone point me in the right direction?

#### Browser Information

* Browser Name, Version: Chrome 58.0.3029.96 (64-bit)
* Operating System: macOS 10.12.4 (sierra)
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

Github [link](https://github.com/sa-mm/pomodoro)
And a [link](https://terrible-porter.surge.sh/) to a live version.

**Comment by no-stack-dub-sack** [comment]
@sa-mm This is one of the few suites I did not write, so this is just speculation without diving in further - but your app seems to be functioning exactly as it should, except for one small thing - when you reset, or change the session time, it is a whole number rather than `25:00` - between each test, the reset button is being called, and that expects values of 5, 25, and 25:00 respectively for break, session, and timer. I'll take a closer look, but see if this changes anything?

**Comment by no-stack-dub-sack** [comment]
That could also explain the `match` issue, there's no colon for the regex to match

**Comment by no-stack-dub-sack** [comment]
But then, it should be calling `getSeconds` when the timer is paused, so not sure...

**Comment by no-stack-dub-sack** [comment]
Also, I do see some helpful errors in some of the other failing tests, perhaps try addressing those first and see how it changes the other failing tests

**Comment by sa-mm** [comment]
@no-stack-dub-sack Thanks for the reply! Changing the timer text to 25:00 instead of 25 helped. The tests also want me to start counting down from say, 25:00, instead of 24:59. This was the cause of several of the errors.  I now have all of the tests working expect 11. It fails the first time I run it but passes after that.

In fact, the same is true for any of the tests that make use of promises. If that particular test is the first test with a promise to be run, then it will fail the first time and pass the second. (I checked this by running each of them individually.) So, it's not so much a problem specific to 11 as it is the order in which 11 appears.

I guess I'll keep poking around.

**Comment by sa-mm** [comment]
OK, got it. Thanks for the help!

**Comment by sa-mm** [comment]
Closing it.

**Comment by no-stack-dub-sack** [comment]
@sa-mm Glad to help! What did you have to end up doing to get everything working? Any suggestions on how we can change the user stories / test case instructions in a way that would have helped you get this right the first time around? I'd like to learn from this and improve if possible, this has been one of the trickier projects to test from the get go and I anticipate we will continue to run into problems unless we really get this down. Open to suggestions...

Reopening the issue for now while the conversation is ongoing, but glad you were able to work through this.

**Comment by no-stack-dub-sack** [comment]
@sa-mm Also, kudos for going straight up vanilla JS! And glad to see you running the suite outside of codepen.

**Comment by sa-mm** [comment]
Thx!

One thing might be to explicitly state that the value of 'time-left' should start with the format 'mm:ss'. It seems that some of the tests rely on that, but that initial value differs from that of the [non-beta example](https://codepen.io/freeCodeCamp/full/aNyxXR) of the project. That might trip up some people as they move to the new version. Also, fwiw, I spent a lot of time looking at the code in the tests to understand how to fix things. I'm not sure if that is intended.

I don't remember everything I changed. However, I feel like I had a project that would have passed muster for the non-beta version of the site, and yet I had to make a significant amount of changes to get all of the tests passing. I think that once the site goes live, you should be prepared for a lot of questions… :)

I'll post here if I can think of any specific issues I had.

**Comment by no-stack-dub-sack** [comment]
@sa-mm 
> However, I feel like I had a project that would have passed muster for the non-beta version of the site, and yet I had to make a significant amount of changes to get all of the tests passing. I think that once the site goes live, you should be prepared for a lot of questions… :)

I agree with this feeling quite strongly, and have had these exact same concerns for quite some time as we've worked on this (which is why I'd like to try to get them as smoothed out as possible), but all things considered, Quincy determined that this was the best course of action to keep things consistent, to help eliminate the need for Core Team member review (as we grow in active user base), etc. etc. 

I'm afraid some users may be turned off by this, but it has been decided that this is the direction we're going in, so best thing to do is make them as good as we possibly can! So the feedback is helpful, I will make that change to the tests, especially since, as you pointed out, the non-beta version is different. Though I expect most people will never see that version if they are going through all of this the first time once the site goes live

**Comment by no-stack-dub-sack** [comment]
> Also, fwiw, I spent a lot of time looking at the code in the tests to understand how to fix things. I'm not sure if that is intended.

Nope, not intended 😄 . Albeit a bit distracting, this is not necessarily a bad thing either &mdash; extra exposure to testing and things like promises can't hurt!
