### ISSUE TITLE
Product Landing Page Test issue [Content #5]

### ISSUE THREAD

**Issue by SwaunyJones** [freeCodeCamp/testable-projects-fcc#890]
#### Issue Description

When I click a .nav-link button in the nav element, I am taken to the corresponding section of the landing page. but it's not registering as working on the "Product Landing Page Tests" even though it works on the site.

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 https://codepen.io/SwaunyJones/pen/EJMvzO?editors=1100
 
 
```

**Comment by abhishekakade** [comment]
@SwaunyJones, you have added empty links to your navigation (except the second link).
```
<li><a class="nav-link" href="#">About Us</a></li>
<li><a class="nav-link" href="#faq">FAQ</a></li> <!-- this one is correct -->
<li><a class="nav-link" href="#">Contact Us</a></li>
```
You need to correct them as you did with the second link for FAQs.

- Provide proper `ID`s to those respective `section`s (About Us, Contact Us) (I also think you are missing the *contact us* section, not sure though). 
- Then add those `ID`s to the `href` attributes of respective navigation links and your pen will clear this test.
- If you go through the test results, you will notice that it also checks for **`name`** attribute with value of **`email`** on `input type="email"`. So you will also need to add that to clear the remaining test. 

Try and see if it clears all the tests.
