### ISSUE TITLE
Drum Machine Keypress test Failure

### ISSUE THREAD

**Issue by philtrem** [freeCodeCamp/testable-projects-fcc#891]
#### Issue Description
Open the pen and run the tests to see what the issue is.
The test fails while it shouldn't. You can verify this yourself.

if I match keypress with id (match with capital letter), the test passes ALTHOUGH the functionality is broken. Whereas if I implement it correctly by matching on the lowercase letter, the test doesn't pass.

#### Your Code / Link to Your Pen
https://codepen.io/philtrem/pen/vwXqJE

**Comment by philtrem** [comment]
Not too surprising given the keycode used are for the capital letters, which makes very little sense to be honest...

```
it(`When I press the trigger key associated with each
      .drum-pad, the audio clip contained in its child <audio> element should be
      triggered (e.g. pressing the Q key should trigger the drum pad which
      contains the string "Q", pressing the W key should trigger the drum pad
      which contains the string "W", etc.).`,
      function() {
        **const keyCodes = [ 81, 87, 69, 65, 83, 68, 90, 88, 67 ];**
        assert.isAtLeast(
          audioElements.length,
          9,
          'Audio elements do not exist '
        );
```

**Comment by philtrem** [comment]
I made a pull request to fix this issue: https://github.com/freeCodeCamp/testable-projects-fcc/pull/892

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
