### ISSUE TITLE
Technical Documentation Page- false negatives in automated test

### ISSUE THREAD

**Issue by Alorell31** [freeCodeCamp/testable-projects-fcc#894]
False Negatives for all of these tests.

1. On regular sized devices (laptops, desktops), the element with id="navbar" should be shown on the left half of the screen. It should always be visible to the user and should remain stationary. You may need to enlarge the viewport or zoom out to ensure the navbar doesn't scroll with the page content.

2. Within the #main-doc ( <main> ) element, I can see several <section> elements, each with a class of "main-section". There should be a minimum of 5.

3. The first element within each .main-section should be a <header> element which contains text that describes the topic of that section. 
4. Each <section> element with the class of "main-section" should also have an id that corresponds with the text of each <header> contained within it. Any spaces should be replaced with underscores (e.g. The <section> that contains the header "Javascript and Java" should have a corresponding id="Javascript_and_Java").

5. The .main-section elements should contain at least 10 <p> elements total (not each).

6. The .main-section elements should contain at least 5 <code> elements total (not each).

7. The .main-section elements should contain at least 5 <li> items total (not each).

10. Additionally, the navbar should contain link (<a>) elements with the class of "nav-link". There should be one for every element with the class "main-section".

#### Browser Information

* Browser Name, Version: 
* Operating System: MAC Mojave
* Desktop, 

#### Your Code / Link to Your Pen

```
 https://codepen.io/Alorell31/pen/bygPZw?editors=1100
 
 #### Screenshot
<img width="569" alt="Screen Shot 2019-05-17 at 8 38 37 AM" src="https://user-images.githubusercontent.com/17624407/57928673-74f67780-787f-11e9-9dbb-285cab018fae.png">
<img width="1182" alt="Screen Shot 2019-05-17 at 8 39 50 AM" src="https://user-images.githubusercontent.com/17624407/57928674-74f67780-787f-11e9-8f09-cc7e9b8d487b.png">
<img width="1147" alt="Screen Shot 2019-05-17 at 8 40 00 AM" src="https://user-images.githubusercontent.com/17624407/57928675-74f67780-787f-11e9-9185-3c08445db614.png">
<img width="1147" alt="Screen Shot 2019-05-17 at 8 40 07 AM" src="https://user-images.githubusercontent.com/17624407/57928676-758f0e00-787f-11e9-954d-854f821eb0bf.png">
<img width="1159" alt="Screen Shot 2019-05-17 at 8 40 13 AM" src="https://user-images.githubusercontent.com/17624407/57928677-758f0e00-787f-11e9-9375-f74eb7aefb98.png">


```

**Comment by ValeraS** [comment]
@Alorell31 Your section tag classes use a `”main-section”` class name with non-standard quotes `”`, use `"` instead.
