### ISSUE TITLE
testing software issue

### ISSUE THREAD

**Issue by Jeremyobrien** [freeCodeCamp/testable-projects-fcc#895]
#### Issue Description

testing software won't register my video

#### Browser Information

* Browser Name, Version: chrome
* Operating System: windows 10
* Mobile, Desktop, or Tablet: laptop

#### Your Code / Link to Your Pen

```
 https://codepen.io/jjob1391/pen/KLpZGZ
 
 
```

#### Screenshot

![image](https://user-images.githubusercontent.com/33386483/57976189-baaa6180-799f-11e9-95e6-6a6043de269b.png)

![image](https://user-images.githubusercontent.com/33386483/57976204-d9105d00-799f-11e9-93ef-15860666f023.png)

**Comment by thecodingaviator** [comment]
It is passing on my side, try another browser or update your current one:
![image](https://user-images.githubusercontent.com/34807532/57978555-ad3bb880-7a2d-11e9-8da4-d0683fcfd151.png)
