### ISSUE TITLE
id="header" id="header-img"

### ISSUE THREAD

**Issue by wasabicocoa** [freeCodeCamp/testable-projects-fcc#898]
#### Issue Description

the error message - I can see an image within the #header element with a corresponding id="header-img". A company logo would make a good image here. 

No matter what I do it won't recognize that there is indeed a img tag with the id #header-img

#### Browser Information

--------Firefox, windows 10, desktop
* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
nav ul {
        padding: 0;
        margin: 0;
      }
      nav li {
        list-style: none;
        display: inline-block;
      }
      header {
        display: flex;
      }
      nav a {
        color: var(--light);
      }
        nav a:hover {
          opacity: 0.7;
          color: var(--light);
        }
 <header id="header" class="bg-dark fixed-top container">
  <div class="logo text-light">
    <img id="header-img" src="site/logo.png" alt="" />
  </div>
  <nav id="nav-bar" class="ml-auto">
    <ul>
      <li><a class="nav-link" href="#features">Features</a></li>
      <li><a class="nav-link" href="#how-it-works">How It Works</a></li>
      <li><a class="nav-link" href="#pricing">Pricing</a></li>
    </ul>
  </nav>
</header>

**Comment by lasjorg** [comment]
It is passing that test for me with the code you have posted. I would suggest using the [FCC forum](https://www.freecodecamp.org/forum/) for this kind of question.
