### ISSUE TITLE
Example project Codepen update: Product Landing Page

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/testable-projects-fcc#899]
New issue for the landing page, separated out from issue https://github.com/freeCodeCamp/testable-projects-fcc/issues/832

### Challenge: Responsive Web Design Projects - Build a Product Landing Page

**Changes made:**

1. Remove SCSS. The project is using SCSS before it has been taught in the curriculum and is confusing people.

2. Improve selectors. It is using some ill-advised selectors.

Challenge: Responsive Web Design Projects - Build a Product Landing Page
https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-projects/build-a-product-landing-page/

Original Codepen:
https://codepen.io/freeCodeCamp/full/RKRbwL

My own forked Codepen version with changes:
https://codepen.io/lasjorg/pen/qwRoRR

Fixed version merged into repo
https://github.com/freeCodeCamp/testable-projects-fcc/tree/master/src/projects/product-landing-page

**Comment by scissorsneedfoodtoo** [comment]
Thank you @lasjorg!

Updated freeCodeCamp pen: https://codepen.io/freeCodeCamp/full/RKRbwL
