### ISSUE TITLE
Proposed update to the FCC portfolio page example project

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/testable-projects-fcc#900]
As I was updating this project for https://github.com/freeCodeCamp/testable-projects-fcc/issues/854, I really started to feel like campers would benefit from the last example project being a better example. Both how a page can look but also using some more modern CSS.

I know on the one hand that making the example simple and not seem unobtainable, is a good idea, so we do not overwhelm the camper. But on the other hand, setting the bar too low with a poor example is also not beneficial.

The page I made is using the same layout, more or less, but looks (hopefully) better and is using some different techniques for the layout. It is nothing too fancy and shouldn't be an unreasonable goal for the final project. I should say I'm not a designer by any stretch of the imagination but I think it looks decent enough.

Here is the page:
https://codepen.io/lasjorg/full/GadWvj

I want to get your feedback and if you think this is a good idea or not?

**Comment by lasjorg** [comment]
@tbushman Not really sure who I should `@mention` here to get feedback.

**Comment by tbushman** [comment]
@lasjorg This looks really neat. I would approve it. Mentioning @raisedadead because it would require coordination to update the project on Codepen.

**Comment by raisedadead** [comment]
Codepen updates are handled by @scissorsneedfoodtoo (our resident curriculum ninja ⚔️).

**Comment by lasjorg** [comment]
I will make a PR for the code update to the repo and then when that has been merged I will open an issue for the update to Codepen.

However, before I can do that I need my PR https://github.com/freeCodeCamp/cdn/pull/25 on the cdn repo to get merged so I can use the correct image links. @tbushman Do you know who I should ping to get the cdn PR merge done? It doesn't seem like anybody has noticed the PR.

**Comment by tbushman** [comment]
@lasjorg OK, you're good to go.

**Comment by scissorsneedfoodtoo** [comment]
@lasjorg, awesome! This looks great. Yes, please just @ mention me whenever you're ready to update the example on Codepen.

**Comment by lasjorg** [comment]
@tbushman The PR for this update https://github.com/freeCodeCamp/testable-projects-fcc/pull/903 is ready for review. I don't mean to spam you, just want to make sure you didn't miss it.

**Comment by lasjorg** [comment]
@scissorsneedfoodtoo I have opened an issue for the update here https://github.com/freeCodeCamp/testable-projects-fcc/issues/905

**Comment by lasjorg** [comment]
@scissorsneedfoodtoo Just in case you missed it we are all set for the update.

**Comment by scissorsneedfoodtoo** [comment]
Sorry for the delay. I just updated the portfolio here: https://codepen.io/freeCodeCamp/full/zNBOYG

**Comment by lasjorg** [comment]
resolved

**Comment by scissorsneedfoodtoo** [comment]
Thank you for closing this issue, @lasjorg!
