### ISSUE TITLE
Tribute Page #7 

### ISSUE THREAD

**Issue by Jryke** [freeCodeCamp/testable-projects-fcc#902]
I am having trouble passing the test on the tribute page because it is saying I don't have an href for my <a> tag.  I have an href and it works when I click on it so I'm not sure why my code isn't passing the test.

#### Issue Description

Tribute Page #7 

when I run the test, I get this message:

7. I should see an <a> element with a corresponding id="tribute-link", which links to an outside site that contains additional information about the subject of the tribute page. HINT: You must give your element an attribute of target and set it to "_blank" in order for your link to open in a new tab (i.e. target="_blank").

and below this message:
<a> element with id="tribute-link" must contain an href attribute 
AssertionError: <a> element with id="tribute-link" must contain an href attribute 

#### Browser Information

* Browser Name, Version: Chrome v.74.0.3729.169
* Operating System: MacOS Mojave
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
 https://codepen.io/Jryke/pen/gJdpNG

```

#### Screenshot

<img width="1202" alt="Screen Shot 2019-05-28 at 9 00 36 PM" src="https://user-images.githubusercontent.com/47799560/58521825-cc53ec00-818b-11e9-9a20-90397ed16d9d.png">

**Comment by tbushman** [comment]
@Jryke You have two elements with `id="tribute-link"` . Please only assign `id="tribute-link"` to the `<a>` element.

**Comment by Jryke** [comment]
Thank you so much @tbushman!  I knew it was something simple like that but I couldn't find it anywhere in my code.  Thanks again!
