### ISSUE TITLE
Test not working

### ISSUE THREAD

**Issue by PhlyingSausage** [freeCodeCamp/testable-projects-fcc#904]
#### Issue Description

None of the tests work when I click the "run" button. I've followed the instructions provided. Please the link to my CodePen: 
https://codepen.io/maximvallee/pen/LoMRey

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

https://codepen.io/maximvallee/pen/LoMRey
 
 
 
```

#### Screenshot
<!-- Add a screenshot of your issue -->

**Comment by tbushman** [comment]
@PhlyingSausage The error messages mention the use of `id` in cases where you've used `class`. I'm also noticing some missing quotation marks.  
For example, please change  
```  
<img class="image" src=https://c2.staticflickr.com/4/3689/10613180113_fdf7bcd316_b.jpg alt="Dr. Norman Borlaug with his friends">  
```  
to  
```  
<img id="image" src="https://c2.staticflickr.com/4/3689/10613180113_fdf7bcd316_b.jpg" alt="Dr. Norman Borlaug with his friends">  
```

**Comment by petercr** [comment]
Yes it's not passing the tests because you have not met the conditions in order to pass the tests. 
Make sure you use `id` where you need it and `class` where you need it
