### ISSUE TITLE
Update portfolio webpage on Codepen

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/testable-projects-fcc#905]
@scissorsneedfoodtoo The update has now been merged https://github.com/freeCodeCamp/testable-projects-fcc/pull/903.

Here is also a link to my Codepen version with the same code. I have left the external resources linked to at the top of the page like in the PR. That way it is also easier for people to see the resources used on the page. But we can just move them to the Codepen settings if that is preferred. The test script is still linked to in the settings.
https://codepen.io/lasjorg/pen/GadWvj

**Comment by scissorsneedfoodtoo** [comment]
@lasjorg, thank you for the heads up! I'll update this example on CodePen now.

**Comment by lasjorg** [comment]
resolved

**Comment by scissorsneedfoodtoo** [comment]
Thank you for closing this issue, @lasjorg!
