### ISSUE TITLE
Technical Document Project Media Query Test Issue

### ISSUE THREAD

**Issue by bgongre** [freeCodeCamp/testable-projects-fcc#906]
#### Issue Description

Attempting to complete the "Technical Document Project" from FCC Responsive Web Design projects. When placing a media query in my CSS and running the tests it is giving me an error code stating it does not see the media query.

#### Browser Information

I am using the FCC CDN provided to run my test in my local environment using VS Code.

* Browser Name, Version: Google Chrome, 75.0.3770.80
* Operating System: Windows 10 64-bit
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
 https://github.com/bgongre/Technical-Document/
 
```

#### Screenshot

![Media_Query_Issue](https://user-images.githubusercontent.com/27456325/59153822-7441a300-8a31-11e9-9e78-41065a94bba0.JPG)

**Comment by tbushman** [comment]
@bgongre The media query test needs to receive the CSS through an http connection. You can achieve this in a local development environment by using `live-server` or Python simpleHTTPServer (https://www.npmjs.com/package/live-server).  
Alternatively, you may put your code into Codepen to verify the media query test.

**Comment by bgongre** [comment]
@tbushman Thanks for the information. I will mess around with live-server since I'll probably need it later on and it seems like a useful tool. Going to CodePen showed that all test completed with no issues.
