### ISSUE TITLE
Calculator test conditions do not permit negative number multiplication

### ISSUE THREAD

**Issue by emptyport** [freeCodeCamp/testable-projects-fcc#908]
#### Issue Description

According to math, the following expression is valid:
-3*-3
The answer is 9.

According to the project requirements, however, -3*-3 becomes -6 because of the requirement "If 2 or more operators are entered consecutively, the operation performed should be the last operator entered."

This might make some aspect of the coding/testing easier, but it is wrong. A JavaScript calculator ought to work like a real calculator.

#### Your Code / Link to Your Pen
You can view this behavior in the example project
https://codepen.io/freeCodeCamp/full/wgGVVX

**Comment by emptyport** [comment]
I think the only cases where a double operator would be needed would be in the case of negative numbers. Maybe there can be an exception for the minus operator when it comes second.

**Comment by tbushman** [comment]
@emptyport Thank you very much for pointing this out.
