### ISSUE TITLE
I'm having trouble getting the test on codePen working

### ISSUE THREAD

**Issue by pcrbus123** [freeCodeCamp/testable-projects-fcc#909]
I am having an issue getting codePen testing to work. everytime i try it gives me a message saying `#mocha div missing. add it to your project`. maybe i didn't set something up right?

**Comment by tbushman** [comment]
@pcrbus123 Thanks for reporting this. Another student reported a similar issue #889   
Could you share your code? Is this the javascript calculator project?

**Comment by thecodingaviator** [comment]
@pcrbus123 Check if you mistakenly used `class` instead of `id`
