### ISSUE TITLE
Tooltip error, treemap project

### ISSUE THREAD

**Issue by GregoryGoncalves** [freeCodeCamp/testable-projects-fcc#91]
Information wasn't previously filled in, i've tried this on Chromium and Firefox. Using Fedora.

The following error happens on my treemap project:
`Error: Tooltip should be hidden when mouse is not on an area`

However the project is behaving correctly, i don't have enough information to debug it. I tried removing the animation time to fade and show the tooltip, it didn't work. 
Here is the codepen: http://codepen.io/Selhar/full/eWKjbL/

**Comment by no-stack-dub-sack** [comment]
@GregoryGoncalves Thanks for reporting this issue.

@Christian-Paul @Paycoguy Any ideas as to why the tooltip tests are failing here? They do seem to be behaving correctly.

**Comment by paycoguy** [comment]
I can look at this tomorrow

**Comment by paycoguy** [comment]
@GregoryGoncalves 
It looks like the entire svg element has the id of "tooltip".  The tooltip_block in line 37 should be the one with id of "tooltip".   Once I made this change, all the tests passed.  Let me know if you have any questions with this.

Thank you so much for testing out these project for us!

**Comment by GregoryGoncalves** [comment]
@paycoguy 
Thanks a lot, i hadn't noticed. 
The error message could be improved, however, for situations where the ID isn't in the correct place, aka if the element with "tooltip" id doesn't have the necessary fields as it's children.
I'll close the issue since it's solved, thanks a lot for your time.
