### ISSUE TITLE
Image responsiveness not recognized by the test suit.

### ISSUE THREAD

**Issue by Jorchie** [freeCodeCamp/testable-projects-fcc#911]
Tribute page
 
I've set my image as responsive according to it's parent but it does not seem to get it in the test suit, in the pen I can test it without an issue but it does not appear to work on the test 

in my css have the following

#img-div{ 
  padding: 10px;
  margin: auto;
} 
#image {
  width: 100%;
  display: block;
  height: auto;
  max-width: none;
  padding-bottom: 10px;
}

being the max-width, height and display the ones requested by the test suit as far as i can see.

#### Issue Description 
I've set the css of my image as needed to be responsive according to it's parent but it does not seem to get it right in the test suit, in the pen I can look at it and it resizes it without an issue but it does not appear to be taken in the test 

#### Browser Information 

* Browser Name, Version:  Chrome 74.0.3729.131
* Operating System: Mac Os Mojave 10.14.3
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen 
```
 https://codepen.io/jorchie/pen/orjWQd?editors=1100
```

#### Screenshot 
<img width="1438" alt="Captura de pantalla 2019-06-13 a la(s) 16 32 32" src="https://user-images.githubusercontent.com/14006732/59468926-ed0d7a00-8df8-11e9-8ef7-6c81faf2abe5.png">

**Comment by tbushman** [comment]
@Jorchie The way this test checks that the `<img>` element responsively resizes is by simply checking CSS values. Please make the max-width 100%. This will ensure that when the window is resized, the `<img>` element will be at most 100% the width of the parent `<figure>` element.
