### ISSUE TITLE
'D3: Bar Chart' test suite, tests 13,14 fail although their requirements are implemented

### ISSUE THREAD

**Issue by bravas** [freeCodeCamp/testable-projects-fcc#912]
#### Issue Description

The last two tests of the 'D3: Bar Chart' test suite are failing when they shouldn't.

> User Story #12: I can mouse over an area and see a tooltip with a corresponding id="tooltip" which displays more information about the area.
User Story #13: My tooltip should have a data-date property that corresponds to the data-date of the active area.

Open codepen https://codepen.io/bravas/pen/dBGdbp

The tooltip is displayed in any of the areas when hoving over.
The property 'data-date' has been added to the tooltip in line 59

#### Browser Information

* Browser Name, Version: Chrome, Version 75.0.3770.90 (Official Build) (64-bit)
* Operating System: Microsoft Windows [Version 10.0.17134.829]
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
https://codepen.io/bravas/pen/dBGdbp
```

**Comment by tbushman** [comment]
@bravas Hello, this is similar to #619 and remains unresolved. Please see the discussion there. Thanks for your patience.

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
