### ISSUE TITLE
Tests 12,13 are not passed although everything seems correct. Please Check. This is in reference to Responsive Web Design Projects - Build a Technical Documentation Page.

### ISSUE THREAD

**Issue by MugdhaBehere** [freeCodeCamp/testable-projects-fcc#913]

**Comment by tbushman** [comment]
@MugdhaBehere Hello, please provide some more information about the error you are experiencing. Please provide a screenshot, a code sample, or a link to your project.

**Comment by MugdhaBehere** [comment]
Thanks but the problem is now solved.
