### ISSUE TITLE
Markdown Previewer - Test 4 - Trailing carriage return rejected

### ISSUE THREAD

**Issue by dloret** [freeCodeCamp/testable-projects-fcc#915]
#### Issue Description

Test 4 is the only test I cannot pass due to the fact I chose NOT to use `dangerouslySetInnerHTML`. I chose to store the markdown-converted html as a string in my Redux state.
Then I use the `react-html-parser` package to render this html on the screen. This parser automatically adds a new line or a carriage return at the end. Despite the update #869 merged in April 2018, my code is rejected.

From the test result screenshot, below, I understand the test is now checking for a `\n` only? So in my case, the little square arrow at the end of my state certainly means the `react-html-parser` adds a carriage return `\r` or even a windows-style newline `\r\n` but these are not accepted?

As I'm not very experimented, I perhaps understand all this wrong, but I can see that my code is correct and should pass the test... Couldn't it be updated to accept whatever is used to add a new line, or no new line at all?
Sorry in advance if I missed something obvious.

#### Browser Information

* Browser Name, Version: Chrome, v75, Firefox v67
* Operating System: Ubuntu 19.04 or Windows 10 WSL
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

I code locally to publish my code in an AWS S3 bucket (check the console after running the tests):
http://2d2h.net/fcc/front_end_libraries/markdown_previewer/

Preview.js file content:
```javascript
import React from 'react';
import Parse from 'react-html-parser';
import '../../styles/Preview.scss';

const Preview = ({ html, editing, edit }) => {
  const size = {};
  if (editing) {
    size.maxHeight = '5vh';
    size.overflow = 'hidden';
  }

  const handleClick = () => edit(editing);

  return (
    <div className="preview">
      <header>
        <h2>Preview</h2>
        <div className="sizing">
          {editing ? (
            <i
              className="fas fa-expand-arrows-alt fa-lg"
              onClick={handleClick}
            />
          ) : (
            <i
              className="fas fa-compress-arrows-alt fa-lg"
              onClick={handleClick}
            />
          )}
        </div>
      </header>
      <div id="preview" className="rendered-html" style={size}>
        {Parse(html)}
      </div>
    </div>
  );
};

export default Preview; 
```

#### Screenshot

Result of test 4:
![image](https://user-images.githubusercontent.com/14251503/59908597-112b1580-940e-11e9-806c-d614bbe44552.png)

The state of my app:
![image](https://user-images.githubusercontent.com/14251503/59908698-4afc1c00-940e-11e9-94ae-2472455dd87c.png)

**Comment by tbushman** [comment]
@dloret It looks like replacing the carriage return with a newline should be handled before rendering, because it looks like react parser is inserting a unicode character, `↵`, and not `\r`, or `\n`.   
Does `Parse(html).replace('↵', '\n')` work?

**Comment by dloret** [comment]
Hi, sorry for the late reply, I was finishing the JS calculator project.
I tried your solution and it doesn't work because the Parse method returns
an Object.
I'm trying to identify where in that object this strange unicode character
is used, without luck currently.
I don't understand why this character is being used. It seems strange.
Thanks a lot for pointing this out.

Le mer. 26 juin 2019 à 06:58, Tracey Bushman <notifications@github.com> a
écrit :
