### ISSUE TITLE
Random Quote machine bug issue with testing

### ISSUE THREAD

**Issue by jsamuel29** [freeCodeCamp/testable-projects-fcc#916]
#### Issue Description

The issue is when i test the project sometimes it will say i passed and sometimes it will say i failed i did everything on the project that was expected of me and didn't make any changes.

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 
Google Chrome
Desktop
#### Your Code / Link to Your Pen

```
 https://codepen.io/jsamuel1/pen/OeNbXz
 
 
```

**Comment by tbushman** [comment]
@jsamuel29 This is similar to #830, wherein short lists of quotes, when randomly selected, sometimes fail the test that ensures each new quote doesn't match the previous quote. You can use your own methods to prevent repeating quotes, or add more quotes to reduce the likelihood of identical quotes coming up in succession.

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
