### ISSUE TITLE
name field not required but gives me error on the automated test.   

### ISSUE THREAD

**Issue by 3zcs** [freeCodeCamp/testable-projects-fcc#918]
#### Issue Description
Project Build a Product Landing Page

If I don't add name attribute at email text field inside the form, the automated test gives me an error, but in the [requirement](https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-projects/build-a-product-landing-page) it's not mentioned as mandatory. 

#### Browser Information
Chrome with Codepen.io 

* Chrome, Version: 74.0.3729.169
* Operating System: Mac OS
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen
https://codepen.io/3zcs/pen/dBpQpN

**Comment by tbushman** [comment]
@3zcs The requirement is not specifically mentioned, it seems, but the `<input name="">` attribute is used server-side when forms are submitted. It will be a good habit to get into.

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
