### ISSUE TITLE
Image centering

### ISSUE THREAD

**Issue by boggyfresh** [freeCodeCamp/testable-projects-fcc#920]
#### Issue Description
Project requires CSS to include `#image {display: block;}` as part of centering an image
This is not necessary when implementing CSS grid and applying `#image {justify-self: center;}` to the image

#### Browser Information

* Browser Name, Version: Chrome 75.0.3770.100 | Edge 42.17134.1.0 | Firefox 67.0.4 
* Operating System: Windows 10, Desktop

#### Your Code / Link to Your Pen
https://codepen.io/boggyfresh/pen/orWEBE
```
 
 
 
```

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
