### ISSUE TITLE
Faulty tests in Pomodoro Clock project.

### ISSUE THREAD

**Issue by theNvN** [freeCodeCamp/testable-projects-fcc#922]
#### Issue Description

Multiple test are failing for the Pomodoro Clock project, which should not. Everything's working fine & id and class attrs are given as required, yet it fails tests even those involved in checking for the id or class attrs. I used React + Redux for the project.

#### Browser Information

* Browser Name, Version: Firefox, 67.0.4 (64-bit)
* Operating System: Windows 10 Home 64 bit.
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

https://codepen.io/theNvN/full/dBdNKR
```
 
 
 
```

**Comment by tbushman** [comment]
@theNvN Sorry for the delay. There were a few omissions which, when fixed, your project passes all but one test, which I can't yet figure out. Thanks for your patience.    
    
Line 388  
`lableId="break-label"` should be `labelId="break-label"`  
  
Line 407  
Add `labelId="timer-label"` to `<Timer className="timer"`  
  
and  
Line 292  
`<div className="timer-label">` to `<div id={this.props.labelId} className="timer-label">`

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
