### ISSUE TITLE
Build a Tribute Page

### ISSUE THREAD

**Issue by ledney07** [freeCodeCamp/testable-projects-fcc#924]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 
 
```

**Comment by tbushman** [comment]
Hello @ledney07 , please provide some more information about the error you are experiencing. Indicate which test is failing and provide a screenshot, a code sample, or a link to your project.
