### ISSUE TITLE
Tests are not passing

### ISSUE THREAD

**Issue by RyanHuang06** [freeCodeCamp/testable-projects-fcc#925]
#### Issue Description
I put a h2 tag embedded into my p tribute-info tag, it does not pass test 10 even though I had the id of "tribute-info".

#### Browser Information

* Browser Name, Version:  Chrome 75
* Operating System:  Windows
* Mobile, Desktop, or Tablet: Laptop

#### Your Code / Link to Your Pen

```
 
 I deleted the <h2> tags to pass the challenge.
 
```

**Comment by tbushman** [comment]
Hello @RyanHuang06 , please provide some more information about the error you are experiencing. Indicate which test is failing and provide a screenshot, a code sample, or a link to your project.

**Comment by RyanHuang06** [comment]
Fixed it, nevermind. The first tribute page project had a glitch where when
I nested other tags in the tribute-info tag, it glitched and the last test
did not pass.

Tracey Bushman <notifications@github.com> 于2019年7月30日周二 下午1:44写道：
