### ISSUE TITLE
Tribute Page in Project #1 Test button not working

### ISSUE THREAD

**Issue by dakshshah14** [freeCodeCamp/testable-projects-fcc#926]
#### Issue Description

The Tests button is not working. It is not showing the individual tests' errors.

#### Browser Information

* Browser Name, Version: Safari Version 12.1.1 (14607.2.6.1.1)
* Operating System: macOS Mojave version 10.14.5 
* Mobile, Desktop, or Tablet: MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)

#### Your Code / Link to Your Pen

```
 https://codepen.io/dakshshah14/pen/ydGjqX
 
 
```

**Comment by RandellDawson** [comment]
Please post your question on the [forum](https://freecodecamp.org/forum).  If they determine it is an actual bug, then ask for this to be reopened.  You posted a link to the FCC template and not an actual project.
