### ISSUE TITLE
Product lannding page - Test 12

### ISSUE THREAD

**Issue by Paul-rapin** [freeCodeCamp/testable-projects-fcc#928]
#### Issue Description
I can't validate the 12th point of the "Product Landing Page", I don't have redirection error when I submit the email. My code seems good to me but I can just be wrong, I'm sorry for the inconvenience if this is the case. 

#### Browser Information

* Browser Name, Version: Chrome, 75.0.3770.100 (Official build) (64 bits)
* Operating System: MacOS Mojave 10.14.5
* Mobile, Desktop, or Tablet: -

#### Your Code / Link to Your Pen

The lines of code concerned by the issue : 
<input id="email" type="email" name="email" placeholder="Email">
    <input id="submit" type="submit" action="https://www.freecodecamp.com/email-submit" method="post">

Here is the pen : 
 https://codepen.io/Paul_volet/pen/zVjGOz

**Comment by RandellDawson** [comment]
@Paul-rapin Issues are only to be used to report bugs in the tests.  The tests are fine.  Your code has bugs in it.  Please use the [forum](https://forum.freecodecamp.org) when asking questions about your project code.

FYI - If you click on the error message showing in the tests, it tells you exactly what is missing.  Form elements need an action attribute (not input elements).

I am closing this as a non-issue.

**Comment by Paul-rapin** [comment]
I'm sorry for the inconvenience, my mistake, thank you very much for the
answer.

Le jeu. 11 juil. 2019 à 22:25, Randell Dawson <notifications@github.com> a
écrit :
