### ISSUE TITLE
there is a bug a can not take the test  (Build a Product Landing Page test ) when a go to the code.pen link to run my code  a can't see nothing all the page is in white(empty)

### ISSUE THREAD

**Issue by Alexoid1** [freeCodeCamp/testable-projects-fcc#931]
#### Browser Information

* Browser Name, Version: google chrome 75.0.3770.100
* Operating System: windows 10
* Mobile, Desktop, or Tablet: PC DESKTOP

#### Your Code / Link to Your Pen

```
 there is a bug a can not take the test  (Build a Product Landing Page test ) when a go to the code.pen link to run my code  a can't see nothing all the page is in white(empty)
 
 
```

#### Screenshot

![2019-07-20](https://user-images.githubusercontent.com/53111464/61576404-5d19ba80-aa9f-11e9-9c77-98b5b8a01359.png)
![2019-07-20](https://user-images.githubusercontent.com/53111464/61576411-660a8c00-aa9f-11e9-84f6-a57a1f86bda5.png)

**Comment by petercr** [comment]
You need to either add the Code Test script to your CodePen, or fork the base CodePen that has nothing. And add all of your code to it. The test script needs to be running on your CodePen to test it
