### ISSUE TITLE
Menu keeps disappearing

### ISSUE THREAD

**Issue by bgoodwell** [freeCodeCamp/testable-projects-fcc#932]
#### Issue Description

After entering code the menu to run test keeps disappearing. 

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: Mac
* Mobile, Desktop, or Tablet: laptop

#### Your Code / Link to Your Pen

```
 
 
 
```

**Comment by tbushman** [comment]
@bgoodwell Thanks for the feedback. When you minimize the test window, it turns into a menu icon situated in the top-left corner. It's dark green, so you may not see it if your project is green. I'll keep this open so we can improve the interface.

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
