### ISSUE TITLE
Personal Portfolio broken link

### ISSUE THREAD

**Issue by Toya88** [freeCodeCamp/testable-projects-fcc#934]
#### Issue Description

#8 on the personal portfolio page requires you to add a link to your FCC or Git hub. However it will not pass the link unless the last closing " that should close the link is missing. With the " missing the link does not work and does not show on the page. But it is being counted as passing.

#### Browser Information

* Browser Name, Version: google chrome
* Operating System: windows 10
* Mobile, Desktop, or Tablet: desktop

#### Your Code / Link to Your Pen

```
 https://codepen.io/toya88/pen/YmWEwg
 
 
```

**Comment by tbushman** [comment]
@Toya88 Hello. Please change `<a " id="profile-link" href="https://github.com/toya88">` to `<a id="profile-link" href="https://github.com/toya88" target="_blank">`  
(remove the `"` before `id=` and add the `target` attribute)  
Here is a discussion about the `target` attribute: https://stackoverflow.com/questions/22660439/what-is-the-use-of-target-attribute-in-html-form-tag
