### ISSUE TITLE
Random Quote Machine Tests fail with fetch API

### ISSUE THREAD

**Issue by vinod-vms** [freeCodeCamp/testable-projects-fcc#935]
#### Issue Description

I have an otherwise fully functional Random Quote Machine here: https://codepen.io/vinod-vms/pen/mNrYxx
But the automated tests fail on 6,7,8, and 9 tests. (Out of 12). It seems that the timeout specified in the test is low. Somehow the fetch API is not resolving within the 15000ms?? as hardcoded in the tests.
It fails with the following information:
Timeout of 15000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. Error: Timeout of 15000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.  at o.f._timeoutError (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:159:32523)  at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:159:30654

#### Browser Information

* Browser Name, Version: Chrome, Firefox
* Operating System: Linux, Windows
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

https://codepen.io/vinod-vms/pen/mNrYxx
```
 
 
 
```

**Comment by dhuang612** [comment]
Hello,

I took a look at your code and the error message. So the reason you are failing this test:
 On first load, my quote machine displays the random quote's author in the element with id="author".

is that you have your fetch request tied to a button press to the function:
handleClick
 and this test is expecting upon first load to have a quote already there.
Your quote is added in after so it fails the test

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
