### ISSUE TITLE
Javascript Calculator tests not running

### ISSUE THREAD

**Issue by LincolnNowell** [freeCodeCamp/testable-projects-fcc#937]
#### Issue Description
I am trying to run tests on my Javascript calculator project. When i click run tests it shows 0/0 tests and acts like the tests have succeeded. I don't know if this effected it, but I used the DOM instead of react, because i just wanted to practice using it. Also i turned Haml off. I tested using both the codepen and the test script, both shared the same issue.

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen
https://codepen.io/lincolnnowell/pen/LwxNBb

#### Screenshot

![Screenshot (33)](https://user-images.githubusercontent.com/45523380/62015066-c075ad80-b16d-11e9-8037-6e821bd3a685.png)

![Screenshot (34)](https://user-images.githubusercontent.com/45523380/62015118-61646880-b16e-11e9-9a6d-2f85fa81661b.png)

**Comment by tbushman** [comment]
I wasn't getting the same issue. I found a couple of things that will help, and then one of the tests is not working as expected, so we need to look into it (see #933 ). Thanks for your patience.  
`<div id="display" class = "display">`  (Add `id="display")  
`<button Onclick='reply_click(this.id)' id="divide">/</button>` (change `id="division"` to `id="divide"`)

**Comment by LincolnNowell** [comment]
I got it to work. Sorry for the inconvenience.
