### ISSUE TITLE
Calculator test case wrong condition

### ISSUE THREAD

**Issue by Ahmed-Elbessfy** [freeCodeCamp/testable-projects-fcc#938]
#### Test Case 13 is not logical
how can this operation 5 * - + 5 have a 10 result!! in any calculator it will give back -25 and this my result! 

another thing: user stories need to be updated with the requirements of this test

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: Windows 8.1
* Mobile, Desktop, or Tablet: Desktop

#### [My Code](https://codepen.io/Ahmedelbessfy/pen/XLKpaj)

```
 
 
 
```

#### Screenshot

![image](https://user-images.githubusercontent.com/25265723/62072161-57aa3600-b23e-11e9-81a2-7cc89b0e4a2e.png)

**Comment by tbushman** [comment]
@Ahmed-Elbessfy Thanks for your feedback. I think we need to re-work this. For now, I think the user story mentions that the calculator should only use the last operand entered, unless it is intended as a negative sign (a minus sign that comes before a number).  
The most recent change was in response to #908 and legacy projects are affected, so we need to work it out.

**Comment by Ahmed-Elbessfy** [comment]
@tbushman  and how can I make an operation on a negative number if I push a minus sign after any operator, it will replace it? 
My suggestion is to require an additional button for negative numbers or allow multiple operators as normal calculators and the final result may be similar to normal calculators results too.

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
