### ISSUE TITLE
how do i submit my project its keep showing my test dint pass but i already get 10/10 right, on tribute page project

### ISSUE THREAD

**Issue by ezmeet** [freeCodeCamp/testable-projects-fcc#939]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 
 
```

**Comment by tbushman** [comment]
Hello @ezmeet , please provide some more information about the error you are experiencing. Indicate which test is failing and provide a screenshot, a code sample, or a link to your project.
