### ISSUE TITLE
What is wrong with my code?

### ISSUE THREAD

**Issue by rithik-jain** [freeCodeCamp/testable-projects-fcc#942]
#### Issue Description

My code is correct. Bu then also error comes.

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Laptop

#### Your Code / Link to Your Pen

```
 https://codepen.io/freeCodeCamp/pen/MJjpwO
 
 
```

**Comment by RandellDawson** [comment]
Please only report issues with the challenge and tests and not your code. Instead, use [our forum](https://www.freecodecamp.org/forum) to ask such questions.

Thank you.
