### ISSUE TITLE
When you try to analyse html, inspector warning seems frozen.

### ISSUE THREAD

**Issue by fanzozo** [freeCodeCamp/testable-projects-fcc#943]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 
 
```

**Comment by tbushman** [comment]
Hello @fanzozo, please provide some more information about the error you are experiencing. Indicate which test is failing and provide a screenshot, a code sample, or a link to your project.
