### ISSUE TITLE
Inspector warning not working.when analysis html

### ISSUE THREAD

**Issue by fanzozo** [freeCodeCamp/testable-projects-fcc#944]
product landing page

#### Browser Information
codepen

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: Mobile and desktop

#### Your Code / Link to Your Pen
https://codepen.io/fanzozo/pen/pMNXOE
```
 
 
 
```

**Comment by tbushman** [comment]
@fanzozo It looks like your tests are passing. Will close this issue if we don't hear back.
