### ISSUE TITLE
1. The navbar should always be at the top of the viewport. Fails on codepen

### ISSUE THREAD

**Issue by ChariseWalraven** [freeCodeCamp/testable-projects-fcc#945]
#### Issue Description
1. The navbar should always be at the top of the viewport. Fails on codepen, because the site also uses their own header. You can't get rid of this header in codepen.

#### Browser Information
* Browser Name, Version: 
Chrome beta  76.0.3809.87
* Operating System: 
Windows 10
* Mobile, Desktop, or Tablet: 
Desktop

#### Your Code / Link to Your Pen
 https://codepen.io/HappyCamper20/full/bOOzbr

**Comment by ChariseWalraven** [comment]
Hmm, further inspection shows that this is not because of the codepen header. I deleted the header from the page in the chrome inspector and the test still failed...

**Comment by RandellDawson** [comment]
@ChariseWalraven GitHub is only for reporting bugs with the tests and not bugs with your code.  Please [create a topic on our forum](https://www.freecodecamp.org/forum/c/help) where you will get the help needed.

Thank you.  

Closing this issue as it is not an actual bug in the tests.
