### ISSUE TITLE
Pomodoro Test Suite Bug: Not reach 00:00 check

### ISSUE THREAD

**Issue by Garciaj007** [freeCodeCamp/testable-projects-fcc#946]
#### Issue Description

Says that break timer does not reach 0 when it clearly does. Done debugging and logging, and it does indeed work. Something to do with the test suite...

#### Browser Information

* Google Chrome V.76.0.3809.100
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

 [https://codepen.io/Garciaj007/full/WVaXdZ](https://codepen.io/Garciaj007/full/WVaXdZ)

**Comment by tbushman** [comment]
@Garciaj007 testing your pen manually, I'm noticing your timer doesn't switch to / from 'Break' and 'Session'.  
```  
if(this.state.timer.minutes === 0 && this.state.timer.seconds === 0){
      console.log(this.state.currentTimer, this.getTime());
      this.timerFinished();
    }   
```  
There should be code for switching in this logic, it seems.
