### ISSUE TITLE
Add example to clarify multiple calculator operators behavior

### ISSUE THREAD

**Issue by tbushman** [freeCodeCamp/testable-projects-fcc#947]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 
 
```

#### Screenshot

see
https://github.com/freeCodeCamp/freeCodeCamp/pull/36523

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
