### ISSUE TITLE
Missing test concerning negative results (Test of JS Calculator)

### ISSUE THREAD

**Issue by felixmuecke** [freeCodeCamp/testable-projects-fcc#95]
#### Issue Description
Ok so this is not exactly a bug report, just a suggestion to add another test to the JS Calculator Test.
Here is the mistake my code produced that was not caught:
1) enter 5-9, press equal
2) -4 is displayed
3) proceed to add +5 so -4+5 is displayed in the formula window, press equal
4) result is -9 due to the way the evaluation works in my code (will fix this :) ). this mistake is not caught by the tests.

#### Your Code / Link to Your Pen
code is still messy but i will leave it like this for a while in case you want to check it

http://codepen.io/felixmuecke/pen/JNpyvp

**Comment by no-stack-dub-sack** [comment]
@felixmuecke hmmm... this is a nice catch. Thanks for reporting this. We don't need an additional test case I don't think, just more stringent tests for test # 9. Maybe a few more calculations to make sure things are working as expected. 

Your calc also produces the same incorrect result when you do not evaluate after entering`5-9`, i.e. `5-9+5` still equals `-9` when it should be one. So perhaps adding this particular sequence will help to catch calculations involving negative values.

By the way, great job overall on the calc! Design looks great and once you work out that kink it will be in great shape!

**Comment by felixmuecke** [comment]
glad i could help and thank your for all your great work, am really enyoing freecodecamp!

**Comment by no-stack-dub-sack** [comment]
@felixmuecke thanks!
