### ISSUE TITLE
Can't seem to pass text #7 for Drum Machine

### ISSUE THREAD

**Issue by kaashin** [freeCodeCamp/testable-projects-fcc#954]
#### Issue Description

For the drum machine, I can't seem to pass test #7. The audio plays for me when I hit the correct keys. I checked to make sure my element ID's are correct, but the test can't seem to detect that I trigger the audio to play.

#### Browser Information

Firefox

* Browser Name, Version: Firefox
* Operating System: Windows
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
 A link to my pen:https://codepen.io/kaashin/pen/mNXrEJ
 
 
```

**Comment by tbushman** [comment]
@kaashin Very sorry for the late response. In my understanding, your audio .wav source urls need to be put in `<audio>` elements. Currently, you are using `clipSrc` on `<button>` elements.
