### ISSUE TITLE
something is refusing my user stories 4 and 5

### ISSUE THREAD

**Issue by lordlinda** [freeCodeCamp/testable-projects-fcc#958]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 https://codepen.io/lordlinda/pen/XWrRMNx
 
 
```

**Comment by tbushman** [comment]
@lordlinda Very sorry for the late response. The user story instructs that we use `class="project-tile"`, and you are using `class="project-title"`. Thanks.
