### ISSUE TITLE
Pomodoro Clock User Stories update

### ISSUE THREAD

**Issue by Ahmed-Elbessfy** [freeCodeCamp/testable-projects-fcc#961]
Update for Session Increment and decrement buttons effect

#### Issue Description

User stories 14 says: 

>  When I click the element with the id of session-decrement, the value within id="session-length"decrements by a value of 1, and I can see the updated value

and 15 says : 

>  When I click the element with the id of session-increment, the value within id="session-length"increments by a value of 1, and I can see the updated value.

But actually, to pass test case 8, I need to update the time-left content too with the new value. So please, modify to help fellow coders to get a clear idea about they have to do.

Thanks for your time & effort.

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
