### ISSUE TITLE
I guess, I made right in 2 and 12 test in #content area. But, still it shows as a mistake, plz help.

### ISSUE THREAD

**Issue by sultonbekairways** [freeCodeCamp/testable-projects-fcc#962]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 
 
```

**Comment by tbushman** [comment]
Hello @sultonbekairways , please provide some more information about the error you are experiencing. Indicate which test is failing and provide a screenshot, a code sample, or a link to your project.
