### ISSUE TITLE
User story #8 not registering

### ISSUE THREAD

**Issue by codetamaracode** [freeCodeCamp/testable-projects-fcc#964]
#### Issue Description

I added the 'profile-link' id to the link that redirects in a new tab to my github, but the test says I do not have the id in the link.

#### Browser Information

Codepen

- Browser Name, Version: google chrome
- Operating System: mac
- Mobile, Desktop, or Tablet: desktop

#### Your Code / Link to Your Pen

https://codepen.io/tglidewell/pen/LYPdvzG?editors=1100

```



```

#### Screenshot

![image](https://user-images.githubusercontent.com/54759992/64723748-f9e84b00-d485-11e9-96e2-7f3faa489298.png)

**Comment by tbushman** [comment]
@codetamaracode Very sorry to delay responding. Please try changing `target="blank"` to `target="_blank"`
