### ISSUE TITLE
Build a Technical Documentation Page not validating

### ISSUE THREAD

**Issue by gaelletjat** [freeCodeCamp/testable-projects-fcc#965]
Build a Technical Documentation Page

I wrote the webpage following all instruction. I even read the sample page code source to make sure i wasn't missing anything. I can't have my test validated.

#### Issue Description

Write the code making sure the id on the main section matches the header of that section as well as the nav link, enter for the test.

#### Browser Information

- Browser Name, Version: Google chrome
- Operating System: MacOS

#### Your Code / Link to Your Pen (https://codepen.io/GaelleTjat/full/jONxQJw)

```

#### Screenshot

<!-- Add a screenshot of your issue -->

**Comment by tbushman** [comment]
@gaelletjat Sorry to delay responding to this issue, but it appears you have fixed whatever was wrong. Please open a new issue if you encounter further problems.
