### ISSUE TITLE
Email input not sending to static page

### ISSUE THREAD

**Issue by alex-a1973** [freeCodeCamp/testable-projects-fcc#966]
#### Issue Description
When I click the #submit element, the email is submitted to a static page (use this mock URL: https://www.freecodecamp.com/email-submit) that confirms the email address was entered (and that it posted successfully).
This step of the project doesn't work when I set the action atttribute of the form tag to the given URL

Happens everytime I test the project for the right requirements 
#### Browser Information

Just using Codepen.io (sorry if this is a bad answer I don't know what you mean by workspace)
- Browser Name, Version: Chrome Version 76.0.3809.132
- Operating System: Windows 10
- Mobile, Desktop, or Tablet: Laptop

#### Your Code / Link to Your Pen

```
<form id="form" action="https://www.freecodecamp.com/email-submit">
        <input type="email" 
               placeholder="Enter your email address"
               id="email"
               required/> 
        <br>
        <input type="submit"
               id="submit"
               value="GET STARTED"/>
      </form>  


```

**Comment by RandellDawson** [comment]
@alex-a1973 Please use [our fourm] to ask questions about your code for challenges/projects.  GitHub issues are only for reporting confirmed bugs.  If someone on the forum determines there is a bug in the tests for this project, then feel free to request this issue to be reopened.  Be prepared to post a link to the forum discussion.

Thank you.

P.S. You did not specify which challenge or project this is for or which test is failing.  You should definitely give more details in your form post.

**Comment by alex-a1973** [comment]
@RandellDawson Alright, thanks for getting back to me. You can delete this issue
