### ISSUE TITLE
Trying to create a simple tribune page

### ISSUE THREAD

**Issue by Ayodeji97** [freeCodeCamp/testable-projects-fcc#967]
#### Issue Description
. I  was ask to create an element with a corresponding id="tribute-info", which contains textual content describing the subject of the tribute page.

and this is what i did: <p id="tribune page">......the content of my tribune page.... </p>
but yet, i didn't pass it. please can someone help.

#### Browser Information

- Browser Name, Version:
- Operating System:
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen

```  <p id ="tribune-info">Xenophobism, which can be put in another word as "racism " or "racialism" is the act of being fearful or an act of extreme dislike of foriegners and their belongings in one country. Prior to 1994, immigrants from elsewhere faced discrimination and even violence in South Africa. After majority rule in 1994, contrary to expectations, the incidence of xenophobia increased.Between 2000 and March 2008, at least 67 people died in what were identified as xenophobic attacks. In May 2008, a series of attacks left 62 people dead; although 21 of those killed were South African citizens. The attacks were motivated by xenophobia.In 2015, another nationwide spike in xenophobic attacks against immigrants in general prompted a number of foreign governments to begin repatriating their citizens.
        Recently, a similar xenophobic attack has been recorded in south africa, with great violent act in some areas leading to looting of foriegner's shops and properties. For more information on xenophobic attack in south africa, click below.
      </p>



```

**Comment by floxSE** [comment]
hi, i'd like to try and help you out, but the code posted isn't enough to point you in the right direction. if your problem persists, please post your whole html document. don't expect too much from me though, since i am a beginner myself and only starting to get a hang of it.
