### ISSUE TITLE
Test running into script errors on my pomodoro timer

### ISSUE THREAD

**Issue by tywmick** [freeCodeCamp/testable-projects-fcc#971]
#### Issue Description

I've completed a [Pomodoro Timer](https://codepen.io/TyWMick/pen/mdbzNGY?editors=0011) that objectively fulfills all 28 user stories. However, running the tests (adding [bundle.js](https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js) to the list of external scripts in CodePen), I fail 12 of them, all for either "Script errors" or because the test expects some integers to be 3 or 4 or 5 off of what it thinks they should be.

Is my code just running too slowly because I'm trying to load Redux, React, jQuery, Bootstrap, and Font Awesome all at once? Does the slowness of my internet connection affect this?

I tried removing the Bootstrap CSS and JS links from the CodePen, and the same tests failed.

One odd thing about my timer is that I made `#session-length` and `#break-length` `<input>`s with the length value in their `value` attributes instead of making them normal text elements. This doesn't seem to affect the tests, though, because changing them to `<div>`s that display the length value inside of them doesn't change any of the tests I fail. And for that matter, changing the [FCC example](https://codepen.io/freeCodeCamp/full/XpKrrW)'s `#session-length` and `#break-length` to `<input>`s and moving the length values to `value` attributes didn't stop it from passing all the tests.

One thing I'm seeing now that I'm looking at the example go through the tests is that the tests are unable to make my timer run at super-speed. Why would that be? I'm just using `setInterval` to tick the clock down, and I read elsewhere that that's what the test manipulates to speed things up.

#### Browser Information

- Browser Name, Version: Chrome 76.0.3809.132 (Official Build) (64-bit)
- Operating System: macOS 10.14.6 (18G95)

Also tested this on a Chromebook, Chrome OS 76.0.3809.136 (Official Build) (64-bit), and ran into the same issues.

#### Your Code / Link to Your Pen

https://codepen.io/TyWMick/pen/mdbzNGY?editors=0011

#### Screenshot

<img width="1680" alt="Screen Shot 2019-09-19 at 3 49 34 AM" src="https://user-images.githubusercontent.com/5317080/65240508-4c34f780-da96-11e9-895f-46a4f3d80d99.png">

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
