### ISSUE TITLE
Survay Form

### ISSUE THREAD

**Issue by hamzapg786** [freeCodeCamp/testable-projects-fcc#972]
#### Browser Information

- Browser Name, Version:
- Operating System:
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen

```



```

**Comment by tbushman** [comment]
Hello @hamzapg786 , please provide some more information about the error you are experiencing. Indicate which test is failing and provide a screenshot, a code sample, or a link to your project.

**Comment by hamzapg786** [comment]
Okay I will resolve the errors...
