### ISSUE TITLE
Fork me test suite issue 

### ISSUE THREAD

**Issue by rcho80** [freeCodeCamp/testable-projects-fcc#974]
Hi

When i fork the test suite and attempt to run tests, the comment shows of Load Tests. I have selected the relevant project from dropdown box but to no avail

In the past, I have been able to run tests successfully by adding the <script> link directly into the body of HTML but now it seems this does not work as well

Can you please help advise?

- Browser Name, Version: chrome 
- Operating System: chromebook 
- Mobile, Desktop, or Tablet:  laptop 

#### Your Code / Link to Your Pen
https://codepen.io/rcho80/pen/dybwqEK

Screenshot
![image](https://user-images.githubusercontent.com/55364865/65396117-3a30bd00-dde6-11e9-888e-c498cec8e836.png)

Thanks
Ray

**Comment by kroham2019** [comment]
I am having the same issue.

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
