### ISSUE TITLE
Can't open Survey Codepen

### ISSUE THREAD

**Issue by greenandhealthy** [freeCodeCamp/testable-projects-fcc#975]
#### Browser Information

- Browser Name, Version: Chrome/latest version
- Operating System: mac iOS
- Mobile, Desktop, or Tablet: laptop

#### Your Code / Link to Your Pen

```



```

**Comment by tbushman** [comment]
Hello @greenandhealthy , please provide some more information about the error you are experiencing. Indicate which test is failing and provide a screenshot, a code sample, or a link to your project.
