### ISSUE TITLE
Problem viewing this work to know more about the challenge

### ISSUE THREAD

**Issue by ejejeok** [freeCodeCamp/testable-projects-fcc#976]
#### Browser Information

- Browser Name, Version:
- Operating System:
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen

```



```

**Comment by tbushman** [comment]
Hello @ejejeok , please provide some more information about the error you are experiencing. Indicate which test is failing and provide a screenshot, a code sample, or a link to your project.
