### ISSUE TITLE
Data Visualization Projects - Tooltip Tests Failing

### ISSUE THREAD

**Issue by SomeDer** [freeCodeCamp/testable-projects-fcc#979]
#### Issue Description

The tests don't recognize tooltips created with `.append("title").text("")` (which is the method taught in the curriculum).
However, tooltips created with `mouseover` events are recognized (but this isn't taught in the curriculum).
This is probably because tooltips created with `title` don't appear immediately after hovering the mouse.

#### Browser Information

- Browser Name, Version: Firefox 69.0.1

#### Your Code

```js
// doesn't work
.append("title")
.attr("id", "tooltip")
.text(d => JSON.stringify(d, null, 2).slice(2, -2).replace(/"/g, "").replace(/:/g, ": "))

// works
const tooltip = svg
        .append("text")
        .attr("id", "tooltip")
        .attr("x", 400)
        .attr("y", 180)
        .style("position", "absolute")
        .style("visibility", "hidden")

.on("mouseover", d => tooltip
  .attr("data-date", d[0])
  .style("visibility", "visible")
  .text(d[0] + " " + d[1]))
.on("mouseout", () => tooltip.style("visibility", "hidden"))

```

**Comment by tbushman** [comment]
Similar to #619

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
