### ISSUE TITLE
.

### ISSUE THREAD

**Issue by benjaminadk** [freeCodeCamp/testable-projects-fcc#98]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code / Link to Your Pen

```
 
 
 
```

**Comment by paycoguy** [comment]
Can you provide a link to your codepen project?

**Comment by benjaminadk** [comment]
ive removed the link to tester but here is my codepen
[link](http://codepen.io/benjaminadk/pen/Kmrdpj)

**Comment by no-stack-dub-sack** [comment]
@benjaminadk I've tested this out with your pen, and it seems to be working fine. This may seem like a silly question, but when you copied the link into your technical documentation project, did you press the "Run" button if you have that setting enabled?

**Comment by no-stack-dub-sack** [comment]
@benjaminadk closing this for now since everything seems to be in working order, if you can provide any more detail, please feel free to reopen.
