### ISSUE TITLE
Update the form example project

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/testable-projects-fcc#983]
As I was fixing some issues with the current example project (there are CI issues pt),  I felt like it might be better to make a new example project.

1. The two-column layout is causing a lot of issues for campers. We regularly get forum posts about aligning the labels and inputs.

2. Forms using a two-column layout are not all that common and [UX tests](https://ai.googleblog.com/2014/07/simple-is-better-making-your-web-forms.html) points to it not being a great choice.

Here is a WIP version of the new example form I suggest we use instead.
https://codepen.io/lasjorg/pen/bGGGEdy

@tbushman Any comments on this idea?

**Comment by tbushman** [comment]
@lasjorg That looks beautiful. Thank you. Sorry I've let this repo get so behind. Thanks for your help.

**Comment by RandellDawson** [comment]
@tbushman How will you incorporate this new design into the tests without breaking older projects which use the same tests?

**Comment by tbushman** [comment]
Hello @RandellDawson . I won't be doing it, but @lasjorg if you do submit a PR for the survey testable-project code, please ensure backward compatibility. The project should pass all current tests. As long as that is the case, it shouldn't be a huge problem.  
Would need to follow-up after to update the Codepen. ...  
What do you think?

**Comment by lasjorg** [comment]
Sorry, I have included the test in the Codepen now, it is passing all the tests. I will make a PR and update the Codepen when I'm ready. Which should be soon.

@tbushman 

I do have one question, I'm using a background image from unsplash. Should it be uploaded to the FCC CDN and linked to from there, or is the unsplash URL good enough?

**Comment by tbushman** [comment]
@lasjorg Use the unsplash URL until the project is approved. Thanks.

**Comment by lasjorg** [comment]
Closing resolved in https://github.com/freeCodeCamp/testable-projects-fcc/pull/988
