### ISSUE TITLE
Please read before opening an issue

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/testable-projects-fcc#984]
1. This repo is not a support forum. Please use the [Free Code Camp forum](https://www.freecodecamp.org/forum) to get help with your projects.

2. The issues tracker is mainly used as a bug tracker and for feature requests. Read more [about issues](https://guides.github.com/features/issues/).

3. If you do have a bug report or feature request please follow the guidelines given when opening up an issue. If you want to contribute please read the [CONTRIBUTING](https://github.com/freeCodeCamp/testable-projects-fcc/blob/master/CONTRIBUTING.md) documentation.

---

@tbushman @tchaffee 
I suggest we sticky this or at least some issue with information about what people should and should not post here. I see a lot of open issues here that should be forum threads and not open issues. It is in my opinion "polluting" the issue tracker.

**Comment by tbushman** [comment]
@lasjorg Thanks. I'll go through and close a lot of the stale issues this weekend. Thanks for all your help.

**Comment by RandellDawson** [comment]
I completely agree.  I have started closing these project help requests and asking the user to use the forum for help.

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
