### ISSUE TITLE
Technical Documentation

### ISSUE THREAD

**Issue by samir3490** [freeCodeCamp/testable-projects-fcc#985]
#### Issue Description

User Story #14: On regular sized devices (laptops, desktops), the element with id="navbar"should be shown on the left side of the screen and should always be visible to the user.
This is not working.
I tried copy pasting the entire CSS from the sample app but it is still not working. I am getting 15/16.

#### Browser Information

- Browser Name, Version: Google Chrome, 77.0.3865.90
- Operating System: Windows 10
- Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```

https://codepen.io/samir-agrawal/pen/yLLLEqK

```

#### Screenshot

![image](https://user-images.githubusercontent.com/4075374/66271884-cf20c500-e880-11e9-9936-d6c6d30b8bd5.png)

**Comment by JuWeber99** [comment]
hey @samir3490 for me the tests justs passed... did you change anything? because it looks alright to me tbh

**Comment by tbushman** [comment]
Confirmed that this project passes tests when the window is wide enough.
