### ISSUE TITLE
Testing bug.

### ISSUE THREAD

**Issue by Jordizer** [freeCodeCamp/testable-projects-fcc#987]
Hi, 

I am using the CDN link in codepen to test my product landing page, but when I go to test the code it says I have 4 passes but only two sections are ticked. I was wondering if it's possibly bugged out.

**Comment by RandellDawson** [comment]
@Jordizer If you have not already done so, please use [our forum](https://www.freecodecamp.org/forum) for debugging your projects.  If others determine there is a bug in our tests, you can request for this issue to be reopened.  Thank you.
