### ISSUE TITLE
Product Landing Page

### ISSUE THREAD

**Issue by l-white** [freeCodeCamp/testable-projects-fcc#989]
#### Issue Description

The checker does not recognize position: sticky as a possible solution to having a navigation bar appear at the top with scroll. I can reproduce the issue by changing sticky to fixed in the CSS for the header position and then the challenge will pass. The nav bar is part of the header div. Sticky is a solution to afixing an nav bar and/or header to the top of a webpage and should be recognized as such.

#### Browser Information

- Browser Name, Version: Chrome
- Operating System: OSX
- Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

https://codepen.io/laurawhite/pen/dyyMOWR

```



```

#### Screenshot

Please see attached screenshots. This shows that the challenge will pass only by changing the header position from sticky to fixed.
<img width="1158" alt="Won't pass with sticky header" src="https://user-images.githubusercontent.com/13588216/66847738-841a4800-ef39-11e9-8833-2e1918dabd9a.png">
<img width="1161" alt="Will only pass with fixed header" src="https://user-images.githubusercontent.com/13588216/66847739-841a4800-ef39-11e9-987c-cc1fd2580f27.png">

**Comment by RandellDawson** [comment]
GitHub is for reporting actual bugs with the tests.  Please use [our forum](https://www.freecodecamp.org/forum) to ask your question there first.  If the users determine you code is fine, then feel free to request this issue to be reopened.

Thank you.
