### ISSUE TITLE
i am stuck in the Random code generator project at freecode camp

### ISSUE THREAD

**Issue by SagirGarba** [freeCodeCamp/testable-projects-fcc#990]
#### Browser Information

- Browser Name, Version:
- Operating System:
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen

```



```

**Comment by SagirGarba** [comment]
https://codepen.io/sagirgarba/pen/abbBGzy
help a brother

**Comment by JuWeber99** [comment]
could you elaborate your issue? this is kinda confusing

**Comment by tbushman** [comment]
`document is undefined`

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
