### ISSUE TITLE
nav

### ISSUE THREAD

**Issue by ikeita22** [freeCodeCamp/testable-projects-fcc#991]
Hello; 
I finish this project but it still giving an error even thought it is working.I am
When I click a .nav-link button in the nav element, I am taken to the corresponding section of the landing page.

#### Browser Information

- Browser Name, Version:
- Operating System:
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen

```



```

**Comment by tbushman** [comment]
Hello @ikeita22 , please provide some more information about the error you are experiencing. Indicate which test is failing and provide a screenshot, a code sample, or a link to your project.
