### ISSUE TITLE
did the Survey test change?

### ISSUE THREAD

**Issue by elbaz1701** [freeCodeCamp/testable-projects-fcc#994]
did you guy change the survey test? if so is their a way to do it with the old code I'm almost done and now I have to start from scratch.

**Comment by thecodingaviator** [comment]
I believe that you're referring to the layout of the survey form. Yes, https://github.com/freeCodeCamp/testable-projects-fcc/pull/988 made some changes but as far as I see, it is a non-breaking change so you don't need to restart anything.
