### ISSUE TITLE
Pomodoro Clock test suite; something about the "hooks" not allowing the tests to run

### ISSUE THREAD

**Issue by wmcooper2** [freeCodeCamp/testable-projects-fcc#996]
#### Issue Description
I am working on the Pomodoro Clock. When I run the test suite, only one test passes. The others can't pass due to something with the "hooks".

#### Browser Information
- Browser Name, Version: Google Chrome, Version 78.0.3904.70 (Official Build) (64-bit)
- Operating System: MacOS Mojave Version 10.14.6 (18G103)
- Mobile, Desktop, or Tablet: MacBook Air (laptop)

#### Your Code / Link to Your Pen
Link to my code pen; https://codepen.io/wmcooper2/pen/qBBqeLM?editors=0010

#### Screenshot
![Screen Shot 2019-10-27 at 17 24 52](https://user-images.githubusercontent.com/24362578/67631825-baaf7580-f8de-11e9-91ab-1aed84464aaa.png)

**Comment by tbushman** [comment]
@wmcooper2 I just ran your tests again and it looks like you got it working. Congratulations. :)  
<img width="894" alt="Screen Shot 2019-12-14 at 11 24 57 AM" src="https://user-images.githubusercontent.com/7049294/70852922-80853d80-1e64-11ea-9e3b-8b8f08567c8e.png">

**Comment by wmcooper2** [comment]
Yes. Thanks, it was a weird problem. It was a while ago and I can't remember what I did to solve the problem. I wish I could, then I could share it. If I remember, then I will try to.
