### ISSUE TITLE
Tests not working on Tribute page

### ISSUE THREAD

**Issue by alex-taylor776** [freeCodeCamp/testable-projects-fcc#998]
#### Issue Description

Hi, I haven't been able to run tests on my Tribute page project.
When I select run tests, it return "mocha div missing"
No clue what that is but I tried adding a black div with the id mocha.
It then returns the test results with both passing and failing at 0.
Please could you help me with running the test properly? Thanks!

#### Browser Information

- Browser Name, Version:  Chrome Version 78.0.3904.70 (Official Build) (64-bit)
- Operating System: Microsoft Windows 10 Home
- Mobile, Desktop, or Tablet: Laptop

#### Your Code / Link to Your Pen
https://codepen.io/alex-taylor776/pen/MWWEweN

**Comment by NetSpud** [comment]
bump, got this issue as well, running chrome

**Comment by kroham2019** [comment]
I have the same issue, also have a banner that says: A referer from CodePen is required to render this page view, and your browser is not sending one (more details).

**Comment by tbushman** [comment]
@alex-taylor776 I just tested your project, and I didn't get the `mocha div missing` error.  
@NetSpud @kroham2019 Please share code we can test. Thank you.

**Comment by kroham2019** [comment]
https://codepen.io/keonr/pen/KKKLroR

**Comment by RandellDawson** [comment]
@alex-taylor776 @kroham2019 My guess is you are using a browser extension which is blocking 3rd party external scripts or you have configured your browser to block 3rd party scripts.

**Comment by kroham2019** [comment]
That is what I thought too, so I removed all my extensions and turned off my VPN and it still doesn't work. I am using the latest version of chrome so not sure why this is happening.

**Comment by kroham2019** [comment]
Sorry, Randell you are correct. Turning off my VPN wasn't enough, I had to remove the actual extension on the browser. Issue fixed for me!

**Comment by Annie4Star** [comment]
@alex-taylor776 I just fixed my issue by checking cookies.  A pivotal codepen cookie was being blocked by my Chrome.

**Comment by moT01** [comment]
For more visibility, please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
